In [32]:
import pandas as pd
import json
from tqdm import tqdm

In [25]:
metadata = pd.read_excel('BAREC-10M/Data/Metadata.xlsx')
metadata.head()

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?
0,BAREC_1001_introduction_1_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,73,6,Yes
1,BAREC_1001_introduction_2_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,730,73,No
2,BAREC_1001_introduction_3_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,397,47,Yes
3,BAREC_1001_introduction_4_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,237,23,Yes
4,BAREC_1001_introduction_5_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,659,62,No

In [26]:
metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 20535 entries, 0 to 20534
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Document          20535 non-null  str
 1   Directory         20535 non-null  object
 2   Source            20535 non-null  str
 3   Book              20535 non-null  object
 4   Author            20535 non-null  str
 5   Domain            20535 non-null  str
 6   Readership Group  20535 non-null  str
 7   Text Category     20535 non-null  str
 8   Word Count        20535 non-null  int64
 9   Sentence Count    20535 non-null  int64
 10  In BAREC Corpus?  20535 non-null  str
dtypes: int64(2), object(2), str(7)
memory usage: 1.7+ MB

In [33]:
shortest_sent_len = []
longest_sent_len = []
for i, row in tqdm(metadata.iterrows()):
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"
    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    shortest_sent_len.append(annotations.sents_word_count.min().item())
    longest_sent_len.append(annotations.sents_word_count.max().item())

20535it [04:53, 69.99it/s]

In [34]:
metadata['shortest_sent_len'] = shortest_sent_len
metadata['longest_sent_len'] = longest_sent_len

In [35]:
metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 20535 entries, 0 to 20534
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Document           20535 non-null  str
 1   Directory          20535 non-null  object
 2   Source             20535 non-null  str
 3   Book               20535 non-null  object
 4   Author             20535 non-null  str
 5   Domain             20535 non-null  str
 6   Readership Group   20535 non-null  str
 7   Text Category      20535 non-null  str
 8   Word Count         20535 non-null  int64
 9   Sentence Count     20535 non-null  int64
 10  In BAREC Corpus?   20535 non-null  str
 11  shortest_sent_len  20535 non-null  int64
 12  longest_sent_len   20535 non-null  int64
dtypes: int64(4), object(2), str(7)
memory usage: 2.0+ MB

In [36]:
metadata.to_json('metadata_with_sent_lengths.json', orient='records', force_ascii=False, indent=4)

In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
# assuming the data is located in the same directory as the notebook and the `Morphology_and_Readability.zip` file has been extracted

In [3]:
metadata = pd.read_json('metadata_with_sent_lengths.json', orient='records')
metadata.head()

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,shortest_sent_len,longest_sent_len
0,BAREC_1001_introduction_1_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,73,6,Yes,4,22
1,BAREC_1001_introduction_2_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,730,73,No,2,31
2,BAREC_1001_introduction_3_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,397,47,Yes,2,24
3,BAREC_1001_introduction_4_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,237,23,Yes,6,18
4,BAREC_1001_introduction_5_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,659,62,No,2,24

In [4]:
metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 20535 entries, 0 to 20534
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Document           20535 non-null  str
 1   Directory          20535 non-null  object
 2   Source             20535 non-null  str
 3   Book               20535 non-null  object
 4   Author             20535 non-null  str
 5   Domain             20535 non-null  str
 6   Readership Group   20535 non-null  str
 7   Text Category      20535 non-null  str
 8   Word Count         20535 non-null  int64
 9   Sentence Count     20535 non-null  int64
 10  In BAREC Corpus?   20535 non-null  str
 11  shortest_sent_len  20535 non-null  int64
 12  longest_sent_len   20535 non-null  int64
dtypes: int64(4), object(2), str(7)
memory usage: 2.0+ MB

In [5]:
metadata['Document'].nunique()

20535

In [6]:
list(metadata['Source'].unique())

['Arabian Nights',
 'Arabic Learner Corpus (ALC)',
 'ANERCorp',
 'Arabic Poem Comprehensive Dataset (APCD)',
 'Akhbarona News',
 'AlArabiya News',
 'AlKhaleej News',
 'National Anthems',
 'Arab Youth Publisher',
 'ArabicMMLU',
 'Basic Travel Expressions Corpus (BTEC)',
 'Batman',
 'Emarati Curriculum',
 'DARES',
 'Green Library',
 'Hadith',
 'Hayy ibn Yaqdhan',
 'Hindawi',
 'Kalima',
 'Library of Arabic Literature',
 'Ladybird',
 'Lulu',
 'Constitutions',
 'Majarra',
 'Majed',
 'MedArabiQ',
 'New Testament',
 'Old Testament',
 'Hanging Odes',
 'Ofoq',
 'Other Minor Sources',
 'Quran',
 'ReadMe++',
 'Reading Corner',
 'Sara',
 'Spacetoon Songs',
 'Subtitles',
 'Superman',
 'The Five Adventurers',
 'Tunis Curriculum',
 'UN (United Nations)',
 'WikiNews',
 'Wikipedia',
 'Zayed Arabic-English Bilingual Undergraduate Corpus (ZAEBUC)',
 'chatGPT']

In [7]:
metadata['Book'].nunique(), np.random.choice(list(metadata['Book'].unique()), 10), metadata['Book'].value_counts()

(4682,
 array(['City of Volcanoes',
        'The Philosophical Harvest of the 20th Century',
        'The Yellow Street', 'One Thousand and One Nights',
        'Influence of Greek Culture on Arab Culture', 'The Gold Train',
        'Living in Reality', '44774',
        'The Big Portrait Mystery and Other Stories', 'The Children Laugh'],
       dtype='<U147'),
 Book
 Sports                       1010
 Culture                      1001
 Medical                      1000
 Tech                         1000
 Finance                       997
                              ...
 Prophet                         1
 The Theory of the Iceberg       1
 Nelson Mandela                  1
 Engineering                     1
 Volubilis                       1
 Name: count, Length: 4682, dtype: int64)

In [8]:
metadata['Author'].nunique(), np.random.choice(list(metadata['Author'].unique()), 10), metadata['Author'].value_counts()

(2597,
 array(['Nawal El-Saadawi', 'Abdulmalik bin Muhammad Al-Jami Al-Faqih',
        'Murad Faraj', 'Ibn Al-Mutarraz', "Al-Harith ibn 'Abbad",
        'Nadim Al-Mansouri', 'Hussein Mehran', 'Amin Al-Khouli',
        'Donatella della Porta and Mario Diani', 'Fock Meier'],
       dtype='<U90'),
 Author
 #                              15227
 Mahmoud Salem                    337
 Kamel Kilani                     123
 Abbas Mahmoud Al-Aqqad            88
 Rafeef Reda Saidawi               59
                                ...
 Talal Ma’alla                      1
 Al-Habib Istani Zain Al-Din        1
 Hashim Qasim                       1
 Suleiman Al-Issa                   1
 UN (United Nations)                1
 Name: count, Length: 2597, dtype: int64)

In [9]:
metadata['Domain'].value_counts()

Domain
Arts & Humanities    10342
STEM                  5444
Social Sciences       4749
Name: count, dtype: int64

In [10]:
metadata['Readership Group'].value_counts()

Readership Group
Advanced Text        9165
Specialized Text     8884
Foundational Text    2486
Name: count, dtype: int64

In [11]:
metadata['Text Category'].value_counts()

Text Category
Media & Culture                                  7122
Educational Materials; Language & Linguistics    4709
Academic                                         4301
Literature; Art & Music                          3974
Religion & Philosophy                             254
Encyclopedic                                      175
Name: count, dtype: int64

In [12]:
metadata['Word Count'].describe()

count    20535.000000
mean       490.731385
std        262.089359
min          3.000000
25%        278.000000
50%        544.000000
75%        622.000000
max       5074.000000
Name: Word Count, dtype: float64

In [13]:
metadata['Sentence Count'].describe()

count    20535.000000
mean        25.073241
std         25.196396
min          1.000000
25%          8.000000
50%         17.000000
75%         33.000000
max        405.000000
Name: Sentence Count, dtype: float64

In [14]:
metadata['average sentence length'] = metadata['Word Count'] / metadata['Sentence Count']
metadata['average sentence length'].describe()

count    20535.000000
mean        31.768280
std         24.374336
min          1.666667
25%         14.820856
50%         27.260870
75%         39.904545
max       1107.000000
Name: average sentence length, dtype: float64

In [15]:
metadata['In BAREC Corpus?'].value_counts()

In BAREC Corpus?
No       18281
Yes       2031
ST2&3      223
Name: count, dtype: int64

In [16]:
for i, text_category in enumerate(metadata['Text Category'].unique()):
    corr_domain = list(metadata[metadata['Text Category'] == text_category]['Domain'].unique())
    print(f"{i+1}: {text_category}: {corr_domain}")

1: Literature; Art & Music: ['Arts & Humanities']
2: Educational Materials; Language & Linguistics: ['Arts & Humanities', 'Social Sciences', 'STEM']
3: Media & Culture: ['Arts & Humanities', 'Social Sciences', 'STEM']
4: Religion & Philosophy: ['Arts & Humanities']
5: Academic: ['Social Sciences', 'STEM', 'Arts & Humanities']
6: Encyclopedic: ['Social Sciences', 'STEM', 'Arts & Humanities']

In [17]:
for i, text_category in enumerate(metadata['Text Category'].unique()):
    corr_readership = list(metadata[metadata['Text Category'] == text_category]['Readership Group'].unique())
    print(f"{i+1}: {text_category}: {corr_readership}")

1: Literature; Art & Music: ['Specialized Text', 'Foundational Text', 'Advanced Text']
2: Educational Materials; Language & Linguistics: ['Advanced Text', 'Foundational Text', 'Specialized Text']
3: Media & Culture: ['Advanced Text', 'Foundational Text']
4: Religion & Philosophy: ['Specialized Text']
5: Academic: ['Specialized Text', 'Foundational Text', 'Advanced Text']
6: Encyclopedic: ['Advanced Text']

In [18]:
LAM_df = metadata[metadata['Text Category']=='Literature; Art & Music']
print("Literature; Art & Music")
print("==========================")
print(f"Number of documents: {LAM_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {LAM_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {LAM_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {LAM_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{LAM_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{LAM_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{LAM_df['average sentence length'].describe().to_dict()}")
print("==========================")

Literature; Art & Music
==========================
Number of documents: 3974
--------------------------
Number of sentences: 148343
--------------------------
Number of unique books: 2858
--------------------------
Number of unique authors: 1681
--------------------------
Domain distribution:
{'Arts & Humanities': 3974}
--------------------------
Readership Group distribution:
{'Specialized Text': 2286, 'Foundational Text': 1281, 'Advanced Text': 407}
--------------------------
Average sentence length distribution:
{'count': 3974.0, 'mean': 16.17055897763152, 'std': 11.658903148591186, 'min': 2.526315789473684, '25%': 9.317993557294063, '50%': 12.6, '75%': 19.884615384615383, 'max': 221.33333333333334}
==========================

In [19]:
LAM_foundational_df = LAM_df[LAM_df['Readership Group']=='Foundational Text']
print("Literature; Art & Music - Foundational")
print("==========================")
print(f"Number of documents: {LAM_foundational_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {LAM_foundational_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {LAM_foundational_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {LAM_foundational_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{LAM_foundational_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{LAM_foundational_df['average sentence length'].describe().to_dict()}")
print("==========================")

Literature; Art & Music - Foundational
==========================
Number of documents: 1281
--------------------------
Number of sentences: 58143
--------------------------
Number of unique books: 1009
--------------------------
Number of unique authors: 32
--------------------------
Domain distribution:
{'Arts & Humanities': 1281}
--------------------------
Average sentence length distribution:
{'count': 1281.0, 'mean': 13.908297148843703, 'std': 6.7821186229810015, 'min': 2.652173913043478, '25%': 8.620689655172415, '50%': 13.263157894736842, '75%': 17.609756097560975, 'max': 56.111111111111114}
==========================

In [21]:
sampled_LAM_foundational_df = LAM_foundational_df[LAM_foundational_df['longest_sent_len'] >= 8].sample(17, random_state=42)

In [22]:
sampled_LAM_foundational_sentences_indices = []
for i, row in sampled_LAM_foundational_df.iterrows():
    found = False
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"
    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    
    sampled_row = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42)
    sampled_LAM_foundational_sentences_indices.append(sampled_row.index.item())
print(sampled_LAM_foundational_sentences_indices)

[42, 59, 3, 5, 2, 76, 20, 1, 10, 14, 2, 68, 22, 32, 3, 4, 9]

In [23]:
sampled_LAM_foundational_df['sampled_sentence_index'] = sampled_LAM_foundational_sentences_indices

In [24]:
LAM_advanced_df = LAM_df[LAM_df['Readership Group']=='Advanced Text']
print("Literature; Art & Music - Advanced")
print("==========================")
print(f"Number of documents: {LAM_advanced_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {LAM_advanced_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {LAM_advanced_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {LAM_advanced_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{LAM_advanced_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{LAM_advanced_df['average sentence length'].describe().to_dict()}")
print("==========================")

Literature; Art & Music - Advanced
==========================
Number of documents: 407
--------------------------
Number of sentences: 13216
--------------------------
Number of unique books: 390
--------------------------
Number of unique authors: 107
--------------------------
Domain distribution:
{'Arts & Humanities': 407}
--------------------------
Average sentence length distribution:
{'count': 407.0, 'mean': 20.54016798418344, 'std': 11.93829403319979, 'min': 4.239316239316239, '25%': 13.561561561561561, '50%': 17.857142857142858, '75%': 24.11904761904762, 'max': 128.25}
==========================

In [25]:
sampled_LAM_advanced_df = LAM_advanced_df[LAM_advanced_df['longest_sent_len'] >= 8].sample(16, random_state=42)

In [26]:
sampled_LAM_advanced_sentences_indices = []
for i, row in sampled_LAM_advanced_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_LAM_advanced_sentences_indices.append(sampled_index)
print(sampled_LAM_advanced_sentences_indices)

[1, 77, 14, 20, 43, 4, 1, 17, 2, 14, 1, 35, 2, 12, 2, 46]

In [27]:
sampled_LAM_advanced_df['sampled_sentence_index'] = sampled_LAM_advanced_sentences_indices

In [28]:
LAM_specialized_df = LAM_df[LAM_df['Readership Group']=='Specialized Text']
print("Literature; Art & Music - Specialized")
print("==========================")
print(f"Number of documents: {LAM_specialized_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {LAM_specialized_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {LAM_specialized_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {LAM_specialized_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{LAM_specialized_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{LAM_specialized_df['average sentence length'].describe().to_dict()}")
print("==========================")

Literature; Art & Music - Specialized
==========================
Number of documents: 2286
--------------------------
Number of sentences: 76984
--------------------------
Number of unique books: 1464
--------------------------
Number of unique authors: 1568
--------------------------
Domain distribution:
{'Arts & Humanities': 2286}
--------------------------
Average sentence length distribution:
{'count': 2286.0, 'mean': 16.660290621118204, 'std': 13.36958423325814, 'min': 2.526315789473684, '25%': 9.314814814814815, '50%': 10.666666666666666, '75%': 20.962222222222223, 'max': 221.33333333333334}
==========================

In [29]:
sampled_LAM_specialized_df = LAM_specialized_df[LAM_specialized_df['longest_sent_len'] >= 8].sample(17, random_state=42)

In [44]:
sampled_LAM_specialized_sentences_indices = []
for i, row in sampled_LAM_specialized_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_LAM_specialized_sentences_indices.append(sampled_index)
print(sampled_LAM_specialized_sentences_indices)

[27, 28, 19, 14, 44, 13, 4, 19, 0, 1, 1, 46, 13, 0, 2, 7, 32]

In [45]:
sampled_LAM_specialized_df['sampled_sentence_index'] = sampled_LAM_specialized_sentences_indices

In [46]:
A_df = pd.concat([sampled_LAM_foundational_df, sampled_LAM_advanced_df, sampled_LAM_specialized_df], ignore_index=True)
A_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,shortest_sent_len,longest_sent_len,average sentence length,sampled_sentence_index
0,BAREC_TheFiveAdventurers_188 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 188,#,Arts & Humanities,Foundational Text,Literature; Art & Music,689,46,No,2,58,14.978261,42
1,BAREC_Batman_040_005,Batman,Batman,Edition: 40,#,Arts & Humanities,Foundational Text,Literature; Art & Music,596,66,No,1,25,9.030303,59
2,BAREC_ArabYouthPublisher_سيدي الحلوي_001,ArabYouthPublisher,Arab Youth Publisher,Sidi Al-Helwi,#,Arts & Humanities,Foundational Text,Literature; Art & Music,603,29,No,2,92,20.793103,3
3,BAREC_ArabYouthPublisher_لمياء،وائل والدراجة_001,ArabYouthPublisher,Arab Youth Publisher,"Lamia, Wael and the Bicycle",#,Arts & Humanities,Foundational Text,Literature; Art & Music,329,26,No,3,27,12.653846,5
4,BAREC_TheFiveAdventurers_003 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 003,#,Arts & Humanities,Foundational Text,Literature; Art & Music,704,35,No,3,43,20.114286,2
5,BAREC_Lulu_030_003,Lulu,Lulu,Edition: 30,#,Arts & Humanities,Foundational Text,Literature; Art & Music,590,80,No,1,24,7.375000,76
6,BAREC_Hindawi_15383148_001,Hindawi,Hindawi,Hardships and Crises,Kamel Kilani,Arts & Humanities,Foundational Text,Literature; Art & Music,501,61,No,2,27,8.213115,20
7,BAREC_Hindawi_52759097_001,Hindawi,Hindawi,The Trojan Horse,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,515,33,No,2,72,15.606061,1
8,BAREC_SpacetoonSong_أنا وأخي_001,SpacetoonSong,Spacetoon Songs,Me and My Brother,#,Arts & Humanities,Foundational Text,Literature; Art & Music,52,13,Yes,2,10,4.000000,10
9,BAREC_SpacetoonSong_ريمي_001,SpacetoonSong,Spacetoon Songs,Remy,#,Arts & Humanities,Foundational Text,Literature; Art & Music,100,22,Yes,2,8,4.545455,14
10,BAREC_SpacetoonSong_مدينة نخل_001,SpacetoonSong,Spacetoon Songs,The City of Palm Trees,#,Arts & Humanities,Foundational Text,Literature; Art & Music,143,18,Yes,6,13,7.944444,2
11,BAREC_Superman_050_004,Superman,Superman,Edition: 50,#,Arts & Humanities,Foundational Text,Literature; Art & Music,599,74,No,2,38,8.094595,68
12,BAREC_TheFiveAdventurers_163 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 163,#,Arts & Humanities,Foundational Text,Literature; Art & Music,679,49,No,3,44,13.857143,22
13,BAREC_Hindawi_49062509_001,Hindawi,Hindawi,The Rain Maker,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,536,36,No,3,41,14.888889,32
14,BAREC_Hindawi_71371742_001,Hindawi,Hindawi,The Giant Mystery,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,530,18,No,3,102,29.444444,3
15,BAREC_SpacetoonSong_الطاقة الزرقاء_001,SpacetoonSong,Spacetoon Songs,Blue Energy,#,Arts & Humanities,Foundational Text,Literature; Art & Music,96,18,Yes,2,16,5.333333,4
16,BAREC_Hindawi_70461585_001,Hindawi,Hindawi,The Wild Cat’s Cry,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,509,32,No,3,42,15.906250,9
17,BAREC_Hindawi_28648582_001,Hindawi,Hindawi,Ragnarok,Antonia Susan Byatt,Arts & Humanities,Advanced Text,Literature; Art & Music,1366,82,Yes,2,50,16.658537,1
18,BAREC_Hindawi_62505363_001,Hindawi,Hindawi,Steps in the Same River,Riyadh Hammadi,Arts & Humanities,Advanced Text,Literature; Art & Music,505,81,No,1,19,6.234568,77
19,BAREC_Hindawi_71693707_001,Hindawi,Hindawi,Cases of John Thorndike,R. Austin Freeman,Arts & Humanities,Advanced Text,Literature; Art & Music,501,23,No,1,56,21.782609,14
20,BAREC_Hindawi_18686373_001,Hindawi,Hindawi,The Gentle Strongman,Naguib Mahfouz,Arts & Humanities,Advanced Text,Literature; Art & Music,502,27,No,1,74,18.592593,20
21,BAREC_Hindawi_20429368_001,Hindawi,Hindawi,The Younger Brother,Corey Ductoro,Arts & Humanities,Advanced Text,Literature; Art & Music,887,46,Yes,2,42,19.282609,43
22,BAREC_Hindawi_29392697_001,Hindawi,Hindawi,The Virtuous Successor,Wadi’ Abu Fadil,Arts & Humanities,Advanced Text,Literature; Art & Music,544,18,No,1,90,30.222222,4
23,BAREC_Hindawi_42475809_001,Hindawi,Hindawi,The Mystery of the Lost Necklace,Jack Footrell,Arts & Humanities,Advanced Text,Literature; Art & Music,516,23,No,4,38,22.434783,1
24,BAREC_Hindawi_85794209_001,Hindawi,Hindawi,In Our Time,Ernest Hemingway,Arts & Humanities,Advanced Text,Literature; Art & Music,505,43,No,1,33,11.744186,17
25,BAREC_Hindawi_69407460_001,Hindawi,Hindawi,The Heart of a Woman,Ponson du Terrail,Arts & Humanities,Advanced Text,Literature; Art & Music,544,26,No,2,48,20.923077,2
26,BAREC_Hindawi_72735281_001,Hindawi,Hindawi,The Earth Gods,Gibran Khalil Gibran,Arts & Humanities,Advanced Text,Literature; Art & Music,503,61,No,2,19,8.245902,14
27,BAREC_Hindawi_93859604_001,Hindawi,Hindawi,The End of the World,Yusuf Idris,Arts & Humanities,Advanced Text,Literature; Art & Music,500,28,No,2,73,17.857143,1
28,BAREC_Hindawi_29403629_001,Hindawi,Hindawi,I Am the Sultan of the Law of Existence,Yusuf Idris,Arts & Humanities,Advanced Text,Literature; Art & Music,740,46,Yes,3,53,16.086957,35
29,BAREC_Hindawi_74748507_001,Hindawi,Hindawi,Discovery of a Continent,Yusuf Idris,Arts & Humanities,Advanced Text,Literature; Art & Music,503,26,No,2,54,19.346154,2
30,BAREC_Hindawi_97951825_001,Hindawi,Hindawi,Hard Times,Charles Dickens,Arts & Humanities,Advanced Text,Literature; Art & Music,506,45,No,1,42,11.244444,12
31,BAREC_Hindawi_48293606_001,Hindawi,Hindawi,The Specter of the Soul,Edward Page Mitchell,Arts & Humanities,Advanced Text,Literature; Art & Music,500,26,No,1,57,19.230769,2
32,BAREC_Hindawi_52951836_001,Hindawi,Hindawi,The Adventure of Sherlo Combs,Robert Barr,Arts & Humanities,Advanced Text,Literature; Art & Music,504,48,No,1,30,10.500000,46
33,BAREC_APCD_ابن العديم_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Ibn al-'Adim,Arts & Humanities,Specialized Text,Literature; Art & Music,500,48,No,8,13,10.416667,27
34,BAREC_APCD_إبراهيم بن المهدي_الديوان الرئيسي...,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Ibrahim ibn al-Mahdi,Arts & Humanities,Specialized Text,Literature; Art & Music,502,49,No,7,13,10.244898,28
35,BAREC_Hindawi_79405794_001,Hindawi,Hindawi,The Entertaining Stories,Ibrahim Zidan,Arts & Humanities,Specialized Text,Literature; Art & Music,502,39,No,2,68,12.871795,19
36,BAREC_APCD_الشريف العقيلي_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Al-Sharif al-'Aqili,Arts & Humanities,Specialized Text,Literature; Art & Music,508,58,No,6,11,8.758621,14
37,BAREC_APCD_محمد رضا الخزاعي_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Mohammed Rida Al-Khuza’i,Arts & Humanities,Specialized Text,Literature; Art & Music,504,52,No,7,13,9.692308,44
38,BAREC_Hindawi_47297974_001,Hindawi,Hindawi,An Opinion on Abu al-‘Ala,Amin Al-Khouli,Arts & Humanities,Specialized Text,Literature; Art & Music,500,44,No,2,102,11.363636,13
39,BAREC_Hindawi_36069074_001,Hindawi,Hindawi,To My Son,Ahmed Amin,Arts & Humanities,Specialized Text,Literature; Art & Music,513,16,No,3,101,32.062500,4
40,BAREC_Hindawi_59616186_001,Hindawi,Hindawi,Al-Fayd al-Khatir (Part 1),Ahmed Amin,Arts & Humanities,Specialized Text,Literature; Art & Music,505,22,No,2,44,22.954545,19
41,BAREC_APCD_جمال الدين ابن منقذ_جمال الدين ابن ...,APCD,Arabic Poem Comprehensive Dataset (APCD),Jamal Al-Din Ibn Munqidh,Jamal Al-Din Ibn Munqidh,Arts & Humanities,Specialized Text,Literature; Art & Music,196,21,No,8,11,9.333333,0
42,BAREC_APCD_عَقِيل بن مَسْعود_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Aqil ibn Mas’ud,Arts & Humanities,Specialized Text,Literature; Art & Music,84,8,No,8,12,10.500000,1
43,BAREC_APCD_الجَواد الهمداني_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Al-Jawad al-Hamdani,Arts & Humanities,Specialized Text,Literature; Art & Music,46,5,No,8,11,9.200000,1
44,BAREC_APCD_ضرار بن الأزور_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Dhirar ibn Al-Azwar,Arts & Humanities,Specialized Text,Literature; Art & Music,462,51,No,4,13,9.058824,46
45,BAREC_APCD_ابن عنين_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Ibn 'Anin,Arts & Humanities,Specialized Text,Literature; Art & Music,503,50,No,8,13,10.060000,13
46,BAREC_APCD_شهدة الكاتبة_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Shahda Al-Katiba,Arts & Humanities,Specialized Text,Literature; Art & Music,147,16,No,8,11,9.187500,0
47,BAREC_Hindawi_28570839_001,Hindawi,Hindawi,Diwan of a Wayfarer,Abbas Mahmoud Al-Aqqad,Arts & Humanities,Specialized Text,Literature; Art & Music,482,130,No,1,32,3.707692,2
48,BAREC_Hindawi_84793046_001,Hindawi,Hindawi,Village Talks,Marun Abbud,Arts & Humanities,Specialized Text,Literature; Art & Music,503,16,No,2,66,31.437500,7
49,BAREC_Kalima_التطريز_في_الهند_وباكستان_001,Kalima,Kalima,Embroidery in India and Pakistan,#,Arts & Humanities,Specialized Text,Literature; Art & Music,842,53,No,1,43,15.886792,32

In [47]:
A_df['selected_sent_raw'] = None
A_df['selected_sent_word_count'] = None
A_df['selected_sent_words'] = None

for i, row in A_df.iterrows():
    directory = row['Directory']
    document = row['Document']

    annotations_file_path = (
        f"BAREC-10M/Data/Morphology_and_Readability/"
        f"{directory}/{document}.json"
    )

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)

    annotations = pd.DataFrame(annotations)

    selected_sentence_index = int(row['sampled_sentence_index'])

    selected_row = annotations.iloc[selected_sentence_index]

    raw_sentence = selected_row['raw_sents']
    word_count = selected_row['sents_word_count']
    words = selected_row['word']   # list of strings

    A_df.at[i, 'selected_sent_raw'] = raw_sentence
    A_df.at[i, 'selected_sent_word_count'] = word_count
    A_df.at[i, 'selected_sent_words'] = words

In [48]:
A_df = A_df[[
    'Directory',
    'Document',
    'sampled_sentence_index',
    'Source',
    'Book',
    'Author',
    'Domain',
    'Readership Group',
    'Text Category',
    'average sentence length',
    'selected_sent_raw',
    'selected_sent_word_count',
    'selected_sent_words'
]]

In [49]:
A_df.rename(columns={
    'average sentence length': 'average_sentence_length_per_doc',
}, inplace=True)

In [50]:
A_df.to_json('sampled_LAM_sentences.json', orient='records', force_ascii=False, indent=4)

In [37]:
metadata['Text Category'].value_counts()

Text Category
Media & Culture                                  7122
Educational Materials; Language & Linguistics    4709
Academic                                         4301
Literature; Art & Music                          3974
Religion & Philosophy                             254
Encyclopedic                                      175
Name: count, dtype: int64

In [38]:
MC_df = metadata[metadata['Text Category']=='Media & Culture']
print("Media & Culture")
print("==========================")
print(f"Number of documents: {MC_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {MC_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {MC_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {MC_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{MC_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{MC_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{MC_df['average sentence length'].describe().to_dict()}")
print("==========================")

Media & Culture
==========================
Number of documents: 7122
--------------------------
Number of sentences: 90271
--------------------------
Number of unique books: 73
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Arts & Humanities': 3339, 'STEM': 2050, 'Social Sciences': 1733}
--------------------------
Readership Group distribution:
{'Advanced Text': 6804, 'Foundational Text': 318}
--------------------------
Average sentence length distribution:
{'count': 7122.0, 'mean': 34.177115010952846, 'std': 21.194923549289182, 'min': 2.5, '25%': 24.4, '50%': 31.550505050505052, '75%': 41.1972972972973, 'max': 1107.0}
==========================

In [39]:
MC_AH_df = MC_df[MC_df['Domain']=='Arts & Humanities']
print("Media & Culture - Arts & Humanities")
print("==========================")
print(f"Number of documents: {MC_AH_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {MC_AH_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {MC_AH_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {MC_AH_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{MC_AH_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{MC_AH_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{MC_AH_df['average sentence length'].describe().to_dict()}")
print("==========================")

Media & Culture - Arts & Humanities
==========================
Number of documents: 3339
--------------------------
Number of sentences: 53523
--------------------------
Number of unique books: 16
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Arts & Humanities': 3339}
--------------------------
Readership Group distribution:
{'Advanced Text': 3021, 'Foundational Text': 318}
--------------------------
Average sentence length distribution:
{'count': 3339.0, 'mean': 33.815569826253, 'std': 26.823106990512063, 'min': 3.0, '25%': 23.0, '50%': 30.555555555555557, '75%': 40.63333333333333, 'max': 1107.0}
==========================

In [42]:
sampled_MC_AH_foundational_df = MC_AH_df[(MC_AH_df['Readership Group']=='Foundational Text') & (MC_AH_df['longest_sent_len'] >= 8)].sample(8, random_state=42)
sampled_MC_AH_advanced_df = MC_AH_df[(MC_AH_df['Readership Group']=='Advanced Text') & (MC_AH_df['longest_sent_len'] >= 8)].sample(9, random_state=42)

In [43]:
sampled_MC_AH_df = pd.concat([sampled_MC_AH_foundational_df, sampled_MC_AH_advanced_df], ignore_index=True)

In [51]:
sampled_MC_AH_sentences_indices = []
for i, row in sampled_MC_AH_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_MC_AH_sentences_indices.append(sampled_index)
print(sampled_MC_AH_sentences_indices)

[15, 124, 3, 44, 13, 1, 1, 14, 6, 1, 1, 1, 12, 13, 0, 7, 5]

In [52]:
sampled_MC_AH_df['sampled_sentence_index'] = sampled_MC_AH_sentences_indices

In [53]:
MC_ST_df = MC_df[MC_df['Domain']=='STEM']
print("Media & Culture - STEM")
print("==========================")
print(f"Number of documents: {MC_ST_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {MC_ST_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {MC_ST_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {MC_ST_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{MC_ST_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{MC_ST_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{MC_ST_df['average sentence length'].describe().to_dict()}")
print("==========================")

Media & Culture - STEM
==========================
Number of documents: 2050
--------------------------
Number of sentences: 18572
--------------------------
Number of unique books: 34
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'STEM': 2050}
--------------------------
Readership Group distribution:
{'Advanced Text': 2050}
--------------------------
Average sentence length distribution:
{'count': 2050.0, 'mean': 36.51979165085057, 'std': 14.279902363926452, 'min': 6.8, '25%': 27.186363636363637, '50%': 34.2, '75%': 43.333333333333336, 'max': 146.0}
==========================

In [57]:
sampled_MC_ST_df = MC_ST_df[(MC_ST_df['longest_sent_len'] >= 8) & (MC_ST_df['shortest_sent_len'] <= 30)].sample(17, random_state=42)

In [58]:
sampled_MC_ST_sentences_indices = []
for i, row in sampled_MC_ST_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_MC_ST_sentences_indices.append(sampled_index)
print(sampled_MC_ST_sentences_indices)

[0, 2, 3, 1, 2, 6, 14, 0, 2, 1, 42, 1, 3, 1, 1, 0, 2]

In [59]:
sampled_MC_ST_df['sampled_sentence_index'] = sampled_MC_ST_sentences_indices

In [60]:
MC_SS_df = MC_df[MC_df['Domain']=='Social Sciences']
print("Media & Culture - Social Sciences")
print("==========================")
print(f"Number of documents: {MC_SS_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {MC_SS_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {MC_SS_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {MC_SS_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{MC_SS_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{MC_SS_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{MC_SS_df['average sentence length'].describe().to_dict()}")
print("==========================")

Media & Culture - Social Sciences
==========================
Number of documents: 1733
--------------------------
Number of sentences: 18176
--------------------------
Number of unique books: 23
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Social Sciences': 1733}
--------------------------
Readership Group distribution:
{'Advanced Text': 1733}
--------------------------
Average sentence length distribution:
{'count': 1733.0, 'mean': 32.10251158332588, 'std': 14.423877229819887, 'min': 2.5, '25%': 23.4, '50%': 30.1, '75%': 39.46666666666667, 'max': 238.33333333333334}
==========================

In [68]:
sampled_MC_SS_df = MC_SS_df[(MC_SS_df['longest_sent_len'] >= 8) & (MC_SS_df['shortest_sent_len'] <= 30) & (MC_SS_df['Sentence Count'] > 10)].sample(16, random_state=42)

In [70]:
sampled_MC_SS_sentences_indices = []
for i, row in sampled_MC_SS_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    
    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_MC_SS_sentences_indices.append(sampled_index)
print(sampled_MC_SS_sentences_indices)

[12, 2, 4, 14, 2, 29, 18, 3, 5, 0, 7, 2, 16, 3, 0, 13]

In [71]:
sampled_MC_SS_df['sampled_sentence_index'] = sampled_MC_SS_sentences_indices

In [72]:
B_df = pd.concat([sampled_MC_AH_df, sampled_MC_ST_df, sampled_MC_SS_df], ignore_index=True)
B_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,shortest_sent_len,longest_sent_len,average sentence length,sampled_sentence_index
0,BAREC_Majed_2082_2019_004,Majed,Majed,Edition: 2082,#,Arts & Humanities,Foundational Text,Media & Culture,336,17,Yes,2,43,19.764706,15
1,BAREC_Majed_0229_1983_011,Majed,Majed,Edition: 229,#,Arts & Humanities,Foundational Text,Media & Culture,923,135,Yes,1,32,6.837037,124
2,BAREC_Majed_0670_1991_006,Majed,Majed,Edition: 670,#,Arts & Humanities,Foundational Text,Media & Culture,1118,114,Yes,2,32,9.807018,3
3,BAREC_Majed_0670_1991_009,Majed,Majed,Edition: 670,#,Arts & Humanities,Foundational Text,Media & Culture,474,77,Yes,1,18,6.155844,44
4,BAREC_Majed_0229_1983_027,Majed,Majed,Edition: 229,#,Arts & Humanities,Foundational Text,Media & Culture,387,39,Yes,2,24,9.923077,13
5,BAREC_Majed_0670_1991_012,Majed,Majed,Edition: 670,#,Arts & Humanities,Foundational Text,Media & Culture,313,20,Yes,4,32,15.650000,1
6,BAREC_Majed_0836_1995_016,Majed,Majed,Edition: 836,#,Arts & Humanities,Foundational Text,Media & Culture,184,35,Yes,1,15,5.257143,1
7,BAREC_Majed_1481_2007_006,Majed,Majed,Edition: 1481,#,Arts & Humanities,Foundational Text,Media & Culture,749,49,Yes,1,45,15.285714,14
8,BAREC_AlArabiya_Culture_0274_001,AlArabiya,AlArabiya News,Culture,#,Arts & Humanities,Advanced Text,Media & Culture,722,42,No,2,94,17.190476,6
9,BAREC_AlArabiya_Sports_00076_001,AlArabiya,AlArabiya News,Sports,#,Arts & Humanities,Advanced Text,Media & Culture,194,8,No,14,31,24.250000,1
10,BAREC_ANERCorp_train_163,ANERCorp,ANERCorp,#,#,Arts & Humanities,Advanced Text,Media & Culture,607,10,No,8,145,60.700000,1
11,BAREC_AlArabiya_Culture_0269_001,AlArabiya,AlArabiya News,Culture,#,Arts & Humanities,Advanced Text,Media & Culture,176,7,No,12,34,25.142857,1
12,BAREC_ANERCorp_train_012,ANERCorp,ANERCorp,#,#,Arts & Humanities,Advanced Text,Media & Culture,606,32,No,4,90,18.937500,12
13,BAREC_Akhbarona_Religion_0167_001,Akhbarona,Akhbarona News,Religion,#,Arts & Humanities,Advanced Text,Media & Culture,799,35,No,1,130,22.828571,13
14,BAREC_Akhbarona_Religion_0227_001,Akhbarona,Akhbarona News,Religion,#,Arts & Humanities,Advanced Text,Media & Culture,1016,31,No,3,85,32.774194,0
15,BAREC_AlKhaleej_Culture_0054_001,AlKhaleej,AlKhaleej News,Culture,#,Arts & Humanities,Advanced Text,Media & Culture,204,8,No,3,61,25.500000,7
16,BAREC_AlKhaleej_Religion_0039_001,AlKhaleej,AlKhaleej News,Religion,#,Arts & Humanities,Advanced Text,Media & Culture,1695,39,No,3,106,43.461538,5
17,BAREC_AlArabiya_Medical_0238_001,AlArabiya,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,278,11,No,12,36,25.272727,0
18,BAREC_AlArabiya_Tech_0037_001,AlArabiya,AlArabiya News,Tech,#,STEM,Advanced Text,Media & Culture,182,7,No,17,35,26.000000,2
19,BAREC_AlArabiya_Medical_0093_001,AlArabiya,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,140,6,No,11,39,23.333333,3
20,BAREC_AlKhaleej_Tech_0318_001,AlKhaleej,AlKhaleej News,Tech,#,STEM,Advanced Text,Media & Culture,293,8,No,15,75,36.625000,1
21,BAREC_Akhbarona_Medical_00271_001,Akhbarona,Akhbarona News,Medical,#,STEM,Advanced Text,Media & Culture,229,6,No,10,63,38.166667,2
22,BAREC_Akhbarona_Tech_00116_001,Akhbarona,Akhbarona News,Tech,#,STEM,Advanced Text,Media & Culture,337,9,No,27,54,37.444444,6
23,BAREC_Akhbarona_Tech_00050_001,Akhbarona,Akhbarona News,Tech,#,STEM,Advanced Text,Media & Culture,500,19,No,5,54,26.315789,14
24,BAREC_Akhbarona_Medical_00025_001,Akhbarona,Akhbarona News,Medical,#,STEM,Advanced Text,Media & Culture,206,9,No,9,41,22.888889,0
25,BAREC_Akhbarona_Tech_00271_001,Akhbarona,Akhbarona News,Tech,#,STEM,Advanced Text,Media & Culture,156,6,No,16,36,26.000000,2
26,BAREC_AlKhaleej_Medical_0005_001,AlKhaleej,AlKhaleej News,Medical,#,STEM,Advanced Text,Media & Culture,159,6,No,13,37,26.500000,1
27,BAREC_AlArabiya_Medical_0025_001,AlArabiya,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,706,47,No,4,31,15.021277,42
28,BAREC_AlKhaleej_Tech_0195_001,AlKhaleej,AlKhaleej News,Tech,#,STEM,Advanced Text,Media & Culture,168,4,No,16,58,42.000000,1
29,BAREC_AlArabiya_Tech_0331_001,AlArabiya,AlArabiya News,Tech,#,STEM,Advanced Text,Media & Culture,227,7,No,13,51,32.428571,3
30,BAREC_Akhbarona_Tech_00152_001,Akhbarona,Akhbarona News,Tech,#,STEM,Advanced Text,Media & Culture,84,3,No,14,39,28.000000,1
31,BAREC_Akhbarona_Medical_00266_001,Akhbarona,Akhbarona News,Medical,#,STEM,Advanced Text,Media & Culture,124,4,No,12,48,31.000000,1
32,BAREC_AlArabiya_Medical_0298_001,AlArabiya,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,91,4,No,9,34,22.750000,0
33,BAREC_AlKhaleej_Medical_0300_001,AlKhaleej,AlKhaleej News,Medical,#,STEM,Advanced Text,Media & Culture,151,3,No,20,79,50.333333,2
34,BAREC_AlKhaleej_Politics_0323_001,AlKhaleej,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,466,17,No,3,63,27.411765,12
35,BAREC_AlArabiya_Finance_00126_001,AlArabiya,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,1186,16,No,17,135,74.125000,2
36,BAREC_AlKhaleej_Politics_0255_001,AlKhaleej,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,874,15,No,15,136,58.266667,4
37,BAREC_Majarra_Stanford_Social_Innovation_Revie...,Majarra,Majarra,How Does Building an Effective Volunteer Commu...,#,Social Sciences,Advanced Text,Media & Culture,550,21,ST2&3,6,69,26.190476,14
38,BAREC_AlKhaleej_Politics_0226_001,AlKhaleej,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,493,16,No,3,58,30.812500,2
39,BAREC_AlKhaleej_Finance_0240_001,AlKhaleej,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,301,47,No,2,19,6.404255,29
40,BAREC_Akhbarona_Finance_0137_001,Akhbarona,Akhbarona News,Finance,#,Social Sciences,Advanced Text,Media & Culture,945,22,No,4,118,42.954545,18
41,BAREC_AlKhaleej_Finance_0059_001,AlKhaleej,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,207,27,No,3,37,7.666667,3
42,BAREC_WikiNews_economy_7_001,WikiNews,WikiNews,Economy,#,Social Sciences,Advanced Text,Media & Culture,277,12,Yes,6,54,23.083333,5
43,BAREC_AlKhaleej_Finance_0082_001,AlKhaleej,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,274,25,No,3,48,10.960000,0
44,BAREC_Akhbarona_Finance_0045_001,Akhbarona,Akhbarona News,Finance,#,Social Sciences,Advanced Text,Media & Culture,221,11,No,1,114,20.090909,7
45,BAREC_AlArabiya_Finance_00288_001,AlArabiya,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,337,12,No,11,41,28.083333,2
46,BAREC_AlKhaleej_Politics_0180_001,AlKhaleej,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,533,18,No,9,51,29.611111,16
47,BAREC_AlKhaleej_Finance_0028_001,AlKhaleej,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,249,31,No,3,37,8.032258,3
48,BAREC_AlKhaleej_Finance_0332_001,AlKhaleej,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,210,20,No,3,28,10.500000,0
49,BAREC_AlArabiya_Finance_00048_001,AlArabiya,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,355,16,No,11,40,22.187500,13

In [73]:
B_df['selected_sent_raw'] = None
B_df['selected_sent_word_count'] = None
B_df['selected_sent_words'] = None

for i, row in B_df.iterrows():
    directory = row['Directory']
    document = row['Document']

    annotations_file_path = (
        f"BAREC-10M/Data/Morphology_and_Readability/"
        f"{directory}/{document}.json"
    )

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)

    annotations = pd.DataFrame(annotations)

    selected_sentence_index = int(row['sampled_sentence_index'])

    selected_row = annotations.iloc[selected_sentence_index]

    raw_sentence = selected_row['raw_sents']
    word_count = selected_row['sents_word_count']
    words = selected_row['word']   # list of strings

    B_df.at[i, 'selected_sent_raw'] = raw_sentence
    B_df.at[i, 'selected_sent_word_count'] = word_count
    B_df.at[i, 'selected_sent_words'] = words

In [74]:
B_df = B_df[[
    'Directory',
    'Document',
    'sampled_sentence_index',
    'Source',
    'Book',
    'Author',
    'Domain',
    'Readership Group',
    'Text Category',
    'average sentence length',
    'selected_sent_raw',
    'selected_sent_word_count',
    'selected_sent_words'
]]

In [75]:
B_df.rename(columns={
    'average sentence length': 'average_sentence_length_per_doc',
}, inplace=True)

In [76]:
B_df

,Directory,Document,sampled_sentence_index,Source,Book,Author,Domain,Readership Group,Text Category,average_sentence_length_per_doc,selected_sent_raw,selected_sent_word_count,selected_sent_words
0,Majed,BAREC_Majed_2082_2019_004,15,Majed,Edition: 2082,#,Arts & Humanities,Foundational Text,Media & Culture,19.764706,10- أول محطة نووية في العالم لتوليد الطاقة الك...,23,"[10, -, أول, محطة, نووية, في, العالم, لتوليد, ..."
1,Majed,BAREC_Majed_0229_1983_011,124,Majed,Edition: 229,#,Arts & Humanities,Foundational Text,Media & Culture,6.837037,فكرة عبد الله الغامدي – جدة – السعودية,8,"[فكرة, عبد, الله, الغامدي, -, جدة, -, السعودية]"
2,Majed,BAREC_Majed_0670_1991_006,3,Majed,Edition: 670,#,Arts & Humanities,Foundational Text,Media & Culture,9.807018,قال زعيم استعماري وهو يخاطب الناس الذين يطالبو...,21,"[قال, زعيم, استعماري, وهو, يخاطب, الناس, الذين..."
3,Majed,BAREC_Majed_0670_1991_009,44,Majed,Edition: 670,#,Arts & Humanities,Foundational Text,Media & Culture,6.155844,إنها مجرد غلاف رقيق يخفي هذه الحضارة..,9,"[إنها, مجرد, غلاف, رقيق, يخفي, هذه, الحضارة, ...."
4,Majed,BAREC_Majed_0229_1983_027,13,Majed,Edition: 229,#,Arts & Humanities,Foundational Text,Media & Culture,9.923077,لكن المدينة بعيد والتنقل إليها والعود منها يوم...,18,"[لكن, المدينة, بعيد, والتنقل, إليها, والعود, م..."
5,Majed,BAREC_Majed_0670_1991_012,1,Majed,Edition: 670,#,Arts & Humanities,Foundational Text,Media & Culture,15.650000,•تقع جزيرة (تاهيتي) في غرب المحيط الهادي،,11,"[•, تقع, جزيرة, (, تاهيتي, ), في, غرب, المحيط,..."
6,Majed,BAREC_Majed_0836_1995_016,1,Majed,Edition: 836,#,Arts & Humanities,Foundational Text,Media & Culture,5.257143,بي بي لا تقف مستقيمة أبدًا..,8,"[بي, بي, لا, تقف, مستقيمة, أبدا, ., .]"
7,Majed,BAREC_Majed_1481_2007_006,14,Majed,Edition: 1481,#,Arts & Humanities,Foundational Text,Media & Culture,15.285714,والجميع لا يعرفون شيئًا عن هذا الخطر أو ما هي ...,17,"[والجميع, لا, يعرفون, شيئا, عن, هذا, الخطر, أو..."
8,AlArabiya,BAREC_AlArabiya_Culture_0274_001,6,AlArabiya News,Culture,#,Arts & Humanities,Advanced Text,Media & Culture,17.190476,"نت"" مع الصور هذه الشخصيات التي ""سرقت الأضواء"" ...",17,"[نت, "", مع, الصور, هذه, الشخصيات, التي, "", سرق..."
9,AlArabiya,BAREC_AlArabiya_Sports_00076_001,1,AlArabiya News,Sports,#,Arts & Humanities,Advanced Text,Media & Culture,24.250000,ورفع الفيصلي رصيده إلى 9 نقاط ليحقق العلامة ال...,23,"[ورفع, الفيصلي, رصيده, إلى, 9, نقاط, ليحقق, ال..."
10,ANERCorp,BAREC_ANERCorp_train_163,1,ANERCorp,#,#,Arts & Humanities,Advanced Text,Media & Culture,60.700000,"كما ارتفعت متحصلات الصادرات الخدمية بنسبة13 , ...",28,"[كما, ارتفعت, متحصلات, الصادرات, الخدمية, بنسب..."
11,AlArabiya,BAREC_AlArabiya_Culture_0269_001,1,AlArabiya News,Culture,#,Arts & Humanities,Advanced Text,Media & Culture,25.142857,وتدور أحداث المسلسل في صعيد مصر، ويناقش العمل ...,20,"[وتدور, أحداث, المسلسل, في, صعيد, مصر, ,, وينا..."
12,ANERCorp,BAREC_ANERCorp_train_012,12,ANERCorp,#,#,Arts & Humanities,Advanced Text,Media & Culture,18.937500,فكان صيادو الأسماك يتاجرون فيها ويبيعون الأسما...,16,"[فكان, صيادو, الأسماك, يتاجرون, فيها, ويبيعون,..."
13,Akhbarona,BAREC_Akhbarona_Religion_0167_001,13,Akhbarona News,Religion,#,Arts & Humanities,Advanced Text,Media & Culture,22.828571,وفي حالة فشل الزوجين في تحقيق مقوم حسن النية م...,12,"[وفي, حالة, فشل, الزوجين, في, تحقيق, مقوم, حسن..."
14,Akhbarona,BAREC_Akhbarona_Religion_0227_001,0,Akhbarona News,Religion,#,Arts & Humanities,Advanced Text,Media & Culture,32.774194,يتعرّض كثير من المسلمين للنسيان أو السّهو عند ...,24,"[يتعرض, كثير, من, المسلمين, للنسيان, أو, السهو..."
15,AlKhaleej,BAREC_AlKhaleej_Culture_0054_001,7,AlKhaleej News,Culture,#,Arts & Humanities,Advanced Text,Media & Culture,25.500000,وتوقع سلطان العميمي مدير أكاديمية الشعر بأبوظب...,30,"[وتوقع, سلطان, العميمي, مدير, أكاديمية, الشعر,..."
16,AlKhaleej,BAREC_AlKhaleej_Religion_0039_001,5,AlKhaleej News,Religion,#,Arts & Humanities,Advanced Text,Media & Culture,43.461538,"من هنا جاء التوجيه النبوي الكريم: ""من رأى منكم...",30,"[من, هنا, جاء, التوجيه, النبوي, الكريم, :, "", ..."
17,AlArabiya,BAREC_AlArabiya_Medical_0238_001,0,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,25.272727,"ذكرت جامعة ""لوند"" في السويد أن مسحوقاً من السب...",27,"[ذكرت, جامعة, "", لوند, "", في, السويد, أن, مسحو..."
18,AlArabiya,BAREC_AlArabiya_Tech_0037_001,2,AlArabiya News,Tech,#,STEM,Advanced Text,Media & Culture,26.000000,وكشف ناطق باسمها أن حوالي 25905 وحدات من هذا ا...,17,"[وكشف, ناطق, باسمها, أن, حوالي, 25905, وحدات, ..."
19,AlArabiya,BAREC_AlArabiya_Medical_0093_001,3,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,23.333333,وتأكدت أول إصابة بكورونا في كوريا في 20 من ماي...,18,"[وتأكدت, أول, إصابة, بكورونا, في, كوريا, في, 2..."
20,AlKhaleej,BAREC_AlKhaleej_Tech_0318_001,1,AlKhaleej News,Tech,#,STEM,Advanced Text,Media & Culture,36.625000,ويتناول التقرير مشهد استخدام تكنولوجيا المعلوم...,15,"[ويتناول, التقرير, مشهد, استخدام, تكنولوجيا, ا..."
21,Akhbarona,BAREC_Akhbarona_Medical_00271_001,2,Akhbarona News,Medical,#,STEM,Advanced Text,Media & Culture,38.166667,"هذا ما نشرته مجلة ""بلوس بايولوجي"" المتخصصة.",10,"[هذا, ما, نشرته, مجلة, "", بلوس, بايولوجي, "", ا..."
22,Akhbarona,BAREC_Akhbarona_Tech_00116_001,6,Akhbarona News,Tech,#,STEM,Advanced Text,Media & Culture,37.444444,ويملك الجهاز أجهزة استشعار متعددة مثل جهاز است...,27,"[ويملك, الجهاز, أجهزة, استشعار, متعددة, مثل, ج..."
23,Akhbarona,BAREC_Akhbarona_Tech_00050_001,14,Akhbarona News,Tech,#,STEM,Advanced Text,Media & Culture,26.315789,وتتناغم عجلة القيادة عالية الأداء بألياف DINAM...,19,"[وتتناغم, عجلة, القيادة, عالية, الأداء, بألياف..."
24,Akhbarona,BAREC_Akhbarona_Medical_00025_001,0,Akhbarona News,Medical,#,STEM,Advanced Text,Media & Culture,22.888889,تعد حساسية المكسرات واحدة من أنواع حساسية الأغ...,27,"[تعد, حساسية, المكسرات, واحدة, من, أنواع, حساس..."
25,Akhbarona,BAREC_Akhbarona_Tech_00271_001,2,Akhbarona News,Tech,#,STEM,Advanced Text,Media & Culture,26.000000,2 - يجب ان تنتبه الى نظافة الاقطاب والكابلات، ...,29,"[2, -, يجب, ان, تنتبه, الى, نظافة, الاقطاب, وا..."
26,AlKhaleej,BAREC_AlKhaleej_Medical_0005_001,1,AlKhaleej News,Medical,#,STEM,Advanced Text,Media & Culture,26.500000,وتعاقدت العيادة مع كبريات شركات التأمين في الد...,19,"[وتعاقدت, العيادة, مع, كبريات, شركات, التأمين,..."
27,AlArabiya,BAREC_AlArabiya_Medical_0025_001,42,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,15.021277,استخدمي ملطفا مرطبا جيدا بعد ذلك، أو صبي الخل ...,25,"[استخدمي, ملطفا, مرطبا, جيدا, بعد, ذلك, ,, أو,..."
28,AlKhaleej,BAREC_AlKhaleej_Tech_0195_001,1,AlKhaleej News,Tech,#,STEM,Advanced Text,Media & Culture,42.000000,كما أشاد سموه بالتنظيم الجيد لمعرض الشرق الأوس...,16,"[كما, أشاد, سموه, بالتنظيم, الجيد, لمعرض, الشر..."
29,AlArabiya,BAREC_AlArabiya_Tech_0331_001,3,AlArabiya News,Tech,#,STEM,Advanced Text,Media & Culture,32.428571,بريسم أو ما تطلق عليه وكالة الأمن القومي اسم U...,21,"[بريسم, أو, ما, تطلق, عليه, وكالة, الأمن, القو..."
30,Akhbarona,BAREC_Akhbarona_Tech_00152_001,1,Akhbarona News,Tech,#,STEM,Advanced Text,Media & Culture,28.000000,وكتبت الشركة في مدونتها الرسمية أن هذا التفعيل...,14,"[وكتبت, الشركة, في, مدونتها, الرسمية, أن, هذا,..."
31,Akhbarona,BAREC_Akhbarona_Medical_00266_001,1,Akhbarona News,Medical,#,STEM,Advanced Text,Media & Culture,31.000000,وبينت الأبحاث أن النظام الغذائي الغني بالدهون ...,12,"[وبينت, الأبحاث, أن, النظام, الغذائي, الغني, ب..."
32,AlArabiya,BAREC_AlArabiya_Medical_0298_001,0,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,22.750000,بدأ الجيش البرازيلي تنفيذ برنامج جديد لتوعية ا...,21,"[بدأ, الجيش, البرازيلي, تنفيذ, برنامج, جديد, ل..."
33,AlKhaleej,BAREC_AlKhaleej_Medical_0300_001,2,AlKhaleej News,Medical,#,STEM,Advanced Text,Media & Culture,50.333333,وتطرق المستشار حمد الظاهري، وكيل أول نيابة بدا...,20,"[وتطرق, المستشار, حمد, الظاهري, ,, وكيل, أول, ..."
34,AlKhaleej,BAREC_AlKhaleej_Politics_0323_001,12,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,27.411765,وفي إقليم قندز اعتقلت إيساف والقوات الأفغانية ...,27,"[وفي, إقليم, قندز, اعتقلت, إيساف, والقوات, الأ..."
35,AlArabiya,BAREC_AlArabiya_Finance_00126_001,2,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,74.125000,وفي المقابل، انخفض أبوظبي 0.12%، كما انخفض سوق...,19,"[وفي, المقابل, ,, انخفض, أبوظبي, 0, ., 12, %, ..."
36,AlKhaleej,BAREC_AlKhaleej_Politics_0255_001,4,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,58.266667,وقال الشاطر عبر حسابه على موقع التواصل الاجتما...,16,"[وقال, الشاطر, عبر, حسابه, على, موقع, التواصل,..."
37,Majarra,BAREC_Majarra_Stanford_Social_Innovation_Revie...,14,Majarra,How Does Building an Effective Volunteer Commu...,#,Social Sciences,Advanced Text,Media & Culture,26.190476,ويشكّل محتواه الذي أنشأه البشر المصدر الرئيسي ...,19,"[ويشكل, محتواه, الذي, أنشأه, البشر, المصدر, ال..."
38,AlKhaleej,BAREC_AlKhaleej_Politics_0226_001,2,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,30.812500,وكان قراقع قد أوضح، أن معلومات أولية وصلت من ق...,30,"[وكان, قراقع, قد, أوضح, ,, أن, معلومات, أولية,..."
39,AlKhaleej,BAREC_AlKhaleej_Finance_0240_001,29,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,6.404255,"230 درهماً، داماك العقارية دبي ""ش .",9,"[230, درهما, ,, داماك, العقارية, دبي, "", ش, .]"
40,Akhbarona,BAREC_Akhbarona_Finance_0137_001,18,Akhbarona News,Finance,#,Social Sciences,Advanced Text,Media & Culture,42.954545,بينما في الجارة إسبانيا التي تعد أول المستفيدي...,30,"[بينما, في, الجارة, إسبانيا, التي, تعد, أول, ا..."
41,AlKhaleej,BAREC_AlKhaleej_Finance_0059_001,3,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,7.666667,1 مليار درهم لتصل القيمة السوقية الى 58 .,9,"[1, مليار, درهم, لتصل, القيمة, السوقية, الى, 5..."
42,WikiNews,BAREC_WikiNews_economy_7_001,5,WikiNews,Economy,#,Social Sciences,Advanced Text,Media & Culture,23.083333,وَأَكَّدَ الْمُتَحَدِّثُ بِاسْمِ وِزَارَةِ الْ...,17,"[وأكد, المتحدث, باسم, وزارة, الخارجية, الصينية..."
43,AlKhaleej,BAREC_AlKhaleej_Finance_0082_001,0,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,10.960000,واصلت أسواق الأسهم التراجع البطيء، أمس، ليغلق ...,15,"[واصلت, أسواق, الأسهم, التراجع, البطيء, ,, أمس..."
44,Akhbarona,BAREC_Akhbarona_Finance_0045_001,7,Akhbarona News,Finance,#,Social Sciences,Advanced Text,Media & Culture,20.090909,والنتيجة بسلا: 25 في المائة نسبة النجاح عِوَض ...,14,"[والنتيجة, بسلا, :, 25, في, المائة, نسبة, النج..."
45,AlArabiya,BAREC_AlArabiya_Finance_00288_001,2,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,28.083333,"وقال مسؤول في الوزارة إن إعصاري ""هارفي"" و""إيرم...",23,"[وقال, مسؤول, في, الوزارة, إن, إعصاري, "", هارف..."
46,AlKhaleej,BAREC_AlKhaleej_Politics_0180_001,16,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,29.611111,أما صحيفة يديعوت فقالت إن المسؤولين الإسرائيلي...,20,"[أما, صحيفة, يديعوت, فقالت, إن, المسؤولين, الإ..."
47,AlKhaleej,BAREC_AlKhaleej_Finance_0028_001,3,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,8.032258,165 مليون درهم أوصلت القيمة السوقية إلى 58 .,9,"[165, مليون, درهم, أوصلت, القيمة, السوقية, إلى..."
48,AlKhaleej,BAREC_AlKhaleej_Finance_0332_001,0,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,10.500000,انخفض مؤشر سوق أبوظبي للأوراق المالية أمس بنسب...,10,"[انخفض, مؤشر, سوق, أبوظبي, للأوراق, المالية, أ..."
49,AlArabiya,BAREC_AlArabiya_Finance_00048_001,13,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,22.187500,وتسببت صراعات قريبة والمشاكل السياسية في لبنان...,16,"[وتسببت, صراعات, قريبة, والمشاكل, السياسية, في..."

In [77]:
B_df.to_json('sampled_MC_sentences.json', orient='records', force_ascii=False, indent=4)

In [78]:
metadata['Text Category'].value_counts()

Text Category
Media & Culture                                  7122
Educational Materials; Language & Linguistics    4709
Academic                                         4301
Literature; Art & Music                          3974
Religion & Philosophy                             254
Encyclopedic                                      175
Name: count, dtype: int64

In [79]:
ELL_df = metadata[metadata['Text Category']=='Educational Materials; Language & Linguistics']
print("Educational Materials; Language & Linguistics")
print("==========================")
print(f"Number of documents: {ELL_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {ELL_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {ELL_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {ELL_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{ELL_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{ELL_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{ELL_df['average sentence length'].describe().to_dict()}")
print("==========================")

Educational Materials; Language & Linguistics
==========================
Number of documents: 4709
--------------------------
Number of sentences: 176003
--------------------------
Number of unique books: 153
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Arts & Humanities': 2644, 'Social Sciences': 1143, 'STEM': 922}
--------------------------
Readership Group distribution:
{'Specialized Text': 2131, 'Advanced Text': 1700, 'Foundational Text': 878}
--------------------------
Average sentence length distribution:
{'count': 4709.0, 'mean': 40.3278243679819, 'std': 36.4060742197123, 'min': 1.6666666666666667, '25%': 9.725806451612904, '50%': 20.12121212121212, '75%': 71.44444444444444, 'max': 233.0}
==========================

In [80]:
ELL_AH_df = ELL_df[ELL_df['Domain']=='Arts & Humanities']
print("Educational Materials; Language & Linguistics - Arts & Humanities")
print("==========================")
print(f"Number of documents: {ELL_AH_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {ELL_AH_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {ELL_AH_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {ELL_AH_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{ELL_AH_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{ELL_AH_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{ELL_AH_df['average sentence length'].describe().to_dict()}")
print("==========================")

Educational Materials; Language & Linguistics - Arts & Humanities
==========================
Number of documents: 2644
--------------------------
Number of sentences: 125647
--------------------------
Number of unique books: 61
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Arts & Humanities': 2644}
--------------------------
Readership Group distribution:
{'Advanced Text': 1107, 'Specialized Text': 961, 'Foundational Text': 576}
--------------------------
Average sentence length distribution:
{'count': 2644.0, 'mean': 31.706006481763776, 'std': 36.29987302225113, 'min': 2.6548672566371683, '25%': 8.173469387755102, '50%': 12.604166666666668, '75%': 43.035714285714285, 'max': 233.0}
==========================

In [84]:
sampled_ELL_AH_foundational_df = ELL_AH_df[(ELL_AH_df['Readership Group']=='Foundational Text') & (ELL_AH_df['longest_sent_len'] >= 8) & (ELL_AH_df['shortest_sent_len'] <= 30) & (ELL_AH_df['Sentence Count'] > 10)].sample(5, random_state=42)
sampled_ELL_AH_advanced_df = ELL_AH_df[(ELL_AH_df['Readership Group']=='Advanced Text') & (ELL_AH_df['longest_sent_len'] >= 8) & (ELL_AH_df['shortest_sent_len'] <= 30) & (ELL_AH_df['Sentence Count'] > 10)].sample(6, random_state=42)
sampled_ELL_AH_special_df = ELL_AH_df[(ELL_AH_df['Readership Group']=='Specialized Text') & (ELL_AH_df['longest_sent_len'] >= 8) & (ELL_AH_df['shortest_sent_len'] <= 30) & (ELL_AH_df['Sentence Count'] > 10)].sample(6, random_state=42)

In [85]:
sampled_ELL_AH_df = pd.concat([sampled_ELL_AH_foundational_df, sampled_ELL_AH_advanced_df, sampled_ELL_AH_special_df], ignore_index=True)

In [86]:
sampled_ELL_AH_sentences_indices = []
for i, row in sampled_ELL_AH_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_ELL_AH_sentences_indices.append(sampled_index)
print(sampled_ELL_AH_sentences_indices)

[47, 32, 37, 0, 57, 2, 37, 107, 8, 0, 11, 26, 3, 11, 3, 16, 1]

In [87]:
sampled_ELL_AH_df['sampled_sentence_index'] = sampled_ELL_AH_sentences_indices

In [88]:
ELL_ST_df = ELL_df[ELL_df['Domain']=='STEM']
print("Educational Materials; Language & Linguistics - STEM")
print("==========================")
print(f"Number of documents: {ELL_ST_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {ELL_ST_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {ELL_ST_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {ELL_ST_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{ELL_ST_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{ELL_ST_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{ELL_ST_df['average sentence length'].describe().to_dict()}")
print("==========================")

Educational Materials; Language & Linguistics - STEM
==========================
Number of documents: 922
--------------------------
Number of sentences: 8695
--------------------------
Number of unique books: 49
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'STEM': 922}
--------------------------
Readership Group distribution:
{'Specialized Text': 662, 'Advanced Text': 175, 'Foundational Text': 85}
--------------------------
Average sentence length distribution:
{'count': 922.0, 'mean': 71.35990994101527, 'std': 21.467599100210514, 'min': 14.6, '25%': 61.51136363636364, '50%': 70.22222222222223, '75%': 81.09375, 'max': 169.0}
==========================

In [89]:
sampled_ELL_ST_foundational_df = ELL_ST_df[(ELL_ST_df['Readership Group']=='Foundational Text') & (ELL_ST_df['longest_sent_len'] >= 8) & (ELL_ST_df['shortest_sent_len'] <= 30) & (ELL_ST_df['Sentence Count'] > 10)].sample(5, random_state=42)
sampled_ELL_ST_advanced_df = ELL_ST_df[(ELL_ST_df['Readership Group']=='Advanced Text') & (ELL_ST_df['longest_sent_len'] >= 8) & (ELL_ST_df['shortest_sent_len'] <= 30) & (ELL_ST_df['Sentence Count'] > 10)].sample(6, random_state=42)
sampled_ELL_ST_special_df = ELL_ST_df[(ELL_ST_df['Readership Group']=='Specialized Text') & (ELL_ST_df['longest_sent_len'] >= 8) & (ELL_ST_df['shortest_sent_len'] <= 30) & (ELL_ST_df['Sentence Count'] > 10)].sample(6, random_state=42)

In [90]:
sampled_ELL_ST_df = pd.concat([sampled_ELL_ST_foundational_df, sampled_ELL_ST_advanced_df, sampled_ELL_ST_special_df], ignore_index=True)

In [91]:
sampled_ELL_ST_sentences_indices = []
for i, row in sampled_ELL_ST_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_ELL_ST_sentences_indices.append(sampled_index)
print(sampled_ELL_ST_sentences_indices)

[8, 0, 9, 20, 0, 3, 10, 8, 8, 1, 0, 16, 0, 14, 13, 4, 8]

In [92]:
sampled_ELL_ST_df['sampled_sentence_index'] = sampled_ELL_ST_sentences_indices

In [93]:
ELL_SS_df = ELL_df[ELL_df['Domain']=='Social Sciences']
print("Educational Materials; Language & Linguistics - Social Sciences")
print("==========================")
print(f"Number of documents: {ELL_SS_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {ELL_SS_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {ELL_SS_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {ELL_SS_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{ELL_SS_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{ELL_SS_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{ELL_SS_df['average sentence length'].describe().to_dict()}")
print("==========================")

Educational Materials; Language & Linguistics - Social Sciences
==========================
Number of documents: 1143
--------------------------
Number of sentences: 41661
--------------------------
Number of unique books: 45
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Social Sciences': 1143}
--------------------------
Readership Group distribution:
{'Specialized Text': 508, 'Advanced Text': 418, 'Foundational Text': 217}
--------------------------
Average sentence length distribution:
{'count': 1143.0, 'mean': 35.23990100212361, 'std': 32.67019027449575, 'min': 1.6666666666666667, '25%': 10.487288135593221, '50%': 15.512820512820513, '75%': 67.0, 'max': 157.0}
==========================

In [94]:
sampled_ELL_SS_foundational_df = ELL_SS_df[(ELL_SS_df['Readership Group']=='Foundational Text') & (ELL_SS_df['longest_sent_len'] >= 8) & (ELL_SS_df['shortest_sent_len'] <= 30) & (ELL_SS_df['Sentence Count'] > 10)].sample(5, random_state=42)
sampled_ELL_SS_advanced_df = ELL_SS_df[(ELL_SS_df['Readership Group']=='Advanced Text') & (ELL_SS_df['longest_sent_len'] >= 8) & (ELL_SS_df['shortest_sent_len'] <= 30) & (ELL_SS_df['Sentence Count'] > 10)].sample(5, random_state=42)
sampled_ELL_SS_special_df = ELL_SS_df[(ELL_SS_df['Readership Group']=='Specialized Text') & (ELL_SS_df['longest_sent_len'] >= 8) & (ELL_SS_df['shortest_sent_len'] <= 30) & (ELL_SS_df['Sentence Count'] > 10)].sample(6, random_state=42)

In [95]:
sampled_ELL_SS_df = pd.concat([sampled_ELL_SS_foundational_df, sampled_ELL_SS_advanced_df, sampled_ELL_SS_special_df], ignore_index=True)

In [96]:
sampled_ELL_SS_sentences_indices = []
for i, row in sampled_ELL_SS_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_ELL_SS_sentences_indices.append(sampled_index)
print(sampled_ELL_SS_sentences_indices)

[1, 98, 0, 102, 0, 31, 14, 101, 0, 0, 8, 3, 15, 17, 4, 7]

In [97]:
sampled_ELL_SS_df['sampled_sentence_index'] = sampled_ELL_SS_sentences_indices

In [98]:
C_df = pd.concat([sampled_ELL_AH_df, sampled_ELL_ST_df, sampled_ELL_SS_df], ignore_index=True)
C_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,shortest_sent_len,longest_sent_len,average sentence length,sampled_sentence_index
0,BAREC_TunisCurriculum_Pri_03_reading_P2_001,TunisCurriculum,Tunis Curriculum,Grade 3 Arabic Language,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,587,55,No,1,47,10.672727,47
1,BAREC_TunisCurriculum_Pri_04_reading_041,TunisCurriculum,Tunis Curriculum,Grade 4 Arabic Language,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,589,45,No,1,39,13.088889,32
2,BAREC_Curriculum_03_arb_t1_u01_006,Curriculum,Emarati Curriculum,Grade 3 Arabic Language,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,493,92,No,1,20,5.358696,37
3,BAREC_TunisCurriculum_Pri_04_reading_013,TunisCurriculum,Tunis Curriculum,Grade 4 Arabic Language,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,610,51,No,1,38,11.960784,0
4,BAREC_Curriculum_04_arb_t1_u03_005,Curriculum,Emarati Curriculum,Grade 4 Arabic Language,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,600,82,No,1,35,7.317073,57
5,BAREC_Curriculum_08_slm_t1_u01_006,Curriculum,Emarati Curriculum,Grade 8 Islamic Studies,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,614,65,No,1,105,9.446154,2
6,BAREC_Curriculum_07_arb_t2_u04_007,Curriculum,Emarati Curriculum,Grade 7 Arabic Language,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,625,56,No,1,100,11.160714,37
7,BAREC_Curriculum_05_arb_t1_u02_002,Curriculum,Emarati Curriculum,Grade 5 Arabic Language,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,604,110,No,1,33,5.490909,107
8,BAREC_Curriculum_09_arb_t1_u04_001,Curriculum,Emarati Curriculum,Grade 9 Arabic Language,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,1053,33,Yes,2,75,31.909091,8
9,BAREC_ArabicMMLU_Group_16_015,ArabicMMLU,ArabicMMLU,#,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,475,20,Yes,17,41,23.750000,0
10,BAREC_ArabicMMLU_Group_20_011,ArabicMMLU,ArabicMMLU,#,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,623,20,Yes,25,33,31.150000,11
11,BAREC_Curriculum_10_arb_a1_u01_015,Curriculum,Emarati Curriculum,Grade 10 Arabic Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,636,32,No,1,96,19.875000,26
12,BAREC_Curriculum_10_arb_a1_u02_029,Curriculum,Emarati Curriculum,Grade 10 Arabic Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,624,25,No,2,130,24.960000,3
13,BAREC_Curriculum_11_arb_a1_u01_006,Curriculum,Emarati Curriculum,Grade 11 Arabic Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,605,80,No,2,31,7.562500,11
14,BAREC_Curriculum_11_arb_t1_u04_011,Curriculum,Emarati Curriculum,Grade 11 Arabic Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,601,23,No,2,94,26.130435,3
15,BAREC_Curriculum_10_slm_t1_u03_005,Curriculum,Emarati Curriculum,Grade 10 Islamic Studies,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,600,78,No,1,36,7.692308,16
16,BAREC_Curriculum_11_arb_t1_u02_024,Curriculum,Emarati Curriculum,Grade 11 Arabic Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,640,56,No,2,72,11.428571,1
17,BAREC_ArabicMMLU_Group_7_012,ArabicMMLU,ArabicMMLU,#,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,551,28,Yes,15,33,19.678571,8
18,BAREC_ArabicMMLU_Group_8_004,ArabicMMLU,ArabicMMLU,#,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,521,20,Yes,15,43,26.050000,0
19,BAREC_DARES_Digital_Skills_G4_002,DARES,DARES,G4 - Digital_Skills,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,605,12,ST2&3,29,89,50.416667,9
20,BAREC_ArabicMMLU_Group_8_011,ArabicMMLU,ArabicMMLU,#,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,812,24,Yes,25,73,33.833333,20
21,BAREC_ArabicMMLU_Group_7_005,ArabicMMLU,ArabicMMLU,#,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,369,20,Yes,13,34,18.450000,0
22,BAREC_ArabicMMLU_Group_23_007,ArabicMMLU,ArabicMMLU,#,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,472,20,Yes,16,53,23.600000,3
23,BAREC_DARES_Science_G8_2_006,DARES,DARES,G8 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,610,12,No,22,117,50.833333,10
24,BAREC_DARES_Science_G8_3_004,DARES,DARES,G8 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,626,11,No,23,89,56.909091,8
25,BAREC_DARES_Science_G8_2_004,DARES,DARES,G8 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,624,11,No,24,90,56.727273,8
26,BAREC_ArabicMMLU_Group_23_011,ArabicMMLU,ArabicMMLU,#,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,733,20,Yes,27,52,36.650000,1
27,BAREC_ArabicMMLU_Group_23_021,ArabicMMLU,ArabicMMLU,#,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,648,20,Yes,25,43,32.400000,0
28,BAREC_ArabicMMLU_Group_25_005,ArabicMMLU,ArabicMMLU,#,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,628,20,Yes,19,50,31.400000,16
29,BAREC_DARES_Biology_G11_006,DARES,DARES,G11 - Biology,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,604,12,No,27,85,50.333333,0
30,BAREC_ArabicMMLU_Group_25_011,ArabicMMLU,ArabicMMLU,#,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,665,20,Yes,18,54,33.250000,14
31,BAREC_ArabicMMLU_Group_25_001,ArabicMMLU,ArabicMMLU,#,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,622,20,Yes,18,42,31.100000,13
32,BAREC_DARES_Chemistry_G11_006,DARES,DARES,G11 - Chemistry,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,640,11,No,17,79,58.181818,4
33,BAREC_DARES_Data_Science_G11_004,DARES,DARES,G11 - Data_Science,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,627,11,No,23,103,57.000000,8
34,BAREC_ArabicMMLU_Group_9_013,ArabicMMLU,ArabicMMLU,#,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,561,20,Yes,24,34,28.050000,1
35,BAREC_Curriculum_01_soc_t2_u04_002,Curriculum,Emarati Curriculum,Grade 1 Social Sciences,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,610,99,No,1,19,6.161616,98
36,BAREC_Curriculum_04_soc_t2_u05_008,Curriculum,Emarati Curriculum,Grade 4 Social Sciences,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,602,43,No,2,46,14.000000,0
37,BAREC_Curriculum_02_soc_t3_u09_001,Curriculum,Emarati Curriculum,Grade 2 Social Sciences,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,604,111,No,1,21,5.441441,102
38,BAREC_Curriculum_04_soc_t2_u04_006,Curriculum,Emarati Curriculum,Grade 4 Social Sciences,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,604,59,No,1,51,10.237288,0
39,BAREC_Curriculum_08_soc_t3_u08_002,Curriculum,Emarati Curriculum,Grade 8 Social Sciences,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,622,80,No,1,51,7.775000,31
40,BAREC_Curriculum_06_soc_t2_u05_011,Curriculum,Emarati Curriculum,Grade 6 Social Sciences,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,145,20,No,1,41,7.250000,14
41,BAREC_Curriculum_09_slm_t1_u02_001,Curriculum,Emarati Curriculum,Grade 9 Social Sciences,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,977,110,Yes,1,29,8.881818,101
42,BAREC_ArabicMMLU_Group_17_001,ArabicMMLU,ArabicMMLU,#,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,386,20,Yes,14,26,19.300000,0
43,BAREC_Curriculum_06_soc_t2_u04_004,Curriculum,Emarati Curriculum,Grade 6 Social Sciences,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,606,45,No,1,50,13.466667,0
44,BAREC_Curriculum_11_soc_t3_u10_009,Curriculum,Emarati Curriculum,Grade 11 Social Sciences,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,600,37,No,1,67,16.216216,8
45,BAREC_Curriculum_12_soc_t1_u02_005,Curriculum,Emarati Curriculum,Grade 12 Social Sciences,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,600,33,No,1,95,18.181818,3
46,BAREC_Curriculum_10_soc_t2_u09_003,Curriculum,Emarati Curriculum,Grade 10 Social Sciences,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,604,56,No,1,67,10.785714,15
47,BAREC_ArabicMMLU_Group_32_012,ArabicMMLU,ArabicMMLU,#,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,667,20,Yes,30,54,33.350000,17
48,BAREC_ArabicMMLU_Group_31_002,ArabicMMLU,ArabicMMLU,#,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,692,20,Yes,27,47,34.600000,4
49,BAREC_ArabicMMLU_Group_30_002,ArabicMMLU,ArabicMMLU,#,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,932,20,Yes,25,108,46.600000,7

In [99]:
C_df['selected_sent_raw'] = None
C_df['selected_sent_word_count'] = None
C_df['selected_sent_words'] = None

for i, row in C_df.iterrows():
    directory = row['Directory']
    document = row['Document']

    annotations_file_path = (
        f"BAREC-10M/Data/Morphology_and_Readability/"
        f"{directory}/{document}.json"
    )

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)

    annotations = pd.DataFrame(annotations)

    selected_sentence_index = int(row['sampled_sentence_index'])

    selected_row = annotations.iloc[selected_sentence_index]

    raw_sentence = selected_row['raw_sents']
    word_count = selected_row['sents_word_count']
    words = selected_row['word']   # list of strings

    C_df.at[i, 'selected_sent_raw'] = raw_sentence
    C_df.at[i, 'selected_sent_word_count'] = word_count
    C_df.at[i, 'selected_sent_words'] = words

In [100]:
C_df = C_df[[
    'Directory',
    'Document',
    'sampled_sentence_index',
    'Source',
    'Book',
    'Author',
    'Domain',
    'Readership Group',
    'Text Category',
    'average sentence length',
    'selected_sent_raw',
    'selected_sent_word_count',
    'selected_sent_words'
]]

In [101]:
C_df.rename(columns={
    'average sentence length': 'average_sentence_length_per_doc',
}, inplace=True)

In [102]:
C_df.to_json('sampled_ELL_sentences.json', orient='records', force_ascii=False, indent=4)

In [103]:
metadata['Text Category'].value_counts()

Text Category
Media & Culture                                  7122
Educational Materials; Language & Linguistics    4709
Academic                                         4301
Literature; Art & Music                          3974
Religion & Philosophy                             254
Encyclopedic                                      175
Name: count, dtype: int64

In [104]:
AC_df = metadata[metadata['Text Category']=='Academic']
print("Academic")
print("==========================")
print(f"Number of documents: {AC_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {AC_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {AC_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {AC_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{AC_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{AC_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{AC_df['average sentence length'].describe().to_dict()}")
print("==========================")

Academic
==========================
Number of documents: 4301
--------------------------
Number of sentences: 90235
--------------------------
Number of unique books: 1389
--------------------------
Number of unique authors: 1001
--------------------------
Domain distribution:
{'STEM': 2435, 'Social Sciences': 1783, 'Arts & Humanities': 83}
--------------------------
Readership Group distribution:
{'Specialized Text': 4213, 'Advanced Text': 79, 'Foundational Text': 9}
--------------------------
Average sentence length distribution:
{'count': 4301.0, 'mean': 34.18488759420031, 'std': 13.131808815146508, 'min': 4.269565217391304, '25%': 25.0, '50%': 33.421052631578945, '75%': 40.4, 'max': 185.6}
==========================

In [105]:
AC_AH_df = AC_df[AC_df['Domain']=='Arts & Humanities']
print("Academic - Arts & Humanities")
print("==========================")
print(f"Number of documents: {AC_AH_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {AC_AH_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {AC_AH_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {AC_AH_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{AC_AH_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{AC_AH_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{AC_AH_df['average sentence length'].describe().to_dict()}")
print("==========================")

Academic - Arts & Humanities
==========================
Number of documents: 83
--------------------------
Number of sentences: 1802
--------------------------
Number of unique books: 83
--------------------------
Number of unique authors: 59
--------------------------
Domain distribution:
{'Arts & Humanities': 83}
--------------------------
Readership Group distribution:
{'Specialized Text': 79, 'Advanced Text': 4}
--------------------------
Average sentence length distribution:
{'count': 83.0, 'mean': 31.188017042231646, 'std': 22.67701525021513, 'min': 11.767441860465116, '25%': 21.682065217391305, '50%': 25.61904761904762, '75%': 34.7, 'max': 185.6}
==========================

In [106]:
sampled_AC_AH_advanced_df = AC_AH_df[(AC_AH_df['Readership Group']=='Advanced Text') & (AC_AH_df['longest_sent_len'] >= 8) & (AC_AH_df['shortest_sent_len'] <= 30) & (AC_AH_df['Sentence Count'] > 10)].sample(4, random_state=42)
sampled_AC_AH_special_df = AC_AH_df[(AC_AH_df['Readership Group']=='Specialized Text') & (AC_AH_df['longest_sent_len'] >= 8) & (AC_AH_df['shortest_sent_len'] <= 30) & (AC_AH_df['Sentence Count'] > 10)].sample(12, random_state=42)

In [107]:
sampled_AC_AH_df = pd.concat([sampled_AC_AH_advanced_df, sampled_AC_AH_special_df], ignore_index=True)

In [108]:
sampled_AC_AH_sentences_indices = []
for i, row in sampled_AC_AH_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_AC_AH_sentences_indices.append(sampled_index)
print(sampled_AC_AH_sentences_indices)

[16, 13, 17, 24, 4, 2, 5, 7, 18, 46, 5, 15, 14, 1, 18, 17]

In [109]:
sampled_AC_AH_df['sampled_sentence_index'] = sampled_AC_AH_sentences_indices

In [110]:
AC_ST_df = AC_df[AC_df['Domain']=='STEM']
print("Academic - STEM")
print("==========================")
print(f"Number of documents: {AC_ST_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {AC_ST_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {AC_ST_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {AC_ST_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{AC_ST_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{AC_ST_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{AC_ST_df['average sentence length'].describe().to_dict()}")
print("==========================")

Academic - STEM
==========================
Number of documents: 2435
--------------------------
Number of sentences: 42324
--------------------------
Number of unique books: 274
--------------------------
Number of unique authors: 190
--------------------------
Domain distribution:
{'STEM': 2435}
--------------------------
Readership Group distribution:
{'Specialized Text': 2392, 'Advanced Text': 34, 'Foundational Text': 9}
--------------------------
Average sentence length distribution:
{'count': 2435.0, 'mean': 38.80142923324701, 'std': 11.955880682021828, 'min': 6.740259740259741, '25%': 32.3078947368421, '50%': 37.35294117647059, '75%': 44.142857142857146, 'max': 105.66666666666667}
==========================

In [111]:
sampled_AC_ST_foundational_df = AC_ST_df[(AC_ST_df['Readership Group']=='Foundational Text') & (AC_ST_df['longest_sent_len'] >= 8) & (AC_ST_df['shortest_sent_len'] <= 30) & (AC_ST_df['Sentence Count'] > 10)].sample(5, random_state=42)
sampled_AC_ST_advanced_df = AC_ST_df[(AC_ST_df['Readership Group']=='Advanced Text') & (AC_ST_df['longest_sent_len'] >= 8) & (AC_ST_df['shortest_sent_len'] <= 30) & (AC_ST_df['Sentence Count'] > 10)].sample(5, random_state=42)
sampled_AC_ST_special_df = AC_ST_df[(AC_ST_df['Readership Group']=='Specialized Text') & (AC_ST_df['longest_sent_len'] >= 8) & (AC_ST_df['shortest_sent_len'] <= 30) & (AC_ST_df['Sentence Count'] > 10)].sample(7, random_state=42)

In [112]:
sampled_AC_ST_df = pd.concat([sampled_AC_ST_foundational_df, sampled_AC_ST_advanced_df, sampled_AC_ST_special_df], ignore_index=True)

In [113]:
sampled_AC_ST_sentences_indices = []
for i, row in sampled_AC_ST_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_AC_ST_sentences_indices.append(sampled_index)
print(sampled_AC_ST_sentences_indices)

[3, 17, 17, 73, 2, 1, 19, 7, 12, 1, 8, 6, 1, 16, 7, 5, 1]

In [114]:
sampled_AC_ST_df['sampled_sentence_index'] = sampled_AC_ST_sentences_indices

In [115]:
AC_SS_df = AC_df[AC_df['Domain']=='Social Sciences']
print("Academic - Social Sciences")
print("==========================")
print(f"Number of documents: {AC_SS_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {AC_SS_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {AC_SS_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {AC_SS_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{AC_SS_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{AC_SS_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{AC_SS_df['average sentence length'].describe().to_dict()}")
print("==========================")

Academic - Social Sciences
==========================
Number of documents: 1783
--------------------------
Number of sentences: 46109
--------------------------
Number of unique books: 1032
--------------------------
Number of unique authors: 779
--------------------------
Domain distribution:
{'Social Sciences': 1783}
--------------------------
Readership Group distribution:
{'Specialized Text': 1742, 'Advanced Text': 41}
--------------------------
Average sentence length distribution:
{'count': 1783.0, 'mean': 28.01969486550411, 'std': 11.385668890412788, 'min': 4.269565217391304, '25%': 20.436666666666667, '50%': 26.05, '75%': 32.91875, 'max': 134.75}
==========================

In [116]:
sampled_AC_SS_advanced_df = AC_SS_df[(AC_SS_df['Readership Group']=='Advanced Text') & (AC_SS_df['longest_sent_len'] >= 8) & (AC_SS_df['shortest_sent_len'] <= 30) & (AC_SS_df['Sentence Count'] > 10)].sample(7, random_state=42)
sampled_AC_SS_special_df = AC_SS_df[(AC_SS_df['Readership Group']=='Specialized Text') & (AC_SS_df['longest_sent_len'] >= 8) & (AC_SS_df['shortest_sent_len'] <= 30) & (AC_SS_df['Sentence Count'] > 10)].sample(10, random_state=42)

In [118]:
sampled_AC_SS_df = pd.concat([sampled_AC_SS_advanced_df, sampled_AC_SS_special_df], ignore_index=True)
sampled_AC_SS_df.shape

(17, 14)

In [119]:
sampled_AC_SS_sentences_indices = []
for i, row in sampled_AC_SS_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_AC_SS_sentences_indices.append(sampled_index)
print(sampled_AC_SS_sentences_indices)

[32, 1, 1, 14, 10, 12, 2, 7, 4, 3, 4, 13, 17, 12, 4, 9, 2]

In [120]:
sampled_AC_SS_df['sampled_sentence_index'] = sampled_AC_SS_sentences_indices

In [121]:
D_df = pd.concat([sampled_AC_AH_df, sampled_AC_ST_df, sampled_AC_SS_df], ignore_index=True)
D_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,shortest_sent_len,longest_sent_len,average sentence length,sampled_sentence_index
0,BAREC_Hindawi_58285828_001,Hindawi,Hindawi,History of Theatre in the Arab World,Said Ali Ismail,Arts & Humanities,Advanced Text,Academic,503,21,No,1,47,23.952381,16
1,BAREC_Hindawi_97969752_001,Hindawi,Hindawi,The Bell Voting Mystery,Ellen Wilkinson,Arts & Humanities,Advanced Text,Academic,501,19,No,1,50,26.368421,13
2,BAREC_Hindawi_42048057_001,Hindawi,Hindawi,Islam Without Borders,Yusuf Idris,Arts & Humanities,Advanced Text,Academic,518,19,No,4,73,27.263158,17
3,BAREC_Hindawi_90507395_001,Hindawi,Hindawi,Translator’s Guide (to the Most Difficult Comm...,Mohamed Anani,Arts & Humanities,Advanced Text,Academic,506,43,No,1,57,11.767442,24
4,BAREC_Hindawi_19204286_001,Hindawi,Hindawi,History of Greek Philosophy,Youssef Karam,Arts & Humanities,Specialized Text,Academic,505,21,No,1,129,24.047619,4
5,BAREC_Hindawi_96283142_001,Hindawi,Hindawi,Sudan from Ancient History to the Egyptian Mis...,Abdullah Hussein,Arts & Humanities,Specialized Text,Academic,571,18,No,4,128,31.722222,2
6,BAREC_Hindawi_39040372_001,Hindawi,Hindawi,"Language, Religion, and Tradition in the Life ...",Zaki Mubarak,Arts & Humanities,Specialized Text,Academic,548,14,No,3,114,39.142857,5
7,BAREC_Hindawi_14046425_001,Hindawi,Hindawi,The Story of Modern Philosophy,Zaki Najib Mahmoud and Ahmed Amin,Arts & Humanities,Specialized Text,Academic,521,11,No,2,151,47.363636,7
8,BAREC_Hindawi_59752571_001,Hindawi,Hindawi,Dialogues of Alfred North Whitehead,#,Arts & Humanities,Specialized Text,Academic,522,21,No,1,56,24.857143,18
9,BAREC_Kalima_لغات_الهند_001,Kalima,Kalima,The Languages of India,Gopal Halder,Arts & Humanities,Specialized Text,Academic,718,52,Yes,2,35,13.807692,46
10,BAREC_Hindawi_29318372_001,Hindawi,Hindawi,Studies on Poetry in the Ayyubid Era,Mohammed Kamil Hussein,Arts & Humanities,Specialized Text,Academic,504,12,No,4,107,42.000000,5
11,BAREC_Hindawi_64625053_001,Hindawi,Hindawi,Horizons of Philosophy,Fouad Zakaria,Arts & Humanities,Specialized Text,Academic,543,23,No,1,64,23.608696,15
12,BAREC_Hindawi_30719715_001,Hindawi,Hindawi,Religious Existentialism,Yamna Tarif al-Khouli,Arts & Humanities,Specialized Text,Academic,529,27,No,1,94,19.592593,14
13,BAREC_Hindawi_82405713_001,Hindawi,Hindawi,The Arabic Language in Europe,Philip de Tarrazi,Arts & Humanities,Specialized Text,Academic,512,17,No,1,76,30.117647,1
14,BAREC_Hindawi_97961385_001,Hindawi,Hindawi,Mental Storms,Muheeb Nasr,Arts & Humanities,Specialized Text,Academic,498,20,No,1,71,24.900000,18
15,BAREC_Hindawi_61731841_001,Hindawi,Hindawi,Philosophy in the Feminine Form,Rashid al-Alawi,Arts & Humanities,Specialized Text,Academic,502,20,No,5,59,25.100000,17
16,BAREC_Hindawi_85285919_001,Hindawi,Hindawi,Almond Borer,Mamoun Abdul Latif Al-Rahhal,STEM,Foundational Text,Academic,508,15,No,3,85,33.866667,3
17,BAREC_Hindawi_25029086_001,Hindawi,Hindawi,Plastic,Mamoun Abdul Latif Al-Rahhal,STEM,Foundational Text,Academic,510,19,No,1,76,26.842105,17
18,BAREC_Hindawi_74618628_001,Hindawi,Hindawi,Abu al-Eid with Seven Marks,Mamoun Abdul Latif Al-Rahhal,STEM,Foundational Text,Academic,511,19,No,5,93,26.894737,17
19,BAREC_Hindawi_13026818_001,Hindawi,Hindawi,Science in Seconds for Kids,Jane Potter,STEM,Foundational Text,Academic,519,77,No,1,36,6.740260,73
20,BAREC_Hindawi_92080696_001,Hindawi,Hindawi,I Am a Sardine Fish,Mamoun Abdul Latif Al-Rahhal,STEM,Foundational Text,Academic,533,27,No,3,71,19.740741,2
21,BAREC_Hindawi_94292572_001,Hindawi,Hindawi,Decoding,Phil Barden,STEM,Advanced Text,Academic,551,23,No,1,64,23.956522,1
22,BAREC_Hindawi_48350803_001,Hindawi,Hindawi,Knocking on Heaven’s Doors,Lisa Randall,STEM,Advanced Text,Academic,504,21,No,1,64,24.000000,19
23,BAREC_Hindawi_60714615_001,Hindawi,Hindawi,The Atom and Atomic Bombs,Ali Mustafa Meshrefa,STEM,Advanced Text,Academic,662,13,No,1,228,50.923077,7
24,BAREC_Hindawi_48405282_001,Hindawi,Hindawi,The Plains of Flight,Ahmed Abdel Salam al-Kirdani,STEM,Advanced Text,Academic,623,25,No,2,153,24.920000,12
25,BAREC_Hindawi_26973525_001,Hindawi,Hindawi,Six Impossible Things,John Griffin,STEM,Advanced Text,Academic,512,26,No,2,49,19.692308,1
26,BAREC_MedArabiQ_Y2_Anatomy_PDF_QA2_010,MedArabiQ,MedArabiQ,Y2 - Anatomy,#,STEM,Specialized Text,Academic,625,17,No,30,42,36.764706,8
27,BAREC_MedArabiQ_Y1_Statistics_Scanned_QA12_022,MedArabiQ,MedArabiQ,Y1 - Statistics,#,STEM,Specialized Text,Academic,625,21,No,15,38,29.761905,6
28,BAREC_MedArabiQ_Y1_Physics_Scanned_QA28_008,MedArabiQ,MedArabiQ,Y1 - Physics,#,STEM,Specialized Text,Academic,602,12,No,25,79,50.166667,1
29,BAREC_MedArabiQ_Y3_Physics_PDF_QA31_019,MedArabiQ,MedArabiQ,Y3 - Physics,#,STEM,Specialized Text,Academic,614,20,No,23,47,30.700000,16
30,BAREC_MedArabiQ_Y1_Statistics_Scanned_QA11_032,MedArabiQ,MedArabiQ,Y1 - Statistics,#,STEM,Specialized Text,Academic,638,15,No,25,73,42.533333,7
31,BAREC_MedArabiQ_Y1_Physiology_Scanned_QA3_019,MedArabiQ,MedArabiQ,Y1 - Physiology,#,STEM,Specialized Text,Academic,620,19,No,19,57,32.631579,5
32,BAREC_MedArabiQ_Y1_Cell Biology_Scanned_QA35_005,MedArabiQ,MedArabiQ,Y1 - Cell Biology,#,STEM,Specialized Text,Academic,627,24,No,19,35,26.125000,1
33,BAREC_Hindawi_46363693_001,Hindawi,Hindawi,Popular Games of Iraqi Boys,Abdul Sattar al-Qurghuli,Social Sciences,Advanced Text,Academic,512,34,No,1,58,15.058824,32
34,BAREC_Hindawi_39490260_001,Hindawi,Hindawi,Africa,Mohammed Riyad and Kawthar Abdul Rasool,Social Sciences,Advanced Text,Academic,631,33,Yes,1,45,19.121212,1
35,BAREC_Hindawi_20271796_001,Hindawi,Hindawi,The Idea Machine,Nadia Shantzler,Social Sciences,Advanced Text,Academic,590,24,No,3,128,24.583333,1
36,BAREC_Hindawi_75730863_001,Hindawi,Hindawi,Guide to Kairouan,Saleh Sweisi al-Qayrawani,Social Sciences,Advanced Text,Academic,521,26,No,1,59,20.038462,14
37,BAREC_Hindawi_96495040_001,Hindawi,Hindawi,Why Rely on Luck?,Harold W. Lewis,Social Sciences,Advanced Text,Academic,504,20,No,4,47,25.200000,10
38,BAREC_Hindawi_68502850_001,Hindawi,Hindawi,The Son of Man,Emil Ludwig,Social Sciences,Advanced Text,Academic,513,22,No,1,61,23.318182,12
39,BAREC_Hindawi_24716913_001,Hindawi,Hindawi,The Minaret of the White Mosque in Ramla,Abdullah Mukhlis,Social Sciences,Advanced Text,Academic,513,23,No,1,69,22.304348,2
40,BAREC_Ofoq_Jan_2024_منصور_مبارك_3_001,Ofoq,Ofoq,45292,Mansour Mubarak,Social Sciences,Specialized Text,Academic,643,17,No,3,91,37.823529,7
41,BAREC_Ofoq_Jan_2021_نبيل_صالح_5_001,Ofoq,Ofoq,44197,Nabil Saleh,Social Sciences,Specialized Text,Academic,624,19,No,3,81,32.842105,4
42,BAREC_Hindawi_90520707_001,Hindawi,Hindawi,Egyptian Sudan and British Political Ambitions,Dawood Barakat,Social Sciences,Specialized Text,Academic,663,11,No,4,190,60.272727,3
43,BAREC_Hindawi_18175075_001,Hindawi,Hindawi,In the House of Revelation,Mohammed Hussein Heikal,Social Sciences,Specialized Text,Academic,541,14,No,2,149,38.642857,4
44,BAREC_Ofoq_November_2024_حسن_الزواوي_001,Ofoq,Ofoq,45597,Hassan Al-Zawawi,Social Sciences,Specialized Text,Academic,615,15,No,3,71,41.000000,13
45,BAREC_Hindawi_75352027_001,Hindawi,Hindawi,Arabic Reading,Nabawiya Musa,Social Sciences,Specialized Text,Academic,537,22,No,2,75,24.409091,17
46,BAREC_Hindawi_57468526_001,Hindawi,Hindawi,Islamic Mysticism and Imam al-Sharani,Taha Abdul Baqi Surur,Social Sciences,Specialized Text,Academic,595,37,Yes,2,56,16.081081,12
47,BAREC_Ofoq_Jan_2024_د._عبد_الله_إبراهيم_8_001,Ofoq,Ofoq,45292,Dr. Abdullah Ibrahim,Social Sciences,Specialized Text,Academic,615,29,No,2,63,21.206897,4
48,BAREC_Ofoq_Sep_2019_عماد_البليك_7_001,Ofoq,Ofoq,43709,Imad Al-Balik,Social Sciences,Specialized Text,Academic,655,18,No,3,85,36.388889,9
49,BAREC_Hindawi_81902572_001,Hindawi,Hindawi,"Dictionary of Egyptian Customs, Traditions, an...",Ahmed Amin,Social Sciences,Specialized Text,Academic,503,16,No,2,105,31.437500,2

In [122]:
D_df['selected_sent_raw'] = None
D_df['selected_sent_word_count'] = None
D_df['selected_sent_words'] = None

for i, row in D_df.iterrows():
    directory = row['Directory']
    document = row['Document']

    annotations_file_path = (
        f"BAREC-10M/Data/Morphology_and_Readability/"
        f"{directory}/{document}.json"
    )

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)

    annotations = pd.DataFrame(annotations)

    selected_sentence_index = int(row['sampled_sentence_index'])

    selected_row = annotations.iloc[selected_sentence_index]

    raw_sentence = selected_row['raw_sents']
    word_count = selected_row['sents_word_count']
    words = selected_row['word']   # list of strings

    D_df.at[i, 'selected_sent_raw'] = raw_sentence
    D_df.at[i, 'selected_sent_word_count'] = word_count
    D_df.at[i, 'selected_sent_words'] = words

In [123]:
D_df = D_df[[
    'Directory',
    'Document',
    'sampled_sentence_index',
    'Source',
    'Book',
    'Author',
    'Domain',
    'Readership Group',
    'Text Category',
    'average sentence length',
    'selected_sent_raw',
    'selected_sent_word_count',
    'selected_sent_words'
]]

In [124]:
D_df.rename(columns={
    'average sentence length': 'average_sentence_length_per_doc',
}, inplace=True)

In [125]:
D_df.to_json('sampled_AC_sentences.json', orient='records', force_ascii=False, indent=4)

In [126]:
metadata['Text Category'].value_counts()

Text Category
Media & Culture                                  7122
Educational Materials; Language & Linguistics    4709
Academic                                         4301
Literature; Art & Music                          3974
Religion & Philosophy                             254
Encyclopedic                                      175
Name: count, dtype: int64

In [127]:
RP_df = metadata[metadata['Text Category']=='Religion & Philosophy']
print("Religion & Philosophy")
print("==========================")
print(f"Number of documents: {RP_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {RP_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {RP_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {RP_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{RP_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{RP_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{RP_df['average sentence length'].describe().to_dict()}")
print("==========================")

Religion & Philosophy
==========================
Number of documents: 254
--------------------------
Number of sentences: 4278
--------------------------
Number of unique books: 49
--------------------------
Number of unique authors: 10
--------------------------
Domain distribution:
{'Arts & Humanities': 254}
--------------------------
Readership Group distribution:
{'Specialized Text': 254}
--------------------------
Average sentence length distribution:
{'count': 254.0, 'mean': 15.191069257160054, 'std': 7.0941729109666545, 'min': 6.2727272727272725, '25%': 10.0, '50%': 13.89247311827957, '75%': 18.065217391304348, 'max': 43.5}
==========================

In [129]:
sampled_RP_df = RP_df[(RP_df['longest_sent_len'] >= 8) & (RP_df['shortest_sent_len'] <= 30) & (RP_df['Sentence Count'] > 10)].sample(50, random_state=42)

In [130]:
sampled_RP_df.shape

(50, 14)

In [131]:
sampled_RP_sentences_indices = []
for i, row in sampled_RP_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_RP_sentences_indices.append(sampled_index)
print(sampled_RP_sentences_indices)

[29, 28, 3, 22, 16, 7, 30, 5, 3, 1, 16, 8, 16, 1, 25, 18, 1, 2, 1, 9, 1, 60, 7, 30, 14, 15, 13, 10, 9, 18, 31, 2, 40, 29, 1, 0, 1, 1, 17, 34, 9, 32, 21, 7, 9, 6, 9, 10, 31, 0]

In [132]:
sampled_RP_df['sampled_sentence_index'] = sampled_RP_sentences_indices

In [133]:
E_df = sampled_RP_df.copy()
E_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,shortest_sent_len,longest_sent_len,average sentence length,sampled_sentence_index
18564,BAREC_NT_Matthew_12_001,NT,New Testament,Chapter 12,#,Arts & Humanities,Specialized Text,Religion & Philosophy,860,51,Yes,3,31,16.862745,29
18597,BAREC_OT_Genesis_9_001,OT,Old Testament,Chapter 9,#,Arts & Humanities,Specialized Text,Religion & Philosophy,469,30,Yes,2,28,15.633333,28
12369,BAREC_Hadith_2_33_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,165,14,Yes,3,44,11.785714,3
13094,BAREC_Hindawi_30353837_001,Hindawi,Hindawi,The Islamic Revolution and the Hero of the Pro...,Mohammed Lotfi Jum'a,Arts & Humanities,Specialized Text,Religion & Philosophy,532,25,No,2,178,21.280000,22
12473,BAREC_Hayy_03_001,Hayy,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,865,62,No,6,37,13.951613,16
19523,BAREC_Quran_3_Aal_Imran_7_001,Quran,Quran,Surah Al-Imran,#,Arts & Humanities,Specialized Text,Religion & Philosophy,222,11,Yes,11,39,20.181818,7
18577,BAREC_NT_Matthew_9_001,NT,New Testament,Chapter 9,#,Arts & Humanities,Specialized Text,Religion & Philosophy,671,39,Yes,2,33,17.205128,30
12405,BAREC_Hadith_3_1_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,128,16,Yes,3,16,8.000000,5
19472,BAREC_Quran_101_Al-Qaria_001,Quran,Quran,Surah Al-Qari'ah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,69,11,Yes,4,8,6.272727,3
18581,BAREC_OT_Genesis_13_001,OT,Old Testament,Chapter 13,#,Arts & Humanities,Specialized Text,Religion & Philosophy,321,19,Yes,3,29,16.894737,1
12449,BAREC_Hadith_3_5_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,225,20,Yes,6,49,11.250000,16
19515,BAREC_Quran_3_Aal_Imran_18_001,Quran,Quran,Surah Al-Imran,#,Arts & Humanities,Specialized Text,Religion & Philosophy,250,11,Yes,12,46,22.727273,8
12406,BAREC_Hadith_3_20_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,202,22,No,3,34,9.181818,16
19493,BAREC_Quran_2_Al-Baqara_16_001,Quran,Quran,Surah Al-Baqarah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,357,13,Yes,9,63,27.461538,1
12489,BAREC_Hayy_19_001,Hayy,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,1073,66,No,4,74,16.257576,25
12478,BAREC_Hayy_08_001,Hayy,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,957,63,No,4,44,15.190476,18
18596,BAREC_OT_Genesis_8_001,OT,Old Testament,Chapter 8,#,Arts & Humanities,Specialized Text,Religion & Philosophy,416,23,Yes,2,38,18.086957,1
12339,BAREC_Hadith_1_3_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,384,40,Yes,3,40,9.600000,2
19495,BAREC_Quran_2_Al-Baqara_18_001,Quran,Quran,Surah Al-Baqarah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,351,13,Yes,14,42,27.000000,1
19510,BAREC_Quran_3_Aal_Imran_13_001,Quran,Quran,Surah Al-Imran,#,Arts & Humanities,Specialized Text,Religion & Philosophy,224,14,No,8,30,16.000000,9
18572,BAREC_NT_Matthew_4_001,NT,New Testament,Chapter 4,#,Arts & Humanities,Specialized Text,Religion & Philosophy,418,26,Yes,2,32,16.076923,1
12487,BAREC_Hayy_17_001,Hayy,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,1237,74,No,5,43,16.716216,60
19491,BAREC_Quran_2_Al-Baqara_14_001,Quran,Quran,Surah Al-Baqarah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,384,14,No,10,60,27.428571,7
15618,BAREC_Kalima_زِن_وفنُُّّ_صيانة_الدرّاجة_الناري...,Kalima,Kalima,Zen and the Art of Motorcycle Maintenance,Robert M. Pirsig,Arts & Humanities,Specialized Text,Religion & Philosophy,767,59,Yes,1,36,13.000000,30
12742,BAREC_Hindawi_19272704_001,Hindawi,Hindawi,Quranic Philosophy,Abbas Mahmoud Al-Aqqad,Arts & Humanities,Specialized Text,Religion & Philosophy,498,22,No,2,60,22.636364,14
12414,BAREC_Hadith_3_28_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,177,18,No,4,23,9.833333,15
12434,BAREC_Hadith_3_46_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,160,15,No,4,25,10.666667,13
18578,BAREC_OT_Genesis_10_001,OT,Old Testament,Chapter 10,#,Arts & Humanities,Specialized Text,Religion & Philosophy,360,33,Yes,2,24,10.909091,10
19507,BAREC_Quran_3_Aal_Imran_10_001,Quran,Quran,Surah Al-Imran,#,Arts & Humanities,Specialized Text,Religion & Philosophy,211,11,Yes,13,37,19.181818,9
12471,BAREC_Hayy_01_001,Hayy,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,987,70,No,3,61,14.100000,18
18574,BAREC_NT_Matthew_6_001,NT,New Testament,Chapter 6,#,Arts & Humanities,Specialized Text,Religion & Philosophy,629,35,Yes,2,32,17.971429,31
12469,BAREC_Hadith_3_8_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,130,11,Yes,3,48,11.818182,2
12483,BAREC_Hayy_13_001,Hayy,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,881,50,No,4,50,17.620000,40
18563,BAREC_NT_Matthew_11_001,NT,New Testament,Chapter 11,#,Arts & Humanities,Specialized Text,Religion & Philosophy,507,31,Yes,3,29,16.354839,29
18589,BAREC_OT_Genesis_20_001,OT,Old Testament,Chapter 20,#,Arts & Humanities,Specialized Text,Religion & Philosophy,391,19,Yes,2,31,20.578947,1
12477,BAREC_Hayy_07_001,Hayy,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,1151,71,No,5,45,16.211268,0
18570,BAREC_NT_Matthew_2_001,NT,New Testament,Chapter 2,#,Arts & Humanities,Specialized Text,Religion & Philosophy,470,24,Yes,2,38,19.583333,1
18580,BAREC_OT_Genesis_12_001,OT,Old Testament,Chapter 12,#,Arts & Humanities,Specialized Text,Religion & Philosophy,359,21,Yes,3,31,17.095238,1
12401,BAREC_Hadith_3_16_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,201,23,Yes,3,24,8.739130,17
12480,BAREC_Hayy_10_001,Hayy,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,999,57,No,3,56,17.526316,34
19520,BAREC_Quran_3_Aal_Imran_4_001,Quran,Quran,Surah Al-Imran,#,Arts & Humanities,Specialized Text,Religion & Philosophy,225,11,Yes,10,38,20.454545,9
18576,BAREC_NT_Matthew_8_001,NT,New Testament,Chapter 8,#,Arts & Humanities,Specialized Text,Religion & Philosophy,621,35,Yes,2,34,17.742857,32
12475,BAREC_Hayy_05_001,Hayy,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,1089,74,No,3,84,14.716216,21
13976,BAREC_Hindawi_59250728_001,Hindawi,Hindawi,Islamic Administration at the Peak of the Arabs,Mohamed Kurd Ali,Arts & Humanities,Specialized Text,Religion & Philosophy,503,14,No,3,142,35.928571,7
18592,BAREC_OT_Genesis_4_001,OT,Old Testament,Chapter 4,#,Arts & Humanities,Specialized Text,Religion & Philosophy,462,27,Yes,2,33,17.111111,9
12375,BAREC_Hadith_2_39_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,163,15,Yes,3,44,10.866667,6
18585,BAREC_OT_Genesis_17_001,OT,Old Testament,Chapter 17,#,Arts & Humanities,Specialized Text,Religion & Philosophy,481,28,Yes,3,32,17.178571,9
18575,BAREC_NT_Matthew_7_001,NT,New Testament,Chapter 7,#,Arts & Humanities,Specialized Text,Religion & Philosophy,483,30,Yes,2,25,16.100000,10
12486,BAREC_Hayy_16_001,Hayy,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,881,56,No,4,88,15.732143,31
14340,BAREC_Hindawi_70930825_001,Hindawi,Hindawi,Islamic Culture in India,Abdel Hay al-Husni,Arts & Humanities,Specialized Text,Religion & Philosophy,500,13,No,1,125,38.461538,0

In [134]:
E_df['selected_sent_raw'] = None
E_df['selected_sent_word_count'] = None
E_df['selected_sent_words'] = None

for i, row in E_df.iterrows():
    directory = row['Directory']
    document = row['Document']

    annotations_file_path = (
        f"BAREC-10M/Data/Morphology_and_Readability/"
        f"{directory}/{document}.json"
    )

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)

    annotations = pd.DataFrame(annotations)

    selected_sentence_index = int(row['sampled_sentence_index'])

    selected_row = annotations.iloc[selected_sentence_index]

    raw_sentence = selected_row['raw_sents']
    word_count = selected_row['sents_word_count']
    words = selected_row['word']   # list of strings

    E_df.at[i, 'selected_sent_raw'] = raw_sentence
    E_df.at[i, 'selected_sent_word_count'] = word_count
    E_df.at[i, 'selected_sent_words'] = words

In [135]:
E_df = E_df[[
    'Directory',
    'Document',
    'sampled_sentence_index',
    'Source',
    'Book',
    'Author',
    'Domain',
    'Readership Group',
    'Text Category',
    'average sentence length',
    'selected_sent_raw',
    'selected_sent_word_count',
    'selected_sent_words'
]]

In [136]:
E_df.rename(columns={
    'average sentence length': 'average_sentence_length_per_doc',
}, inplace=True)

In [137]:
E_df.to_json('sampled_RP_sentences.json', orient='records', force_ascii=False, indent=4)

In [138]:
metadata['Text Category'].value_counts()

Text Category
Media & Culture                                  7122
Educational Materials; Language & Linguistics    4709
Academic                                         4301
Literature; Art & Music                          3974
Religion & Philosophy                             254
Encyclopedic                                      175
Name: count, dtype: int64

In [139]:
EN_df = metadata[metadata['Text Category']=='Encyclopedic']
print("Encyclopedic")
print("==========================")
print(f"Number of documents: {EN_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {EN_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {EN_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {EN_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{EN_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{EN_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{EN_df['average sentence length'].describe().to_dict()}")
print("==========================")

Encyclopedic
==========================
Number of documents: 175
--------------------------
Number of sentences: 5749
--------------------------
Number of unique books: 175
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Social Sciences': 90, 'Arts & Humanities': 48, 'STEM': 37}
--------------------------
Readership Group distribution:
{'Advanced Text': 175}
--------------------------
Average sentence length distribution:
{'count': 175.0, 'mean': 22.279801555703763, 'std': 3.686049565777941, 'min': 11.491228070175438, '25%': 19.79873949579832, '50%': 21.8125, '75%': 24.34188034188034, 'max': 36.904761904761905}
==========================

In [140]:
EN_AH_df = EN_df[EN_df['Domain']=='Arts & Humanities']
print("Encyclopedic - Arts & Humanities")
print("==========================")
print(f"Number of documents: {EN_AH_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {EN_AH_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {EN_AH_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {EN_AH_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{EN_AH_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{EN_AH_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{EN_AH_df['average sentence length'].describe().to_dict()}")
print("==========================")

Encyclopedic - Arts & Humanities
==========================
Number of documents: 48
--------------------------
Number of sentences: 1674
--------------------------
Number of unique books: 48
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Arts & Humanities': 48}
--------------------------
Readership Group distribution:
{'Advanced Text': 48}
--------------------------
Average sentence length distribution:
{'count': 48.0, 'mean': 21.893738189027854, 'std': 3.8578502565209836, 'min': 11.491228070175438, '25%': 19.16559829059829, '50%': 21.563541666666666, '75%': 24.717741935483872, 'max': 33.12903225806452}
==========================

In [141]:
sampled_EN_AH_advanced_df = EN_AH_df[(EN_AH_df['longest_sent_len'] >= 8) & (EN_AH_df['shortest_sent_len'] <= 30) & (EN_AH_df['Sentence Count'] > 10)].sample(17, random_state=42)

In [142]:
sampled_EN_AH_df = sampled_EN_AH_advanced_df.copy()

In [143]:
sampled_EN_AH_sentences_indices = []
for i, row in sampled_EN_AH_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_EN_AH_sentences_indices.append(sampled_index)
print(sampled_EN_AH_sentences_indices)

[11, 21, 33, 0, 20, 10, 22, 0, 4, 48, 0, 8, 2, 1, 22, 1, 35]

In [144]:
sampled_EN_AH_df['sampled_sentence_index'] = sampled_EN_AH_sentences_indices

In [145]:
EN_ST_df = EN_df[EN_df['Domain']=='STEM']
print("Encyclopedic - STEM")
print("==========================")
print(f"Number of documents: {EN_ST_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {EN_ST_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {EN_ST_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {EN_ST_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{EN_ST_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{EN_ST_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{EN_ST_df['average sentence length'].describe().to_dict()}")
print("==========================")

Encyclopedic - STEM
==========================
Number of documents: 37
--------------------------
Number of sentences: 1207
--------------------------
Number of unique books: 37
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'STEM': 37}
--------------------------
Readership Group distribution:
{'Advanced Text': 37}
--------------------------
Average sentence length distribution:
{'count': 37.0, 'mean': 21.50345219510831, 'std': 3.586902951861836, 'min': 11.76923076923077, '25%': 18.72222222222222, '50%': 21.7, '75%': 23.25, 'max': 30.291666666666668}
==========================

In [146]:
sampled_EN_ST_advanced_df = EN_ST_df[(EN_ST_df['longest_sent_len'] >= 8) & (EN_ST_df['shortest_sent_len'] <= 30) & (EN_ST_df['Sentence Count'] > 10)].sample(16, random_state=42)

In [147]:
sampled_EN_ST_df = sampled_EN_ST_advanced_df.copy()

In [148]:
sampled_EN_ST_sentences_indices = []
for i, row in sampled_EN_ST_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_EN_ST_sentences_indices.append(sampled_index)
print(sampled_EN_ST_sentences_indices)

[1, 12, 36, 11, 0, 34, 1, 21, 0, 14, 2, 18, 1, 1, 21, 0]

In [149]:
sampled_EN_ST_df['sampled_sentence_index'] = sampled_EN_ST_sentences_indices

In [150]:
EN_SS_df = EN_df[EN_df['Domain']=='Social Sciences']
print("Encyclopedic - Social Sciences")
print("==========================")
print(f"Number of documents: {EN_SS_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {EN_SS_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {EN_SS_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {EN_SS_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{EN_SS_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{EN_SS_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{EN_SS_df['average sentence length'].describe().to_dict()}")
print("==========================")

Encyclopedic - Social Sciences
==========================
Number of documents: 90
--------------------------
Number of sentences: 2868
--------------------------
Number of unique books: 90
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Social Sciences': 90}
--------------------------
Readership Group distribution:
{'Advanced Text': 90}
--------------------------
Average sentence length distribution:
{'count': 90.0, 'mean': 22.804867866175705, 'std': 3.590235208744769, 'min': 15.5, '25%': 20.44017595307918, '50%': 22.192028985507246, '75%': 24.75607142857143, 'max': 36.904761904761905}
==========================

In [151]:
sampled_EN_SS_advanced_df = EN_SS_df[(EN_SS_df['longest_sent_len'] >= 8) & (EN_SS_df['shortest_sent_len'] <= 30) & (EN_SS_df['Sentence Count'] > 10)].sample(17, random_state=42)

In [152]:
sampled_EN_SS_df = sampled_EN_SS_advanced_df.copy()
sampled_EN_SS_df.shape

(17, 14)

In [153]:
sampled_EN_SS_sentences_indices = []
for i, row in sampled_EN_SS_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[(annotations['sents_word_count'] >= 8) & (annotations['sents_word_count'] <= 30)].sample(1, random_state=42).index.item()
    sampled_EN_SS_sentences_indices.append(sampled_index)
print(sampled_EN_SS_sentences_indices)

[0, 0, 16, 11, 8, 20, 8, 2, 2, 1, 10, 35, 0, 0, 21, 1, 9]

In [154]:
sampled_EN_SS_df['sampled_sentence_index'] = sampled_EN_SS_sentences_indices

In [155]:
F_df = pd.concat([sampled_EN_AH_df, sampled_EN_ST_df, sampled_EN_SS_df], ignore_index=True)
F_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,shortest_sent_len,longest_sent_len,average sentence length,sampled_sentence_index
0,BAREC_Wikipedia_أنغكور_وات_001,Wikipedia,Wikipedia,Angkor Wat,#,Arts & Humanities,Advanced Text,Encyclopedic,659,31,Yes,6,38,21.258065,11
1,BAREC_Wikipedia_ضريح_سليمان_شاه_001,Wikipedia,Wikipedia,The Tomb of Suleiman Shah,#,Arts & Humanities,Advanced Text,Encyclopedic,585,23,Yes,5,55,25.434783,21
2,BAREC_Wikipedia_أليساندرو_دل_بييرو_001,Wikipedia,Wikipedia,Alessandro Del Piero,#,Arts & Humanities,Advanced Text,Encyclopedic,767,38,Yes,5,57,20.184211,33
3,BAREC_Wikipedia_عمارة_بنائية_001,Wikipedia,Wikipedia,Architectural Buildings,#,Arts & Humanities,Advanced Text,Encyclopedic,621,24,Yes,5,60,25.875000,0
4,BAREC_Wikipedia_ألسنة_اللهب_001,Wikipedia,Wikipedia,Flames,#,Arts & Humanities,Advanced Text,Encyclopedic,990,49,Yes,4,53,20.204082,20
5,BAREC_Wikipedia_ريتان_001,Wikipedia,Wikipedia,Ritan,#,Arts & Humanities,Advanced Text,Encyclopedic,675,32,Yes,6,47,21.093750,10
6,BAREC_Wikipedia_المسجد_الأقصى_001,Wikipedia,Wikipedia,Al-Aqsa Mosque,#,Arts & Humanities,Advanced Text,Encyclopedic,743,39,Yes,5,45,19.051282,22
7,BAREC_Wikipedia_الموثوقية_التاريخية_للأناجيل_001,Wikipedia,Wikipedia,Historical Reliability of the Gospels,#,Arts & Humanities,Advanced Text,Encyclopedic,709,27,Yes,6,58,26.259259,0
8,BAREC_Wikipedia_الحج_في_الإسلام_001,Wikipedia,Wikipedia,Hajj in Islam,#,Arts & Humanities,Advanced Text,Encyclopedic,589,31,Yes,3,49,19.000000,4
9,BAREC_Wikipedia_ألفية_ابن_مالك_001,Wikipedia,Wikipedia,The Millennium of Ibn Malik,#,Arts & Humanities,Advanced Text,Encyclopedic,924,56,Yes,2,81,16.500000,48
10,BAREC_Wikipedia_الطائر_المقلد_001,Wikipedia,Wikipedia,The Imitative Bird,#,Arts & Humanities,Advanced Text,Encyclopedic,689,30,Yes,7,48,22.966667,0
11,BAREC_Wikipedia_الجامع_الأزهر_001,Wikipedia,Wikipedia,Al-Azhar Mosque,#,Arts & Humanities,Advanced Text,Encyclopedic,637,29,Yes,5,47,21.965517,8
12,BAREC_Wikipedia_الزوجة_القروية_001,Wikipedia,Wikipedia,The Country Wife,#,Arts & Humanities,Advanced Text,Encyclopedic,809,28,Yes,6,54,28.892857,2
13,BAREC_Wikipedia_شاعر_في_نيويورك_001,Wikipedia,Wikipedia,A Poet in New York,#,Arts & Humanities,Advanced Text,Encyclopedic,729,29,Yes,5,46,25.137931,1
14,BAREC_Wikipedia_جامع_بني_أمية_الكبير_001,Wikipedia,Wikipedia,The Great Umayyad Mosque,#,Arts & Humanities,Advanced Text,Encyclopedic,800,44,Yes,5,36,18.181818,22
15,BAREC_Wikipedia_المسجد_الإبراهيمي_001,Wikipedia,Wikipedia,The Ibrahimi Mosque,#,Arts & Humanities,Advanced Text,Encyclopedic,842,35,Yes,5,48,24.057143,1
16,BAREC_Wikipedia_المشاعر_المقدسة_001,Wikipedia,Wikipedia,The Holy Sites,#,Arts & Humanities,Advanced Text,Encyclopedic,767,44,Yes,3,62,17.431818,35
17,BAREC_Wikipedia_ترانزستور_ثنائي_القطب_001,Wikipedia,Wikipedia,Bipolar Transistor,#,STEM,Advanced Text,Encyclopedic,627,28,Yes,10,42,22.392857,1
18,BAREC_Wikipedia_تاريخ_المنهج_العلمي_001,Wikipedia,Wikipedia,The History of the Scientific Method,#,STEM,Advanced Text,Encyclopedic,881,38,Yes,6,67,23.184211,12
19,BAREC_Wikipedia_إلكترون_001,Wikipedia,Wikipedia,Electron,#,STEM,Advanced Text,Encyclopedic,868,40,Yes,5,36,21.700000,36
20,BAREC_Wikipedia_عدد أولي_001,Wikipedia,Wikipedia,Prime Number,#,STEM,Advanced Text,Encyclopedic,605,33,Yes,5,58,18.333333,11
21,BAREC_Wikipedia_مرصد_هابل_الفضائي_001,Wikipedia,Wikipedia,The Hubble Space Telescope,#,STEM,Advanced Text,Encyclopedic,651,28,Yes,7,49,23.250000,0
22,BAREC_Wikipedia_ذكاء_اصطناعي_001,Wikipedia,Wikipedia,Artificial Intelligence,#,STEM,Advanced Text,Encyclopedic,676,37,Yes,5,40,18.270270,34
23,BAREC_Wikipedia_بث_متعدد_001,Wikipedia,Wikipedia,Multiple Broadcasting,#,STEM,Advanced Text,Encyclopedic,693,26,Yes,6,68,26.653846,1
24,BAREC_Wikipedia_روبوت_001,Wikipedia,Wikipedia,Robot,#,STEM,Advanced Text,Encyclopedic,676,23,Yes,8,53,29.391304,21
25,BAREC_Wikipedia_خوارزمية_001,Wikipedia,Wikipedia,Algorithm,#,STEM,Advanced Text,Encyclopedic,471,25,Yes,6,58,18.840000,0
26,BAREC_Wikipedia_تجزئة_الشبكة_001,Wikipedia,Wikipedia,Network Segmentation,#,STEM,Advanced Text,Encyclopedic,344,16,Yes,5,49,21.500000,14
27,BAREC_Wikipedia_بروتوكول_التوجيه_الداخلي_المحس...,Wikipedia,Wikipedia,Enhanced Internal Routing Protocol Between Gates,#,STEM,Advanced Text,Encyclopedic,734,29,Yes,6,53,25.310345,2
28,BAREC_Wikipedia_تاريخ_علم_الأحياء_001,Wikipedia,Wikipedia,History of Biology,#,STEM,Advanced Text,Encyclopedic,727,24,Yes,10,77,30.291667,18
29,BAREC_Wikipedia_تاريخ_الإمارات_العربية_المتحد...,Wikipedia,Wikipedia,The History of Aluminum,#,STEM,Advanced Text,Encyclopedic,657,26,Yes,7,51,25.269231,1
30,BAREC_Wikipedia_فيزياء_001,Wikipedia,Wikipedia,Physics,#,STEM,Advanced Text,Encyclopedic,654,27,Yes,6,46,24.222222,1
31,BAREC_Wikipedia_بروتوكول_تهيئة_المضيف_الآلية...,Wikipedia,Wikipedia,Host Initialization Protocol,#,STEM,Advanced Text,Encyclopedic,734,30,Yes,6,49,24.466667,21
32,BAREC_Wikipedia_تمثيل_القبولية_001,Wikipedia,Wikipedia,Representation of Acceptance,#,STEM,Advanced Text,Encyclopedic,586,27,Yes,5,71,21.703704,0
33,BAREC_Wikipedia_تاريخ_الكويت_001,Wikipedia,Wikipedia,History of Kuwait,#,Social Sciences,Advanced Text,Encyclopedic,576,27,Yes,4,47,21.333333,0
34,BAREC_Wikipedia_جوائز_محمد_السادس_للقرآن_الك...,Wikipedia,Wikipedia,King Mohammed VI Quran Awards,#,Social Sciences,Advanced Text,Encyclopedic,758,34,Yes,6,41,22.294118,0
35,BAREC_Wikipedia_إمبراطورية_المغول_001,Wikipedia,Wikipedia,The Mongol Empire,#,Social Sciences,Advanced Text,Encyclopedic,776,38,Yes,5,65,20.421053,16
36,BAREC_Wikipedia_الصومال_001,Wikipedia,Wikipedia,Somalia,#,Social Sciences,Advanced Text,Encyclopedic,775,21,Yes,7,119,36.904762,11
37,BAREC_Wikipedia_تجارة_001,Wikipedia,Wikipedia,Trade,#,Social Sciences,Advanced Text,Encyclopedic,701,34,Yes,5,92,20.617647,8
38,BAREC_Wikipedia_ابن_خلدون_001,Wikipedia,Wikipedia,Ibn Khaldun,#,Social Sciences,Advanced Text,Encyclopedic,641,32,Yes,5,46,20.031250,20
39,BAREC_Wikipedia_صابون_نابلسي_001,Wikipedia,Wikipedia,Nabulsi Soap,#,Social Sciences,Advanced Text,Encyclopedic,634,31,Yes,7,49,20.451613,8
40,BAREC_Wikipedia_المرأة_في_إيطاليا_001,Wikipedia,Wikipedia,Women in Italy,#,Social Sciences,Advanced Text,Encyclopedic,737,28,Yes,5,57,26.321429,2
41,BAREC_Wikipedia_الريفيون_001,Wikipedia,Wikipedia,The Ryfiyyun,#,Social Sciences,Advanced Text,Encyclopedic,695,28,Yes,5,52,24.821429,2
42,BAREC_Wikipedia_المهرجان_العالمي_للعلوم_001,Wikipedia,Wikipedia,The World Science Festival,#,Social Sciences,Advanced Text,Encyclopedic,599,23,Yes,7,64,26.043478,1
43,BAREC_Wikipedia_الإمارات_العربية_المتحدة_001,Wikipedia,Wikipedia,United Arab Emirates,#,Social Sciences,Advanced Text,Encyclopedic,671,35,Yes,5,40,19.171429,10
44,BAREC_Wikipedia_إنسبروك_001,Wikipedia,Wikipedia,Innsbruck,#,Social Sciences,Advanced Text,Encyclopedic,782,38,Yes,5,51,20.578947,35
45,BAREC_Wikipedia_بيروت_001,Wikipedia,Wikipedia,Beirut,#,Social Sciences,Advanced Text,Encyclopedic,639,27,Yes,5,58,23.666667,0
46,BAREC_Wikipedia_كريستيانو_رونالدو_001,Wikipedia,Wikipedia,Cristiano Ronaldo,#,Social Sciences,Advanced Text,Encyclopedic,762,29,Yes,10,44,26.275862,0
47,BAREC_Wikipedia_كيرلا_001,Wikipedia,Wikipedia,Kerala,#,Social Sciences,Advanced Text,Encyclopedic,699,29,Yes,7,74,24.103448,21
48,BAREC_Wikipedia_بوبي_روبسون_001,Wikipedia,Wikipedia,Bobby Robson,#,Social Sciences,Advanced Text,Encyclopedic,607,28,Yes,5,47,21.678571,1
49,BAREC_Wikipedia_قاعدة الخمس ثواني_001,Wikipedia,Wikipedia,The Five-Second Rule,#,Social Sciences,Advanced Text,Encyclopedic,665,31,Yes,5,41,21.451613,9

In [156]:
F_df['selected_sent_raw'] = None
F_df['selected_sent_word_count'] = None
F_df['selected_sent_words'] = None

for i, row in F_df.iterrows():
    directory = row['Directory']
    document = row['Document']

    annotations_file_path = (
        f"BAREC-10M/Data/Morphology_and_Readability/"
        f"{directory}/{document}.json"
    )

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)

    annotations = pd.DataFrame(annotations)

    selected_sentence_index = int(row['sampled_sentence_index'])

    selected_row = annotations.iloc[selected_sentence_index]

    raw_sentence = selected_row['raw_sents']
    word_count = selected_row['sents_word_count']
    words = selected_row['word']   # list of strings

    F_df.at[i, 'selected_sent_raw'] = raw_sentence
    F_df.at[i, 'selected_sent_word_count'] = word_count
    F_df.at[i, 'selected_sent_words'] = words

In [157]:
F_df = F_df[[
    'Directory',
    'Document',
    'sampled_sentence_index',
    'Source',
    'Book',
    'Author',
    'Domain',
    'Readership Group',
    'Text Category',
    'average sentence length',
    'selected_sent_raw',
    'selected_sent_word_count',
    'selected_sent_words'
]]

In [158]:
F_df.rename(columns={
    'average sentence length': 'average_sentence_length_per_doc',
}, inplace=True)

In [159]:
F_df.to_json('sampled_EN_sentences.json', orient='records', force_ascii=False, indent=4)

In [ ]:
## Data groups:

# A --> Literature; Arts & Music
# B --> Media & Culture
# C --> Educational Materials; Language & Linguistics
# D --> Academic
# E --> Religion & Philosophy
# F --> Encyclopedic

In [ ]:
## Annotators:

# 1 --> 
# 2 --> 
# 3 -->
# 4 -->
# 5 -->
# 6 -->

In [ ]:
## Annotation Assignment:

# A --> 1, 2, 3
# B --> 1, 2, 4
# C --> 1, 5, 6
# D --> 2, 5, 6
# E --> 3, 4, 5
# F --> 3, 4, 6