In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
# assuming the data is located in the same directory as the notebook and the `Morphology_and_Readability.zip` file has been extracted

In [3]:
metadata = pd.read_excel('BAREC-10M/Data/Metadata.xlsx')
metadata.head()

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?
0,BAREC_1001_introduction_1_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,73,6,Yes
1,BAREC_1001_introduction_2_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,730,73,No
2,BAREC_1001_introduction_3_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,397,47,Yes
3,BAREC_1001_introduction_4_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,237,23,Yes
4,BAREC_1001_introduction_5_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,659,62,No

In [4]:
metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 20535 entries, 0 to 20534
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Document          20535 non-null  str
 1   Directory         20535 non-null  object
 2   Source            20535 non-null  str
 3   Book              20535 non-null  object
 4   Author            20535 non-null  str
 5   Domain            20535 non-null  str
 6   Readership Group  20535 non-null  str
 7   Text Category     20535 non-null  str
 8   Word Count        20535 non-null  int64
 9   Sentence Count    20535 non-null  int64
 10  In BAREC Corpus?  20535 non-null  str
dtypes: int64(2), object(2), str(7)
memory usage: 1.7+ MB

In [5]:
metadata['Document'].nunique()

20535

In [6]:
list(metadata['Source'].unique())

['Arabian Nights',
 'Arabic Learner Corpus (ALC)',
 'ANERCorp',
 'Arabic Poem Comprehensive Dataset (APCD)',
 'Akhbarona News',
 'AlArabiya News',
 'AlKhaleej News',
 'National Anthems',
 'Arab Youth Publisher',
 'ArabicMMLU',
 'Basic Travel Expressions Corpus (BTEC)',
 'Batman',
 'Emarati Curriculum',
 'DARES',
 'Green Library',
 'Hadith',
 'Hayy ibn Yaqdhan',
 'Hindawi',
 'Kalima',
 'Library of Arabic Literature',
 'Ladybird',
 'Lulu',
 'Constitutions',
 'Majarra',
 'Majed',
 'MedArabiQ',
 'New Testament',
 'Old Testament',
 'Hanging Odes',
 'Ofoq',
 'Other Minor Sources',
 'Quran',
 'ReadMe++',
 'Reading Corner',
 'Sara',
 'Spacetoon Songs',
 'Subtitles',
 'Superman',
 'The Five Adventurers',
 'Tunis Curriculum',
 'UN (United Nations)',
 'WikiNews',
 'Wikipedia',
 'Zayed Arabic-English Bilingual Undergraduate Corpus (ZAEBUC)',
 'chatGPT']

In [7]:
metadata['Book'].nunique(), np.random.choice(list(metadata['Book'].unique()), 10), metadata['Book'].value_counts()

(4682,
 array(['Riddle: 137', 'Sanka', 'The White Palace', 'Distant Memories',
        'Riddle: 078', 'The Disguised Beauty', 'Martin Luther',
        'The Rhinoceros and the Birds',
        'Colors of the Short Story in American Literature', '44409'],
       dtype='<U147'),
 Book
 Sports                       1010
 Culture                      1001
 Medical                      1000
 Tech                         1000
 Finance                       997
                              ...
 Prophet                         1
 The Theory of the Iceberg       1
 Nelson Mandela                  1
 Engineering                     1
 Volubilis                       1
 Name: count, Length: 4682, dtype: int64)

In [8]:
metadata['Author'].nunique(), np.random.choice(list(metadata['Author'].unique()), 10), metadata['Author'].value_counts()

(2597,
 array(['Abdul Aziz Al-Bashri', 'Khadouj', 'Nasif al-Yazji',
        'Harriet Beecher Stowe', 'C. Julian Chen', 'Abu Hafs al-Salmi',
        'Mahmoud Mohammed Ali', 'Mohamed Saeed al-Arian', 'Firas Hamieh',
        'Hassan Hanafi'], dtype='<U90'),
 Author
 #                              15227
 Mahmoud Salem                    337
 Kamel Kilani                     123
 Abbas Mahmoud Al-Aqqad            88
 Rafeef Reda Saidawi               59
                                ...
 Talal Ma’alla                      1
 Al-Habib Istani Zain Al-Din        1
 Hashim Qasim                       1
 Suleiman Al-Issa                   1
 UN (United Nations)                1
 Name: count, Length: 2597, dtype: int64)

In [9]:
metadata['Domain'].value_counts()

Domain
Arts & Humanities    10342
STEM                  5444
Social Sciences       4749
Name: count, dtype: int64

In [10]:
metadata['Readership Group'].value_counts()

Readership Group
Advanced Text        9165
Specialized Text     8884
Foundational Text    2486
Name: count, dtype: int64

In [11]:
metadata['Text Category'].value_counts()

Text Category
Media & Culture                                  7122
Educational Materials; Language & Linguistics    4709
Academic                                         4301
Literature; Art & Music                          3974
Religion & Philosophy                             254
Encyclopedic                                      175
Name: count, dtype: int64

In [12]:
metadata['Word Count'].describe()

count    20535.000000
mean       490.731385
std        262.089359
min          3.000000
25%        278.000000
50%        544.000000
75%        622.000000
max       5074.000000
Name: Word Count, dtype: float64

In [13]:
metadata['Sentence Count'].describe()

count    20535.000000
mean        25.073241
std         25.196396
min          1.000000
25%          8.000000
50%         17.000000
75%         33.000000
max        405.000000
Name: Sentence Count, dtype: float64

In [14]:
metadata['average sentence length'] = metadata['Word Count'] / metadata['Sentence Count']
metadata['average sentence length'].describe()

count    20535.000000
mean        31.768280
std         24.374336
min          1.666667
25%         14.820856
50%         27.260870
75%         39.904545
max       1107.000000
Name: average sentence length, dtype: float64

In [15]:
metadata['In BAREC Corpus?'].value_counts()

In BAREC Corpus?
No       18281
Yes       2031
ST2&3      223
Name: count, dtype: int64

In [16]:
for i, text_category in enumerate(metadata['Text Category'].unique()):
    corr_domain = list(metadata[metadata['Text Category'] == text_category]['Domain'].unique())
    print(f"{i+1}: {text_category}: {corr_domain}")

1: Literature; Art & Music: ['Arts & Humanities']
2: Educational Materials; Language & Linguistics: ['Arts & Humanities', 'Social Sciences', 'STEM']
3: Media & Culture: ['Arts & Humanities', 'Social Sciences', 'STEM']
4: Religion & Philosophy: ['Arts & Humanities']
5: Academic: ['Social Sciences', 'STEM', 'Arts & Humanities']
6: Encyclopedic: ['Social Sciences', 'STEM', 'Arts & Humanities']

In [17]:
for i, text_category in enumerate(metadata['Text Category'].unique()):
    corr_readership = list(metadata[metadata['Text Category'] == text_category]['Readership Group'].unique())
    print(f"{i+1}: {text_category}: {corr_readership}")

1: Literature; Art & Music: ['Specialized Text', 'Foundational Text', 'Advanced Text']
2: Educational Materials; Language & Linguistics: ['Advanced Text', 'Foundational Text', 'Specialized Text']
3: Media & Culture: ['Advanced Text', 'Foundational Text']
4: Religion & Philosophy: ['Specialized Text']
5: Academic: ['Specialized Text', 'Foundational Text', 'Advanced Text']
6: Encyclopedic: ['Advanced Text']

In [19]:
LAM_df = metadata[metadata['Text Category']=='Literature; Art & Music']
print("Literature; Art & Music")
print("==========================")
print(f"Number of documents: {LAM_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {LAM_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {LAM_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {LAM_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{LAM_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{LAM_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{LAM_df['average sentence length'].describe().to_dict()}")
print("==========================")

Literature; Art & Music
==========================
Number of documents: 3974
--------------------------
Number of sentences: 148343
--------------------------
Number of unique books: 2858
--------------------------
Number of unique authors: 1681
--------------------------
Domain distribution:
{'Arts & Humanities': 3974}
--------------------------
Readership Group distribution:
{'Specialized Text': 2286, 'Foundational Text': 1281, 'Advanced Text': 407}
--------------------------
Average sentence length distribution:
{'count': 3974.0, 'mean': 16.17055897763152, 'std': 11.658903148591186, 'min': 2.526315789473684, '25%': 9.317993557294063, '50%': 12.6, '75%': 19.884615384615383, 'max': 221.33333333333334}
==========================

In [20]:
LAM_foundational_df = LAM_df[LAM_df['Readership Group']=='Foundational Text']
print("Literature; Art & Music - Foundational")
print("==========================")
print(f"Number of documents: {LAM_foundational_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {LAM_foundational_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {LAM_foundational_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {LAM_foundational_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{LAM_foundational_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{LAM_foundational_df['average sentence length'].describe().to_dict()}")
print("==========================")

Literature; Art & Music - Foundational
==========================
Number of documents: 1281
--------------------------
Number of sentences: 58143
--------------------------
Number of unique books: 1009
--------------------------
Number of unique authors: 32
--------------------------
Domain distribution:
{'Arts & Humanities': 1281}
--------------------------
Average sentence length distribution:
{'count': 1281.0, 'mean': 13.908297148843703, 'std': 6.7821186229810015, 'min': 2.652173913043478, '25%': 8.620689655172415, '50%': 13.263157894736842, '75%': 17.609756097560975, 'max': 56.111111111111114}
==========================

In [21]:
sampled_LAM_foundational_df = LAM_foundational_df.sample(17, random_state=42)

In [22]:
sampled_LAM_foundational_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,average sentence length
20002,BAREC_TheFiveAdventurers_149 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 149,#,Arts & Humanities,Foundational Text,Literature; Art & Music,698,54,No,12.925926
15247,BAREC_Hindawi_97962586_001,Hindawi,Hindawi,Baba Abdullah and the Dervish,Kamel Kilani,Arts & Humanities,Foundational Text,Literature; Art & Music,505,39,No,12.948718
19981,BAREC_TheFiveAdventurers_128 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 128,#,Arts & Humanities,Foundational Text,Literature; Art & Music,691,44,No,15.704545
15889,BAREC_Ladybird_القدر السحرية_001,Ladybird,Ladybird,The Magic Pot,#,Arts & Humanities,Foundational Text,Literature; Art & Music,630,56,No,11.250000
14792,BAREC_Hindawi_83941583_001,Hindawi,Hindawi,The Poplar Forest,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,530,22,No,24.090909
19686,BAREC_SpacetoonSong_أنا وأخي_001,SpacetoonSong,Spacetoon Songs,Me and My Brother,#,Arts & Humanities,Foundational Text,Literature; Art & Music,52,13,Yes,4.000000
12666,BAREC_Hindawi_17290296_001,Hindawi,Hindawi,Information War,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,500,23,No,21.739130
19823,BAREC_Superman_070_011,Superman,Superman,Edition: 70,#,Arts & Humanities,Foundational Text,Literature; Art & Music,349,43,No,8.116279
12837,BAREC_Hindawi_24146069_001,Hindawi,Hindawi,The Adventure of the Missing Rugby Player,Arthur Conan Doyle,Arts & Humanities,Foundational Text,Literature; Art & Music,518,37,No,14.000000
19930,BAREC_TheFiveAdventurers_077 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 077,#,Arts & Humanities,Foundational Text,Literature; Art & Music,731,68,No,10.750000
19853,BAREC_Superman_100_010,Superman,Superman,Edition: 100,#,Arts & Humanities,Foundational Text,Literature; Art & Music,593,76,No,7.802632
12664,BAREC_Hindawi_17271461_001,Hindawi,Hindawi,The Last of the Mohicans,James Fenimore Cooper,Arts & Humanities,Foundational Text,Literature; Art & Music,653,51,Yes,12.803922
7760,BAREC_ArabYouthPublisher_مالك الحزين يشتري حذا...,ArabYouthPublisher,Arab Youth Publisher,The Heron Buys Shoes,#,Arts & Humanities,Foundational Text,Literature; Art & Music,280,22,No,12.727273
7739,BAREC_ArabYouthPublisher_جزيرة الضياع_001,ArabYouthPublisher,Arab Youth Publisher,The Island of Loss,#,Arts & Humanities,Foundational Text,Literature; Art & Music,490,25,No,19.600000
19783,BAREC_Superman_040_010,Superman,Superman,Edition: 40,#,Arts & Humanities,Foundational Text,Literature; Art & Music,598,61,No,9.803279
19986,BAREC_TheFiveAdventurers_133 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 133,#,Arts & Humanities,Foundational Text,Literature; Art & Music,662,53,No,12.490566
19738,BAREC_Superman_010_011,Superman,Superman,Edition: 10,#,Arts & Humanities,Foundational Text,Literature; Art & Music,594,69,No,8.608696

In [23]:
sampled_LAM_foundational_sentences_indices = []
for i, row in sampled_LAM_foundational_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_LAM_foundational_sentences_indices.append(sampled_index)
print(sampled_LAM_foundational_sentences_indices)

[45, 10, 20, 49, 1, 10, 1, 16, 21, 27, 66, 28, 3, 4, 54, 33, 60]

In [24]:
sampled_LAM_foundational_df['sampled_sentence_index'] = sampled_LAM_foundational_sentences_indices

In [25]:
LAM_advanced_df = LAM_df[LAM_df['Readership Group']=='Advanced Text']
print("Literature; Art & Music - Advanced")
print("==========================")
print(f"Number of documents: {LAM_advanced_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {LAM_advanced_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {LAM_advanced_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {LAM_advanced_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{LAM_advanced_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{LAM_advanced_df['average sentence length'].describe().to_dict()}")
print("==========================")

Literature; Art & Music - Advanced
==========================
Number of documents: 407
--------------------------
Number of sentences: 13216
--------------------------
Number of unique books: 390
--------------------------
Number of unique authors: 107
--------------------------
Domain distribution:
{'Arts & Humanities': 407}
--------------------------
Average sentence length distribution:
{'count': 407.0, 'mean': 20.54016798418344, 'std': 11.93829403319979, 'min': 4.239316239316239, '25%': 13.561561561561561, '50%': 17.857142857142858, '75%': 24.11904761904762, 'max': 128.25}
==========================

In [26]:
sampled_LAM_advanced_df = LAM_advanced_df.sample(16, random_state=42)

In [27]:
sampled_LAM_advanced_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,average sentence length
13033,BAREC_Hindawi_28648582_001,Hindawi,Hindawi,Ragnarok,Antonia Susan Byatt,Arts & Humanities,Advanced Text,Literature; Art & Music,1366,82,Yes,16.658537
14107,BAREC_Hindawi_62505363_001,Hindawi,Hindawi,Steps in the Same River,Riyadh Hammadi,Arts & Humanities,Advanced Text,Literature; Art & Music,505,81,No,6.234568
14368,BAREC_Hindawi_71693707_001,Hindawi,Hindawi,Cases of John Thorndike,R. Austin Freeman,Arts & Humanities,Advanced Text,Literature; Art & Music,501,23,No,21.782609
12727,BAREC_Hindawi_18686373_001,Hindawi,Hindawi,The Gentle Strongman,Naguib Mahfouz,Arts & Humanities,Advanced Text,Literature; Art & Music,502,27,No,18.592593
12795,BAREC_Hindawi_20429368_001,Hindawi,Hindawi,The Younger Brother,Corey Ductoro,Arts & Humanities,Advanced Text,Literature; Art & Music,887,46,Yes,19.282609
13064,BAREC_Hindawi_29392697_001,Hindawi,Hindawi,The Virtuous Successor,Wadi’ Abu Fadil,Arts & Humanities,Advanced Text,Literature; Art & Music,544,18,No,30.222222
13515,BAREC_Hindawi_42475809_001,Hindawi,Hindawi,The Mystery of the Lost Necklace,Jack Footrell,Arts & Humanities,Advanced Text,Literature; Art & Music,516,23,No,22.434783
14867,BAREC_Hindawi_85802403_001,Hindawi,Hindawi,The Thief and the Dogs,Naguib Mahfouz,Arts & Humanities,Advanced Text,Literature; Art & Music,524,26,No,20.153846
14287,BAREC_Hindawi_69407460_001,Hindawi,Hindawi,The Heart of a Woman,Ponson du Terrail,Arts & Humanities,Advanced Text,Literature; Art & Music,544,26,No,20.923077
14412,BAREC_Hindawi_72735281_001,Hindawi,Hindawi,The Earth Gods,Gibran Khalil Gibran,Arts & Humanities,Advanced Text,Literature; Art & Music,503,61,No,8.245902
15102,BAREC_Hindawi_94264040_001,Hindawi,Hindawi,The Big Portrait Mystery and Other Stories,R. Austin Freeman,Arts & Humanities,Advanced Text,Literature; Art & Music,517,43,No,12.023256
13066,BAREC_Hindawi_29403629_001,Hindawi,Hindawi,I Am the Sultan of the Law of Existence,Yusuf Idris,Arts & Humanities,Advanced Text,Literature; Art & Music,740,46,Yes,16.086957
14492,BAREC_Hindawi_74859409_001,Hindawi,Hindawi,The Amazing Visit,Herbert George Wells,Arts & Humanities,Advanced Text,Literature; Art & Music,629,39,Yes,16.128205
19437,BAREC_Other_الكشكول_001,Other,Other Minor Sources,al-Kashkuul,Bayan Safadi,Arts & Humanities,Advanced Text,Literature; Art & Music,287,15,Yes,19.133333
13648,BAREC_Hindawi_48293606_001,Hindawi,Hindawi,The Specter of the Soul,Edward Page Mitchell,Arts & Humanities,Advanced Text,Literature; Art & Music,500,26,No,19.230769
13846,BAREC_Hindawi_52951836_001,Hindawi,Hindawi,The Adventure of Sherlo Combs,Robert Barr,Arts & Humanities,Advanced Text,Literature; Art & Music,504,48,No,10.500000

In [28]:
sampled_LAM_advanced_sentences_indices = []
for i, row in sampled_LAM_advanced_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_LAM_advanced_sentences_indices.append(sampled_index)
print(sampled_LAM_advanced_sentences_indices)

[5, 46, 1, 1, 39, 12, 1, 1, 9, 16, 15, 21, 18, 9, 2, 20]

In [29]:
sampled_LAM_advanced_df['sampled_sentence_index'] = sampled_LAM_advanced_sentences_indices

In [30]:
LAM_specialized_df = LAM_df[LAM_df['Readership Group']=='Specialized Text']
print("Literature; Art & Music - Specialized")
print("==========================")
print(f"Number of documents: {LAM_specialized_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {LAM_specialized_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {LAM_specialized_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {LAM_specialized_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{LAM_specialized_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{LAM_specialized_df['average sentence length'].describe().to_dict()}")
print("==========================")

Literature; Art & Music - Specialized
==========================
Number of documents: 2286
--------------------------
Number of sentences: 76984
--------------------------
Number of unique books: 1464
--------------------------
Number of unique authors: 1568
--------------------------
Domain distribution:
{'Arts & Humanities': 2286}
--------------------------
Average sentence length distribution:
{'count': 2286.0, 'mean': 16.660290621118204, 'std': 13.36958423325814, 'min': 2.526315789473684, '25%': 9.314814814814815, '50%': 10.666666666666666, '75%': 20.962222222222223, 'max': 221.33333333333334}
==========================

In [31]:
sampled_LAM_specialized_df = LAM_specialized_df.sample(17, random_state=42)

In [32]:
sampled_LAM_specialized_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,average sentence length
13887,BAREC_Hindawi_53957515_001,Hindawi,Hindawi,Gardens and Satan,Nawal El-Saadawi,Arts & Humanities,Specialized Text,Literature; Art & Music,505,26,No,19.423077
12902,BAREC_Hindawi_25817168_001,Hindawi,Hindawi,Letters of Holy Ankara,Qudriya Hussein,Arts & Humanities,Specialized Text,Literature; Art & Music,523,20,No,26.150000
13898,BAREC_Hindawi_57097372_001,Hindawi,Hindawi,Breezes,Salma Saigh,Arts & Humanities,Specialized Text,Literature; Art & Music,506,32,No,15.812500
1077,BAREC_APCD_علي بن أبي طالب_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Ali ibn Abi Talib,Arts & Humanities,Specialized Text,Literature; Art & Music,501,52,No,9.634615
15676,BAREC_Kalima_عدو_001,Kalima,Kalima,Running,Jean Echenoz,Arts & Humanities,Specialized Text,Literature; Art & Music,687,47,Yes,14.617021
808,BAREC_APCD_جرجس عيسى السكاف_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Jurjis Isa al-Sakkaf,Arts & Humanities,Specialized Text,Literature; Art & Music,503,61,No,8.245902
975,BAREC_APCD_شيخ الدولة البركردزي_شيخ الدولة الب...,APCD,Arabic Poem Comprehensive Dataset (APCD),Shaykh Al-Dawla Al-Barkardzi,Shaykh Al-Dawla Al-Barkardzi,Arts & Humanities,Specialized Text,Literature; Art & Music,38,4,No,9.500000
15692,BAREC_Kalima_غوته_ونابليون_001,Kalima,Kalima,Goethe and Napoleon: A Historical Encounter,Gustave Seibt,Arts & Humanities,Specialized Text,Literature; Art & Music,729,35,No,20.828571
15280,BAREC_Kalima_الاسلام_الايطالي_001,Kalima,Kalima,Italian Islam: A Journey Through the Realities...,Stefano Alievi,Arts & Humanities,Specialized Text,Literature; Art & Music,748,31,No,24.129032
14933,BAREC_Hindawi_86952059_001,Hindawi,Hindawi,My Diaries in Women’s Prison,Nawal El-Saadawi,Arts & Humanities,Specialized Text,Literature; Art & Music,526,16,No,32.875000
643,BAREC_APCD_أبو جعفر الزوزني الزاهد_أبو جعفر ...,APCD,Arabic Poem Comprehensive Dataset (APCD),Abu Ja'far Al-Zuzani Al-Zahid,Abu Ja'far Al-Zuzani Al-Zahid,Arts & Humanities,Specialized Text,Literature; Art & Music,16,2,No,8.000000
14160,BAREC_Hindawi_63795362_001,Hindawi,Hindawi,Complete Works,Poet of the Nile Muhammad Hafiz Ibrahim,Arts & Humanities,Specialized Text,Literature; Art & Music,504,85,No,5.929412
13432,BAREC_Hindawi_40702826_001,Hindawi,Hindawi,Roland Barthes,Jonathan Koller,Arts & Humanities,Specialized Text,Literature; Art & Music,513,23,No,22.304348
448,BAREC_APCD_الحبسي_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Al-Habsi,Arts & Humanities,Specialized Text,Literature; Art & Music,507,62,No,8.177419
627,BAREC_APCD_أبو المواهب المعري_أبو المواهب ال...,APCD,Arabic Poem Comprehensive Dataset (APCD),Abu Al-Mawahib Al-Ma'arri,Abu Al-Mawahib Al-Ma'arri,Arts & Humanities,Specialized Text,Literature; Art & Music,52,5,No,10.400000
13756,BAREC_Hindawi_50926304_001,Hindawi,Hindawi,Letters of the Orators,Mohamed Kurd Ali,Arts & Humanities,Specialized Text,Literature; Art & Music,521,21,No,24.809524
15642,BAREC_Kalima_شعراء_القرن_16_بيير_دو_رونسار_001,Kalima,Kalima,Sixteenth Century Poets (3),Pierre de Ronsard,Arts & Humanities,Specialized Text,Literature; Art & Music,686,47,No,14.595745

In [33]:
sampled_LAM_specialized_sentences_indices = []
for i, row in sampled_LAM_specialized_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_LAM_specialized_sentences_indices.append(sampled_index)
print(sampled_LAM_specialized_sentences_indices)

[9, 1, 11, 19, 30, 0, 1, 15, 5, 11, 1, 22, 1, 0, 1, 2, 27]

In [34]:
sampled_LAM_specialized_df['sampled_sentence_index'] = sampled_LAM_specialized_sentences_indices

In [35]:
A_df = pd.concat([sampled_LAM_foundational_df, sampled_LAM_advanced_df, sampled_LAM_specialized_df], ignore_index=True)
A_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,average sentence length,sampled_sentence_index
0,BAREC_TheFiveAdventurers_149 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 149,#,Arts & Humanities,Foundational Text,Literature; Art & Music,698,54,No,12.925926,45
1,BAREC_Hindawi_97962586_001,Hindawi,Hindawi,Baba Abdullah and the Dervish,Kamel Kilani,Arts & Humanities,Foundational Text,Literature; Art & Music,505,39,No,12.948718,10
2,BAREC_TheFiveAdventurers_128 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 128,#,Arts & Humanities,Foundational Text,Literature; Art & Music,691,44,No,15.704545,20
3,BAREC_Ladybird_القدر السحرية_001,Ladybird,Ladybird,The Magic Pot,#,Arts & Humanities,Foundational Text,Literature; Art & Music,630,56,No,11.250000,49
4,BAREC_Hindawi_83941583_001,Hindawi,Hindawi,The Poplar Forest,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,530,22,No,24.090909,1
5,BAREC_SpacetoonSong_أنا وأخي_001,SpacetoonSong,Spacetoon Songs,Me and My Brother,#,Arts & Humanities,Foundational Text,Literature; Art & Music,52,13,Yes,4.000000,10
6,BAREC_Hindawi_17290296_001,Hindawi,Hindawi,Information War,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,500,23,No,21.739130,1
7,BAREC_Superman_070_011,Superman,Superman,Edition: 70,#,Arts & Humanities,Foundational Text,Literature; Art & Music,349,43,No,8.116279,16
8,BAREC_Hindawi_24146069_001,Hindawi,Hindawi,The Adventure of the Missing Rugby Player,Arthur Conan Doyle,Arts & Humanities,Foundational Text,Literature; Art & Music,518,37,No,14.000000,21
9,BAREC_TheFiveAdventurers_077 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 077,#,Arts & Humanities,Foundational Text,Literature; Art & Music,731,68,No,10.750000,27
10,BAREC_Superman_100_010,Superman,Superman,Edition: 100,#,Arts & Humanities,Foundational Text,Literature; Art & Music,593,76,No,7.802632,66
11,BAREC_Hindawi_17271461_001,Hindawi,Hindawi,The Last of the Mohicans,James Fenimore Cooper,Arts & Humanities,Foundational Text,Literature; Art & Music,653,51,Yes,12.803922,28
12,BAREC_ArabYouthPublisher_مالك الحزين يشتري حذا...,ArabYouthPublisher,Arab Youth Publisher,The Heron Buys Shoes,#,Arts & Humanities,Foundational Text,Literature; Art & Music,280,22,No,12.727273,3
13,BAREC_ArabYouthPublisher_جزيرة الضياع_001,ArabYouthPublisher,Arab Youth Publisher,The Island of Loss,#,Arts & Humanities,Foundational Text,Literature; Art & Music,490,25,No,19.600000,4
14,BAREC_Superman_040_010,Superman,Superman,Edition: 40,#,Arts & Humanities,Foundational Text,Literature; Art & Music,598,61,No,9.803279,54
15,BAREC_TheFiveAdventurers_133 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 133,#,Arts & Humanities,Foundational Text,Literature; Art & Music,662,53,No,12.490566,33
16,BAREC_Superman_010_011,Superman,Superman,Edition: 10,#,Arts & Humanities,Foundational Text,Literature; Art & Music,594,69,No,8.608696,60
17,BAREC_Hindawi_28648582_001,Hindawi,Hindawi,Ragnarok,Antonia Susan Byatt,Arts & Humanities,Advanced Text,Literature; Art & Music,1366,82,Yes,16.658537,5
18,BAREC_Hindawi_62505363_001,Hindawi,Hindawi,Steps in the Same River,Riyadh Hammadi,Arts & Humanities,Advanced Text,Literature; Art & Music,505,81,No,6.234568,46
19,BAREC_Hindawi_71693707_001,Hindawi,Hindawi,Cases of John Thorndike,R. Austin Freeman,Arts & Humanities,Advanced Text,Literature; Art & Music,501,23,No,21.782609,1
20,BAREC_Hindawi_18686373_001,Hindawi,Hindawi,The Gentle Strongman,Naguib Mahfouz,Arts & Humanities,Advanced Text,Literature; Art & Music,502,27,No,18.592593,1
21,BAREC_Hindawi_20429368_001,Hindawi,Hindawi,The Younger Brother,Corey Ductoro,Arts & Humanities,Advanced Text,Literature; Art & Music,887,46,Yes,19.282609,39
22,BAREC_Hindawi_29392697_001,Hindawi,Hindawi,The Virtuous Successor,Wadi’ Abu Fadil,Arts & Humanities,Advanced Text,Literature; Art & Music,544,18,No,30.222222,12
23,BAREC_Hindawi_42475809_001,Hindawi,Hindawi,The Mystery of the Lost Necklace,Jack Footrell,Arts & Humanities,Advanced Text,Literature; Art & Music,516,23,No,22.434783,1
24,BAREC_Hindawi_85802403_001,Hindawi,Hindawi,The Thief and the Dogs,Naguib Mahfouz,Arts & Humanities,Advanced Text,Literature; Art & Music,524,26,No,20.153846,1
25,BAREC_Hindawi_69407460_001,Hindawi,Hindawi,The Heart of a Woman,Ponson du Terrail,Arts & Humanities,Advanced Text,Literature; Art & Music,544,26,No,20.923077,9
26,BAREC_Hindawi_72735281_001,Hindawi,Hindawi,The Earth Gods,Gibran Khalil Gibran,Arts & Humanities,Advanced Text,Literature; Art & Music,503,61,No,8.245902,16
27,BAREC_Hindawi_94264040_001,Hindawi,Hindawi,The Big Portrait Mystery and Other Stories,R. Austin Freeman,Arts & Humanities,Advanced Text,Literature; Art & Music,517,43,No,12.023256,15
28,BAREC_Hindawi_29403629_001,Hindawi,Hindawi,I Am the Sultan of the Law of Existence,Yusuf Idris,Arts & Humanities,Advanced Text,Literature; Art & Music,740,46,Yes,16.086957,21
29,BAREC_Hindawi_74859409_001,Hindawi,Hindawi,The Amazing Visit,Herbert George Wells,Arts & Humanities,Advanced Text,Literature; Art & Music,629,39,Yes,16.128205,18
30,BAREC_Other_الكشكول_001,Other,Other Minor Sources,al-Kashkuul,Bayan Safadi,Arts & Humanities,Advanced Text,Literature; Art & Music,287,15,Yes,19.133333,9
31,BAREC_Hindawi_48293606_001,Hindawi,Hindawi,The Specter of the Soul,Edward Page Mitchell,Arts & Humanities,Advanced Text,Literature; Art & Music,500,26,No,19.230769,2
32,BAREC_Hindawi_52951836_001,Hindawi,Hindawi,The Adventure of Sherlo Combs,Robert Barr,Arts & Humanities,Advanced Text,Literature; Art & Music,504,48,No,10.500000,20
33,BAREC_Hindawi_53957515_001,Hindawi,Hindawi,Gardens and Satan,Nawal El-Saadawi,Arts & Humanities,Specialized Text,Literature; Art & Music,505,26,No,19.423077,9
34,BAREC_Hindawi_25817168_001,Hindawi,Hindawi,Letters of Holy Ankara,Qudriya Hussein,Arts & Humanities,Specialized Text,Literature; Art & Music,523,20,No,26.150000,1
35,BAREC_Hindawi_57097372_001,Hindawi,Hindawi,Breezes,Salma Saigh,Arts & Humanities,Specialized Text,Literature; Art & Music,506,32,No,15.812500,11
36,BAREC_APCD_علي بن أبي طالب_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Ali ibn Abi Talib,Arts & Humanities,Specialized Text,Literature; Art & Music,501,52,No,9.634615,19
37,BAREC_Kalima_عدو_001,Kalima,Kalima,Running,Jean Echenoz,Arts & Humanities,Specialized Text,Literature; Art & Music,687,47,Yes,14.617021,30
38,BAREC_APCD_جرجس عيسى السكاف_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Jurjis Isa al-Sakkaf,Arts & Humanities,Specialized Text,Literature; Art & Music,503,61,No,8.245902,0
39,BAREC_APCD_شيخ الدولة البركردزي_شيخ الدولة الب...,APCD,Arabic Poem Comprehensive Dataset (APCD),Shaykh Al-Dawla Al-Barkardzi,Shaykh Al-Dawla Al-Barkardzi,Arts & Humanities,Specialized Text,Literature; Art & Music,38,4,No,9.500000,1
40,BAREC_Kalima_غوته_ونابليون_001,Kalima,Kalima,Goethe and Napoleon: A Historical Encounter,Gustave Seibt,Arts & Humanities,Specialized Text,Literature; Art & Music,729,35,No,20.828571,15
41,BAREC_Kalima_الاسلام_الايطالي_001,Kalima,Kalima,Italian Islam: A Journey Through the Realities...,Stefano Alievi,Arts & Humanities,Specialized Text,Literature; Art & Music,748,31,No,24.129032,5
42,BAREC_Hindawi_86952059_001,Hindawi,Hindawi,My Diaries in Women’s Prison,Nawal El-Saadawi,Arts & Humanities,Specialized Text,Literature; Art & Music,526,16,No,32.875000,11
43,BAREC_APCD_أبو جعفر الزوزني الزاهد_أبو جعفر ...,APCD,Arabic Poem Comprehensive Dataset (APCD),Abu Ja'far Al-Zuzani Al-Zahid,Abu Ja'far Al-Zuzani Al-Zahid,Arts & Humanities,Specialized Text,Literature; Art & Music,16,2,No,8.000000,1
44,BAREC_Hindawi_63795362_001,Hindawi,Hindawi,Complete Works,Poet of the Nile Muhammad Hafiz Ibrahim,Arts & Humanities,Specialized Text,Literature; Art & Music,504,85,No,5.929412,22
45,BAREC_Hindawi_40702826_001,Hindawi,Hindawi,Roland Barthes,Jonathan Koller,Arts & Humanities,Specialized Text,Literature; Art & Music,513,23,No,22.304348,1
46,BAREC_APCD_الحبسي_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Al-Habsi,Arts & Humanities,Specialized Text,Literature; Art & Music,507,62,No,8.177419,0
47,BAREC_APCD_أبو المواهب المعري_أبو المواهب ال...,APCD,Arabic Poem Comprehensive Dataset (APCD),Abu Al-Mawahib Al-Ma'arri,Abu Al-Mawahib Al-Ma'arri,Arts & Humanities,Specialized Text,Literature; Art & Music,52,5,No,10.400000,1
48,BAREC_Hindawi_50926304_001,Hindawi,Hindawi,Letters of the Orators,Mohamed Kurd Ali,Arts & Humanities,Specialized Text,Literature; Art & Music,521,21,No,24.809524,2
49,BAREC_Kalima_شعراء_القرن_16_بيير_دو_رونسار_001,Kalima,Kalima,Sixteenth Century Poets (3),Pierre de Ronsard,Arts & Humanities,Specialized Text,Literature; Art & Music,686,47,No,14.595745,27

In [36]:
A_df['selected_sent_raw'] = None
A_df['selected_sent_word_count'] = None
A_df['selected_sent_words'] = None

for i, row in A_df.iterrows():
    directory = row['Directory']
    document = row['Document']

    annotations_file_path = (
        f"BAREC-10M/Data/Morphology_and_Readability/"
        f"{directory}/{document}.json"
    )

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)

    annotations = pd.DataFrame(annotations)

    selected_sentence_index = int(row['sampled_sentence_index'])

    selected_row = annotations.iloc[selected_sentence_index]

    raw_sentence = selected_row['raw_sents']
    word_count = selected_row['sents_word_count']
    words = selected_row['word']   # list of strings

    A_df.at[i, 'selected_sent_raw'] = raw_sentence
    A_df.at[i, 'selected_sent_word_count'] = word_count
    A_df.at[i, 'selected_sent_words'] = words

In [37]:
A_df = A_df[[
    'Directory',
    'Document',
    'sampled_sentence_index',
    'Source',
    'Book',
    'Author',
    'Domain',
    'Readership Group',
    'Text Category',
    'average sentence length',
    'selected_sent_raw',
    'selected_sent_word_count',
    'selected_sent_words'
]]

In [38]:
A_df.rename(columns={
    'average sentence length': 'average_sentence_length_per_doc',
}, inplace=True)

In [39]:
A_df

,Directory,Document,sampled_sentence_index,Source,Book,Author,Domain,Readership Group,Text Category,average_sentence_length_per_doc,selected_sent_raw,selected_sent_word_count,selected_sent_words
0,TheFiveAdventurers,BAREC_TheFiveAdventurers_149 لغز_001,45,The Five Adventurers,Riddle: 149,#,Arts & Humanities,Foundational Text,Literature; Art & Music,12.925926,"وسوف أبدؤها بزيارة أخي ""طلعت""..",9,"[وسوف, أبدؤها, بزيارة, أخي, "", طلعت, "", ., .]"
1,Hindawi,BAREC_Hindawi_97962586_001,10,Hindawi,Baba Abdullah and the Dervish,Kamel Kilani,Arts & Humanities,Foundational Text,Literature; Art & Music,12.948718,وَبَيْنا كانَ عَائِدًا وَجَدَ — فِي طَرِيقِهِ ...,11,"[وبينا, كان, عائدا, وجد, -, في, طريقه, -, مكان..."
2,TheFiveAdventurers,BAREC_TheFiveAdventurers_128 لغز_001,20,The Five Adventurers,Riddle: 128,#,Arts & Humanities,Foundational Text,Literature; Art & Music,15.704545,"أجاب ""ممدوح"" وهو يجري مبتعدًا: ليس عندي وقت لم...",20,"[أجاب, "", ممدوح, "", وهو, يجري, مبتعدا, :, ليس,..."
3,Ladybird,BAREC_Ladybird_القدر السحرية_001,49,Ladybird,The Magic Pot,#,Arts & Humanities,Foundational Text,Literature; Art & Music,11.250000,أما القدر الصغيرة فإنها واصلت طبخ المهلبية طبخ...,10,"[أما, القدر, الصغيرة, فإنها, واصلت, طبخ, المهل..."
4,Hindawi,BAREC_Hindawi_83941583_001,1,Hindawi,The Poplar Forest,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,24.090909,رقم «١»: «أحمد» من مصر.,11,"[رقم, "", ١, "", :, "", أحمد, "", من, مصر, .]"
5,SpacetoonSong,BAREC_SpacetoonSong_أنا وأخي_001,10,Spacetoon Songs,Me and My Brother,#,Arts & Humanities,Foundational Text,Literature; Art & Music,4.000000,لو سرقت منا الأيام قلبا معطاء بسّام لن نستسلم ...,10,"[لو, سرقت, منا, الأيام, قلبا, معطاء, بسام, لن,..."
6,Hindawi,BAREC_Hindawi_17290296_001,1,Hindawi,Information War,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,21.739130,رقم «١»: «أحمد» من مصر.,11,"[رقم, "", ١, "", :, "", أحمد, "", من, مصر, .]"
7,Superman,BAREC_Superman_070_011,16,Superman,Edition: 70,#,Arts & Humanities,Foundational Text,Literature; Art & Music,8.116279,ما أسهل سرقة المصرف الآن...,8,"[ما, أسهل, سرقة, المصرف, الآن, ., ., .]"
8,Hindawi,BAREC_Hindawi_24146069_001,21,Hindawi,The Adventure of the Missing Rugby Player,Arthur Conan Doyle,Arts & Humanities,Foundational Text,Literature; Art & Music,14.000000,وقد تَجاوَزَ المدخل بِمَنْكِبَيْهِ العَريضَين،...,18,"[وقد, تجاوز, المدخل, بمنكبيه, العريضين, ,, ورا..."
9,TheFiveAdventurers,BAREC_TheFiveAdventurers_077 لغز_001,27,The Five Adventurers,Riddle: 077,#,Arts & Humanities,Foundational Text,Literature; Art & Music,10.750000,وأخذت السيدة العجوز تشير بيدها..,7,"[وأخذت, السيدة, العجوز, تشير, بيدها, ., .]"
10,Superman,BAREC_Superman_100_010,66,Superman,Edition: 100,#,Arts & Humanities,Foundational Text,Literature; Art & Music,7.802632,"فتح ""سوبرمان"" خزانة خفية...",9,"[فتح, "", سوبرمان, "", خزانة, خفية, ., ., .]"
11,Hindawi,BAREC_Hindawi_17271461_001,28,Hindawi,The Last of the Mohicans,James Fenimore Cooper,Arts & Humanities,Foundational Text,Literature; Art & Music,12.803922,ثم استدار إلى كورا وساعدها على امتطاء حصانها.,9,"[ثم, استدار, إلى, كورا, وساعدها, على, امتطاء, ..."
12,ArabYouthPublisher,BAREC_ArabYouthPublisher_مالك الحزين يشتري حذا...,3,Arab Youth Publisher,The Heron Buys Shoes,#,Arts & Humanities,Foundational Text,Literature; Art & Music,12.727273,"ذهب ""مالك الحزين"" مع زوجته إلى سوق الأحذية ليش...",16,"[ذهب, "", مالك, الحزين, "", مع, زوجته, إلى, سوق,..."
13,ArabYouthPublisher,BAREC_ArabYouthPublisher_جزيرة الضياع_001,4,Arab Youth Publisher,The Island of Loss,#,Arts & Humanities,Foundational Text,Literature; Art & Music,19.600000,تحطمت سفينة السائحين وغرقت في بحر الظلمات، واس...,24,"[تحطمت, سفينة, السائحين, وغرقت, في, بحر, الظلم..."
14,Superman,BAREC_Superman_040_010,54,Superman,Edition: 40,#,Arts & Humanities,Foundational Text,Literature; Art & Music,9.803279,"نجحت خطة ""الفتى الجبار"" ولفت المعطف نظر كلبه...",13,"[نجحت, خطة, "", الفتى, الجبار, "", ولفت, المعطف,..."
15,TheFiveAdventurers,BAREC_TheFiveAdventurers_133 لغز_001,33,The Five Adventurers,Riddle: 133,#,Arts & Humanities,Foundational Text,Literature; Art & Music,12.490566,وقد تردد أن الثري المصري على علاقة بهذا المهرب...,18,"[وقد, تردد, أن, الثري, المصري, على, علاقة, بهذ..."
16,Superman,BAREC_Superman_010_011,60,Superman,Edition: 10,#,Arts & Humanities,Foundational Text,Literature; Art & Music,8.608696,يجب أن أبعد هذا الصاروخ!,6,"[يجب, أن, أبعد, هذا, الصاروخ, !]"
17,Hindawi,BAREC_Hindawi_28648582_001,5,Hindawi,Ragnarok,Antonia Susan Byatt,Arts & Humanities,Advanced Text,Literature; Art & Music,16.658537,كانت الحياةُ عبارة عن حالة تدور فيها رحى حرب م...,11,"[كانت, الحياة, عبارة, عن, حالة, تدور, فيها, رح..."
18,Hindawi,BAREC_Hindawi_62505363_001,46,Hindawi,Steps in the Same River,Riyadh Hammadi,Arts & Humanities,Advanced Text,Literature; Art & Music,6.234568,تنافَسَ تجار الفنون على لوحة بيضاء،,7,"[تنافس, تجار, الفنون, على, لوحة, بيضاء, ,]"
19,Hindawi,BAREC_Hindawi_71693707_001,1,Hindawi,Cases of John Thorndike,R. Austin Freeman,Arts & Humanities,Advanced Text,Literature; Art & Music,21.782609,في اعتقادي أنه ليس هناك الكثير من الأماكن حتى ...,28,"[في, اعتقادي, أنه, ليس, هناك, الكثير, من, الأم..."
20,Hindawi,BAREC_Hindawi_18686373_001,1,Hindawi,The Gentle Strongman,Naguib Mahfouz,Arts & Humanities,Advanced Text,Literature; Art & Music,18.592593,جلس ينظر إلى صورته في المرآة الكبيرة، ويتابع ب...,35,"[جلس, ينظر, إلى, صورته, في, المرآة, الكبيرة, ,..."
21,Hindawi,BAREC_Hindawi_20429368_001,39,Hindawi,The Younger Brother,Corey Ductoro,Arts & Humanities,Advanced Text,Literature; Art & Music,19.282609,كان فريدريك بينسان — رقم الضمان الاجتماعي ٥٤٥-...,34,"[كان, فريدريك, بينسان, -, رقم, الضمان, الاجتما..."
22,Hindawi,BAREC_Hindawi_29392697_001,12,Hindawi,The Virtuous Successor,Wadi’ Abu Fadil,Arts & Humanities,Advanced Text,Literature; Art & Music,30.222222,حاشا للدين أنْ يكون كما تفعلون وإلَّا كان الكف...,13,"[حاشا, للدين, أن, يكون, كما, تفعلون, وإلا, كان..."
23,Hindawi,BAREC_Hindawi_42475809_001,1,Hindawi,The Mystery of the Lost Necklace,Jack Footrell,Arts & Humanities,Advanced Text,Literature; Art & Music,22.434783,في صباح اليوم التالي تلقَّى «مُحب» رسالة من «ت...,29,"[في, صباح, اليوم, التالي, تلقى, "", محب, "", رسا..."
24,Hindawi,BAREC_Hindawi_85802403_001,1,Hindawi,The Thief and the Dogs,Naguib Mahfouz,Arts & Humanities,Advanced Text,Literature; Art & Music,20.153846,نظر إلى الباب المفتوح، المفتوح دائمًا كما عهِد...,32,"[نظر, إلى, الباب, المفتوح, ,, المفتوح, دائما, ..."
25,Hindawi,BAREC_Hindawi_69407460_001,9,Hindawi,The Heart of a Woman,Ponson du Terrail,Arts & Humanities,Advanced Text,Literature; Art & Music,20.923077,وأريد بذلك أن ابنك ليس لك الآن، بل هو للبوليس ...,18,"[وأريد, بذلك, أن, ابنك, ليس, لك, الآن, ,, بل, ..."
26,Hindawi,BAREC_Hindawi_72735281_001,16,Hindawi,The Earth Gods,Gibran Khalil Gibran,Arts & Humanities,Advanced Text,Literature; Art & Music,8.245902,وهي ما أودُّ أن أتنشقَّه الآن وفي كل أوان.,10,"[وهي, ما, أود, أن, أتنشقه, الآن, وفي, كل, أوان..."
27,Hindawi,BAREC_Hindawi_94264040_001,15,Hindawi,The Big Portrait Mystery and Other Stories,R. Austin Freeman,Arts & Humanities,Advanced Text,Literature; Art & Music,12.023256,وقد مثلت هذه المشكلةُ موضعَ اهتمام عميق للسيد ...,36,"[وقد, مثلت, هذه, المشكلة, موضع, اهتمام, عميق, ..."
28,Hindawi,BAREC_Hindawi_29403629_001,21,Hindawi,I Am the Sultan of the Law of Existence,Yusuf Idris,Arts & Humanities,Advanced Text,Literature; Art & Music,16.086957,في هالة من فرقعة الأسواط والجئير الذي تضخِّمه ...,22,"[في, هالة, من, فرقعة, الأسواط, والجئير, الذي, ..."
29,Hindawi,BAREC_Hindawi_74859409_001,18,Hindawi,The Amazing Visit,Herbert George Wells,Arts & Humanities,Advanced Text,Literature; Art & Music,16.128205,ولا أعرف إن كان لهذا الوهج أو تلك الموسيقى صلة...,18,"[ولا, أعرف, إن, كان, لهذا, الوهج, أو, تلك, الم..."
30,Other,BAREC_Other_الكشكول_001,9,Other Minor Sources,al-Kashkuul,Bayan Safadi,Arts & Humanities,Advanced Text,Literature; Art & Music,19.133333,إن اختيار النصوص لا يعني تفضيلاً فنياً لها على...,27,"[إن, اختيار, النصوص, لا, يعني, تفضيلا, فنيا, ل..."
31,Hindawi,BAREC_Hindawi_48293606_001,2,Hindawi,The Specter of the Soul,Edward Page Mitchell,Arts & Humanities,Advanced Text,Literature; Art & Music,19.230769,آراء البروفيسور تيندال التي أثبتَتها بما لا يد...,19,"[آراء, البروفيسور, تيندال, التي, أثبتتها, بما,..."
32,Hindawi,BAREC_Hindawi_52951836_001,20,Hindawi,The Adventure of Sherlo Combs,Robert Barr,Arts & Humanities,Advanced Text,Literature; Art & Music,10.500000,«حيَّر لغز بيجرام حتى المُحقق جريجوري من شرطة ...,12,"["", حير, لغز, بيجرام, حتى, المحقق, جريجوري, من..."
33,Hindawi,BAREC_Hindawi_53957515_001,9,Hindawi,Gardens and Satan,Nawal El-Saadawi,Arts & Humanities,Specialized Text,Literature; Art & Music,19.423077,وجوههم يغطيها شعرٌ ذابل يتدلَّى فوق صدورهم.,8,"[وجوههم, يغطيها, شعر, ذابل, يتدلى, فوق, صدورهم..."
34,Hindawi,BAREC_Hindawi_25817168_001,1,Hindawi,Letters of Holy Ankara,Qudriya Hussein,Arts & Humanities,Specialized Text,Literature; Art & Music,26.150000,رأيت أبناء وطني توَّاقين إلى الاستقلال متعطشين...,22,"[رأيت, أبناء, وطني, تواقين, إلى, الاستقلال, مت..."
35,Hindawi,BAREC_Hindawi_57097372_001,11,Hindawi,Breezes,Salma Saigh,Arts & Humanities,Specialized Text,Literature; Art & Music,15.812500,يا لجمالك في الماء تشابهين الدُّمى والتماثيل، ...,23,"[يا, لجمالك, في, الماء, تشابهين, الدمى, والتما..."
36,APCD,BAREC_APCD_علي بن أبي طالب_الديوان الرئيسي_001,19,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Ali ibn Abi Talib,Arts & Humanities,Specialized Text,Literature; Art & Music,9.634615,إِذا أَنكَرتُ عَهداً مِن حَميمٍ فَفي نَفسي ...,9,"[إذا, أنكرت, عهدا, من, حميم, ففي, نفسي, التكرم..."
37,Kalima,BAREC_Kalima_عدو_001,30,Kalima,Running,Jean Echenoz,Arts & Humanities,Specialized Text,Literature; Art & Music,14.617021,إميل في السابعة عشرة، وهو ولد فارع القامة أشقر...,26,"[إميل, في, السابعة, عشرة, ,, وهو, ولد, فارع, ا..."
38,APCD,BAREC_APCD_جرجس عيسى السكاف_الديوان الرئيسي_001,0,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Jurjis Isa al-Sakkaf,Arts & Humanities,Specialized Text,Literature; Art & Music,8.245902,لقد حزتم صفات الأكرمينا فعدتم في الورى غوثا...,9,"[لقد, حزتم, صفات, الأكرمينا, فعدتم, في, الورى,..."
39,APCD,BAREC_APCD_شيخ الدولة البركردزي_شيخ الدولة الب...,1,Arabic Poem Comprehensive Dataset (APCD),Shaykh Al-Dawla Al-Barkardzi,Shaykh Al-Dawla Al-Barkardzi,Arts & Humanities,Specialized Text,Literature; Art & Music,9.500000,من تراخي العظام عند قيام وفتور الكلام مع ما...,10,"[من, تراخي, العظام, عند, قيام, وفتور, الكلام, ..."
40,Kalima,BAREC_Kalima_غوته_ونابليون_001,15,Kalima,Goethe and Napoleon: A Historical Encounter,Gustave Seibt,Arts & Humanities,Specialized Text,Literature; Art & Music,20.828571,ثم بدأت عشرات القذائف تتساقط في معركة فالمي، ك...,46,"[ثم, بدأت, عشرات, القذائف, تتساقط, في, معركة, ..."
41,Kalima,BAREC_Kalima_الاسلام_الايطالي_001,5,Kalima,Italian Islam: A Journey Through the Realities...,Stefano Alievi,Arts & Humanities,Specialized Text,Literature; Art & Music,24.129032,عز الدين عناية - عدنان علي,6,"[عز, الدين, عناية, -, عدنان, علي]"
42,Hindawi,BAREC_Hindawi_86952059_001,11,Hindawi,My Diaries in Women’s Prison,Nawal El-Saadawi,Arts & Humanities,Specialized Text,Literature; Art & Music,32.875000,وإن كان عضوًا بحزب الجهاد أو داعش أو حزب الحكو...,26,"[وإن, كان, عضوا, بحزب, الجهاد, أو, داعش, أو, ح..."
43,APCD,BAREC_APCD_أبو جعفر الزوزني الزاهد_أبو جعفر ...,1,Arabic Poem Comprehensive Dataset (APCD),Abu Ja'far Al-Zuzani Al-Zahid,Abu Ja'far Al-Zuzani Al-Zahid,Arts & Humanities,Specialized Text,Literature; Art & Music,8.000000,بكيت عليه وقد فاتني بكاء الكظيم على يوسف,8,"[بكيت, عليه, وقد, فاتني, بكاء, الكظيم, على, يوسف]"
44,Hindawi,BAREC_Hindawi_63795362_001,22,Hindawi,Complete Works,Poet of the Nile Muhammad Hafiz Ibrahim,Arts & Humanities,Specialized Text,Literature; Art & Music,5.929412,(٤) تهنئة المؤيّد بداره وبمظهره الجديدين (نشرت...,17,"[(, ٤, ), تهنئة, المؤيد, بداره, وبمظهره, الجدي..."
45,Hindawi,BAREC_Hindawi_40702826_001,1,Hindawi,Roland Barthes,Jonathan Koller,Arts & Humanities,Specialized Text,Literature; Art & Music,22.304348,عندما رحل رولان بارت عن عالمنا عن عمر يناهز ال...,28,"[عندما, رحل, رولان, بارت, عن, عالمنا, عن, عمر,..."
46,APCD,BAREC_APCD_الحبسي_الديوان الرئيسي_001,0,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Al-Habsi,Arts & Humanities,Specialized Text,Literature; Art & Music,8.177419,وقائلٍ مَن شفيعُ ال أنام يومَ اللقاءِ,7,"[وقائل, من, شفيع, ال, أنام, يوم, اللقاء]"
47,APCD,BAREC_APCD_أبو المواهب المعري_أبو المواهب ال...,1,Arabic Poem Comprehensive Dataset (APCD),Abu Al-Mawahib Al-Ma'arri,Abu Al-Mawahib Al-Ma'arri,Arts & Humanities,Specialized Text,Literature; Art & Music,10.400000,ليت شعري بأي جرمٍ تفرد ت عن الأصدقاء بأكل ا...,10,"[ليت, شعري, بأي, جرم, تفرد, ت, عن, الأصدقاء, ب..."
48,Hindawi,BAREC_Hindawi_50926304_001,2,Hindawi,Letters of the Orators,Mohamed Kurd Ali,Arts & Humanities,Specialized Text,Literature; Art & Music,24.809524,أمَّا بعد: فإنَّ لكل مخلوق حاجةً، ولكل حاجة غا...,37,"[أما, بعد, :, فإن, لكل, مخلوق, حاجة, ,, ولكل, ..."
49,Kalima,BAREC_Kalima_شعراء_القرن_16_بيير_دو_رونسار_001,27,Kalima,Sixteenth Century Poets (3),Pierre de Ronsard,Arts & Humanities,Specialized Text,Literature; Art & Music,14.595745,بالشمس التي أعشقها أوحد الشمس الأخرى.,7,"[بالشمس, التي, أعشقها, أوحد, الشمس, الأخرى, .]"

In [40]:
# A_df.to_json('sampled_LAM_sentences.json', orient='records', force_ascii=False, indent=4)

In [43]:
metadata['Text Category'].value_counts()

Text Category
Media & Culture                                  7122
Educational Materials; Language & Linguistics    4709
Academic                                         4301
Literature; Art & Music                          3974
Religion & Philosophy                             254
Encyclopedic                                      175
Name: count, dtype: int64

In [47]:
MC_df = metadata[metadata['Text Category']=='Media & Culture']
print("Media & Culture")
print("==========================")
print(f"Number of documents: {MC_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {MC_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {MC_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {MC_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{MC_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{MC_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{MC_df['average sentence length'].describe().to_dict()}")
print("==========================")

Media & Culture
==========================
Number of documents: 7122
--------------------------
Number of sentences: 90271
--------------------------
Number of unique books: 73
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Arts & Humanities': 3339, 'STEM': 2050, 'Social Sciences': 1733}
--------------------------
Readership Group distribution:
{'Advanced Text': 6804, 'Foundational Text': 318}
--------------------------
Average sentence length distribution:
{'count': 7122.0, 'mean': 34.177115010952846, 'std': 21.194923549289182, 'min': 2.5, '25%': 24.4, '50%': 31.550505050505052, '75%': 41.1972972972973, 'max': 1107.0}
==========================

In [58]:
MC_AH_df = MC_df[MC_df['Domain']=='Arts & Humanities']
print("Media & Culture - Arts & Humanities")
print("==========================")
print(f"Number of documents: {MC_AH_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {MC_AH_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {MC_AH_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {MC_AH_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{MC_AH_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{MC_AH_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{MC_AH_df['average sentence length'].describe().to_dict()}")
print("==========================")

Media & Culture - Arts & Humanities
==========================
Number of documents: 3339
--------------------------
Number of sentences: 53523
--------------------------
Number of unique books: 16
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Arts & Humanities': 3339}
--------------------------
Readership Group distribution:
{'Advanced Text': 3021, 'Foundational Text': 318}
--------------------------
Average sentence length distribution:
{'count': 3339.0, 'mean': 33.815569826253, 'std': 26.823106990512063, 'min': 3.0, '25%': 23.0, '50%': 30.555555555555557, '75%': 40.63333333333333, 'max': 1107.0}
==========================

In [50]:
sampled_MC_AH_foundational_df = MC_AH_df[MC_AH_df['Readership Group']=='Foundational Text'].sample(8, random_state=42)
sampled_MC_AH_advanced_df = MC_AH_df[MC_AH_df['Readership Group']=='Advanced Text'].sample(9, random_state=42)

In [51]:
sampled_MC_AH_df = pd.concat([sampled_MC_AH_foundational_df, sampled_MC_AH_advanced_df], ignore_index=True)

In [55]:
sampled_MC_AH_sentences_indices = []
for i, row in sampled_MC_AH_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_MC_AH_sentences_indices.append(sampled_index)
print(sampled_MC_AH_sentences_indices)

[30, 7, 32, 33, 26, 43, 5, 36, 0, 0, 1, 0, 28, 1, 8, 0, 9]

In [56]:
sampled_MC_AH_df['sampled_sentence_index'] = sampled_MC_AH_sentences_indices

In [59]:
MC_ST_df = MC_df[MC_df['Domain']=='STEM']
print("Media & Culture - STEM")
print("==========================")
print(f"Number of documents: {MC_ST_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {MC_ST_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {MC_ST_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {MC_ST_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{MC_ST_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{MC_ST_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{MC_ST_df['average sentence length'].describe().to_dict()}")
print("==========================")

Media & Culture - STEM
==========================
Number of documents: 2050
--------------------------
Number of sentences: 18572
--------------------------
Number of unique books: 34
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'STEM': 2050}
--------------------------
Readership Group distribution:
{'Advanced Text': 2050}
--------------------------
Average sentence length distribution:
{'count': 2050.0, 'mean': 36.51979165085057, 'std': 14.279902363926452, 'min': 6.8, '25%': 27.186363636363637, '50%': 34.2, '75%': 43.333333333333336, 'max': 146.0}
==========================

In [60]:
sampled_MC_ST_df = MC_ST_df.sample(17, random_state=42)

In [65]:
sampled_MC_ST_sentences_indices = []
for i, row in sampled_MC_ST_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_MC_ST_sentences_indices.append(sampled_index)
print(sampled_MC_ST_sentences_indices)

[0, 0, 7, 0, 1, 10, 38, 0, 5, 10, 0, 7, 0, 0, 0, 0, 0]

In [66]:
sampled_MC_ST_df['sampled_sentence_index'] = sampled_MC_ST_sentences_indices

In [67]:
MC_SS_df = MC_df[MC_df['Domain']=='Social Sciences']
print("Media & Culture - Social Sciences")
print("==========================")
print(f"Number of documents: {MC_SS_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {MC_SS_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {MC_SS_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {MC_SS_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{MC_SS_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{MC_SS_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{MC_SS_df['average sentence length'].describe().to_dict()}")
print("==========================")

Media & Culture - Social Sciences
==========================
Number of documents: 1733
--------------------------
Number of sentences: 18176
--------------------------
Number of unique books: 23
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Social Sciences': 1733}
--------------------------
Readership Group distribution:
{'Advanced Text': 1733}
--------------------------
Average sentence length distribution:
{'count': 1733.0, 'mean': 32.10251158332588, 'std': 14.423877229819887, 'min': 2.5, '25%': 23.4, '50%': 30.1, '75%': 39.46666666666667, 'max': 238.33333333333334}
==========================

In [72]:
sampled_MC_SS_df = MC_SS_df.sample(16, random_state=42)

In [73]:
sampled_MC_SS_sentences_indices = []
for i, row in sampled_MC_SS_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_MC_SS_sentences_indices.append(sampled_index)
print(sampled_MC_SS_sentences_indices)

[10, 1, 1, 9, 1, 8, 2, 0, 9, 0, 8, 8, 1, 1, 0, 0]

In [74]:
sampled_MC_SS_df['sampled_sentence_index'] = sampled_MC_SS_sentences_indices

In [75]:
B_df = pd.concat([sampled_MC_AH_df, sampled_MC_ST_df, sampled_MC_SS_df], ignore_index=True)
B_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,average sentence length,sampled_sentence_index
0,BAREC_Majed_0670_1991_021,Majed,Majed,Edition: 670,#,Arts & Humanities,Foundational Text,Media & Culture,340,41,Yes,8.292683,30
1,BAREC_Majed_1901_2015_022,Majed,Majed,Edition: 1901,#,Arts & Humanities,Foundational Text,Media & Culture,86,28,Yes,3.071429,7
2,BAREC_Majed_0229_1983_026,Majed,Majed,Edition: 229,#,Arts & Humanities,Foundational Text,Media & Culture,611,92,Yes,6.641304,32
3,BAREC_Majed_1901_2015_001,Majed,Majed,Edition: 1901,#,Arts & Humanities,Foundational Text,Media & Culture,374,41,Yes,9.121951,33
4,BAREC_Majed_0229_1983_010,Majed,Majed,Edition: 229,#,Arts & Humanities,Foundational Text,Media & Culture,389,55,Yes,7.072727,26
5,BAREC_Majed_0836_1995_023,Majed,Majed,Edition: 836,#,Arts & Humanities,Foundational Text,Media & Culture,561,71,Yes,7.901408,43
6,BAREC_Majed_1269_2003_034,Majed,Majed,Edition: 1269,#,Arts & Humanities,Foundational Text,Media & Culture,148,37,Yes,4.000000,5
7,BAREC_Majed_1481_2007_006,Majed,Majed,Edition: 1481,#,Arts & Humanities,Foundational Text,Media & Culture,749,49,Yes,15.285714,36
8,BAREC_AlArabiya_Culture_0275_001,AlArabiya,AlArabiya News,Culture,#,Arts & Humanities,Advanced Text,Media & Culture,309,7,No,44.142857,0
9,BAREC_Akhbarona_Religion_0073_001,Akhbarona,Akhbarona News,Religion,#,Arts & Humanities,Advanced Text,Media & Culture,40,5,No,8.000000,0
10,BAREC_Akhbarona_Culture_0088_001,Akhbarona,Akhbarona News,Culture,#,Arts & Humanities,Advanced Text,Media & Culture,136,2,No,68.000000,1
11,BAREC_ANERCorp_train_171,ANERCorp,ANERCorp,#,#,Arts & Humanities,Advanced Text,Media & Culture,603,16,No,37.687500,0
12,BAREC_ANERCorp_train_012,ANERCorp,ANERCorp,#,#,Arts & Humanities,Advanced Text,Media & Culture,606,32,No,18.937500,28
13,BAREC_Akhbarona_Culture_0190_001,Akhbarona,Akhbarona News,Culture,#,Arts & Humanities,Advanced Text,Media & Culture,165,4,No,41.250000,1
14,BAREC_Akhbarona_Sports_0191_001,Akhbarona,Akhbarona News,Sports,#,Arts & Humanities,Advanced Text,Media & Culture,564,24,No,23.500000,8
15,BAREC_Akhbarona_Sports_0214_001,Akhbarona,Akhbarona News,Sports,#,Arts & Humanities,Advanced Text,Media & Culture,108,1,No,108.000000,0
16,BAREC_ReadMe_Test_008,ReadMe,ReadMe++,#,#,Arts & Humanities,Advanced Text,Media & Culture,239,20,Yes,11.950000,9
17,BAREC_AlKhaleej_Tech_0158_001,AlKhaleej,AlKhaleej News,Tech,#,STEM,Advanced Text,Media & Culture,252,8,No,31.500000,0
18,BAREC_AlArabiya_Medical_0094_001,AlArabiya,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,201,7,No,28.714286,0
19,BAREC_AlArabiya_Medical_0306_001,AlArabiya,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,279,9,No,31.000000,7
20,BAREC_Akhbarona_Tech_00244_001,Akhbarona,Akhbarona News,Tech,#,STEM,Advanced Text,Media & Culture,246,7,No,35.142857,0
21,BAREC_AlKhaleej_Tech_0197_001,AlKhaleej,AlKhaleej News,Tech,#,STEM,Advanced Text,Media & Culture,278,8,No,34.750000,1
22,BAREC_AlKhaleej_Medical_0266_001,AlKhaleej,AlKhaleej News,Medical,#,STEM,Advanced Text,Media & Culture,627,12,No,52.250000,10
23,BAREC_AlKhaleej_Medical_0272_001,AlKhaleej,AlKhaleej News,Medical,#,STEM,Advanced Text,Media & Culture,2212,45,No,49.155556,38
24,BAREC_AlArabiya_Medical_0344_001,AlArabiya,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,527,21,No,25.095238,0
25,BAREC_AlArabiya_Medical_0218_001,AlArabiya,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,305,11,No,27.727273,5
26,BAREC_AlArabiya_Medical_0229_001,AlArabiya,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,333,12,No,27.750000,10
27,BAREC_AlKhaleej_Medical_0230_001,AlKhaleej,AlKhaleej News,Medical,#,STEM,Advanced Text,Media & Culture,254,6,No,42.333333,0
28,BAREC_AlArabiya_Tech_0028_001,AlArabiya,AlArabiya News,Tech,#,STEM,Advanced Text,Media & Culture,450,9,No,50.000000,7
29,BAREC_AlKhaleej_Medical_0275_001,AlKhaleej,AlKhaleej News,Medical,#,STEM,Advanced Text,Media & Culture,134,3,No,44.666667,0
30,BAREC_AlArabiya_Medical_0185_001,AlArabiya,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,218,7,No,31.142857,0
31,BAREC_Akhbarona_Medical_00070_001,Akhbarona,Akhbarona News,Medical,#,STEM,Advanced Text,Media & Culture,284,25,No,11.360000,0
32,BAREC_AlArabiya_Tech_0056_001,AlArabiya,AlArabiya News,Tech,#,STEM,Advanced Text,Media & Culture,299,7,No,42.714286,0
33,BAREC_Akhbarona_Medical_00188_001,Akhbarona,Akhbarona News,Medical,#,STEM,Advanced Text,Media & Culture,330,7,No,47.142857,0
34,BAREC_AlKhaleej_Politics_0297_001,AlKhaleej,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,1349,29,No,46.517241,10
35,BAREC_AlArabiya_Finance_00209_001,AlArabiya,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,270,5,No,54.000000,1
36,BAREC_AlArabiya_Politics_0291_001,AlArabiya,AlArabiya News,Politics,#,Social Sciences,Advanced Text,Media & Culture,97,4,No,24.250000,1
37,BAREC_AlKhaleej_Politics_0156_001,AlKhaleej,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,611,15,No,40.733333,9
38,BAREC_AlKhaleej_Politics_0318_001,AlKhaleej,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,193,4,No,48.250000,1
39,BAREC_AlKhaleej_Finance_0290_001,AlKhaleej,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,376,10,Yes,37.600000,8
40,BAREC_Akhbarona_Finance_0023_001,Akhbarona,Akhbarona News,Finance,#,Social Sciences,Advanced Text,Media & Culture,70,3,No,23.333333,2
41,BAREC_AlKhaleej_Finance_0234_001,AlKhaleej,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,45,1,No,45.000000,0
42,BAREC_AlArabiya_Politics_0322_001,AlArabiya,AlArabiya News,Politics,#,Social Sciences,Advanced Text,Media & Culture,374,14,No,26.714286,9
43,BAREC_AlKhaleej_Finance_0089_001,AlKhaleej,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,230,6,No,38.333333,0
44,BAREC_AlKhaleej_Politics_0235_001,AlKhaleej,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,186,11,No,16.909091,8
45,BAREC_AlArabiya_Politics_0075_001,AlArabiya,AlArabiya News,Politics,#,Social Sciences,Advanced Text,Media & Culture,277,10,No,27.700000,8
46,BAREC_AlArabiya_Finance_00047_001,AlArabiya,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,151,9,No,16.777778,1
47,BAREC_AlArabiya_Finance_00116_001,AlArabiya,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,331,8,No,41.375000,1
48,BAREC_AlArabiya_Finance_00198_001,AlArabiya,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,349,7,No,49.857143,0
49,BAREC_AlArabiya_Finance_00001_001,AlArabiya,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,307,7,No,43.857143,0

In [76]:
B_df['selected_sent_raw'] = None
B_df['selected_sent_word_count'] = None
B_df['selected_sent_words'] = None

for i, row in B_df.iterrows():
    directory = row['Directory']
    document = row['Document']

    annotations_file_path = (
        f"BAREC-10M/Data/Morphology_and_Readability/"
        f"{directory}/{document}.json"
    )

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)

    annotations = pd.DataFrame(annotations)

    selected_sentence_index = int(row['sampled_sentence_index'])

    selected_row = annotations.iloc[selected_sentence_index]

    raw_sentence = selected_row['raw_sents']
    word_count = selected_row['sents_word_count']
    words = selected_row['word']   # list of strings

    B_df.at[i, 'selected_sent_raw'] = raw_sentence
    B_df.at[i, 'selected_sent_word_count'] = word_count
    B_df.at[i, 'selected_sent_words'] = words

In [77]:
B_df = B_df[[
    'Directory',
    'Document',
    'sampled_sentence_index',
    'Source',
    'Book',
    'Author',
    'Domain',
    'Readership Group',
    'Text Category',
    'average sentence length',
    'selected_sent_raw',
    'selected_sent_word_count',
    'selected_sent_words'
]]

In [78]:
B_df.rename(columns={
    'average sentence length': 'average_sentence_length_per_doc',
}, inplace=True)

In [79]:
B_df

,Directory,Document,sampled_sentence_index,Source,Book,Author,Domain,Readership Group,Text Category,average_sentence_length_per_doc,selected_sent_raw,selected_sent_word_count,selected_sent_words
0,Majed,BAREC_Majed_0670_1991_021,30,Majed,Edition: 670,#,Arts & Humanities,Foundational Text,Media & Culture,8.292683,وقال لهم: اهجموا على الأكل، بلا شفقة ولا رحمةـ...,17,"[وقال, لهم, :, اهجموا, على, الأكل, ,, بلا, شفق..."
1,Majed,BAREC_Majed_1901_2015_022,7,Majed,Edition: 1901,#,Arts & Humanities,Foundational Text,Media & Culture,3.071429,هلا.. هلا.. هلا,7,"[هلا, ., ., هلا, ., ., هلا]"
2,Majed,BAREC_Majed_0229_1983_026,32,Majed,Edition: 229,#,Arts & Humanities,Foundational Text,Media & Culture,6.641304,أنا واثق من نجاح الخطة..,7,"[أنا, واثق, من, نجاح, الخطة, ., .]"
3,Majed,BAREC_Majed_1901_2015_001,33,Majed,Edition: 1901,#,Arts & Humanities,Foundational Text,Media & Culture,9.121951,الإجازة فرصة كي نستفيد ونتعلم ونكتسب مهارات جد...,10,"[الإجازة, فرصة, كي, نستفيد, ونتعلم, ونكتسب, مه..."
4,Majed,BAREC_Majed_0229_1983_010,26,Majed,Edition: 229,#,Arts & Humanities,Foundational Text,Media & Culture,7.072727,كوثر محمد – شمبات – السودان:,7,"[كوثر, محمد, -, شمبات, -, السودان, :]"
5,Majed,BAREC_Majed_0836_1995_023,43,Majed,Edition: 836,#,Arts & Humanities,Foundational Text,Media & Culture,7.901408,وأحيانًا أخرى تضحكين من كل قلبك.,7,"[وأحيانا, أخرى, تضحكين, من, كل, قلبك, .]"
6,Majed,BAREC_Majed_1269_2003_034,5,Majed,Edition: 1269,#,Arts & Humanities,Foundational Text,Media & Culture,4.000000,لا بد أن يكون لك اسم أناديك به,8,"[لا, بد, أن, يكون, لك, اسم, أناديك, به]"
7,Majed,BAREC_Majed_1481_2007_006,36,Majed,Edition: 1481,#,Arts & Humanities,Foundational Text,Media & Culture,15.285714,ستتسبب هذه القوة في العديد من المشاكل لفريقه ح...,14,"[ستتسبب, هذه, القوة, في, العديد, من, المشاكل, ..."
8,AlArabiya,BAREC_AlArabiya_Culture_0275_001,0,AlArabiya News,Culture,#,Arts & Humanities,Advanced Text,Media & Culture,44.142857,غضب وشوق حملته منة فضالي لجمهورها، بعد عودتها ...,30,"[غضب, وشوق, حملته, منة, فضالي, لجمهورها, ,, بع..."
9,Akhbarona,BAREC_Akhbarona_Religion_0073_001,0,Akhbarona News,Religion,#,Arts & Humanities,Advanced Text,Media & Culture,8.000000,الإيمان صفحة اسبوعية تصدر كل يوم جمعة,7,"[الإيمان, صفحة, اسبوعية, تصدر, كل, يوم, جمعة]"
10,Akhbarona,BAREC_Akhbarona_Culture_0088_001,1,Akhbarona News,Culture,#,Arts & Humanities,Advanced Text,Media & Culture,68.000000,حيث توصل في هذا الإطار بعدد من رسائل المدح من...,65,"[حيث, توصل, في, هذا, الإطار, بعدد, من, رسائل, ..."
11,ANERCorp,BAREC_ANERCorp_train_171,0,ANERCorp,#,#,Arts & Humanities,Advanced Text,Media & Culture,37.687500,وكان قادة الانقلاب الذي وقع يوم 19 سبتمبر / أي...,54,"[وكان, قادة, الانقلاب, الذي, وقع, يوم, 19, سبت..."
12,ANERCorp,BAREC_ANERCorp_train_012,28,ANERCorp,#,#,Arts & Humanities,Advanced Text,Media & Culture,18.937500,وانتشرت زراعة الأرز في غينيا وسيراليون وليبيريا .,8,"[وانتشرت, زراعة, الأرز, في, غينيا, وسيراليون, ..."
13,Akhbarona,BAREC_Akhbarona_Culture_0190_001,1,Akhbarona News,Culture,#,Arts & Humanities,Advanced Text,Media & Culture,41.250000,يبدو أن المنشط الإذاعي محمد بوصفيحة الشهير بمو...,63,"[يبدو, أن, المنشط, الإذاعي, محمد, بوصفيحة, الش..."
14,Akhbarona,BAREC_Akhbarona_Sports_0191_001,8,Akhbarona News,Sports,#,Arts & Humanities,Advanced Text,Media & Culture,23.500000,وتحلم تشيلي بالفوز باللقب لأول مرة بعد عروضها ...,31,"[وتحلم, تشيلي, بالفوز, باللقب, لأول, مرة, بعد,..."
15,Akhbarona,BAREC_Akhbarona_Sports_0214_001,0,Akhbarona News,Sports,#,Arts & Humanities,Advanced Text,Media & Culture,108.000000,عبدالاله بوسحابة : أخبارنا المغربيةبعدما شاعت ...,108,"[عبدالاله, بوسحابة, :, أخبارنا, المغربيةبعدما,..."
16,ReadMe,BAREC_ReadMe_Test_008,9,ReadMe++,#,#,Arts & Humanities,Advanced Text,Media & Culture,11.950000,أرني كل الانذارات التي أعددتها.,6,"[أرني, كل, الانذارات, التي, أعددتها, .]"
17,AlKhaleej,BAREC_AlKhaleej_Tech_0158_001,0,AlKhaleej News,Tech,#,STEM,Advanced Text,Media & Culture,31.500000,قدمت وزارة الداخلية، خلال مؤتمر أمن الإنترنت و...,37,"[قدمت, وزارة, الداخلية, ,, خلال, مؤتمر, أمن, ا..."
18,AlArabiya,BAREC_AlArabiya_Medical_0094_001,0,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,28.714286,"هل صادف أن وجدت نفسك في الشارع ""تتمتم متحدثاً ...",14,"[هل, صادف, أن, وجدت, نفسك, في, الشارع, "", تتمت..."
19,AlArabiya,BAREC_AlArabiya_Medical_0306_001,7,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,31.000000,والكميات التي طلبت إيطاليا تعليق استخدامها مصن...,18,"[والكميات, التي, طلبت, إيطاليا, تعليق, استخدام..."
20,Akhbarona,BAREC_Akhbarona_Tech_00244_001,0,Akhbarona News,Tech,#,STEM,Advanced Text,Media & Culture,35.142857,أعلنت شركة سامسونغ عن إجراء تحسينات شاملة على ...,27,"[أعلنت, شركة, سامسونغ, عن, إجراء, تحسينات, شام..."
21,AlKhaleej,BAREC_AlKhaleej_Tech_0197_001,1,AlKhaleej News,Tech,#,STEM,Advanced Text,Media & Culture,34.750000,وتوفر كومون سينس ميديا نصائح للآباء فيما يتعلق...,22,"[وتوفر, كومون, سينس, ميديا, نصائح, للآباء, فيم..."
22,AlKhaleej,BAREC_AlKhaleej_Medical_0266_001,10,AlKhaleej News,Medical,#,STEM,Advanced Text,Media & Culture,52.250000,وأوضح التقرير أنه من المتوقع أن يصل حجم سوق ال...,49,"[وأوضح, التقرير, أنه, من, المتوقع, أن, يصل, حج..."
23,AlKhaleej,BAREC_AlKhaleej_Medical_0272_001,38,AlKhaleej News,Medical,#,STEM,Advanced Text,Media & Culture,49.155556,"وصرحت ل""الخليج"" على هامش مؤتمر الصحة العربي، ب...",49,"[وصرحت, ل, "", الخليج, "", على, هامش, مؤتمر, الص..."
24,AlArabiya,BAREC_AlArabiya_Medical_0344_001,0,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,25.095238,نحن لا نولد ومعنا الميل إلى كراهية من يختلفون ...,13,"[نحن, لا, نولد, ومعنا, الميل, إلى, كراهية, من,..."
25,AlArabiya,BAREC_AlArabiya_Medical_0218_001,5,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,27.727273,وينتج جسم الإنسان بشكل طبيعي مستويات عالية من ...,32,"[وينتج, جسم, الإنسان, بشكل, طبيعي, مستويات, عا..."
26,AlArabiya,BAREC_AlArabiya_Medical_0229_001,10,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,27.750000,وقال رودريكو اوفرين مسؤول الاستجابة للطوارئ في...,56,"[وقال, رودريكو, اوفرين, مسؤول, الاستجابة, للطو..."
27,AlKhaleej,BAREC_AlKhaleej_Medical_0230_001,0,AlKhaleej News,Medical,#,STEM,Advanced Text,Media & Culture,42.333333,أكد إبراهيم بوملحة، مستشار صاحب السموّ حاكم دب...,99,"[أكد, إبراهيم, بوملحة, ,, مستشار, صاحب, السمو,..."
28,AlArabiya,BAREC_AlArabiya_Tech_0028_001,7,AlArabiya News,Tech,#,STEM,Advanced Text,Media & Culture,50.000000,"ولهذا السبب وصلت ""فيسبوك"" إلى طريقة تستفيد من ...",49,"[ولهذا, السبب, وصلت, "", فيسبوك, "", إلى, طريقة,..."
29,AlKhaleej,BAREC_AlKhaleej_Medical_0275_001,0,AlKhaleej News,Medical,#,STEM,Advanced Text,Media & Culture,44.666667,أكدت نخبة من الخبراء والأطباء المحليين والإقلي...,53,"[أكدت, نخبة, من, الخبراء, والأطباء, المحليين, ..."
30,AlArabiya,BAREC_AlArabiya_Medical_0185_001,0,AlArabiya News,Medical,#,STEM,Advanced Text,Media & Culture,31.142857,يؤكد متخصصون على أهمية مراجعة الطبيب في حال عد...,44,"[يؤكد, متخصصون, على, أهمية, مراجعة, الطبيب, في..."
31,Akhbarona,BAREC_Akhbarona_Medical_00070_001,0,Akhbarona News,Medical,#,STEM,Advanced Text,Media & Culture,11.360000,فكرة التنظيف متعبة من جميع الاتجاهات ولكن اكثر...,18,"[فكرة, التنظيف, متعبة, من, جميع, الاتجاهات, ول..."
32,AlArabiya,BAREC_AlArabiya_Tech_0056_001,0,AlArabiya News,Tech,#,STEM,Advanced Text,Media & Culture,42.714286,ألمح صاحب التسريبات الشهير إيفان بلاس إلى أن ش...,37,"[ألمح, صاحب, التسريبات, الشهير, إيفان, بلاس, إ..."
33,Akhbarona,BAREC_Akhbarona_Medical_00188_001,0,Akhbarona News,Medical,#,STEM,Advanced Text,Media & Culture,47.142857,هناك أطعمة ربما تتسبب في إصابة الجسم بالتهابات...,36,"[هناك, أطعمة, ربما, تتسبب, في, إصابة, الجسم, ب..."
34,AlKhaleej,BAREC_AlKhaleej_Politics_0297_001,10,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,46.517241,مراد، إلى إشارة الأمير في خطابه إلى تركيا على ...,38,"[مراد, ,, إلى, إشارة, الأمير, في, خطابه, إلى, ..."
35,AlArabiya,BAREC_AlArabiya_Finance_00209_001,1,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,54.000000,ووفقا لصحيفة الجزيرة السعودية، يجتمع صباح اليو...,35,"[ووفقا, لصحيفة, الجزيرة, السعودية, ,, يجتمع, ص..."
36,AlArabiya,BAREC_AlArabiya_Politics_0291_001,1,AlArabiya News,Politics,#,Social Sciences,Advanced Text,Media & Culture,24.250000,وقال المتحدث باسم قيادة الجيش العقيد فادي أبو ...,34,"[وقال, المتحدث, باسم, قيادة, الجيش, العقيد, فا..."
37,AlKhaleej,BAREC_AlKhaleej_Politics_0156_001,9,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,40.733333,ونقلت وسائل إعلام تركية تصريحات داود أوغلو للص...,35,"[ونقلت, وسائل, إعلام, تركية, تصريحات, داود, أو..."
38,AlKhaleej,BAREC_AlKhaleej_Politics_0318_001,1,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,48.250000,وقال أنان في تصريحات على هامش زيارته لمكتبة ال...,74,"[وقال, أنان, في, تصريحات, على, هامش, زيارته, ل..."
39,AlKhaleej,BAREC_AlKhaleej_Finance_0290_001,8,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,37.600000,ولا شك أن نشر سعر شهري رسمي للنفط الخام في دبي...,48,"[ولا, شك, أن, نشر, سعر, شهري, رسمي, للنفط, الخ..."
40,Akhbarona,BAREC_Akhbarona_Finance_0023_001,2,Akhbarona News,Finance,#,Social Sciences,Advanced Text,Media & Culture,23.333333,و تابعت يومية المساء في عددها الصادر اليوم ، أ...,41,"[و, تابعت, يومية, المساء, في, عددها, الصادر, ا..."
41,AlKhaleej,BAREC_AlKhaleej_Finance_0234_001,0,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,45.000000,اعلنت شركة ديبا في بيان على موقع ناسداك دبي ام...,45,"[اعلنت, شركة, ديبا, في, بيان, على, موقع, ناسدا..."
42,AlArabiya,BAREC_AlArabiya_Politics_0322_001,9,AlArabiya News,Politics,#,Social Sciences,Advanced Text,Media & Culture,26.714286,ويجري اتحاد القوى مشاورات مع رؤساء الكتل السيا...,24,"[ويجري, اتحاد, القوى, مشاورات, مع, رؤساء, الكت..."
43,AlKhaleej,BAREC_AlKhaleej_Finance_0089_001,0,AlKhaleej News,Finance,#,Social Sciences,Advanced Text,Media & Culture,38.333333,ارتفع المؤشر العام لسوق أبوظبي للأوراق المالية...,18,"[ارتفع, المؤشر, العام, لسوق, أبوظبي, للأوراق, ..."
44,AlKhaleej,BAREC_AlKhaleej_Politics_0235_001,8,AlKhaleej News,Politics,#,Social Sciences,Advanced Text,Media & Culture,16.909091,وأضاف أنه تم إلقاء القبض على الجنديين العراقيي...,16,"[وأضاف, أنه, تم, إلقاء, القبض, على, الجنديين, ..."
45,AlArabiya,BAREC_AlArabiya_Politics_0075_001,8,AlArabiya News,Politics,#,Social Sciences,Advanced Text,Media & Culture,27.700000,وتفجرت موجة احتجاجات عالمية على قرار ترمب.,8,"[وتفجرت, موجة, احتجاجات, عالمية, على, قرار, تر..."
46,AlArabiya,BAREC_AlArabiya_Finance_00047_001,1,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,16.777778,وتدير شركة سينو-سي.,6,"[وتدير, شركة, سينو, -, سي, .]"
47,AlArabiya,BAREC_AlArabiya_Finance_00116_001,1,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,41.375000,وأوضحت أن التمويلات الإسلامية حققت أرقاماً جيد...,24,"[وأوضحت, أن, التمويلات, الإسلامية, حققت, أرقام..."
48,AlArabiya,BAREC_AlArabiya_Finance_00198_001,0,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,49.857143,أكد رئيس مجلس إدارة غرفة الشرقية عبدالرحمن الر...,33,"[أكد, رئيس, مجلس, إدارة, غرفة, الشرقية, عبدالر..."
49,AlArabiya,BAREC_AlArabiya_Finance_00001_001,0,AlArabiya News,Finance,#,Social Sciences,Advanced Text,Media & Culture,43.857143,أفادت وزارة المالية الإماراتية بأنها تدرس فرض ...,19,"[أفادت, وزارة, المالية, الإماراتية, بأنها, تدر..."

In [ ]:
# B_df.to_json('sampled_MC_sentences.json', orient='records', force_ascii=False, indent=4)

In [81]:
metadata['Text Category'].value_counts()

Text Category
Media & Culture                                  7122
Educational Materials; Language & Linguistics    4709
Academic                                         4301
Literature; Art & Music                          3974
Religion & Philosophy                             254
Encyclopedic                                      175
Name: count, dtype: int64

In [82]:
ELL_df = metadata[metadata['Text Category']=='Educational Materials; Language & Linguistics']
print("Educational Materials; Language & Linguistics")
print("==========================")
print(f"Number of documents: {ELL_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {ELL_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {ELL_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {ELL_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{ELL_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{ELL_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{ELL_df['average sentence length'].describe().to_dict()}")
print("==========================")

Educational Materials; Language & Linguistics
==========================
Number of documents: 4709
--------------------------
Number of sentences: 176003
--------------------------
Number of unique books: 153
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Arts & Humanities': 2644, 'Social Sciences': 1143, 'STEM': 922}
--------------------------
Readership Group distribution:
{'Specialized Text': 2131, 'Advanced Text': 1700, 'Foundational Text': 878}
--------------------------
Average sentence length distribution:
{'count': 4709.0, 'mean': 40.3278243679819, 'std': 36.4060742197123, 'min': 1.6666666666666667, '25%': 9.725806451612904, '50%': 20.12121212121212, '75%': 71.44444444444444, 'max': 233.0}
==========================

In [83]:
ELL_AH_df = ELL_df[ELL_df['Domain']=='Arts & Humanities']
print("Educational Materials; Language & Linguistics - Arts & Humanities")
print("==========================")
print(f"Number of documents: {ELL_AH_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {ELL_AH_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {ELL_AH_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {ELL_AH_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{ELL_AH_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{ELL_AH_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{ELL_AH_df['average sentence length'].describe().to_dict()}")
print("==========================")

Educational Materials; Language & Linguistics - Arts & Humanities
==========================
Number of documents: 2644
--------------------------
Number of sentences: 125647
--------------------------
Number of unique books: 61
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Arts & Humanities': 2644}
--------------------------
Readership Group distribution:
{'Advanced Text': 1107, 'Specialized Text': 961, 'Foundational Text': 576}
--------------------------
Average sentence length distribution:
{'count': 2644.0, 'mean': 31.706006481763776, 'std': 36.29987302225113, 'min': 2.6548672566371683, '25%': 8.173469387755102, '50%': 12.604166666666668, '75%': 43.035714285714285, 'max': 233.0}
==========================

In [84]:
sampled_ELL_AH_foundational_df = ELL_AH_df[ELL_AH_df['Readership Group']=='Foundational Text'].sample(5, random_state=42)
sampled_ELL_AH_advanced_df = ELL_AH_df[ELL_AH_df['Readership Group']=='Advanced Text'].sample(6, random_state=42)
sampled_ELL_AH_special_df = ELL_AH_df[ELL_AH_df['Readership Group']=='Specialized Text'].sample(6, random_state=42)

In [85]:
sampled_ELL_AH_df = pd.concat([sampled_ELL_AH_foundational_df, sampled_ELL_AH_advanced_df, sampled_ELL_AH_special_df], ignore_index=True)

In [87]:
sampled_ELL_AH_sentences_indices = []
for i, row in sampled_ELL_AH_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_ELL_AH_sentences_indices.append(sampled_index)
print(sampled_ELL_AH_sentences_indices)

[68, 42, 51, 52, 7, 84, 42, 0, 0, 41, 0, 0, 20, 0, 0, 58, 0]

In [88]:
sampled_ELL_AH_df['sampled_sentence_index'] = sampled_ELL_AH_sentences_indices

In [90]:
ELL_ST_df = ELL_df[ELL_df['Domain']=='STEM']
print("Educational Materials; Language & Linguistics - STEM")
print("==========================")
print(f"Number of documents: {ELL_ST_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {ELL_ST_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {ELL_ST_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {ELL_ST_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{ELL_ST_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{ELL_ST_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{ELL_ST_df['average sentence length'].describe().to_dict()}")
print("==========================")

Educational Materials; Language & Linguistics - STEM
==========================
Number of documents: 922
--------------------------
Number of sentences: 8695
--------------------------
Number of unique books: 49
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'STEM': 922}
--------------------------
Readership Group distribution:
{'Specialized Text': 662, 'Advanced Text': 175, 'Foundational Text': 85}
--------------------------
Average sentence length distribution:
{'count': 922.0, 'mean': 71.35990994101527, 'std': 21.467599100210514, 'min': 14.6, '25%': 61.51136363636364, '50%': 70.22222222222223, '75%': 81.09375, 'max': 169.0}
==========================

In [91]:
sampled_ELL_ST_foundational_df = ELL_ST_df[ELL_ST_df['Readership Group']=='Foundational Text'].sample(5, random_state=42)
sampled_ELL_ST_advanced_df = ELL_ST_df[ELL_ST_df['Readership Group']=='Advanced Text'].sample(6, random_state=42)
sampled_ELL_ST_special_df = ELL_ST_df[ELL_ST_df['Readership Group']=='Specialized Text'].sample(6, random_state=42)

In [92]:
sampled_ELL_ST_df = pd.concat([sampled_ELL_ST_foundational_df, sampled_ELL_ST_advanced_df, sampled_ELL_ST_special_df], ignore_index=True)

In [93]:
sampled_ELL_ST_sentences_indices = []
for i, row in sampled_ELL_ST_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_ELL_ST_sentences_indices.append(sampled_index)
print(sampled_ELL_ST_sentences_indices)

[0, 0, 1, 0, 0, 8, 1, 0, 7, 5, 7, 1, 0, 1, 5, 1, 1]

In [94]:
sampled_ELL_ST_df['sampled_sentence_index'] = sampled_ELL_ST_sentences_indices

In [95]:
ELL_SS_df = ELL_df[ELL_df['Domain']=='Social Sciences']
print("Educational Materials; Language & Linguistics - Social Sciences")
print("==========================")
print(f"Number of documents: {ELL_SS_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {ELL_SS_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {ELL_SS_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {ELL_SS_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{ELL_SS_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{ELL_SS_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{ELL_SS_df['average sentence length'].describe().to_dict()}")
print("==========================")

Educational Materials; Language & Linguistics - Social Sciences
==========================
Number of documents: 1143
--------------------------
Number of sentences: 41661
--------------------------
Number of unique books: 45
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Social Sciences': 1143}
--------------------------
Readership Group distribution:
{'Specialized Text': 508, 'Advanced Text': 418, 'Foundational Text': 217}
--------------------------
Average sentence length distribution:
{'count': 1143.0, 'mean': 35.23990100212361, 'std': 32.67019027449575, 'min': 1.6666666666666667, '25%': 10.487288135593221, '50%': 15.512820512820513, '75%': 67.0, 'max': 157.0}
==========================

In [96]:
sampled_ELL_SS_foundational_df = ELL_SS_df[ELL_SS_df['Readership Group']=='Foundational Text'].sample(5, random_state=42)
sampled_ELL_SS_advanced_df = ELL_SS_df[ELL_SS_df['Readership Group']=='Advanced Text'].sample(5, random_state=42)
sampled_ELL_SS_special_df = ELL_SS_df[ELL_SS_df['Readership Group']=='Specialized Text'].sample(6, random_state=42)

In [97]:
sampled_ELL_SS_df = pd.concat([sampled_ELL_SS_foundational_df, sampled_ELL_SS_advanced_df, sampled_ELL_SS_special_df], ignore_index=True)

In [98]:
sampled_ELL_SS_sentences_indices = []
for i, row in sampled_ELL_SS_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_ELL_SS_sentences_indices.append(sampled_index)
print(sampled_ELL_SS_sentences_indices)

[7, 7, 17, 17, 0, 32, 27, 7, 71, 76, 15, 7, 0, 7, 16, 1]

In [99]:
sampled_ELL_SS_df['sampled_sentence_index'] = sampled_ELL_SS_sentences_indices

In [100]:
C_df = pd.concat([sampled_ELL_AH_df, sampled_ELL_ST_df, sampled_ELL_SS_df], ignore_index=True)
C_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,average sentence length,sampled_sentence_index
0,BAREC_Curriculum_03_slm_t1_u01_008,Curriculum,Emarati Curriculum,Grade 3 Islamic Studies,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,525,70,No,7.500000,68
1,BAREC_Curriculum_02_arb_t1_u02_003,Curriculum,Emarati Curriculum,Grade 2 Arabic Language,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,606,82,No,7.390244,42
2,BAREC_Curriculum_04_slm_t1_u02_001,Curriculum,Emarati Curriculum,Grade 4 Islamic Studies,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,983,143,Yes,6.874126,51
3,BAREC_TunisCurriculum_Pri_03_reading_P1_007,TunisCurriculum,Tunis Curriculum,Grade 3 Arabic Language,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,587,59,No,9.949153,52
4,BAREC_DARES_ArabicLanguage_G3_2_001,DARES,DARES,G3 - ArabicLanguage,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,602,9,No,66.888889,7
5,BAREC_Curriculum_09_arb_a1_u02_001,Curriculum,Emarati Curriculum,Grade 9 Arabic Language,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,724,85,Yes,8.517647,84
6,BAREC_TunisCurriculum_Pri_05_reading_020,TunisCurriculum,Tunis Curriculum,Grade 5 Arabic Language,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,607,49,No,12.387755,42
7,BAREC_ArabicMMLU_Group_19_002,ArabicMMLU,ArabicMMLU,#,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,529,20,Yes,26.450000,0
8,BAREC_Curriculum_09_arb_t1_u02_006,Curriculum,Emarati Curriculum,Grade 9 Arabic Language,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,605,34,No,17.794118,0
9,BAREC_Curriculum_08_arb_t1_u03_008,Curriculum,Emarati Curriculum,Grade 8 Arabic Language,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,604,141,No,4.283688,41
10,BAREC_Curriculum_09_arb_t1_u02_023,Curriculum,Emarati Curriculum,Grade 9 Arabic Language,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,601,21,No,28.619048,0
11,BAREC_Curriculum_11_arb_a1_u03_020,Curriculum,Emarati Curriculum,Grade 11 Arabic Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,621,35,No,17.742857,0
12,BAREC_Curriculum_11_arb_t1_u02_034,Curriculum,Emarati Curriculum,Grade 11 Arabic Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,613,41,No,14.951220,20
13,BAREC_Curriculum_11_arb_t1_u02_004,Curriculum,Emarati Curriculum,Grade 11 Arabic Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,605,24,No,25.208333,0
14,BAREC_DARES_Artistic_Education_G9_5_001,DARES,DARES,G9 - Artistic_Education,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,673,6,No,112.166667,0
15,BAREC_Curriculum_11_arb_a1_u01_047,Curriculum,Emarati Curriculum,Grade 11 Arabic Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,607,69,No,8.797101,58
16,BAREC_DARES_Arabic_Language_G10_5_008,DARES,DARES,G10 - Arabic_Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,621,6,No,103.500000,0
17,BAREC_DARES_Science_G4_006,DARES,DARES,G4 - Science,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,477,7,No,68.142857,0
18,BAREC_ArabicMMLU_Group_2_001,ArabicMMLU,ArabicMMLU,#,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,372,20,Yes,18.600000,0
19,BAREC_DARES_Science_G3_3_001,DARES,DARES,G3 - Science,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,614,8,No,76.750000,1
20,BAREC_ArabicMMLU_Group_8_007,ArabicMMLU,ArabicMMLU,#,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,509,20,Yes,25.450000,0
21,BAREC_ArabicMMLU_Group_7_009,ArabicMMLU,ArabicMMLU,#,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,357,20,Yes,17.850000,0
22,BAREC_DARES_Science_G8_2_008,DARES,DARES,G8 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,670,10,No,67.000000,8
23,BAREC_DARES_Science_G8_003,DARES,DARES,G8 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,644,8,No,80.500000,1
24,BAREC_DARES_Science_G5_4_001,DARES,DARES,G5 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,499,7,No,71.285714,0
25,BAREC_DARES_Science_G7_3_001,DARES,DARES,G7 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,611,9,No,67.888889,7
26,BAREC_DARES_Science_G7_4_005,DARES,DARES,G7 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,634,11,No,57.636364,5
27,BAREC_DARES_Science_G7_4_003,DARES,DARES,G7 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,659,9,No,73.222222,7
28,BAREC_DARES_Geography_G10_001,DARES,DARES,G10 - Geography,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,674,8,No,84.250000,1
29,BAREC_DARES_Psychology_G10_008,DARES,DARES,G10 - Psychology,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,602,7,No,86.000000,0
30,BAREC_DARES_Physics_G10_2_001,DARES,DARES,G10 - Physics,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,641,8,No,80.125000,1
31,BAREC_DARES_Geology_G10_012,DARES,DARES,G10 - Geology,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,601,11,No,54.636364,5
32,BAREC_DARES_Computer_Sci_G10_3_005,DARES,DARES,G10 - Computer_Sci,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,656,8,No,82.000000,1
33,BAREC_DARES_Tech_G12_003,DARES,DARES,G12 - Tech,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,684,8,No,85.500000,1
34,BAREC_DARES_Sociology_G4_006,DARES,DARES,G4 - Sociology,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,651,9,No,72.333333,7
35,BAREC_DARES_Sociology_G4_4_005,DARES,DARES,G4 - Sociology,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,631,9,No,70.111111,7
36,BAREC_Curriculum_04_soc_t1_u03_004,Curriculum,Emarati Curriculum,Grade 4 Social Sciences,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,606,59,No,10.271186,17
37,BAREC_Curriculum_04_soc_t2_u08_004,Curriculum,Emarati Curriculum,Grade 4 Social Sciences,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,604,44,No,13.727273,17
38,BAREC_ArabicMMLU_Group_9_009,ArabicMMLU,ArabicMMLU,#,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,304,20,Yes,15.200000,0
39,BAREC_Curriculum_09_soc_t3_u07_006,Curriculum,Emarati Curriculum,Grade 9 Social Sciences,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,607,65,No,9.338462,32
40,BAREC_Curriculum_09_soc_t3_u08_002,Curriculum,Emarati Curriculum,Grade 9 Social Sciences,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,606,52,No,11.653846,27
41,BAREC_DARES_Sociology_G7_2_009,DARES,DARES,G7 - Sociology,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,649,9,No,72.111111,7
42,BAREC_Curriculum_05_soc_t3_u06_001,Curriculum,Emarati Curriculum,Grade 5 Social Sciences,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,605,132,No,4.583333,71
43,BAREC_Curriculum_07_soc_t1_u02_001,Curriculum,Emarati Curriculum,Grade 7 Social Sciences,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,851,85,Yes,10.011765,76
44,BAREC_Curriculum_10_soc_t2_u07_003,Curriculum,Emarati Curriculum,Grade 10 Social Sciences,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,640,50,No,12.800000,15
45,BAREC_DARES_Critical_Thinking_G9_2_006,DARES,DARES,G9 - Critical_Thinking,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,609,9,No,67.666667,7
46,BAREC_DARES_Sociology_G10_2_009,DARES,DARES,G10 - Sociology,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,635,7,No,90.714286,0
47,BAREC_DARES_History_G11_008,DARES,DARES,G11 - History,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,629,9,No,69.888889,7
48,BAREC_Curriculum_11_soc_t3_u09_004,Curriculum,Emarati Curriculum,Grade 11 Social Sciences,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,649,51,No,12.725490,16
49,BAREC_DARES_Sociology_G9_2_001,DARES,DARES,G9 - Sociology,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,73,2,No,36.500000,1

In [101]:
C_df['selected_sent_raw'] = None
C_df['selected_sent_word_count'] = None
C_df['selected_sent_words'] = None

for i, row in C_df.iterrows():
    directory = row['Directory']
    document = row['Document']

    annotations_file_path = (
        f"BAREC-10M/Data/Morphology_and_Readability/"
        f"{directory}/{document}.json"
    )

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)

    annotations = pd.DataFrame(annotations)

    selected_sentence_index = int(row['sampled_sentence_index'])

    selected_row = annotations.iloc[selected_sentence_index]

    raw_sentence = selected_row['raw_sents']
    word_count = selected_row['sents_word_count']
    words = selected_row['word']   # list of strings

    C_df.at[i, 'selected_sent_raw'] = raw_sentence
    C_df.at[i, 'selected_sent_word_count'] = word_count
    C_df.at[i, 'selected_sent_words'] = words

In [102]:
C_df = C_df[[
    'Directory',
    'Document',
    'sampled_sentence_index',
    'Source',
    'Book',
    'Author',
    'Domain',
    'Readership Group',
    'Text Category',
    'average sentence length',
    'selected_sent_raw',
    'selected_sent_word_count',
    'selected_sent_words'
]]

In [103]:
C_df.rename(columns={
    'average sentence length': 'average_sentence_length_per_doc',
}, inplace=True)

In [104]:
C_df

,Directory,Document,sampled_sentence_index,Source,Book,Author,Domain,Readership Group,Text Category,average_sentence_length_per_doc,selected_sent_raw,selected_sent_word_count,selected_sent_words
0,Curriculum,BAREC_Curriculum_03_slm_t1_u01_008,68,Emarati Curriculum,Grade 3 Islamic Studies,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,7.500000,"سَأُرْسِلُ إِلَيْهِمْ بِهَدِيَّةٍ ثَمينَةٍ, وَ...",9,"[سأرسل, إليهم, بهدية, ثمينة, ,, وأرى, ما, سيفع..."
1,Curriculum,BAREC_Curriculum_02_arb_t1_u02_003,42,Emarati Curriculum,Grade 2 Arabic Language,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,7.390244,"وَطَنُنا وَطَنُ خيرٍ وَعَطاءٍ, وَطَنُ أَمْنٍ س...",9,"[وطننا, وطن, خير, وعطاء, ,, وطن, أمن, سلام, .]"
2,Curriculum,BAREC_Curriculum_04_slm_t1_u02_001,51,Emarati Curriculum,Grade 4 Islamic Studies,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,6.874126,ما الْكُتُبُ الْمَقْصودَةُ في الْآيَةِ الْكَري...,7,"[ما, الكتب, المقصودة, في, الآية, الكريمة, ؟]"
3,TunisCurriculum,BAREC_TunisCurriculum_Pri_03_reading_P1_007,52,Tunis Curriculum,Grade 3 Arabic Language,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,9.949153,وعلى ساعدك المضنى لنا كل فصل موسم يطفح رزقاً,9,"[وعلى, ساعدك, المضنى, لنا, كل, فصل, موسم, يطفح..."
4,DARES,BAREC_DARES_ArabicLanguage_G3_2_001,7,DARES,G3 - ArabicLanguage,#,Arts & Humanities,Foundational Text,Educational Materials; Language & Linguistics,66.888889,قف خالد يتأمل البحر وجماله وأمواجه المتلاطمة، ...,81,"[قف, خالد, يتأمل, البحر, وجماله, وأمواجه, المت..."
5,Curriculum,BAREC_Curriculum_09_arb_a1_u02_001,84,Emarati Curriculum,Grade 9 Arabic Language,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,8.517647,ما الّذي يمكنُ أنْ تعملَهُ لكي تصبحَ كلُّ وصاي...,16,"[ما, الذي, يمكن, أن, تعمله, لكي, تصبح, كل, وصا..."
6,TunisCurriculum,BAREC_TunisCurriculum_Pri_05_reading_020,42,Tunis Curriculum,Grade 5 Arabic Language,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,12.387755,ذات يوم من أواخر شهر جوان خرجت كعادتي إلى أطرا...,30,"[ذات, يوم, من, أواخر, شهر, جوان, خرجت, كعادتي,..."
7,ArabicMMLU,BAREC_ArabicMMLU_Group_19_002,0,ArabicMMLU,#,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,26.450000,دعاء الاستفتاح من (أ) شروط الاستفتاح (ب) أرك...,23,"[دعاء, الاستفتاح, من, (, أ, ), شروط, الاستفتاح..."
8,Curriculum,BAREC_Curriculum_09_arb_t1_u02_006,0,Emarati Curriculum,Grade 9 Arabic Language,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,17.794118,إذ مال الشعراء إلى إحياء النماذج التراثية في ا...,61,"[إذ, مال, الشعراء, إلى, إحياء, النماذج, التراث..."
9,Curriculum,BAREC_Curriculum_08_arb_t1_u03_008,41,Emarati Curriculum,Grade 8 Arabic Language,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,4.283688,إنَّ التلَوُّثَ وارْتفاعِ نِسَبِ المُلوحةِ في ...,17,"[إن, التلوث, وارتفاع, نسب, الملوحة, في, الكثير..."
10,Curriculum,BAREC_Curriculum_09_arb_t1_u02_023,0,Emarati Curriculum,Grade 9 Arabic Language,#,Arts & Humanities,Advanced Text,Educational Materials; Language & Linguistics,28.619048,ولذلك يعدّ الصدق من أهم شروط كتابة السيرة الأد...,10,"[ولذلك, يعد, الصدق, من, أهم, شروط, كتابة, السي..."
11,Curriculum,BAREC_Curriculum_11_arb_a1_u03_020,0,Emarati Curriculum,Grade 11 Arabic Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,17.742857,وأن يكون قد سجّل أي سؤال لديه حول أي نقطة من ن...,14,"[وأن, يكون, قد, سجل, أي, سؤال, لديه, حول, أي, ..."
12,Curriculum,BAREC_Curriculum_11_arb_t1_u02_034,20,Emarati Curriculum,Grade 11 Arabic Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,14.951220,كل ما في الأمر أننا كنا ثمانية عشر شخصًا في بي...,23,"[كل, ما, في, الأمر, أننا, كنا, ثمانية, عشر, شخ..."
13,Curriculum,BAREC_Curriculum_11_arb_t1_u02_004,0,Emarati Curriculum,Grade 11 Arabic Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,25.208333,يقول حسان بن ثابت في إحدى بديعياته:,8,"[يقول, حسان, بن, ثابت, في, إحدى, بديعياته, :]"
14,DARES,BAREC_DARES_Artistic_Education_G9_5_001,0,DARES,G9 - Artistic_Education,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,112.166667,صحيح أن الألوان الشائعة غالبا ما تكون الأسود، ...,175,"[صحيح, أن, الألوان, الشائعة, غالبا, ما, تكون, ..."
15,Curriculum,BAREC_Curriculum_11_arb_a1_u01_047,58,Emarati Curriculum,Grade 11 Arabic Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,8.797101,الكَلامُ المتَواصِلُ بِصوتٍ مُنخَفِضٍ وَصوتُ ا...,8,"[الكلام, المتواصل, بصوت, منخفض, وصوت, الذباب, ..."
16,DARES,BAREC_DARES_Arabic_Language_G10_5_008,0,DARES,G10 - Arabic_Language,#,Arts & Humanities,Specialized Text,Educational Materials; Language & Linguistics,103.500000,تقع الأخطاء الإملائية واللغوية في النص التالي ...,116,"[تقع, الأخطاء, الإملائية, واللغوية, في, النص, ..."
17,DARES,BAREC_DARES_Science_G4_006,0,DARES,G4 - Science,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,68.142857,تحسين التصاميم يتم من خلال استخدام النماذج، وا...,133,"[تحسين, التصاميم, يتم, من, خلال, استخدام, النم..."
18,ArabicMMLU,BAREC_ArabicMMLU_Group_2_001,0,ArabicMMLU,#,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,18.600000,تظهر نتيجة العمل في منطقة المنصة. (أ) صح (ب)...,15,"[تظهر, نتيجة, العمل, في, منطقة, المنصة, ., (, ..."
19,DARES,BAREC_DARES_Science_G3_3_001,1,DARES,G3 - Science,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,76.750000,نظرا لمرور الهواء الرطب من فوق البحر نحو الجبا...,56,"[نظرا, لمرور, الهواء, الرطب, من, فوق, البحر, ن..."
20,ArabicMMLU,BAREC_ArabicMMLU_Group_8_007,0,ArabicMMLU,#,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,25.450000,عندما تسمع شيئا ما فالذي يعمل على التعرف على ه...,29,"[عندما, تسمع, شيئا, ما, فالذي, يعمل, على, التع..."
21,ArabicMMLU,BAREC_ArabicMMLU_Group_7_009,0,ArabicMMLU,#,#,STEM,Foundational Text,Educational Materials; Language & Linguistics,17.850000,عدد إذا جمعته مع 4 كان الناتج 4 (أ) 0 (ب) 4 ...,20,"[عدد, إذا, جمعته, مع, 4, كان, الناتج, 4, (, أ,..."
22,DARES,BAREC_DARES_Science_G8_2_008,8,DARES,G8 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,67.000000,يمكن تصحيح طول النظر باستخدام جراحة الليزر. تح...,42,"[يمكن, تصحيح, طول, النظر, باستخدام, جراحة, الل..."
23,DARES,BAREC_DARES_Science_G8_003,1,DARES,G8 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,80.500000,على الرغم من أن هذا الحامض يعمل على هضم الطعام...,64,"[على, الرغم, من, أن, هذا, الحامض, يعمل, على, ه..."
24,DARES,BAREC_DARES_Science_G5_4_001,0,DARES,G5 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,71.285714,الفصل السابع الدرس الأول الغلاف الجوي والطقس أ...,119,"[الفصل, السابع, الدرس, الأول, الغلاف, الجوي, و..."
25,DARES,BAREC_DARES_Science_G7_3_001,7,DARES,G7 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,67.888889,الصخرة المتحولة هي الصخرة الأم التي تغيرت تحت ...,51,"[الصخرة, المتحولة, هي, الصخرة, الأم, التي, تغي..."
26,DARES,BAREC_DARES_Science_G7_4_005,5,DARES,G7 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,57.636364,التصرف اللائق المتوقع في المختبر هو الجدية وال...,49,"[التصرف, اللائق, المتوقع, في, المختبر, هو, الج..."
27,DARES,BAREC_DARES_Science_G7_4_003,7,DARES,G7 - Science,#,STEM,Advanced Text,Educational Materials; Language & Linguistics,73.222222,أثناء تنفيذ هذه الدراسة، يجب توخي الدقة في تسج...,59,"[أثناء, تنفيذ, هذه, الدراسة, ,, يجب, توخي, الد..."
28,DARES,BAREC_DARES_Geography_G10_001,1,DARES,G10 - Geography,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,84.250000,مدينة المكسيك، العاصمة السابعة عشرة من حيث عدد...,80,"[مدينة, المكسيك, ,, العاصمة, السابعة, عشرة, من..."
29,DARES,BAREC_DARES_Psychology_G10_008,0,DARES,G10 - Psychology,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,86.000000,ما الفرق بين التوكيد والعدوان والخضوع في الإشا...,120,"[ما, الفرق, بين, التوكيد, والعدوان, والخضوع, ف..."
30,DARES,BAREC_DARES_Physics_G10_2_001,1,DARES,G10 - Physics,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,80.125000,القانون الثاني لكيبلر ينص على أن الخط الوهمي م...,46,"[القانون, الثاني, لكيبلر, ينص, على, أن, الخط, ..."
31,DARES,BAREC_DARES_Geology_G10_012,5,DARES,G10 - Geology,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,54.636364,تتكون الكثبان الرملية عادة من رمل ناعم جيد الف...,82,"[تتكون, الكثبان, الرملية, عادة, من, رمل, ناعم,..."
32,DARES,BAREC_DARES_Computer_Sci_G10_3_005,1,DARES,G10 - Computer_Sci,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,82.000000,تمت زيارتي لمتحف الفن الحديث يوم الخميس الماضي...,114,"[تمت, زيارتي, لمتحف, الفن, الحديث, يوم, الخميس..."
33,DARES,BAREC_DARES_Tech_G12_003,1,DARES,G12 - Tech,#,STEM,Specialized Text,Educational Materials; Language & Linguistics,85.500000,هناك برامج مصممة للتخطيط للمشاريع والمجموعات ا...,56,"[هناك, برامج, مصممة, للتخطيط, للمشاريع, والمجم..."
34,DARES,BAREC_DARES_Sociology_G4_006,7,DARES,G4 - Sociology,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,72.333333,تصحيح مسار الرسالة في أي زمن، وتجنب التشويش وا...,95,"[تصحيح, مسار, الرسالة, في, أي, زمن, ,, وتجنب, ..."
35,DARES,BAREC_DARES_Sociology_G4_4_005,7,DARES,G4 - Sociology,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,70.111111,أقاربي من جهة أمي يكتبون. ثلاثة من فوائد العمل...,52,"[أقاربي, من, جهة, أمي, يكتبون, ., ثلاثة, من, ف..."
36,Curriculum,BAREC_Curriculum_04_soc_t1_u03_004,17,Emarati Curriculum,Grade 4 Social Sciences,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,10.271186,أَمَامَي مَجْمُوعَةُ صُوَرٍ لِعِدَّةِ مَوَانِئ...,22,"[أمامي, مجموعة, صور, لعدة, موانئ, في, بلدنا, د..."
37,Curriculum,BAREC_Curriculum_04_soc_t2_u08_004,17,Emarati Curriculum,Grade 4 Social Sciences,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,13.727273,وَمِنْ هَذا المُنْطَلَقِ اسْتَخْدَمَتْ دَوْلَة...,33,"[ومن, هذا, المنطلق, استخدمت, دولة, الإمارات, ا..."
38,ArabicMMLU,BAREC_ArabicMMLU_Group_9_009,0,ArabicMMLU,#,#,Social Sciences,Foundational Text,Educational Materials; Language & Linguistics,15.200000,من النباتات البریة (أ) الزعرور (ب) الصنوبر ...,15,"[من, النباتات, البرية, (, أ, ), الزعرور, (, ب,..."
39,Curriculum,BAREC_Curriculum_09_soc_t3_u07_006,32,Emarati Curriculum,Grade 9 Social Sciences,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,9.338462,إذا أردت نشر أي شئ عن أصدقائك تأكد أنت تنشر عن...,17,"[إذا, أردت, نشر, أي, شئ, عن, أصدقائك, تأكد, أن..."
40,Curriculum,BAREC_Curriculum_09_soc_t3_u08_002,27,Emarati Curriculum,Grade 9 Social Sciences,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,11.653846,أقرأُ بتركيز الفقرات الواردة في كتاب وسائل الت...,23,"[أقرأ, بتركيز, الفقرات, الواردة, في, كتاب, وسا..."
41,DARES,BAREC_DARES_Sociology_G7_2_009,7,DARES,G7 - Sociology,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,72.111111,هل يدل شكل الأرض على أنها كاملة القطر؟ يلاحظ أ...,76,"[هل, يدل, شكل, الأرض, على, أنها, كاملة, القطر,..."
42,Curriculum,BAREC_Curriculum_05_soc_t3_u06_001,71,Emarati Curriculum,Grade 5 Social Sciences,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,4.583333,أَصوغُ بِأُسْلوبي مِنْ خِلالِ الشَّكْلِ مَفْهو...,9,"[أصوغ, بأسلوبي, من, خلال, الشكل, مفهوم, دوائر,..."
43,Curriculum,BAREC_Curriculum_07_soc_t1_u02_001,76,Emarati Curriculum,Grade 7 Social Sciences,#,Social Sciences,Advanced Text,Educational Materials; Language & Linguistics,10.011765,أشارَ الرسولُ على أصحابِهِ أنْ يهاجروا إلى الح...,21,"[أشار, الرسول, على, أصحابه, أن, يهاجروا, إلى, ..."
44,Curriculum,BAREC_Curriculum_10_soc_t2_u07_003,15,Emarati Curriculum,Grade 10 Social Sciences,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,12.800000,"هو الزعيم الروحي للهند, والزعيم الروحي للثورة ...",17,"[هو, الزعيم, الروحي, للهند, ,, والزعيم, الروحي..."
45,DARES,BAREC_DARES_Critical_Thinking_G9_2_006,7,DARES,G9 - Critical_Thinking,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,67.666667,القدرة على الفهم والاستيعاب، وإصدار الحكم بناء...,59,"[القدرة, على, الفهم, والاستيعاب, ,, وإصدار, ال..."
46,DARES,BAREC_DARES_Sociology_G10_2_009,0,DARES,G10 - Sociology,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,90.714286,مصطلح المغرب العربي يطلق على عدد من الدول العر...,109,"[مصطلح, المغرب, العربي, يطلق, على, عدد, من, ال..."
47,DARES,BAREC_DARES_History_G11_008,7,DARES,G11 - History,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,69.888889,قرر منصور المريدي جد الأسرة المالكة من أهم الأ...,68,"[قرر, منصور, المريدي, جد, الأسرة, المالكة, من,..."
48,Curriculum,BAREC_Curriculum_11_soc_t3_u09_004,16,Emarati Curriculum,Grade 11 Social Sciences,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,12.725490,الى ما يغرس بداخلهم لأننا سنجده يتردد في أعمال...,17,"[الى, ما, يغرس, بداخلهم, لأننا, سنجده, يتردد, ..."
49,DARES,BAREC_DARES_Sociology_G9_2_001,1,DARES,G9 - Sociology,#,Social Sciences,Specialized Text,Educational Materials; Language & Linguistics,36.500000,الصيانة الدائمة للأدوات والأجهزة المستخدمة داخ...,35,"[الصيانة, الدائمة, للأدوات, والأجهزة, المستخدم..."

In [ ]:
# C_df.to_json('sampled_ELL_sentences.json', orient='records', force_ascii=False, indent=4)

In [106]:
metadata['Text Category'].value_counts()

Text Category
Media & Culture                                  7122
Educational Materials; Language & Linguistics    4709
Academic                                         4301
Literature; Art & Music                          3974
Religion & Philosophy                             254
Encyclopedic                                      175
Name: count, dtype: int64

In [107]:
AC_df = metadata[metadata['Text Category']=='Academic']
print("Academic")
print("==========================")
print(f"Number of documents: {AC_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {AC_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {AC_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {AC_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{AC_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{AC_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{AC_df['average sentence length'].describe().to_dict()}")
print("==========================")

Academic
==========================
Number of documents: 4301
--------------------------
Number of sentences: 90235
--------------------------
Number of unique books: 1389
--------------------------
Number of unique authors: 1001
--------------------------
Domain distribution:
{'STEM': 2435, 'Social Sciences': 1783, 'Arts & Humanities': 83}
--------------------------
Readership Group distribution:
{'Specialized Text': 4213, 'Advanced Text': 79, 'Foundational Text': 9}
--------------------------
Average sentence length distribution:
{'count': 4301.0, 'mean': 34.18488759420031, 'std': 13.131808815146508, 'min': 4.269565217391304, '25%': 25.0, '50%': 33.421052631578945, '75%': 40.4, 'max': 185.6}
==========================

In [108]:
AC_AH_df = AC_df[AC_df['Domain']=='Arts & Humanities']
print("Academic - Arts & Humanities")
print("==========================")
print(f"Number of documents: {AC_AH_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {AC_AH_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {AC_AH_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {AC_AH_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{AC_AH_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{AC_AH_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{AC_AH_df['average sentence length'].describe().to_dict()}")
print("==========================")

Academic - Arts & Humanities
==========================
Number of documents: 83
--------------------------
Number of sentences: 1802
--------------------------
Number of unique books: 83
--------------------------
Number of unique authors: 59
--------------------------
Domain distribution:
{'Arts & Humanities': 83}
--------------------------
Readership Group distribution:
{'Specialized Text': 79, 'Advanced Text': 4}
--------------------------
Average sentence length distribution:
{'count': 83.0, 'mean': 31.188017042231646, 'std': 22.67701525021513, 'min': 11.767441860465116, '25%': 21.682065217391305, '50%': 25.61904761904762, '75%': 34.7, 'max': 185.6}
==========================

In [110]:
sampled_AC_AH_advanced_df = AC_AH_df[AC_AH_df['Readership Group']=='Advanced Text'].sample(4, random_state=42)
sampled_AC_AH_special_df = AC_AH_df[AC_AH_df['Readership Group']=='Specialized Text'].sample(12, random_state=42)

In [111]:
sampled_AC_AH_df = pd.concat([sampled_AC_AH_advanced_df, sampled_AC_AH_special_df], ignore_index=True)

In [112]:
sampled_AC_AH_sentences_indices = []
for i, row in sampled_AC_AH_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_AC_AH_sentences_indices.append(sampled_index)
print(sampled_AC_AH_sentences_indices)

[1, 1, 1, 35, 2, 9, 10, 1, 2, 9, 6, 1, 19, 1, 2, 16]

In [113]:
sampled_AC_AH_df['sampled_sentence_index'] = sampled_AC_AH_sentences_indices

In [114]:
AC_ST_df = AC_df[AC_df['Domain']=='STEM']
print("Academic - STEM")
print("==========================")
print(f"Number of documents: {AC_ST_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {AC_ST_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {AC_ST_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {AC_ST_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{AC_ST_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{AC_ST_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{AC_ST_df['average sentence length'].describe().to_dict()}")
print("==========================")

Academic - STEM
==========================
Number of documents: 2435
--------------------------
Number of sentences: 42324
--------------------------
Number of unique books: 274
--------------------------
Number of unique authors: 190
--------------------------
Domain distribution:
{'STEM': 2435}
--------------------------
Readership Group distribution:
{'Specialized Text': 2392, 'Advanced Text': 34, 'Foundational Text': 9}
--------------------------
Average sentence length distribution:
{'count': 2435.0, 'mean': 38.80142923324701, 'std': 11.955880682021828, 'min': 6.740259740259741, '25%': 32.3078947368421, '50%': 37.35294117647059, '75%': 44.142857142857146, 'max': 105.66666666666667}
==========================

In [115]:
sampled_AC_ST_foundational_df = AC_ST_df[AC_ST_df['Readership Group']=='Foundational Text'].sample(5, random_state=42)
sampled_AC_ST_advanced_df = AC_ST_df[AC_ST_df['Readership Group']=='Advanced Text'].sample(5, random_state=42)
sampled_AC_ST_special_df = AC_ST_df[AC_ST_df['Readership Group']=='Specialized Text'].sample(7, random_state=42)

In [116]:
sampled_AC_ST_df = pd.concat([sampled_AC_ST_foundational_df, sampled_AC_ST_advanced_df, sampled_AC_ST_special_df], ignore_index=True)

In [118]:
sampled_AC_ST_sentences_indices = []
for i, row in sampled_AC_ST_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_AC_ST_sentences_indices.append(sampled_index)
print(sampled_AC_ST_sentences_indices)

[10, 1, 1, 76, 9, 1, 1, 36, 2, 1, 0, 15, 10, 9, 0, 15, 5]

In [119]:
sampled_AC_ST_df['sampled_sentence_index'] = sampled_AC_ST_sentences_indices

In [120]:
AC_SS_df = AC_df[AC_df['Domain']=='Social Sciences']
print("Academic - Social Sciences")
print("==========================")
print(f"Number of documents: {AC_SS_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {AC_SS_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {AC_SS_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {AC_SS_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{AC_SS_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{AC_SS_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{AC_SS_df['average sentence length'].describe().to_dict()}")
print("==========================")

Academic - Social Sciences
==========================
Number of documents: 1783
--------------------------
Number of sentences: 46109
--------------------------
Number of unique books: 1032
--------------------------
Number of unique authors: 779
--------------------------
Domain distribution:
{'Social Sciences': 1783}
--------------------------
Readership Group distribution:
{'Specialized Text': 1742, 'Advanced Text': 41}
--------------------------
Average sentence length distribution:
{'count': 1783.0, 'mean': 28.01969486550411, 'std': 11.385668890412788, 'min': 4.269565217391304, '25%': 20.436666666666667, '50%': 26.05, '75%': 32.91875, 'max': 134.75}
==========================

In [121]:
sampled_AC_SS_advanced_df = AC_SS_df[AC_SS_df['Readership Group']=='Advanced Text'].sample(7, random_state=42)
sampled_AC_SS_special_df = AC_SS_df[AC_SS_df['Readership Group']=='Specialized Text'].sample(10, random_state=42)

In [122]:
sampled_AC_SS_df = pd.concat([sampled_AC_SS_advanced_df, sampled_AC_SS_special_df], ignore_index=True)
sampled_AC_SS_df.shape

(17, 12)

In [123]:
sampled_AC_SS_sentences_indices = []
for i, row in sampled_AC_SS_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_AC_SS_sentences_indices.append(sampled_index)
print(sampled_AC_SS_sentences_indices)

[35, 1, 29, 9, 1, 77, 1, 21, 14, 3, 0, 45, 1, 12, 11, 8, 12]

In [124]:
sampled_AC_SS_df['sampled_sentence_index'] = sampled_AC_SS_sentences_indices

In [125]:
D_df = pd.concat([sampled_AC_AH_df, sampled_AC_ST_df, sampled_AC_SS_df], ignore_index=True)
D_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,average sentence length,sampled_sentence_index
0,BAREC_Hindawi_58285828_001,Hindawi,Hindawi,History of Theatre in the Arab World,Said Ali Ismail,Arts & Humanities,Advanced Text,Academic,503,21,No,23.952381,1
1,BAREC_Hindawi_97969752_001,Hindawi,Hindawi,The Bell Voting Mystery,Ellen Wilkinson,Arts & Humanities,Advanced Text,Academic,501,19,No,26.368421,1
2,BAREC_Hindawi_42048057_001,Hindawi,Hindawi,Islam Without Borders,Yusuf Idris,Arts & Humanities,Advanced Text,Academic,518,19,No,27.263158,1
3,BAREC_Hindawi_90507395_001,Hindawi,Hindawi,Translator’s Guide (to the Most Difficult Comm...,Mohamed Anani,Arts & Humanities,Advanced Text,Academic,506,43,No,11.767442,35
4,BAREC_Hindawi_57379637_001,Hindawi,Hindawi,History of Modern Philosophy,Youssef Karam,Arts & Humanities,Specialized Text,Academic,525,10,No,52.500000,2
5,BAREC_Hindawi_14046425_001,Hindawi,Hindawi,The Story of Modern Philosophy,Zaki Najib Mahmoud and Ahmed Amin,Arts & Humanities,Specialized Text,Academic,521,11,No,47.363636,9
6,BAREC_Hindawi_41928480_001,Hindawi,Hindawi,Dream of Reason,Anthony Gottlieb,Arts & Humanities,Specialized Text,Academic,542,15,No,36.133333,10
7,BAREC_Hindawi_59752571_001,Hindawi,Hindawi,Dialogues of Alfred North Whitehead,#,Arts & Humanities,Specialized Text,Academic,522,21,No,24.857143,1
8,BAREC_Hindawi_38614175_001,Hindawi,Hindawi,Wonders of Monuments in Biographies and News (...,Abdul Rahman al-Jabarti,Arts & Humanities,Specialized Text,Academic,928,5,No,185.600000,2
9,BAREC_Hindawi_51971317_001,Hindawi,Hindawi,An Islamic Perspective,Zaki Naguib Mahmoud,Arts & Humanities,Specialized Text,Academic,529,11,No,48.090909,9
10,BAREC_Hindawi_29318372_001,Hindawi,Hindawi,Studies on Poetry in the Ayyubid Era,Mohammed Kamil Hussein,Arts & Humanities,Specialized Text,Academic,504,12,No,42.000000,6
11,BAREC_Hindawi_97961385_001,Hindawi,Hindawi,Mental Storms,Muheeb Nasr,Arts & Humanities,Specialized Text,Academic,498,20,No,24.900000,1
12,BAREC_Hindawi_19204286_001,Hindawi,Hindawi,History of Greek Philosophy,Youssef Karam,Arts & Humanities,Specialized Text,Academic,505,21,No,24.047619,19
13,BAREC_Hindawi_30719715_001,Hindawi,Hindawi,Religious Existentialism,Yamna Tarif al-Khouli,Arts & Humanities,Specialized Text,Academic,529,27,No,19.592593,1
14,BAREC_Hindawi_74969797_001,Hindawi,Hindawi,"Mind, Heart, and Courage","David L. Dotlich, Peter C. Cairo, and Stephen ...",Arts & Humanities,Specialized Text,Academic,500,23,No,21.739130,2
15,BAREC_Hindawi_60697085_001,Hindawi,Hindawi,History of Arabic Grammar,Ali al-Shadwi,Arts & Humanities,Specialized Text,Academic,503,24,No,20.958333,16
16,BAREC_Hindawi_85285919_001,Hindawi,Hindawi,Almond Borer,Mamoun Abdul Latif Al-Rahhal,STEM,Foundational Text,Academic,508,15,No,33.866667,10
17,BAREC_Hindawi_25029086_001,Hindawi,Hindawi,Plastic,Mamoun Abdul Latif Al-Rahhal,STEM,Foundational Text,Academic,510,19,No,26.842105,1
18,BAREC_Hindawi_74618628_001,Hindawi,Hindawi,Abu al-Eid with Seven Marks,Mamoun Abdul Latif Al-Rahhal,STEM,Foundational Text,Academic,511,19,No,26.894737,1
19,BAREC_Hindawi_13026818_001,Hindawi,Hindawi,Science in Seconds for Kids,Jane Potter,STEM,Foundational Text,Academic,519,77,No,6.740260,76
20,BAREC_Hindawi_92080696_001,Hindawi,Hindawi,I Am a Sardine Fish,Mamoun Abdul Latif Al-Rahhal,STEM,Foundational Text,Academic,533,27,No,19.740741,9
21,BAREC_Hindawi_48350803_001,Hindawi,Hindawi,Knocking on Heaven’s Doors,Lisa Randall,STEM,Advanced Text,Academic,504,21,No,24.000000,1
22,BAREC_Hindawi_51929307_001,Hindawi,Hindawi,Cancer,Nicholas James,STEM,Advanced Text,Academic,523,21,No,24.904762,1
23,BAREC_Hindawi_79392975_001,Hindawi,Hindawi,Physics of Solar Energy,C. Julian Chen,STEM,Advanced Text,Academic,509,40,No,12.725000,36
24,BAREC_Hindawi_75261636_001,Hindawi,Hindawi,Animal Migration,Ahmed Hamad Al-Husseini,STEM,Advanced Text,Academic,535,7,No,76.428571,2
25,BAREC_Hindawi_26973525_001,Hindawi,Hindawi,Six Impossible Things,John Griffin,STEM,Advanced Text,Academic,512,26,No,19.692308,1
26,BAREC_MedArabiQ_Y1_Physiology_PDF_QA1_015,MedArabiQ,MedArabiQ,Y1 - Physiology,#,STEM,Specialized Text,Academic,626,19,No,32.947368,0
27,BAREC_MedArabiQ_Y1_Anatomy_PDF_QA13_010,MedArabiQ,MedArabiQ,Y1 - Anatomy,#,STEM,Specialized Text,Academic,634,23,No,27.565217,15
28,BAREC_MedArabiQ_Y5_Ophthalmology_Scanned_QA2_007,MedArabiQ,MedArabiQ,Y5 - Ophthalmology,#,STEM,Specialized Text,Academic,616,12,No,51.333333,10
29,BAREC_MedArabiQ_Y2_Histology_Scanned_QA26_023,MedArabiQ,MedArabiQ,Y2 - Histology,#,STEM,Specialized Text,Academic,624,14,No,44.571429,9
30,BAREC_MedArabiQ_Y1_Cardiology_PDF_QA10_002,MedArabiQ,MedArabiQ,Y1 - Cardiology,#,STEM,Specialized Text,Academic,631,17,No,37.117647,0
31,BAREC_MedArabiQ_Y1_Anatomy_Scanned_QA5_036,MedArabiQ,MedArabiQ,Y1 - Anatomy,#,STEM,Specialized Text,Academic,615,23,No,26.739130,15
32,BAREC_MedArabiQ_Y2_Biochemistry_Scanned_QA11_012,MedArabiQ,MedArabiQ,Y2 - Biochemistry,#,STEM,Specialized Text,Academic,630,11,No,57.272727,5
33,BAREC_Hindawi_59395164_001,Hindawi,Hindawi,End This Recession Now,Paul Krugman,Social Sciences,Advanced Text,Academic,1303,59,Yes,22.084746,35
34,BAREC_Hindawi_38063631_001,Hindawi,Hindawi,Nuclear Weapons,Joseph M. Siracusa,Social Sciences,Advanced Text,Academic,504,23,No,21.913043,1
35,BAREC_Hindawi_31306851_001,Hindawi,Hindawi,Where Are Our Clothes Made?,Kelsey Timmerman,Social Sciences,Advanced Text,Academic,511,33,No,15.484848,29
36,BAREC_Hindawi_63172484_001,Hindawi,Hindawi,365 Days Without “Made in China”,Sarah Bonjourni,Social Sciences,Advanced Text,Academic,508,27,No,18.814815,9
37,BAREC_Hindawi_20271796_001,Hindawi,Hindawi,The Idea Machine,Nadia Shantzler,Social Sciences,Advanced Text,Academic,590,24,No,24.583333,1
38,BAREC_UN_Universal Declaration of Human Rights...,UN,UN (United Nations),Universal Declaration of Human Rights,UN (United Nations),Social Sciences,Advanced Text,Academic,1426,93,Yes,15.333333,77
39,BAREC_Hindawi_46494205_001,Hindawi,Hindawi,Without Restrictions,Richard L. Courier,Social Sciences,Advanced Text,Academic,523,21,No,24.904762,1
40,BAREC_Hindawi_71858151_001,Hindawi,Hindawi,Egyptian Armanosa,George Zidan,Social Sciences,Specialized Text,Academic,507,27,No,18.777778,21
41,BAREC_Ofoq_May_2023_أحمد_جابر_7_001,Ofoq,Ofoq,45047,Ahmed Jaber,Social Sciences,Specialized Text,Academic,663,20,No,33.150000,14
42,BAREC_Ofoq_April_2021_عبد_الإله_الديوهﭽي_6_001,Ofoq,Ofoq,44287,Abdul Ilah Al-Diwaji,Social Sciences,Specialized Text,Academic,624,28,No,22.285714,3
43,BAREC_Ofoq_Aug_2020_رفيف_رضا_صيداوي_10_001,Ofoq,Ofoq,44044,Rafeef Reda Saidawi,Social Sciences,Specialized Text,Academic,617,20,No,30.850000,0
44,BAREC_Kalima_الارض_واحلام_يقظة_الإرادة_001,Kalima,Kalima,Earth and the Daydreams of Will: A Study in th...,Gaston Bachelard,Social Sciences,Specialized Text,Academic,754,52,No,14.500000,45
45,BAREC_Hindawi_46050209_001,Hindawi,Hindawi,Sufism and Farid al-Din Attar,Abdul Wahab Azzam,Social Sciences,Specialized Text,Academic,504,22,No,22.909091,1
46,BAREC_Hindawi_64731631_001,Hindawi,Hindawi,The Eastern Question and the Paris Conference,Mohamed Mustafa Safwat,Social Sciences,Specialized Text,Academic,535,14,No,38.214286,12
47,BAREC_Ofoq_July_2023_نبيه_البرجي_3_001,Ofoq,Ofoq,45108,Nabih Al-Burji,Social Sciences,Specialized Text,Academic,619,17,ST2&3,36.411765,11
48,BAREC_Ofoq_Feb_2019_محسن_التليلي_1_001,Ofoq,Ofoq,43497,Mohsen Al-Talili,Social Sciences,Specialized Text,Academic,667,14,No,47.642857,8
49,BAREC_Hindawi_90306293_001,Hindawi,Hindawi,Love in History,Salama Moussa,Social Sciences,Specialized Text,Academic,505,14,No,36.071429,12

In [126]:
D_df['selected_sent_raw'] = None
D_df['selected_sent_word_count'] = None
D_df['selected_sent_words'] = None

for i, row in D_df.iterrows():
    directory = row['Directory']
    document = row['Document']

    annotations_file_path = (
        f"BAREC-10M/Data/Morphology_and_Readability/"
        f"{directory}/{document}.json"
    )

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)

    annotations = pd.DataFrame(annotations)

    selected_sentence_index = int(row['sampled_sentence_index'])

    selected_row = annotations.iloc[selected_sentence_index]

    raw_sentence = selected_row['raw_sents']
    word_count = selected_row['sents_word_count']
    words = selected_row['word']   # list of strings

    D_df.at[i, 'selected_sent_raw'] = raw_sentence
    D_df.at[i, 'selected_sent_word_count'] = word_count
    D_df.at[i, 'selected_sent_words'] = words

In [127]:
D_df = D_df[[
    'Directory',
    'Document',
    'sampled_sentence_index',
    'Source',
    'Book',
    'Author',
    'Domain',
    'Readership Group',
    'Text Category',
    'average sentence length',
    'selected_sent_raw',
    'selected_sent_word_count',
    'selected_sent_words'
]]

In [128]:
D_df.rename(columns={
    'average sentence length': 'average_sentence_length_per_doc',
}, inplace=True)

In [129]:
D_df

,Directory,Document,sampled_sentence_index,Source,Book,Author,Domain,Readership Group,Text Category,average_sentence_length_per_doc,selected_sent_raw,selected_sent_word_count,selected_sent_words
0,Hindawi,BAREC_Hindawi_58285828_001,1,Hindawi,History of Theatre in the Arab World,Said Ali Ismail,Arts & Humanities,Advanced Text,Academic,23.952381,الحديث عن تاريخ المسرح العربي، في القرن التاسع...,20,"[الحديث, عن, تاريخ, المسرح, العربي, ,, في, الق..."
1,Hindawi,BAREC_Hindawi_97969752_001,1,Hindawi,The Bell Voting Mystery,Ellen Wilkinson,Arts & Humanities,Advanced Text,Academic,26.368421,عندما وقع هذا الكتاب بين يدي، كان هدفي الأساسي...,27,"[عندما, وقع, هذا, الكتاب, بين, يدي, ,, كان, هد..."
2,Hindawi,BAREC_Hindawi_42048057_001,1,Hindawi,Islam Without Borders,Yusuf Idris,Arts & Humanities,Advanced Text,Academic,27.263158,لا بُدَّ منها لأني أخشى أن يتصور مَن يقتني هذا...,31,"[لا, بد, منها, لأني, أخشى, أن, يتصور, من, يقتن..."
3,Hindawi,BAREC_Hindawi_90507395_001,35,Hindawi,Translator’s Guide (to the Most Difficult Comm...,Mohamed Anani,Arts & Humanities,Advanced Text,Academic,11.767442,وهكذا فحين يبدأ المُترجِم كتابةَ نصه المُترجَم...,55,"[وهكذا, فحين, يبدأ, المترجم, كتابة, نصه, المتر..."
4,Hindawi,BAREC_Hindawi_57379637_001,2,Hindawi,History of Modern Philosophy,Youssef Karam,Arts & Humanities,Specialized Text,Academic,52.500000,أديب كما يهواه الإنسانيون ورياضي وفيلسوف وصوفي...,132,"[أديب, كما, يهواه, الإنسانيون, ورياضي, وفيلسوف..."
5,Hindawi,BAREC_Hindawi_14046425_001,9,Hindawi,The Story of Modern Philosophy,Zaki Najib Mahmoud and Ahmed Amin,Arts & Humanities,Specialized Text,Academic,47.363636,انتقلت التجارة من البحر الأبيض إلى المحيط الأط...,72,"[انتقلت, التجارة, من, البحر, الأبيض, إلى, المح..."
6,Hindawi,BAREC_Hindawi_41928480_001,10,Hindawi,Dream of Reason,Anthony Gottlieb,Arts & Humanities,Specialized Text,Academic,36.133333,ولا شك أن هذا يفيد القارئ في الإلمام بإنجازات ...,35,"[ولا, شك, أن, هذا, يفيد, القارئ, في, الإلمام, ..."
7,Hindawi,BAREC_Hindawi_59752571_001,1,Hindawi,Dialogues of Alfred North Whitehead,#,Arts & Humanities,Specialized Text,Academic,24.857143,يزخر القرن الذي يقع بين عامَي ١٨٥٠م و١٩٥٠م بمج...,54,"[يزخر, القرن, الذي, يقع, بين, عامي, ١٨٥٠م, و١٩..."
8,Hindawi,BAREC_Hindawi_38614175_001,2,Hindawi,Wonders of Monuments in Biographies and News (...,Abdul Rahman al-Jabarti,Arts & Humanities,Specialized Text,Academic,185.600000,وخبر موت حسين بك المذكور أنه لما مات إبراهيم ك...,43,"[وخبر, موت, حسين, بك, المذكور, أنه, لما, مات, ..."
9,Hindawi,BAREC_Hindawi_51971317_001,9,Hindawi,An Islamic Perspective,Zaki Naguib Mahmoud,Arts & Humanities,Specialized Text,Academic,48.090909,لكيلا يفلت منه زمام عقله أو تشرد الأهواء بقلبه...,79,"[لكيلا, يفلت, منه, زمام, عقله, أو, تشرد, الأهو..."
10,Hindawi,BAREC_Hindawi_29318372_001,6,Hindawi,Studies on Poetry in the Ayyubid Era,Mohammed Kamil Hussein,Arts & Humanities,Specialized Text,Academic,42.000000,ولعلنا لا نغالي إذا قلنا: إن هذا الضعف بدأ في ...,39,"[ولعلنا, لا, نغالي, إذا, قلنا, :, إن, هذا, الض..."
11,Hindawi,BAREC_Hindawi_97961385_001,1,Hindawi,Mental Storms,Muheeb Nasr,Arts & Humanities,Specialized Text,Academic,24.900000,رخيصة هي الأفكار، إذا ما تشبَّعت بحرارة الطور ...,47,"[رخيصة, هي, الأفكار, ,, إذا, ما, تشبعت, بحرارة..."
12,Hindawi,BAREC_Hindawi_19204286_001,19,Hindawi,History of Greek Philosophy,Youssef Karam,Arts & Humanities,Specialized Text,Academic,24.047619,إذ أغار أهل تساليا على شمال اليونان فهاجر الأي...,41,"[إذ, أغار, أهل, تساليا, على, شمال, اليونان, فه..."
13,Hindawi,BAREC_Hindawi_30719715_001,1,Hindawi,Religious Existentialism,Yamna Tarif al-Khouli,Arts & Humanities,Specialized Text,Academic,19.592593,إلى الإنجيليِّين الأقباط … والإخوة الأعزاء بال...,18,"[إلى, الإنجيليين, الأقباط, ., ., ., والإخوة, ا..."
14,Hindawi,BAREC_Hindawi_74969797_001,2,Hindawi,"Mind, Heart, and Courage","David L. Dotlich, Peter C. Cairo, and Stephen ...",Arts & Humanities,Specialized Text,Academic,21.739130,إننا نمتلك الآن المعرفة والأدوات اللازمة لتطوي...,10,"[إننا, نمتلك, الآن, المعرفة, والأدوات, اللازمة..."
15,Hindawi,BAREC_Hindawi_60697085_001,16,Hindawi,History of Arabic Grammar,Ali al-Shadwi,Arts & Humanities,Specialized Text,Academic,20.958333,لذلك لن أتجاهله، إنما سآخذه مأخذ الجد، وسأبحث ...,14,"[لذلك, لن, أتجاهله, ,, إنما, سآخذه, مأخذ, الجد..."
16,Hindawi,BAREC_Hindawi_85285919_001,10,Hindawi,Almond Borer,Mamoun Abdul Latif Al-Rahhal,STEM,Foundational Text,Academic,33.866667,وبعد وصولها تبدأ بحفر الأنفاق مُؤدِّيةً إلى تد...,69,"[وبعد, وصولها, تبدأ, بحفر, الأنفاق, مؤدية, إلى..."
17,Hindawi,BAREC_Hindawi_25029086_001,1,Hindawi,Plastic,Mamoun Abdul Latif Al-Rahhal,STEM,Foundational Text,Academic,26.842105,حيث نظرتم حولكم في زوايا غرفتكم، أو في حقيبة ك...,46,"[حيث, نظرتم, حولكم, في, زوايا, غرفتكم, ,, أو, ..."
18,Hindawi,BAREC_Hindawi_74618628_001,1,Hindawi,Abu al-Eid with Seven Marks,Mamoun Abdul Latif Al-Rahhal,STEM,Foundational Text,Academic,26.894737,ما إن يأتي فصل الربيع بطَلَّته الجميلة، وتكتسي...,93,"[ما, إن, يأتي, فصل, الربيع, بطلته, الجميلة, ,,..."
19,Hindawi,BAREC_Hindawi_13026818_001,76,Hindawi,Science in Seconds for Kids,Jane Potter,STEM,Foundational Text,Academic,6.740260,عندما يُطلَق صاروخ، فإنه يحتاج قوةً هائلة لرفع...,36,"[عندما, يطلق, صاروخ, ,, فإنه, يحتاج, قوة, هائل..."
20,Hindawi,BAREC_Hindawi_92080696_001,9,Hindawi,I Am a Sardine Fish,Mamoun Abdul Latif Al-Rahhal,STEM,Foundational Text,Academic,19.740741,تُحلِّق فوقنا طيور النورس الجائعة بأعدادها الك...,13,"[تحلق, فوقنا, طيور, النورس, الجائعة, بأعدادها,..."
21,Hindawi,BAREC_Hindawi_48350803_001,1,Hindawi,Knocking on Heaven’s Doors,Lisa Randall,STEM,Advanced Text,Academic,24.000000,تحيا البشرية الآن على أعتاب عصر الاكتشافات؛,8,"[تحيا, البشرية, الآن, على, أعتاب, عصر, الاكتشا..."
22,Hindawi,BAREC_Hindawi_51929307_001,1,Hindawi,Cancer,Nicholas James,STEM,Advanced Text,Academic,24.904762,السرطان مرض شائع، بل هو شديد الشيوع.,9,"[السرطان, مرض, شائع, ,, بل, هو, شديد, الشيوع, .]"
23,Hindawi,BAREC_Hindawi_79392975_001,36,Hindawi,Physics of Solar Energy,C. Julian Chen,STEM,Advanced Text,Academic,12.725000,توضح الأرقام أن الاحتياطيات الإجمالية المُثبتة...,24,"[توضح, الأرقام, أن, الاحتياطيات, الإجمالية, ال..."
24,Hindawi,BAREC_Hindawi_75261636_001,2,Hindawi,Animal Migration,Ahmed Hamad Al-Husseini,STEM,Advanced Text,Academic,76.428571,ومعظم الثدييات يعيش على الأرض يتجول عليها ويقت...,55,"[ومعظم, الثدييات, يعيش, على, الأرض, يتجول, علي..."
25,Hindawi,BAREC_Hindawi_26973525_001,1,Hindawi,Six Impossible Things,John Griffin,STEM,Advanced Text,Academic,19.692308,تتلخَّص غرابة عالَم الكَم فيما يُعرَف رسميًّا ...,14,"[تتلخص, غرابة, عالم, الكم, فيما, يعرف, رسميا, ..."
26,MedArabiQ,BAREC_MedArabiQ_Y1_Physiology_PDF_QA1_015,0,MedArabiQ,Y1 - Physiology,#,STEM,Specialized Text,Academic,32.947368,كل مما يلي يحدث في آلية التنظيم الموضعي لضغط ا...,49,"[كل, مما, يلي, يحدث, في, آلية, التنظيم, الموضع..."
27,MedArabiQ,BAREC_MedArabiQ_Y1_Anatomy_PDF_QA13_010,15,MedArabiQ,Y1 - Anatomy,#,STEM,Specialized Text,Academic,27.565217,. الدوران الوحشي (أ) صدرية كبيرة (ب) تحت الكتف...,23,"[., الدوران, الوحشي, (, أ, ), صدرية, كبيرة, (,..."
28,MedArabiQ,BAREC_MedArabiQ_Y5_Ophthalmology_Scanned_QA2_007,10,MedArabiQ,Y5 - Ophthalmology,#,STEM,Specialized Text,Academic,51.333333,واحدة فقط مما يلي خاطئة: (أ) الجدار العلوي للح...,73,"[واحدة, فقط, مما, يلي, خاطئة, :, (, أ, ), الجد..."
29,MedArabiQ,BAREC_MedArabiQ_Y2_Histology_Scanned_QA26_023,9,MedArabiQ,Y2 - Histology,#,STEM,Specialized Text,Academic,44.571429,في المخيخ: (أ) الطبقة الجزيئية تتألف من عصبونا...,51,"[في, المخيخ, :, (, أ, ), الطبقة, الجزيئية, تتأ..."
30,MedArabiQ,BAREC_MedArabiQ_Y1_Cardiology_PDF_QA10_002,0,MedArabiQ,Y1 - Cardiology,#,STEM,Specialized Text,Academic,37.117647,تختلف الخلايا ذاتية النظم عن الخلايا المتقلصة ...,43,"[تختلف, الخلايا, ذاتية, النظم, عن, الخلايا, ال..."
31,MedArabiQ,BAREC_MedArabiQ_Y1_Anatomy_Scanned_QA5_036,15,MedArabiQ,Y1 - Anatomy,#,STEM,Specialized Text,Academic,26.739130,الجزء العلوي للرحم فوق مدخل البوق (أ) القاع (ب...,22,"[الجزء, العلوي, للرحم, فوق, مدخل, البوق, (, أ,..."
32,MedArabiQ,BAREC_MedArabiQ_Y2_Biochemistry_Scanned_QA11_012,5,MedArabiQ,Y2 - Biochemistry,#,STEM,Specialized Text,Academic,57.272727,كل مما يلي حول التهاب الكبد الفيروسي B صحيح ما...,64,"[كل, مما, يلي, حول, التهاب, الكبد, الفيروسي, B..."
33,Hindawi,BAREC_Hindawi_59395164_001,35,Hindawi,End This Recession Now,Paul Krugman,Social Sciences,Advanced Text,Academic,22.084746,بالفعل تخبرنا أبحاثُ السعادةِ أن المال لا يظلُ...,22,"[بالفعل, تخبرنا, أبحاث, السعادة, أن, المال, لا..."
34,Hindawi,BAREC_Hindawi_38063631_001,1,Hindawi,Nuclear Weapons,Joseph M. Siracusa,Social Sciences,Advanced Text,Academic,21.913043,في عام ١٩٥١ أشرفت إدارة الدفاع المدني الفيدرال...,28,"[في, عام, ١٩٥١, أشرفت, إدارة, الدفاع, المدني, ..."
35,Hindawi,BAREC_Hindawi_31306851_001,29,Hindawi,Where Are Our Clothes Made?,Kelsey Timmerman,Social Sciences,Advanced Text,Academic,15.484848,عيونٍ تَتطلع إلى مستقبل يتخطى حدود مُستقبلي؛,8,"[عيون, تتطلع, إلى, مستقبل, يتخطى, حدود, مستقبل..."
36,Hindawi,BAREC_Hindawi_63172484_001,9,Hindawi,365 Days Without “Made in China”,Sarah Bonjourni,Social Sciences,Advanced Text,Academic,18.814815,وَوَفَّرَ تشارلز ريتشارد وباربرا كلارك الدَّفع...,10,"[ووفر, تشارلز, ريتشارد, وباربرا, كلارك, الدفعة..."
37,Hindawi,BAREC_Hindawi_20271796_001,1,Hindawi,The Idea Machine,Nadia Shantzler,Social Sciences,Advanced Text,Academic,24.583333,استخدِمْ هذه المساحة في تسجيل كلِّ الأفكار الت...,16,"[استخدم, هذه, المساحة, في, تسجيل, كل, الأفكار,..."
38,UN,BAREC_UN_Universal Declaration of Human Rights...,77,UN (United Nations),Universal Declaration of Human Rights,UN (United Nations),Social Sciences,Advanced Text,Academic,15.333333,ويكون التعليمُ الفنِّي والمهني متاحًا للعموم.,7,"[ويكون, التعليم, الفني, والمهني, متاحا, للعموم..."
39,Hindawi,BAREC_Hindawi_46494205_001,1,Hindawi,Without Restrictions,Richard L. Courier,Social Sciences,Advanced Text,Academic,24.904762,تمرُّ كل الحقائق بثلاث مراحل؛,6,"[تمر, كل, الحقائق, بثلاث, مراحل, ؛]"
40,Hindawi,BAREC_Hindawi_71858151_001,21,Hindawi,Egyptian Armanosa,George Zidan,Social Sciences,Specialized Text,Academic,18.777778,وكان في وسط تلك البلدة حصن كبير يدعى حصن بابل،...,76,"[وكان, في, وسط, تلك, البلدة, حصن, كبير, يدعى, ..."
41,Ofoq,BAREC_Ofoq_May_2023_أحمد_جابر_7_001,14,Ofoq,45047,Ahmed Jaber,Social Sciences,Specialized Text,Academic,33.150000,"خارج القيد الطائفي""، فأضاف إلى مكتبة ""التجديدي...",93,"[خارج, القيد, الطائفي, "", ,, فأضاف, إلى, مكتبة..."
42,Ofoq,BAREC_Ofoq_April_2021_عبد_الإله_الديوهﭽي_6_001,3,Ofoq,44287,Abdul Ilah Al-Diwaji,Social Sciences,Specialized Text,Academic,22.285714,"يُستخدم مُصطلح Algorithm هذه الأيّام ليعني ""مج...",22,"[يستخدم, مصطلح, Algorithm, هذه, الأيام, ليعني,..."
43,Ofoq,BAREC_Ofoq_Aug_2020_رفيف_رضا_صيداوي_10_001,0,Ofoq,44044,Rafeef Reda Saidawi,Social Sciences,Specialized Text,Academic,30.850000,"قراءة في ""صباح الخامس والعشرين من شهر ديسمبر"" ...",12,"[قراءة, في, "", صباح, الخامس, والعشرين, من, شهر..."
44,Kalima,BAREC_Kalima_الارض_واحلام_يقظة_الإرادة_001,45,Kalima,Earth and the Daydreams of Will: A Study in th...,Gaston Bachelard,Social Sciences,Specialized Text,Academic,14.500000,وبمجرد أن يكشف عن صورة اندفاعية، وبمجرد أن يُر...,23,"[وبمجرد, أن, يكشف, عن, صورة, اندفاعية, ,, وبمج..."
45,Hindawi,BAREC_Hindawi_46050209_001,1,Hindawi,Sufism and Farid al-Din Attar,Abdul Wahab Azzam,Social Sciences,Specialized Text,Academic,22.909091,فريد الدين العطار شاعر فارسي من أئمة شعراء الت...,41,"[فريد, الدين, العطار, شاعر, فارسي, من, أئمة, ش..."
46,Hindawi,BAREC_Hindawi_64731631_001,12,Hindawi,The Eastern Question and the Paris Conference,Mohamed Mustafa Safwat,Social Sciences,Specialized Text,Academic,38.214286,أخذت المسألة الشرقية تظهر بشكل واضح إذن في الق...,65,"[أخذت, المسألة, الشرقية, تظهر, بشكل, واضح, إذن..."
47,Ofoq,BAREC_Ofoq_July_2023_نبيه_البرجي_3_001,11,Ofoq,45108,Nabih Al-Burji,Social Sciences,Specialized Text,Academic,36.411765,لكنّ أردوغان الذي تمكّن، وبواسطة قواعده الشعبي...,43,"[لكن, أردوغان, الذي, تمكن, ,, وبواسطة, قواعده,..."
48,Ofoq,BAREC_Ofoq_Feb_2019_محسن_التليلي_1_001,8,Ofoq,43497,Mohsen Al-Talili,Social Sciences,Specialized Text,Academic,47.642857,ففي ظلّ العربيّة وحضنها القرآنيّ، نبغَ الفكر ا...,42,"[ففي, ظل, العربية, وحضنها, القرآني, ,, نبغ, ال..."
49,Hindawi,BAREC_Hindawi_90306293_001,12,Hindawi,Love in History,Salama Moussa,Social Sciences,Specialized Text,Academic,36.071429,وهنا قد يرد بعض القراء: ولكنَّ هناك أزواجًا يخ...,36,"[وهنا, قد, يرد, بعض, القراء, :, ولكن, هناك, أز..."

In [ ]:
# D_df.to_json('sampled_AC_sentences.json', orient='records', force_ascii=False, indent=4)

In [131]:
metadata['Text Category'].value_counts()

Text Category
Media & Culture                                  7122
Educational Materials; Language & Linguistics    4709
Academic                                         4301
Literature; Art & Music                          3974
Religion & Philosophy                             254
Encyclopedic                                      175
Name: count, dtype: int64

In [154]:
RP_df = metadata[metadata['Text Category']=='Religion & Philosophy']
print("Religion & Philosophy")
print("==========================")
print(f"Number of documents: {RP_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {RP_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {RP_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {RP_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{RP_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{RP_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{RP_df['average sentence length'].describe().to_dict()}")
print("==========================")

Religion & Philosophy
==========================
Number of documents: 254
--------------------------
Number of sentences: 4278
--------------------------
Number of unique books: 49
--------------------------
Number of unique authors: 10
--------------------------
Domain distribution:
{'Arts & Humanities': 254}
--------------------------
Readership Group distribution:
{'Specialized Text': 254}
--------------------------
Average sentence length distribution:
{'count': 254.0, 'mean': 15.191069257160054, 'std': 7.0941729109666545, 'min': 6.2727272727272725, '25%': 10.0, '50%': 13.89247311827957, '75%': 18.065217391304348, 'max': 43.5}
==========================

In [155]:
sampled_RP_df = RP_df.sample(50, random_state=42)

In [156]:
sampled_RP_df.shape

(50, 12)

In [157]:
sampled_RP_sentences_indices = []
for i, row in sampled_RP_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_RP_sentences_indices.append(sampled_index)
print(sampled_RP_sentences_indices)

[29, 5, 1, 1, 38, 1, 1, 1, 0, 1, 10, 7, 0, 9, 50, 9, 1, 1, 0, 1, 0, 2, 2, 64, 0, 8, 5, 7, 1, 26, 9, 13, 13, 0, 11, 1, 2, 2, 2, 65, 30, 16, 10, 30, 2, 1, 0, 3, 1, 2]

In [158]:
sampled_RP_df['sampled_sentence_index'] = sampled_RP_sentences_indices

In [159]:
E_df = sampled_RP_df.copy()
E_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,average sentence length,sampled_sentence_index
18588,BAREC_OT_Genesis_1_001,OT,Old Testament,Chapter 1,#,Arts & Humanities,Specialized Text,Religion & Philosophy,578,33,Yes,17.515152,29
12343,BAREC_Hadith_1_7_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,922,99,Yes,9.313131,5
12416,BAREC_Hadith_3_2_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,63,7,Yes,9.000000,1
19477,BAREC_Quran_106_Quraysh_001,Quran,Quran,Surah Quraish,#,Arts & Humanities,Specialized Text,Religion & Philosophy,29,4,Yes,7.250000,1
12454,BAREC_Hadith_3_64_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,484,56,No,8.642857,38
18583,BAREC_OT_Genesis_15_001,OT,Old Testament,Chapter 15,#,Arts & Humanities,Specialized Text,Religion & Philosophy,354,22,Yes,16.090909,1
19473,BAREC_Quran_102_Al-Takathur_001,Quran,Quran,Surah At-Takathur,#,Arts & Humanities,Specialized Text,Religion & Philosophy,52,8,Yes,6.500000,1
18565,BAREC_NT_Matthew_13_001,NT,New Testament,Chapter 13,#,Arts & Humanities,Specialized Text,Religion & Philosophy,1000,59,Yes,16.949153,1
12346,BAREC_Hadith_2_12_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,57,2,Yes,28.500000,0
12367,BAREC_Hadith_2_31_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,43,4,Yes,10.750000,1
18578,BAREC_OT_Genesis_10_001,OT,Old Testament,Chapter 10,#,Arts & Humanities,Specialized Text,Religion & Philosophy,360,33,Yes,10.909091,10
19492,BAREC_Quran_2_Al-Baqara_15_001,Quran,Quran,Surah Al-Baqarah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,377,9,No,41.888889,7
19500,BAREC_Quran_2_Al-Baqara_3_001,Quran,Quran,Surah Al-Baqarah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,355,21,Yes,16.904762,0
19488,BAREC_Quran_2_Al-Baqara_11_001,Quran,Quran,Surah Al-Baqarah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,370,14,No,26.428571,9
12473,BAREC_Hayy_03_001,Hayy,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,865,62,No,13.951613,50
12405,BAREC_Hadith_3_1_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,128,16,Yes,8.000000,9
18596,BAREC_OT_Genesis_8_001,OT,Old Testament,Chapter 8,#,Arts & Humanities,Specialized Text,Religion & Philosophy,416,23,Yes,18.086957,1
12352,BAREC_Hadith_2_18_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,77,6,Yes,12.833333,1
12433,BAREC_Hadith_3_45_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,80,8,No,10.000000,0
12361,BAREC_Hadith_2_26_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,50,5,Yes,10.000000,1
19505,BAREC_Quran_2_Al-Baqara_8_001,Quran,Quran,Surah Al-Baqarah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,360,17,No,21.176471,0
12356,BAREC_Hadith_2_21_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,48,3,Yes,16.000000,2
12457,BAREC_Hadith_3_67_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,119,13,No,9.153846,2
12489,BAREC_Hayy_19_001,Hayy,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,1073,66,No,16.257576,64
12370,BAREC_Hadith_2_34_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,60,4,Yes,15.000000,0
12461,BAREC_Hadith_3_70_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,113,10,No,11.300000,8
19523,BAREC_Quran_3_Aal_Imran_7_001,Quran,Quran,Surah Al-Imran,#,Arts & Humanities,Specialized Text,Religion & Philosophy,222,11,Yes,20.181818,5
19514,BAREC_Quran_3_Aal_Imran_17_001,Quran,Quran,Surah Al-Imran,#,Arts & Humanities,Specialized Text,Religion & Philosophy,215,9,Yes,23.888889,7
12347,BAREC_Hadith_2_13_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,66,7,Yes,9.428571,1
18562,BAREC_NT_Matthew_10_001,NT,New Testament,Chapter 10,#,Arts & Humanities,Specialized Text,Religion & Philosophy,679,43,Yes,15.790698,26
18582,BAREC_OT_Genesis_14_001,OT,Old Testament,Chapter 14,#,Arts & Humanities,Specialized Text,Religion & Philosophy,463,25,Yes,18.520000,9
12434,BAREC_Hadith_3_46_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,160,15,No,10.666667,13
12485,BAREC_Hayy_15_001,Hayy,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,918,51,No,18.000000,13
19481,BAREC_Quran_110_Al-Nasr_001,Quran,Quran,Surah An-Nasr,#,Arts & Humanities,Specialized Text,Religion & Philosophy,28,3,Yes,9.333333,0
19493,BAREC_Quran_2_Al-Baqara_16_001,Quran,Quran,Surah Al-Baqarah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,357,13,Yes,27.461538,11
12362,BAREC_Hadith_2_27_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,67,4,Yes,16.750000,1
12423,BAREC_Hadith_3_36_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,44,5,No,8.800000,2
12355,BAREC_Hadith_2_20_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,129,10,Yes,12.900000,2
12412,BAREC_Hadith_3_26_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,52,6,No,8.666667,2
12474,BAREC_Hayy_04_001,Hayy,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,1064,67,Yes,15.880597,65
18593,BAREC_OT_Genesis_5_001,OT,Old Testament,Chapter 5,#,Arts & Humanities,Specialized Text,Religion & Philosophy,439,33,Yes,13.303030,30
18574,BAREC_NT_Matthew_6_001,NT,New Testament,Chapter 6,#,Arts & Humanities,Specialized Text,Religion & Philosophy,629,35,Yes,17.971429,16
19509,BAREC_Quran_3_Aal_Imran_12_001,Quran,Quran,Surah Al-Imran,#,Arts & Humanities,Specialized Text,Religion & Philosophy,213,12,No,17.750000,10
18579,BAREC_OT_Genesis_11_001,OT,Old Testament,Chapter 11,#,Arts & Humanities,Specialized Text,Religion & Philosophy,485,33,Yes,14.696970,30
12382,BAREC_Hadith_2_45_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,92,10,Yes,9.200000,2
12403,BAREC_Hadith_3_18_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,72,7,No,10.285714,1
12353,BAREC_Hadith_2_19_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,67,6,Yes,11.166667,0
12404,BAREC_Hadith_3_19_001,Hadith,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,46,4,No,11.500000,3
19478,BAREC_Quran_107_Al-Maaoun_001,Quran,Quran,Surah Al-Ma'un,#,Arts & Humanities,Specialized Text,Religion & Philosophy,46,7,Yes,6.571429,1
19472,BAREC_Quran_101_Al-Qaria_001,Quran,Quran,Surah Al-Qari'ah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,69,11,Yes,6.272727,2

In [160]:
E_df['selected_sent_raw'] = None
E_df['selected_sent_word_count'] = None
E_df['selected_sent_words'] = None

for i, row in E_df.iterrows():
    directory = row['Directory']
    document = row['Document']

    annotations_file_path = (
        f"BAREC-10M/Data/Morphology_and_Readability/"
        f"{directory}/{document}.json"
    )

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)

    annotations = pd.DataFrame(annotations)

    selected_sentence_index = int(row['sampled_sentence_index'])

    selected_row = annotations.iloc[selected_sentence_index]

    raw_sentence = selected_row['raw_sents']
    word_count = selected_row['sents_word_count']
    words = selected_row['word']   # list of strings

    E_df.at[i, 'selected_sent_raw'] = raw_sentence
    E_df.at[i, 'selected_sent_word_count'] = word_count
    E_df.at[i, 'selected_sent_words'] = words

In [161]:
E_df = E_df[[
    'Directory',
    'Document',
    'sampled_sentence_index',
    'Source',
    'Book',
    'Author',
    'Domain',
    'Readership Group',
    'Text Category',
    'average sentence length',
    'selected_sent_raw',
    'selected_sent_word_count',
    'selected_sent_words'
]]

In [162]:
E_df.rename(columns={
    'average sentence length': 'average_sentence_length_per_doc',
}, inplace=True)

In [163]:
E_df

,Directory,Document,sampled_sentence_index,Source,Book,Author,Domain,Readership Group,Text Category,average_sentence_length_per_doc,selected_sent_raw,selected_sent_word_count,selected_sent_words
18588,OT,BAREC_OT_Genesis_1_001,29,Old Testament,Chapter 1,#,Arts & Humanities,Specialized Text,Religion & Philosophy,17.515152,28 وَبَارَكَهُمُ اللهُ وَقَالَ لَهُمْ: «أَثْمِ...,29,"[28, وباركهم, الله, وقال, لهم, :, "", أثمروا, و..."
12343,Hadith,BAREC_Hadith_1_7_001,5,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,9.313131,فَقَالَ أَيُّكُمْ أَقْرَبُ نَسَبًا بِهَذَا الر...,10,"[فقال, أيكم, أقرب, نسبا, بهذا, الرجل, الذي, يز..."
12416,Hadith,BAREC_Hadith_3_2_001,1,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,9.000000,قَالَ حَدَّثَنَا أَبُو عَوَانَةَ ، عَنْ أَبِي ...,20,"[قال, حدثنا, أبو, عوانة, ,, عن, أبي, بشر, ,, ع..."
19477,Quran,BAREC_Quran_106_Quraysh_001,1,Quran,Surah Quraish,#,Arts & Humanities,Specialized Text,Religion & Philosophy,7.250000,إِيلَافِهِمْ رِحْلَةَ الشِّتَاءِ وَالصَّيْفِ (2),7,"[إيلافهم, رحلة, الشتاء, والصيف, (, 2, )]"
12454,Hadith,BAREC_Hadith_3_64_001,38,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,8.642857,فَجَاءَ عُصْفُورٌ فَوَقَعَ عَلَى حَرْفِ السَّف...,7,"[فجاء, عصفور, فوقع, على, حرف, السفينة, ,]"
18583,OT,BAREC_OT_Genesis_15_001,1,Old Testament,Chapter 15,#,Arts & Humanities,Specialized Text,Religion & Philosophy,16.090909,1 بَعْدَ هذِهِ الأُمُورِ صَارَ كَلاَمُ الرَّبِ...,28,"[1, بعد, هذه, الأمور, صار, كلام, الرب, إلى, أب..."
19473,Quran,BAREC_Quran_102_Al-Takathur_001,1,Quran,Surah At-Takathur,#,Arts & Humanities,Specialized Text,Religion & Philosophy,6.500000,حَتَّى زُرْتُمُ الْمَقَابِرَ (2),6,"[حتى, زرتم, المقابر, (, 2, )]"
18565,NT,BAREC_NT_Matthew_13_001,1,New Testament,Chapter 13,#,Arts & Humanities,Specialized Text,Religion & Philosophy,16.949153,1 فِي ذلِكَ الْيَوْمِ خَرَجَ يَسُوعُ مِنَ الْب...,12,"[1, في, ذلك, اليوم, خرج, يسوع, من, البيت, وجلس..."
12346,Hadith,BAREC_Hadith_2_12_001,0,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,28.500000,حَدَّثَنَا عَبْدُ اللَّهِ بْنُ مَسْلَمَةَ ، عَ...,53,"[حدثنا, عبد, الله, بن, مسلمة, ,, عن, مالك, ,, ..."
12367,Hadith,BAREC_Hadith_2_31_001,1,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,10.750000,قَالَ أَخْبَرَنَا مُحَمَّدُ بْنُ فُضَيْلٍ ،,6,"[قال, أخبرنا, محمد, بن, فضيل, ,]"
18578,OT,BAREC_OT_Genesis_10_001,10,Old Testament,Chapter 10,#,Arts & Humanities,Specialized Text,Religion & Philosophy,10.909091,10 وَكَانَ ابْتِدَاءُ مَمْلَكَتِهِ بَابِلَ وَأ...,13,"[10, وكان, ابتداء, مملكته, بابل, وأرك, وأكد, و..."
19492,Quran,BAREC_Quran_2_Al-Baqara_15_001,7,Quran,Surah Al-Baqarah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,41.888889,لَا جُنَاحَ عَلَيْكُمْ إِنْ طَلَّقْتُمُ النِّس...,28,"[لا, جناح, عليكم, إن, طلقتم, النساء, ما, لم, ت..."
19500,Quran,BAREC_Quran_2_Al-Baqara_3_001,0,Quran,Surah Al-Baqarah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,16.904762,يَا بَنِي إِسْرَائِيلَ اذْكُرُوا نِعْمَتِيَ ال...,17,"[يا, بني, إسرائيل, اذكروا, نعمتي, التي, أنعمت,..."
19488,Quran,BAREC_Quran_2_Al-Baqara_11_001,9,Quran,Surah Al-Baqarah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,26.428571,فَمَنْ بَدَّلَهُ بَعْدَمَا سَمِعَهُ فَإِنَّمَا...,16,"[فمن, بدله, بعدما, سمعه, فإنما, إثمه, على, الذ..."
12473,Hayy,BAREC_Hayy_03_001,50,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,13.951613,فإنها لم تفارقه ولا فارقها إلى أن أسنَّت وضعفت,9,"[فإنها, لم, تفارقه, ولا, فارقها, إلى, أن, أسنت..."
12405,Hadith,BAREC_Hadith_3_1_001,9,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,8.000000,فَقَالَ بَعْضُ الْقَوْمِ سَمِعَ مَا قَالَ ، فَ...,11,"[فقال, بعض, القوم, سمع, ما, قال, ,, فكره, ما, ..."
18596,OT,BAREC_OT_Genesis_8_001,1,Old Testament,Chapter 8,#,Arts & Humanities,Specialized Text,Religion & Philosophy,18.086957,1 ثُمَّ ذَكَرَ اللهُ نُوحًا وَكُلَّ الْوُحُوشِ...,22,"[1, ثم, ذكر, الله, نوحا, وكل, الوحوش, وكل, الب..."
12352,Hadith,BAREC_Hadith_2_18_001,1,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,12.833333,قَالَ حَدَّثَنَا أَبُو رَوْحٍ الْحَرَمِيُّ بْن...,8,"[قال, حدثنا, أبو, روح, الحرمي, بن, عمارة, ,]"
12433,Hadith,BAREC_Hadith_3_45_001,0,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,10.000000,حَدَّثَنَا سَعِيدُ بْنُ أَبِي مَرْيَمَ ،,6,"[حدثنا, سعيد, بن, أبي, مريم, ,]"
12361,Hadith,BAREC_Hadith_2_26_001,1,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,10.000000,قَالَ حَدَّثَنَا إِسْمَاعِيلُ بْنُ جَعْفَرٍ ،,6,"[قال, حدثنا, إسماعيل, بن, جعفر, ,]"
19505,Quran,BAREC_Quran_2_Al-Baqara_8_001,0,Quran,Surah Al-Baqarah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,21.176471,يَا بَنِي إِسْرَائِيلَ اذْكُرُوا نِعْمَتِيَ ال...,15,"[يا, بني, إسرائيل, اذكروا, نعمتي, التي, أنعمت,..."
12356,Hadith,BAREC_Hadith_2_21_001,2,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,16.000000,قَالَ تُطْعِمُ الطَّعَامَ ، وَتَقْرَأُ السَّلا...,12,"[قال, تطعم, الطعام, ,, وتقرأ, السلام, على, من,..."
12457,Hadith,BAREC_Hadith_3_67_001,2,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,9.153846,قَالَ حَدَّثَنَا الأَعْمَشُ ، سُلَيْمَانُ عَنْ...,15,"[قال, حدثنا, الأعمش, ,, سليمان, عن, إبراهيم, ,..."
12489,Hayy,BAREC_Hayy_19_001,64,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,16.257576,وكان رأس تلك الجزيرة وكبيرها سلامان، وهو صاحب ...,19,"[وكان, رأس, تلك, الجزيرة, وكبيرها, سلامان, ,, ..."
12370,Hadith,BAREC_Hadith_2_34_001,0,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,15.000000,قَالَ مَالِكٌ أَخْبَرَنِي زَيْدُ بْنُ أَسْلَمَ...,41,"[قال, مالك, أخبرني, زيد, بن, أسلم, ,, أن, عطاء..."
12461,Hadith,BAREC_Hadith_3_70_001,8,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,11.300000,قَالَ يَا رَسُولَ اللَّهِ ، أَفَلاَ أُخْبِرُ ب...,16,"[قال, يا, رسول, الله, ,, أفلا, أخبر, به, الناس..."
19523,Quran,BAREC_Quran_3_Aal_Imran_7_001,5,Quran,Surah Al-Imran,#,Arts & Humanities,Specialized Text,Religion & Philosophy,20.181818,يَا أَهْلَ الْكِتَابِ لِمَ تَكْفُرُونَ بِآيَات...,12,"[يا, أهل, الكتاب, لم, تكفرون, بآيات, الله, وأن..."
19514,Quran,BAREC_Quran_3_Aal_Imran_17_001,7,Quran,Surah Al-Imran,#,Arts & Humanities,Specialized Text,Religion & Philosophy,23.888889,الَّذِينَ قَالُوا إِنَّ اللَّهَ عَهِدَ إِلَيْن...,31,"[الذين, قالوا, إن, الله, عهد, إلينا, ألا, نؤمن..."
12347,Hadith,BAREC_Hadith_2_13_001,1,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,9.428571,قَالَ أَخْبَرَنَا عَبْدَةُ ، عَنْ هِشَامٍ ، عَ...,13,"[قال, أخبرنا, عبدة, ,, عن, هشام, ,, عن, أبيه, ..."
18562,NT,BAREC_NT_Matthew_10_001,26,New Testament,Chapter 10,#,Arts & Humanities,Specialized Text,Religion & Philosophy,15.790698,26 فَلاَ تَخَافُوهُمْ. لأَنْ لَيْسَ مَكْتُومٌ ...,15,"[26, فلا, تخافوهم, ., لأن, ليس, مكتوم, لن, يست..."
18582,OT,BAREC_OT_Genesis_14_001,9,Old Testament,Chapter 14,#,Arts & Humanities,Specialized Text,Religion & Philosophy,18.520000,9 مَعَ كَدَرْلَعَوْمَرَ مَلِكِ عِيلاَمَ، وَتِد...,23,"[9, مع, كدرلعومر, ملك, عيلام, ,, وتدعال, ملك, ..."
12434,Hadith,BAREC_Hadith_3_46_001,13,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,10.666667,قَالَ أَنَا أَعْلَمُ مِنْكَ يَا أَبَا شُرَيْحٍ ،,8,"[قال, أنا, أعلم, منك, يا, أبا, شريح, ,]"
12485,Hayy,BAREC_Hayy_15_001,13,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,18.000000,وأما الضرب الثالث: فكان تشبهه بها فيه أن كان ي...,22,"[وأما, الضرب, الثالث, :, فكان, تشبهه, بها, فيه..."
19481,Quran,BAREC_Quran_110_Al-Nasr_001,0,Quran,Surah An-Nasr,#,Arts & Humanities,Specialized Text,Religion & Philosophy,9.333333,إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ (1),8,"[إذا, جاء, نصر, الله, والفتح, (, 1, )]"
19493,Quran,BAREC_Quran_2_Al-Baqara_16_001,11,Quran,Surah Al-Baqarah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,27.461538,فَلَمَّا فَصَلَ طَالُوتُ بِالْجُنُودِ قَالَ إِ...,63,"[فلما, فصل, طالوت, بالجنود, قال, إن, الله, مبت..."
12362,Hadith,BAREC_Hadith_2_27_001,1,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,16.750000,قَالَ حَدَّثَنَا سُفْيَانُ ، عَنِ الأَعْمَشِ ،...,37,"[قال, حدثنا, سفيان, ,, عن, الأعمش, ,, عن, عبد,..."
12423,Hadith,BAREC_Hadith_3_36_001,2,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,8.800000,قَالَ حَدَّثَنَا عَبْدُ اللَّهِ بْنُ الْمُثَنّ...,7,"[قال, حدثنا, عبد, الله, بن, المثنى, ,]"
12355,Hadith,BAREC_Hadith_2_20_001,2,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,12.900000,قَالَ أَخْبَرَنِي عَامِرُ بْنُ سَعْدِ بْنِ أَب...,27,"[قال, أخبرني, عامر, بن, سعد, بن, أبي, وقاص, ,,..."
12412,Hadith,BAREC_Hadith_3_26_001,2,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,8.666667,قَالَ حَدَّثَنَا أَيُّوبُ ، عَنْ عِكْرِمَةَ ، ...,26,"[قال, حدثنا, أيوب, ,, عن, عكرمة, ,, عن, ابن, ع..."
12474,Hayy,BAREC_Hayy_04_001,65,Hayy ibn Yaqdhan,Hayy ibn Yaqdhan,Ibn Tufail,Arts & Humanities,Specialized Text,Religion & Philosophy,15.880597,وتشتَّت فكره في ذلك كله وسلا عن الجسد وطرحه.,10,"[وتشتت, فكره, في, ذلك, كله, وسلا, عن, الجسد, و..."
18593,OT,BAREC_OT_Genesis_5_001,30,Old Testament,Chapter 5,#,Arts & Humanities,Specialized Text,Religion & Philosophy,13.303030,30 وَعَاشَ لاَمَكُ بَعْدَ مَا وَلَدَ نُوحًا خَ...,17,"[30, وعاش, لامك, بعد, ما, ولد, نوحا, خمس, مئة,..."
18574,NT,BAREC_NT_Matthew_6_001,16,New Testament,Chapter 6,#,Arts & Humanities,Specialized Text,Religion & Philosophy,17.971429,16 «وَمَتَى صُمْتُمْ فَلاَ تَكُونُوا عَابِسِين...,26,"[16, "", ومتى, صمتم, فلا, تكونوا, عابسين, كالمر..."
19509,Quran,BAREC_Quran_3_Aal_Imran_12_001,10,Quran,Surah Al-Imran,#,Arts & Humanities,Specialized Text,Religion & Philosophy,17.750000,وَلِلَّهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأ...,19,"[ولله, ما, في, السماوات, وما, في, الأرض, يغفر,..."
18579,OT,BAREC_OT_Genesis_11_001,30,Old Testament,Chapter 11,#,Arts & Humanities,Specialized Text,Religion & Philosophy,14.696970,30 وَكَانَتْ سَارَايُ عَاقِرًا لَيْسَ لَهَا وَ...,8,"[30, وكانت, ساراي, عاقرا, ليس, لها, ولد, .]"
12382,Hadith,BAREC_Hadith_2_45_001,2,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,9.200000,قَالَ سَمِعْتُ النُّعْمَانَ بْنَ بَشِيرٍ ، يَق...,20,"[قال, سمعت, النعمان, بن, بشير, ,, يقول, سمعت, ..."
12403,Hadith,BAREC_Hadith_3_18_001,1,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,10.285714,قَالَ حَدَّثَنِي مَالِكٌ ، عَنِ ابْنِ شِهَابٍ ...,23,"[قال, حدثني, مالك, ,, عن, ابن, شهاب, ,, عن, عب..."
12353,Hadith,BAREC_Hadith_2_19_001,0,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,11.166667,حَدَّثَنَا أَحْمَدُ بْنُ يُونُسَ ، وَمُوسَى بْ...,9,"[حدثنا, أحمد, بن, يونس, ,, وموسى, بن, إسماعيل, ,]"
12404,Hadith,BAREC_Hadith_3_19_001,3,Hadith,Sahih Bukhari,#,Arts & Humanities,Specialized Text,Religion & Philosophy,11.500000,قَالَ عَقَلْتُ مِنَ النَّبِيِّ صلى الله عليه و...,19,"[قال, عقلت, من, النبي, صلى, الله, عليه, وسلم, ..."
19478,Quran,BAREC_Quran_107_Al-Maaoun_001,1,Quran,Surah Al-Ma'un,#,Arts & Humanities,Specialized Text,Religion & Philosophy,6.571429,فَذَلِكَ الَّذِي يَدُعُّ الْيَتِيمَ (2),7,"[فذلك, الذي, يدع, اليتيم, (, 2, )]"
19472,Quran,BAREC_Quran_101_Al-Qaria_001,2,Quran,Surah Al-Qari'ah,#,Arts & Humanities,Specialized Text,Religion & Philosophy,6.272727,وَمَا أَدْرَاكَ مَا الْقَارِعَةُ (3),7,"[وما, أدراك, ما, القارعة, (, 3, )]"

In [ ]:
# E_df.to_json('sampled_RP_sentences.json', orient='records', force_ascii=False, indent=4)

In [ ]:
metadata['Text Category'].value_counts()

Text Category
Media & Culture                                  7122
Educational Materials; Language & Linguistics    4709
Academic                                         4301
Literature; Art & Music                          3974
Religion & Philosophy                             254
Encyclopedic                                      175
Name: count, dtype: int64

In [165]:
EN_df = metadata[metadata['Text Category']=='Encyclopedic']
print("Encyclopedic")
print("==========================")
print(f"Number of documents: {EN_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {EN_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {EN_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {EN_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{EN_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{EN_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{EN_df['average sentence length'].describe().to_dict()}")
print("==========================")

Encyclopedic
==========================
Number of documents: 175
--------------------------
Number of sentences: 5749
--------------------------
Number of unique books: 175
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Social Sciences': 90, 'Arts & Humanities': 48, 'STEM': 37}
--------------------------
Readership Group distribution:
{'Advanced Text': 175}
--------------------------
Average sentence length distribution:
{'count': 175.0, 'mean': 22.279801555703763, 'std': 3.686049565777941, 'min': 11.491228070175438, '25%': 19.79873949579832, '50%': 21.8125, '75%': 24.34188034188034, 'max': 36.904761904761905}
==========================

In [166]:
EN_AH_df = EN_df[EN_df['Domain']=='Arts & Humanities']
print("Encyclopedic - Arts & Humanities")
print("==========================")
print(f"Number of documents: {EN_AH_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {EN_AH_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {EN_AH_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {EN_AH_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{EN_AH_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{EN_AH_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{EN_AH_df['average sentence length'].describe().to_dict()}")
print("==========================")

Encyclopedic - Arts & Humanities
==========================
Number of documents: 48
--------------------------
Number of sentences: 1674
--------------------------
Number of unique books: 48
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Arts & Humanities': 48}
--------------------------
Readership Group distribution:
{'Advanced Text': 48}
--------------------------
Average sentence length distribution:
{'count': 48.0, 'mean': 21.893738189027854, 'std': 3.8578502565209836, 'min': 11.491228070175438, '25%': 19.16559829059829, '50%': 21.563541666666666, '75%': 24.717741935483872, 'max': 33.12903225806452}
==========================

In [167]:
sampled_EN_AH_advanced_df = EN_AH_df.sample(17, random_state=42)

In [168]:
sampled_EN_AH_df = sampled_EN_AH_advanced_df.copy()

In [169]:
sampled_EN_AH_sentences_indices = []
for i, row in sampled_EN_AH_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_EN_AH_sentences_indices.append(sampled_index)
print(sampled_EN_AH_sentences_indices)

[27, 0, 18, 16, 28, 29, 26, 8, 29, 23, 27, 9, 9, 9, 27, 33, 27]

In [170]:
sampled_EN_AH_df['sampled_sentence_index'] = sampled_EN_AH_sentences_indices

In [171]:
EN_ST_df = EN_df[EN_df['Domain']=='STEM']
print("Encyclopedic - STEM")
print("==========================")
print(f"Number of documents: {EN_ST_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {EN_ST_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {EN_ST_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {EN_ST_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{EN_ST_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{EN_ST_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{EN_ST_df['average sentence length'].describe().to_dict()}")
print("==========================")

Encyclopedic - STEM
==========================
Number of documents: 37
--------------------------
Number of sentences: 1207
--------------------------
Number of unique books: 37
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'STEM': 37}
--------------------------
Readership Group distribution:
{'Advanced Text': 37}
--------------------------
Average sentence length distribution:
{'count': 37.0, 'mean': 21.50345219510831, 'std': 3.586902951861836, 'min': 11.76923076923077, '25%': 18.72222222222222, '50%': 21.7, '75%': 23.25, 'max': 30.291666666666668}
==========================

In [172]:
sampled_EN_ST_advanced_df = EN_ST_df.sample(16, random_state=42)

In [173]:
sampled_EN_ST_df = sampled_EN_ST_advanced_df.copy()

In [174]:
sampled_EN_ST_sentences_indices = []
for i, row in sampled_EN_ST_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_EN_ST_sentences_indices.append(sampled_index)
print(sampled_EN_ST_sentences_indices)

[9, 33, 34, 29, 9, 28, 8, 15, 8, 9, 27, 8, 8, 8, 27, 8]

In [175]:
sampled_EN_ST_df['sampled_sentence_index'] = sampled_EN_ST_sentences_indices

In [176]:
EN_SS_df = EN_df[EN_df['Domain']=='Social Sciences']
print("Encyclopedic - Social Sciences")
print("==========================")
print(f"Number of documents: {EN_SS_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {EN_SS_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {EN_SS_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {EN_SS_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{EN_SS_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{EN_SS_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{EN_SS_df['average sentence length'].describe().to_dict()}")
print("==========================")

Encyclopedic - Social Sciences
==========================
Number of documents: 90
--------------------------
Number of sentences: 2868
--------------------------
Number of unique books: 90
--------------------------
Number of unique authors: 1
--------------------------
Domain distribution:
{'Social Sciences': 90}
--------------------------
Readership Group distribution:
{'Advanced Text': 90}
--------------------------
Average sentence length distribution:
{'count': 90.0, 'mean': 22.804867866175705, 'std': 3.590235208744769, 'min': 15.5, '25%': 20.44017595307918, '50%': 22.192028985507246, '75%': 24.75607142857143, 'max': 36.904761904761905}
==========================

In [177]:
sampled_EN_SS_advanced_df = EN_SS_df.sample(17, random_state=42)

In [178]:
sampled_EN_SS_df = sampled_EN_SS_advanced_df.copy()
sampled_EN_SS_df.shape

(17, 12)

In [179]:
sampled_EN_SS_sentences_indices = []
for i, row in sampled_EN_SS_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_EN_SS_sentences_indices.append(sampled_index)
print(sampled_EN_SS_sentences_indices)

[8, 15, 17, 29, 28, 26, 8, 9, 8, 9, 27, 8, 36, 36, 0, 15, 9]

In [180]:
sampled_EN_SS_df['sampled_sentence_index'] = sampled_EN_SS_sentences_indices

In [181]:
F_df = pd.concat([sampled_EN_AH_df, sampled_EN_ST_df, sampled_EN_SS_df], ignore_index=True)
F_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,average sentence length,sampled_sentence_index
0,BAREC_Wikipedia_أنغكور_وات_001,Wikipedia,Wikipedia,Angkor Wat,#,Arts & Humanities,Advanced Text,Encyclopedic,659,31,Yes,21.258065,27
1,BAREC_Wikipedia_ضريح_سليمان_شاه_001,Wikipedia,Wikipedia,The Tomb of Suleiman Shah,#,Arts & Humanities,Advanced Text,Encyclopedic,585,23,Yes,25.434783,0
2,BAREC_Wikipedia_أليساندرو_دل_بييرو_001,Wikipedia,Wikipedia,Alessandro Del Piero,#,Arts & Humanities,Advanced Text,Encyclopedic,767,38,Yes,20.184211,18
3,BAREC_Wikipedia_عمارة_بنائية_001,Wikipedia,Wikipedia,Architectural Buildings,#,Arts & Humanities,Advanced Text,Encyclopedic,621,24,Yes,25.875000,16
4,BAREC_Wikipedia_ألسنة_اللهب_001,Wikipedia,Wikipedia,Flames,#,Arts & Humanities,Advanced Text,Encyclopedic,990,49,Yes,20.204082,28
5,BAREC_Wikipedia_ريتان_001,Wikipedia,Wikipedia,Ritan,#,Arts & Humanities,Advanced Text,Encyclopedic,675,32,Yes,21.093750,29
6,BAREC_Wikipedia_المسجد_الأقصى_001,Wikipedia,Wikipedia,Al-Aqsa Mosque,#,Arts & Humanities,Advanced Text,Encyclopedic,743,39,Yes,19.051282,26
7,BAREC_Wikipedia_الموثوقية_التاريخية_للأناجيل_001,Wikipedia,Wikipedia,Historical Reliability of the Gospels,#,Arts & Humanities,Advanced Text,Encyclopedic,709,27,Yes,26.259259,8
8,BAREC_Wikipedia_الحج_في_الإسلام_001,Wikipedia,Wikipedia,Hajj in Islam,#,Arts & Humanities,Advanced Text,Encyclopedic,589,31,Yes,19.000000,29
9,BAREC_Wikipedia_ألفية_ابن_مالك_001,Wikipedia,Wikipedia,The Millennium of Ibn Malik,#,Arts & Humanities,Advanced Text,Encyclopedic,924,56,Yes,16.500000,23
10,BAREC_Wikipedia_الطائر_المقلد_001,Wikipedia,Wikipedia,The Imitative Bird,#,Arts & Humanities,Advanced Text,Encyclopedic,689,30,Yes,22.966667,27
11,BAREC_Wikipedia_الجامع_الأزهر_001,Wikipedia,Wikipedia,Al-Azhar Mosque,#,Arts & Humanities,Advanced Text,Encyclopedic,637,29,Yes,21.965517,9
12,BAREC_Wikipedia_الزوجة_القروية_001,Wikipedia,Wikipedia,The Country Wife,#,Arts & Humanities,Advanced Text,Encyclopedic,809,28,Yes,28.892857,9
13,BAREC_Wikipedia_شاعر_في_نيويورك_001,Wikipedia,Wikipedia,A Poet in New York,#,Arts & Humanities,Advanced Text,Encyclopedic,729,29,Yes,25.137931,9
14,BAREC_Wikipedia_جامع_بني_أمية_الكبير_001,Wikipedia,Wikipedia,The Great Umayyad Mosque,#,Arts & Humanities,Advanced Text,Encyclopedic,800,44,Yes,18.181818,27
15,BAREC_Wikipedia_المسجد_الإبراهيمي_001,Wikipedia,Wikipedia,The Ibrahimi Mosque,#,Arts & Humanities,Advanced Text,Encyclopedic,842,35,Yes,24.057143,33
16,BAREC_Wikipedia_المشاعر_المقدسة_001,Wikipedia,Wikipedia,The Holy Sites,#,Arts & Humanities,Advanced Text,Encyclopedic,767,44,Yes,17.431818,27
17,BAREC_Wikipedia_ترانزستور_ثنائي_القطب_001,Wikipedia,Wikipedia,Bipolar Transistor,#,STEM,Advanced Text,Encyclopedic,627,28,Yes,22.392857,9
18,BAREC_Wikipedia_تاريخ_المنهج_العلمي_001,Wikipedia,Wikipedia,The History of the Scientific Method,#,STEM,Advanced Text,Encyclopedic,881,38,Yes,23.184211,33
19,BAREC_Wikipedia_إلكترون_001,Wikipedia,Wikipedia,Electron,#,STEM,Advanced Text,Encyclopedic,868,40,Yes,21.700000,34
20,BAREC_Wikipedia_عدد أولي_001,Wikipedia,Wikipedia,Prime Number,#,STEM,Advanced Text,Encyclopedic,605,33,Yes,18.333333,29
21,BAREC_Wikipedia_مرصد_هابل_الفضائي_001,Wikipedia,Wikipedia,The Hubble Space Telescope,#,STEM,Advanced Text,Encyclopedic,651,28,Yes,23.250000,9
22,BAREC_Wikipedia_ذكاء_اصطناعي_001,Wikipedia,Wikipedia,Artificial Intelligence,#,STEM,Advanced Text,Encyclopedic,676,37,Yes,18.270270,28
23,BAREC_Wikipedia_بث_متعدد_001,Wikipedia,Wikipedia,Multiple Broadcasting,#,STEM,Advanced Text,Encyclopedic,693,26,Yes,26.653846,8
24,BAREC_Wikipedia_روبوت_001,Wikipedia,Wikipedia,Robot,#,STEM,Advanced Text,Encyclopedic,676,23,Yes,29.391304,15
25,BAREC_Wikipedia_خوارزمية_001,Wikipedia,Wikipedia,Algorithm,#,STEM,Advanced Text,Encyclopedic,471,25,Yes,18.840000,8
26,BAREC_Wikipedia_تجزئة_الشبكة_001,Wikipedia,Wikipedia,Network Segmentation,#,STEM,Advanced Text,Encyclopedic,344,16,Yes,21.500000,9
27,BAREC_Wikipedia_بروتوكول_التوجيه_الداخلي_المحس...,Wikipedia,Wikipedia,Enhanced Internal Routing Protocol Between Gates,#,STEM,Advanced Text,Encyclopedic,734,29,Yes,25.310345,27
28,BAREC_Wikipedia_تاريخ_علم_الأحياء_001,Wikipedia,Wikipedia,History of Biology,#,STEM,Advanced Text,Encyclopedic,727,24,Yes,30.291667,8
29,BAREC_Wikipedia_تاريخ_الإمارات_العربية_المتحد...,Wikipedia,Wikipedia,The History of Aluminum,#,STEM,Advanced Text,Encyclopedic,657,26,Yes,25.269231,8
30,BAREC_Wikipedia_فيزياء_001,Wikipedia,Wikipedia,Physics,#,STEM,Advanced Text,Encyclopedic,654,27,Yes,24.222222,8
31,BAREC_Wikipedia_بروتوكول_تهيئة_المضيف_الآلية...,Wikipedia,Wikipedia,Host Initialization Protocol,#,STEM,Advanced Text,Encyclopedic,734,30,Yes,24.466667,27
32,BAREC_Wikipedia_تمثيل_القبولية_001,Wikipedia,Wikipedia,Representation of Acceptance,#,STEM,Advanced Text,Encyclopedic,586,27,Yes,21.703704,8
33,BAREC_Wikipedia_بوبي_فيشر_001,Wikipedia,Wikipedia,Bobby Fischer,#,Social Sciences,Advanced Text,Encyclopedic,563,27,Yes,20.851852,8
34,BAREC_Wikipedia_المهرجان_العالمي_للعلوم_001,Wikipedia,Wikipedia,The World Science Festival,#,Social Sciences,Advanced Text,Encyclopedic,599,23,Yes,26.043478,15
35,BAREC_Wikipedia_حفل_زفاف_الأمير_ويليام_وكيت_م...,Wikipedia,Wikipedia,The Wedding of Prince William and Kate Middleton,#,Social Sciences,Advanced Text,Encyclopedic,796,37,Yes,21.513514,17
36,BAREC_Wikipedia_عروج_بربروس_001,Wikipedia,Wikipedia,The Ascension of Barbarossa,#,Social Sciences,Advanced Text,Encyclopedic,687,32,Yes,21.468750,29
37,BAREC_Wikipedia_ابن_خلدون_001,Wikipedia,Wikipedia,Ibn Khaldun,#,Social Sciences,Advanced Text,Encyclopedic,641,32,Yes,20.031250,28
38,BAREC_Wikipedia_أرمينيا_001,Wikipedia,Wikipedia,Armenia,#,Social Sciences,Advanced Text,Encyclopedic,794,43,Yes,18.465116,26
39,BAREC_Wikipedia_بوبي_روبسون_001,Wikipedia,Wikipedia,Bobby Robson,#,Social Sciences,Advanced Text,Encyclopedic,607,28,Yes,21.678571,8
40,BAREC_Wikipedia_طريق_الحرير_001,Wikipedia,Wikipedia,The Silk Road,#,Social Sciences,Advanced Text,Encyclopedic,636,26,Yes,24.461538,9
41,BAREC_Wikipedia_الريفيون_001,Wikipedia,Wikipedia,The Ryfiyyun,#,Social Sciences,Advanced Text,Encyclopedic,695,28,Yes,24.821429,8
42,BAREC_Wikipedia_تاريخ_الكويت_001,Wikipedia,Wikipedia,History of Kuwait,#,Social Sciences,Advanced Text,Encyclopedic,576,27,Yes,21.333333,9
43,BAREC_Wikipedia_كيرلا_001,Wikipedia,Wikipedia,Kerala,#,Social Sciences,Advanced Text,Encyclopedic,699,29,Yes,24.103448,27
44,BAREC_Wikipedia_بايرن_ميونخ_001,Wikipedia,Wikipedia,Bayern Munich,#,Social Sciences,Advanced Text,Encyclopedic,763,27,Yes,28.259259,8
45,BAREC_Wikipedia_رجال_المينتش_الزرق_001,Wikipedia,Wikipedia,The Blue Men of the Mintoch,#,Social Sciences,Advanced Text,Encyclopedic,888,37,Yes,24.000000,36
46,BAREC_Wikipedia_مكة_001,Wikipedia,Wikipedia,Mecca,#,Social Sciences,Advanced Text,Encyclopedic,715,37,Yes,19.324324,36
47,BAREC_Wikipedia_الصومال_001,Wikipedia,Wikipedia,Somalia,#,Social Sciences,Advanced Text,Encyclopedic,775,21,Yes,36.904762,0
48,BAREC_Wikipedia_الإمارات_العربية_المتحدة_001,Wikipedia,Wikipedia,United Arab Emirates,#,Social Sciences,Advanced Text,Encyclopedic,671,35,Yes,19.171429,15
49,BAREC_Wikipedia_المرأة_في_إيطاليا_001,Wikipedia,Wikipedia,Women in Italy,#,Social Sciences,Advanced Text,Encyclopedic,737,28,Yes,26.321429,9

In [184]:
F_df['selected_sent_raw'] = None
F_df['selected_sent_word_count'] = None
F_df['selected_sent_words'] = None

for i, row in F_df.iterrows():
    directory = row['Directory']
    document = row['Document']

    annotations_file_path = (
        f"BAREC-10M/Data/Morphology_and_Readability/"
        f"{directory}/{document}.json"
    )

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)

    annotations = pd.DataFrame(annotations)

    selected_sentence_index = int(row['sampled_sentence_index'])

    selected_row = annotations.iloc[selected_sentence_index]

    raw_sentence = selected_row['raw_sents']
    word_count = selected_row['sents_word_count']
    words = selected_row['word']   # list of strings

    F_df.at[i, 'selected_sent_raw'] = raw_sentence
    F_df.at[i, 'selected_sent_word_count'] = word_count
    F_df.at[i, 'selected_sent_words'] = words

In [185]:
F_df = F_df[[
    'Directory',
    'Document',
    'sampled_sentence_index',
    'Source',
    'Book',
    'Author',
    'Domain',
    'Readership Group',
    'Text Category',
    'average sentence length',
    'selected_sent_raw',
    'selected_sent_word_count',
    'selected_sent_words'
]]

In [186]:
F_df.rename(columns={
    'average sentence length': 'average_sentence_length_per_doc',
}, inplace=True)

In [187]:
F_df

,Directory,Document,sampled_sentence_index,Source,Book,Author,Domain,Readership Group,Text Category,average_sentence_length_per_doc,selected_sent_raw,selected_sent_word_count,selected_sent_words
0,Wikipedia,BAREC_Wikipedia_أنغكور_وات_001,27,Wikipedia,Angkor Wat,#,Arts & Humanities,Advanced Text,Encyclopedic,21.258065,يرجع ذلك إلى وجود الخندق المائي الذي قام كعامل...,15,"[يرجع, ذلك, إلى, وجود, الخندق, المائي, الذي, ق..."
1,Wikipedia,BAREC_Wikipedia_ضريح_سليمان_شاه_001,0,Wikipedia,The Tomb of Suleiman Shah,#,Arts & Humanities,Advanced Text,Encyclopedic,25.434783,قبر سليمان شاه أو ضريح سليمان شاه (بالتركية ال...,38,"[قبر, سليمان, شاه, أو, ضريح, سليمان, شاه, (, ب..."
2,Wikipedia,BAREC_Wikipedia_أليساندرو_دل_بييرو_001,18,Wikipedia,Alessandro Del Piero,#,Arts & Humanities,Advanced Text,Encyclopedic,20.184211,وترعرع في قرية «ساكون» ببلدية سان فينديميانو ا...,10,"[وترعرع, في, قرية, "", ساكون, "", ببلدية, سان, ف..."
3,Wikipedia,BAREC_Wikipedia_عمارة_بنائية_001,16,Wikipedia,Architectural Buildings,#,Arts & Humanities,Advanced Text,Encyclopedic,25.875000,وقد تمحور هذا الصراع منذ البداية بين شخصيتين ر...,16,"[وقد, تمحور, هذا, الصراع, منذ, البداية, بين, ش..."
4,Wikipedia,BAREC_Wikipedia_ألسنة_اللهب_001,28,Wikipedia,Flames,#,Arts & Humanities,Advanced Text,Encyclopedic,20.204082,توفي والدها في انفجار منجم تعدين قبل سنوات، وه...,37,"[توفي, والدها, في, انفجار, منجم, تعدين, قبل, س..."
5,Wikipedia,BAREC_Wikipedia_ريتان_001,29,Wikipedia,Ritan,#,Arts & Humanities,Advanced Text,Encyclopedic,21.093750,وكانت نسبة 16.3% من القاطنين تحت سن الثامنة عش...,26,"[وكانت, نسبة, 16, ., 3, %, من, القاطنين, تحت, ..."
6,Wikipedia,BAREC_Wikipedia_المسجد_الأقصى_001,26,Wikipedia,Al-Aqsa Mosque,#,Arts & Humanities,Advanced Text,Encyclopedic,19.051282,'== تاريخ المسجد الأقصى ==,7,"[', =, =, تاريخ, المسجد, الأقصى, =, =]"
7,Wikipedia,BAREC_Wikipedia_الموثوقية_التاريخية_للأناجيل_001,8,Wikipedia,Historical Reliability of the Gospels,#,Arts & Humanities,Advanced Text,Encyclopedic,26.259259,يلجأ المؤرخون الذين يخضعون الأناجيل إلى التحلي...,20,"[يلجأ, المؤرخون, الذين, يخضعون, الأناجيل, إلى,..."
8,Wikipedia,BAREC_Wikipedia_الحج_في_الإسلام_001,29,Wikipedia,Hajj in Islam,#,Arts & Humanities,Advanced Text,Encyclopedic,19.000000,والطوائف الإسلامية المختلفة، من سنة وشيعة، تؤد...,14,"[والطوائف, الإسلامية, المختلفة, ,, من, سنة, وش..."
9,Wikipedia,BAREC_Wikipedia_ألفية_ابن_مالك_001,23,Wikipedia,The Millennium of Ibn Malik,#,Arts & Humanities,Advanced Text,Encyclopedic,16.500000,محمد بن عبد الله بن محمد بن عبد الله بن مالك ا...,23,"[محمد, بن, عبد, الله, بن, محمد, بن, عبد, الله,..."
10,Wikipedia,BAREC_Wikipedia_الطائر_المقلد_001,27,Wikipedia,The Imitative Bird,#,Arts & Humanities,Advanced Text,Encyclopedic,22.966667,ففي الميثولوجيا الإغريقية، كعقوبة على مقتل أند...,34,"[ففي, الميثولوجيا, الإغريقية, ,, كعقوبة, على, ..."
11,Wikipedia,BAREC_Wikipedia_الجامع_الأزهر_001,9,Wikipedia,Al-Azhar Mosque,#,Arts & Humanities,Advanced Text,Encyclopedic,21.965517,يعتبر المسجد ثاني أقدم جامعة قائمة بشكل مستمر ...,14,"[يعتبر, المسجد, ثاني, أقدم, جامعة, قائمة, بشكل..."
12,Wikipedia,BAREC_Wikipedia_الزوجة_القروية_001,9,Wikipedia,The Country Wife,#,Arts & Humanities,Advanced Text,Encyclopedic,28.892857,ولكن من جديد عادت المسرحية الأصلية لتُصبح مُفض...,35,"[ولكن, من, جديد, عادت, المسرحية, الأصلية, لتصب..."
13,Wikipedia,BAREC_Wikipedia_شاعر_في_نيويورك_001,9,Wikipedia,A Poet in New York,#,Arts & Humanities,Advanced Text,Encyclopedic,25.137931,لقد كان هذا الديوان صرخة مدويّة ضد الرّعب، للت...,33,"[لقد, كان, هذا, الديوان, صرخة, مدوية, ضد, الرع..."
14,Wikipedia,BAREC_Wikipedia_جامع_بني_أمية_الكبير_001,27,Wikipedia,The Great Umayyad Mosque,#,Arts & Humanities,Advanced Text,Encyclopedic,18.181818,وقد أُعجب السكان المحليين بتماثُل وأبعاد «معبد...,13,"[وقد, أعجب, السكان, المحليين, بتماثل, وأبعاد, ..."
15,Wikipedia,BAREC_Wikipedia_المسجد_الإبراهيمي_001,33,Wikipedia,The Ibrahimi Mosque,#,Arts & Humanities,Advanced Text,Encyclopedic,24.057143,قال ابن كثير في كتابه البداية والنهاية: «فقبره...,37,"[قال, ابن, كثير, في, كتابه, البداية, والنهاية,..."
16,Wikipedia,BAREC_Wikipedia_المشاعر_المقدسة_001,27,Wikipedia,The Holy Sites,#,Arts & Humanities,Advanced Text,Encyclopedic,17.431818,ثبير الأثبرة: أو ثبير غيناء، يواجه جبل النور م...,28,"[ثبير, الأثبرة, :, أو, ثبير, غيناء, ,, يواجه, ..."
17,Wikipedia,BAREC_Wikipedia_ترانزستور_ثنائي_القطب_001,9,Wikipedia,Bipolar Transistor,#,STEM,Advanced Text,Encyclopedic,22.392857,ولهذا فإنّ الترانزستور يخضع لقواعد التحييز الخ...,10,"[ولهذا, فإن, الترانزستور, يخضع, لقواعد, التحيي..."
18,Wikipedia,BAREC_Wikipedia_تاريخ_المنهج_العلمي_001,33,Wikipedia,The History of the Scientific Method,#,STEM,Advanced Text,Encyclopedic,23.184211,في محاورة بروتاغوراس، ذكر أفلاطون وجود تعليم ل...,14,"[في, محاورة, بروتاغوراس, ,, ذكر, أفلاطون, وجود..."
19,Wikipedia,BAREC_Wikipedia_إلكترون_001,34,Wikipedia,Electron,#,STEM,Advanced Text,Encyclopedic,21.700000,وكان قادرًا على تقييم قيمة هذه الشحنة الأولية ...,16,"[وكان, قادرا, على, تقييم, قيمة, هذه, الشحنة, ا..."
20,Wikipedia,BAREC_Wikipedia_عدد أولي_001,29,Wikipedia,Prime Number,#,STEM,Advanced Text,Encyclopedic,18.333333,3 عدد أولي أيضا لأن القاسمين الوحيدين له هما 1...,14,"[3, عدد, أولي, أيضا, لأن, القاسمين, الوحيدين, ..."
21,Wikipedia,BAREC_Wikipedia_مرصد_هابل_الفضائي_001,9,Wikipedia,The Hubble Space Telescope,#,STEM,Advanced Text,Encyclopedic,23.250000,لقد أدَّت العديد من مُشاهدات مرصد هابل إلى تقد...,21,"[لقد, أدت, العديد, من, مشاهدات, مرصد, هابل, إل..."
22,Wikipedia,BAREC_Wikipedia_ذكاء_اصطناعي_001,28,Wikipedia,Artificial Intelligence,#,STEM,Advanced Text,Encyclopedic,18.270270,بحلول منتصف الستينيات أصبحت تلك البحوث تمول بس...,13,"[بحلول, منتصف, الستينيات, أصبحت, تلك, البحوث, ..."
23,Wikipedia,BAREC_Wikipedia_بث_متعدد_001,8,Wikipedia,Multiple Broadcasting,#,STEM,Advanced Text,Encyclopedic,26.653846,'== نظرة عامة ==,6,"[', =, =, نظرة, عامة, =, =]"
24,Wikipedia,BAREC_Wikipedia_روبوت_001,15,Wikipedia,Robot,#,STEM,Advanced Text,Encyclopedic,29.391304,وهذه الإنسالات مبرمجة عادةً لتنفيذ مهامها بصور...,11,"[وهذه, الإنسالات, مبرمجة, عادة, لتنفيذ, مهامها..."
25,Wikipedia,BAREC_Wikipedia_خوارزمية_001,8,Wikipedia,Algorithm,#,STEM,Advanced Text,Encyclopedic,18.840000,هذه الطريقة هي ما تسمى اتخاذ القرار أو الاختيار.,10,"[هذه, الطريقة, هي, ما, تسمى, اتخاذ, القرار, أو..."
26,Wikipedia,BAREC_Wikipedia_تجزئة_الشبكة_001,9,Wikipedia,Network Segmentation,#,STEM,Advanced Text,Encyclopedic,21.500000,تجزئة فضاء العناوين هي عملية رياضية يُقسَّم فض...,20,"[تجزئة, فضاء, العناوين, هي, عملية, رياضية, يقس..."
27,Wikipedia,BAREC_Wikipedia_بروتوكول_التوجيه_الداخلي_المحس...,27,Wikipedia,Enhanced Internal Routing Protocol Between Gates,#,STEM,Advanced Text,Encyclopedic,25.310345,واستغرق العمل 3 سنوات أخرى، مع مشاركة من أطراف...,22,"[واستغرق, العمل, 3, سنوات, أخرى, ,, مع, مشاركة..."
28,Wikipedia,BAREC_Wikipedia_تاريخ_علم_الأحياء_001,8,Wikipedia,History of Biology,#,STEM,Advanced Text,Encyclopedic,30.291667,بدأ أنطوان لافوازييه وغيره من علماء الفيزياء ب...,16,"[بدأ, أنطوان, لافوازييه, وغيره, من, علماء, الف..."
29,Wikipedia,BAREC_Wikipedia_تاريخ_الإمارات_العربية_المتحد...,8,Wikipedia,The History of Aluminum,#,STEM,Advanced Text,Encyclopedic,25.269231,لأرض الإمارات العربية المتحدة تاريخ قديم.,7,"[لأرض, الإمارات, العربية, المتحدة, تاريخ, قديم..."
30,Wikipedia,BAREC_Wikipedia_فيزياء_001,8,Wikipedia,Physics,#,STEM,Advanced Text,Encyclopedic,24.222222,تهتم الفيزياء في نفس الوقت بدقة القياس وابتكار...,15,"[تهتم, الفيزياء, في, نفس, الوقت, بدقة, القياس,..."
31,Wikipedia,BAREC_Wikipedia_بروتوكول_تهيئة_المضيف_الآلية...,27,Wikipedia,Host Initialization Protocol,#,STEM,Advanced Text,Encyclopedic,24.466667,في حين يعتمد العملاء الموجودون في شبكة بعيدة ع...,29,"[في, حين, يعتمد, العملاء, الموجودون, في, شبكة,..."
32,Wikipedia,BAREC_Wikipedia_تمثيل_القبولية_001,8,Wikipedia,Representation of Acceptance,#,STEM,Advanced Text,Encyclopedic,21.703704,وبالتالي جميع قوانين تحليل الدوائر الكهربية - ...,24,"[وبالتالي, جميع, قوانين, تحليل, الدوائر, الكهر..."
33,Wikipedia,BAREC_Wikipedia_بوبي_فيشر_001,8,Wikipedia,Bobby Fischer,#,Social Sciences,Advanced Text,Encyclopedic,20.851852,في تموز 1971 صار فيشر الأول عالمياً في تصنيف ا...,13,"[في, تموز, 1971, صار, فيشر, الأول, عالميا, في,..."
34,Wikipedia,BAREC_Wikipedia_المهرجان_العالمي_للعلوم_001,15,Wikipedia,The World Science Festival,#,Social Sciences,Advanced Text,Encyclopedic,26.043478,وفقًا لغرين، فإن الفكرة لاقت القبول والاستحسان...,25,"[وفقا, لغرين, ,, فإن, الفكرة, لاقت, القبول, وا..."
35,Wikipedia,BAREC_Wikipedia_حفل_زفاف_الأمير_ويليام_وكيت_م...,17,Wikipedia,The Wedding of Prince William and Kate Middleton,#,Social Sciences,Advanced Text,Encyclopedic,21.513514,'=== بروفة الحفل ===,8,"[', =, =, =, بروفة, الحفل, =, =, =]"
36,Wikipedia,BAREC_Wikipedia_عروج_بربروس_001,29,Wikipedia,The Ascension of Barbarossa,#,Social Sciences,Advanced Text,Encyclopedic,21.468750,وبعد أن استقر يعقوب في الجزيرة وانتظمت أمور حي...,23,"[وبعد, أن, استقر, يعقوب, في, الجزيرة, وانتظمت,..."
37,Wikipedia,BAREC_Wikipedia_ابن_خلدون_001,28,Wikipedia,Ibn Khaldun,#,Social Sciences,Advanced Text,Encyclopedic,20.031250,فإذا كان جده الداخل إلى الأندلس عند الفتح فإن ...,31,"[فإذا, كان, جده, الداخل, إلى, الأندلس, عند, ال..."
38,Wikipedia,BAREC_Wikipedia_أرمينيا_001,26,Wikipedia,Armenia,#,Social Sciences,Advanced Text,Encyclopedic,18.465116,بلغت المملكة ذروتها بين 95 و66 قبل الميلاد تحت...,24,"[بلغت, المملكة, ذروتها, بين, 95, و66, قبل, الم..."
39,Wikipedia,BAREC_Wikipedia_بوبي_روبسون_001,8,Wikipedia,Bobby Robson,#,Social Sciences,Advanced Text,Encyclopedic,21.678571,عانى من مشاكل بالرئة منذ عام 1991، حتى أعلن في...,18,"[عانى, من, مشاكل, بالرئة, منذ, عام, 1991, ,, ح..."
40,Wikipedia,BAREC_Wikipedia_طريق_الحرير_001,9,Wikipedia,The Silk Road,#,Social Sciences,Advanced Text,Encyclopedic,24.461538,وقد أذهلت هذه الصناعة الناس قديماً، فسعوا لاقت...,23,"[وقد, أذهلت, هذه, الصناعة, الناس, قديما, ,, فس..."
41,Wikipedia,BAREC_Wikipedia_الريفيون_001,8,Wikipedia,The Ryfiyyun,#,Social Sciences,Advanced Text,Encyclopedic,24.821429,في نفس السياق، يصنف الأنثروبولوجيون أيضا سكان ...,17,"[في, نفس, السياق, ,, يصنف, الأنثروبولوجيون, أي..."
42,Wikipedia,BAREC_Wikipedia_تاريخ_الكويت_001,9,Wikipedia,History of Kuwait,#,Social Sciences,Advanced Text,Encyclopedic,21.333333,'== التاريخ القديم ==,6,"[', =, =, التاريخ, القديم, =, =]"
43,Wikipedia,BAREC_Wikipedia_كيرلا_001,27,Wikipedia,Kerala,#,Social Sciences,Advanced Text,Encyclopedic,24.103448,وتُعد إحدى الوجهات السياحية البارزة في الهند، ...,17,"[وتعد, إحدى, الوجهات, السياحية, البارزة, في, ا..."
44,Wikipedia,BAREC_Wikipedia_بايرن_ميونخ_001,8,Wikipedia,Bayern Munich,#,Social Sciences,Advanced Text,Encyclopedic,28.259259,فاز بايرن أيضًا بكأس الاتحاد الأوروبي مرة واحد...,30,"[فاز, بايرن, أيضا, بكأس, الاتحاد, الأوروبي, مر..."
45,Wikipedia,BAREC_Wikipedia_رجال_المينتش_الزرق_001,36,Wikipedia,The Blue Men of the Mintoch,#,Social Sciences,Advanced Text,Encyclopedic,24.000000,وعندما تنقلب السفينة يجعلهم هذا الأمر يضحكون م...,10,"[وعندما, تنقلب, السفينة, يجعلهم, هذا, الأمر, ي..."
46,Wikipedia,BAREC_Wikipedia_مكة_001,36,Wikipedia,Mecca,#,Social Sciences,Advanced Text,Encyclopedic,19.324324,من الأسماء الأخرى لمكة في التوراة: تل فران، وه...,19,"[من, الأسماء, الأخرى, لمكة, في, التوراة, :, تل..."
47,Wikipedia,BAREC_Wikipedia_الصومال_001,0,Wikipedia,Somalia,#,Social Sciences,Advanced Text,Encyclopedic,36.904762,الصومال (بالصومالية: Soomaaliya)‏، أو (رسمياً:...,65,"[الصومال, (, بالصومالية, :, Soomaaliya, ), ,, ..."
48,Wikipedia,BAREC_Wikipedia_الإمارات_العربية_المتحدة_001,15,Wikipedia,United Arab Emirates,#,Social Sciences,Advanced Text,Encyclopedic,19.171429,إن اقتصاد دولة الإمارات يحتل المرتبة 22 على مس...,15,"[إن, اقتصاد, دولة, الإمارات, يحتل, المرتبة, 22..."
49,Wikipedia,BAREC_Wikipedia_المرأة_في_إيطاليا_001,9,Wikipedia,Women in Italy,#,Social Sciences,Advanced Text,Encyclopedic,26.321429,وبعد قرن من ظهور كتاب كريستين دي بيزان، ستؤكد ...,19,"[وبعد, قرن, من, ظهور, كتاب, كريستين, دي, بيزان..."

In [ ]:
# F_df.to_json('sampled_EN_sentences.json', orient='records', force_ascii=False, indent=4)

In [ ]:
## Data groups:

# A --> Literature; Arts & Music
# B --> Media & Culture
# C --> Educational Materials; Language & Linguistics
# D --> Academic
# E --> Religion & Philosophy
# F --> Encyclopedic

In [ ]:
## Annotators:

# 1 --> 
# 2 --> 
# 3 -->
# 4 -->
# 5 -->
# 6 -->

In [ ]:
## Annotation Assignment:

# A --> 1, 2, 3
# B --> 1, 2, 4
# C --> 1, 5, 6
# D --> 2, 5, 6
# E --> 3, 4, 5
# F --> 3, 4, 6