In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
# assuming the data is located in the same directory as the notebook and the `Morphology_and_Readability.zip` file has been extracted

In [3]:
metadata = pd.read_excel('BAREC-10M/Data/Metadata.xlsx')
metadata.head()

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?
0,BAREC_1001_introduction_1_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,73,6,Yes
1,BAREC_1001_introduction_2_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,730,73,No
2,BAREC_1001_introduction_3_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,397,47,Yes
3,BAREC_1001_introduction_4_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,237,23,Yes
4,BAREC_1001_introduction_5_001,1001,Arabian Nights,Introduction,#,Arts & Humanities,Specialized Text,Literature; Art & Music,659,62,No

In [4]:
metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 20535 entries, 0 to 20534
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Document          20535 non-null  str
 1   Directory         20535 non-null  object
 2   Source            20535 non-null  str
 3   Book              20535 non-null  object
 4   Author            20535 non-null  str
 5   Domain            20535 non-null  str
 6   Readership Group  20535 non-null  str
 7   Text Category     20535 non-null  str
 8   Word Count        20535 non-null  int64
 9   Sentence Count    20535 non-null  int64
 10  In BAREC Corpus?  20535 non-null  str
dtypes: int64(2), object(2), str(7)
memory usage: 1.7+ MB

In [5]:
metadata['Document'].nunique()

20535

In [6]:
list(metadata['Source'].unique())

['Arabian Nights',
 'Arabic Learner Corpus (ALC)',
 'ANERCorp',
 'Arabic Poem Comprehensive Dataset (APCD)',
 'Akhbarona News',
 'AlArabiya News',
 'AlKhaleej News',
 'National Anthems',
 'Arab Youth Publisher',
 'ArabicMMLU',
 'Basic Travel Expressions Corpus (BTEC)',
 'Batman',
 'Emarati Curriculum',
 'DARES',
 'Green Library',
 'Hadith',
 'Hayy ibn Yaqdhan',
 'Hindawi',
 'Kalima',
 'Library of Arabic Literature',
 'Ladybird',
 'Lulu',
 'Constitutions',
 'Majarra',
 'Majed',
 'MedArabiQ',
 'New Testament',
 'Old Testament',
 'Hanging Odes',
 'Ofoq',
 'Other Minor Sources',
 'Quran',
 'ReadMe++',
 'Reading Corner',
 'Sara',
 'Spacetoon Songs',
 'Subtitles',
 'Superman',
 'The Five Adventurers',
 'Tunis Curriculum',
 'UN (United Nations)',
 'WikiNews',
 'Wikipedia',
 'Zayed Arabic-English Bilingual Undergraduate Corpus (ZAEBUC)',
 'chatGPT']

In [7]:
metadata['Book'].nunique(), np.random.choice(list(metadata['Book'].unique()), 10), metadata['Book'].value_counts()

(4682,
 array(['Love Under the Rain', 'The Heron Buys Shoes', 'Hajj in Islam',
        'The Bird', 'The Age of Mahler',
        'A Treasury of Virtues: Sayings, Sermons, and Teachings of ʿAlī',
        'The Three Questions', 'Overseas', '44652',
        'The Elite of the Age in the History and Portraits of Egypt’s Famous Men'],
       dtype='<U147'),
 Book
 Sports                       1010
 Culture                      1001
 Medical                      1000
 Tech                         1000
 Finance                       997
                              ...
 Prophet                         1
 The Theory of the Iceberg       1
 Nelson Mandela                  1
 Engineering                     1
 Volubilis                       1
 Name: count, Length: 4682, dtype: int64)

In [8]:
metadata['Author'].nunique(), np.random.choice(list(metadata['Author'].unique()), 10), metadata['Author'].value_counts()

(2597,
 array(['Myron Olberg', 'M. E. Finley', 'Ibn Hashisha Al-Maqdisi',
        'Al-Nabigha al-Shibani', 'Abu Al-Ayoun Al-Antaki', 'Fouad Zakaria',
        "Imru' al-Qais al-Zuhri", 'Jane Potter', 'Alqama Al-Fahl',
        'Edmund Bacon'], dtype='<U90'),
 Author
 #                              15227
 Mahmoud Salem                    337
 Kamel Kilani                     123
 Abbas Mahmoud Al-Aqqad            88
 Rafeef Reda Saidawi               59
                                ...
 Talal Ma’alla                      1
 Al-Habib Istani Zain Al-Din        1
 Hashim Qasim                       1
 Suleiman Al-Issa                   1
 UN (United Nations)                1
 Name: count, Length: 2597, dtype: int64)

In [9]:
metadata['Domain'].value_counts()

Domain
Arts & Humanities    10342
STEM                  5444
Social Sciences       4749
Name: count, dtype: int64

In [10]:
metadata['Readership Group'].value_counts()

Readership Group
Advanced Text        9165
Specialized Text     8884
Foundational Text    2486
Name: count, dtype: int64

In [11]:
metadata['Text Category'].value_counts()

Text Category
Media & Culture                                  7122
Educational Materials; Language & Linguistics    4709
Academic                                         4301
Literature; Art & Music                          3974
Religion & Philosophy                             254
Encyclopedic                                      175
Name: count, dtype: int64

In [12]:
metadata['Word Count'].describe()

count    20535.000000
mean       490.731385
std        262.089359
min          3.000000
25%        278.000000
50%        544.000000
75%        622.000000
max       5074.000000
Name: Word Count, dtype: float64

In [13]:
metadata['Sentence Count'].describe()

count    20535.000000
mean        25.073241
std         25.196396
min          1.000000
25%          8.000000
50%         17.000000
75%         33.000000
max        405.000000
Name: Sentence Count, dtype: float64

In [14]:
metadata['average sentence length'] = metadata['Word Count'] / metadata['Sentence Count']
metadata['average sentence length'].describe()

count    20535.000000
mean        31.768280
std         24.374336
min          1.666667
25%         14.820856
50%         27.260870
75%         39.904545
max       1107.000000
Name: average sentence length, dtype: float64

In [15]:
metadata['In BAREC Corpus?'].value_counts()

In BAREC Corpus?
No       18281
Yes       2031
ST2&3      223
Name: count, dtype: int64

In [16]:
for i, text_category in enumerate(metadata['Text Category'].unique()):
    corr_domain = list(metadata[metadata['Text Category'] == text_category]['Domain'].unique())
    print(f"{i+1}: {text_category}: {corr_domain}")

1: Literature; Art & Music: ['Arts & Humanities']
2: Educational Materials; Language & Linguistics: ['Arts & Humanities', 'Social Sciences', 'STEM']
3: Media & Culture: ['Arts & Humanities', 'Social Sciences', 'STEM']
4: Religion & Philosophy: ['Arts & Humanities']
5: Academic: ['Social Sciences', 'STEM', 'Arts & Humanities']
6: Encyclopedic: ['Social Sciences', 'STEM', 'Arts & Humanities']

In [17]:
for i, text_category in enumerate(metadata['Text Category'].unique()):
    corr_readership = list(metadata[metadata['Text Category'] == text_category]['Readership Group'].unique())
    print(f"{i+1}: {text_category}: {corr_readership}")

1: Literature; Art & Music: ['Specialized Text', 'Foundational Text', 'Advanced Text']
2: Educational Materials; Language & Linguistics: ['Advanced Text', 'Foundational Text', 'Specialized Text']
3: Media & Culture: ['Advanced Text', 'Foundational Text']
4: Religion & Philosophy: ['Specialized Text']
5: Academic: ['Specialized Text', 'Foundational Text', 'Advanced Text']
6: Encyclopedic: ['Advanced Text']

In [18]:
# A --> 1, 2, 3
# B --> 1, 2, 4
# C --> 1, 5, 6
# D --> 2, 5, 6
# E --> 3, 4, 5
# F --> 3, 4, 6

In [19]:
LAM_df = metadata[metadata['Text Category']=='Literature; Art & Music']
print("Literature; Art & Music")
print("==========================")
print(f"Number of documents: {LAM_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {LAM_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {LAM_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {LAM_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{LAM_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Readership Group distribution:\n{LAM_df['Readership Group'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{LAM_df['average sentence length'].describe().to_dict()}")
print("==========================")

Literature; Art & Music
==========================
Number of documents: 3974
--------------------------
Number of sentences: 148343
--------------------------
Number of unique books: 2858
--------------------------
Number of unique authors: 1681
--------------------------
Domain distribution:
{'Arts & Humanities': 3974}
--------------------------
Readership Group distribution:
{'Specialized Text': 2286, 'Foundational Text': 1281, 'Advanced Text': 407}
--------------------------
Average sentence length distribution:
{'count': 3974.0, 'mean': 16.17055897763152, 'std': 11.658903148591186, 'min': 2.526315789473684, '25%': 9.317993557294063, '50%': 12.6, '75%': 19.884615384615383, 'max': 221.33333333333334}
==========================

In [20]:
LAM_foundational_df = LAM_df[LAM_df['Readership Group']=='Foundational Text']
print("Literature; Art & Music - Foundational")
print("==========================")
print(f"Number of documents: {LAM_foundational_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {LAM_foundational_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {LAM_foundational_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {LAM_foundational_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{LAM_foundational_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{LAM_foundational_df['average sentence length'].describe().to_dict()}")
print("==========================")

Literature; Art & Music - Foundational
==========================
Number of documents: 1281
--------------------------
Number of sentences: 58143
--------------------------
Number of unique books: 1009
--------------------------
Number of unique authors: 32
--------------------------
Domain distribution:
{'Arts & Humanities': 1281}
--------------------------
Average sentence length distribution:
{'count': 1281.0, 'mean': 13.908297148843703, 'std': 6.7821186229810015, 'min': 2.652173913043478, '25%': 8.620689655172415, '50%': 13.263157894736842, '75%': 17.609756097560975, 'max': 56.111111111111114}
==========================

In [21]:
sampled_LAM_foundational_df = LAM_foundational_df.sample(17, random_state=42)

In [22]:
sampled_LAM_foundational_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,average sentence length
20002,BAREC_TheFiveAdventurers_149 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 149,#,Arts & Humanities,Foundational Text,Literature; Art & Music,698,54,No,12.925926
15247,BAREC_Hindawi_97962586_001,Hindawi,Hindawi,Baba Abdullah and the Dervish,Kamel Kilani,Arts & Humanities,Foundational Text,Literature; Art & Music,505,39,No,12.948718
19981,BAREC_TheFiveAdventurers_128 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 128,#,Arts & Humanities,Foundational Text,Literature; Art & Music,691,44,No,15.704545
15889,BAREC_Ladybird_القدر السحرية_001,Ladybird,Ladybird,The Magic Pot,#,Arts & Humanities,Foundational Text,Literature; Art & Music,630,56,No,11.250000
14792,BAREC_Hindawi_83941583_001,Hindawi,Hindawi,The Poplar Forest,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,530,22,No,24.090909
19686,BAREC_SpacetoonSong_أنا وأخي_001,SpacetoonSong,Spacetoon Songs,Me and My Brother,#,Arts & Humanities,Foundational Text,Literature; Art & Music,52,13,Yes,4.000000
12666,BAREC_Hindawi_17290296_001,Hindawi,Hindawi,Information War,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,500,23,No,21.739130
19823,BAREC_Superman_070_011,Superman,Superman,Edition: 70,#,Arts & Humanities,Foundational Text,Literature; Art & Music,349,43,No,8.116279
12837,BAREC_Hindawi_24146069_001,Hindawi,Hindawi,The Adventure of the Missing Rugby Player,Arthur Conan Doyle,Arts & Humanities,Foundational Text,Literature; Art & Music,518,37,No,14.000000
19930,BAREC_TheFiveAdventurers_077 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 077,#,Arts & Humanities,Foundational Text,Literature; Art & Music,731,68,No,10.750000
19853,BAREC_Superman_100_010,Superman,Superman,Edition: 100,#,Arts & Humanities,Foundational Text,Literature; Art & Music,593,76,No,7.802632
12664,BAREC_Hindawi_17271461_001,Hindawi,Hindawi,The Last of the Mohicans,James Fenimore Cooper,Arts & Humanities,Foundational Text,Literature; Art & Music,653,51,Yes,12.803922
7760,BAREC_ArabYouthPublisher_مالك الحزين يشتري حذا...,ArabYouthPublisher,Arab Youth Publisher,The Heron Buys Shoes,#,Arts & Humanities,Foundational Text,Literature; Art & Music,280,22,No,12.727273
7739,BAREC_ArabYouthPublisher_جزيرة الضياع_001,ArabYouthPublisher,Arab Youth Publisher,The Island of Loss,#,Arts & Humanities,Foundational Text,Literature; Art & Music,490,25,No,19.600000
19783,BAREC_Superman_040_010,Superman,Superman,Edition: 40,#,Arts & Humanities,Foundational Text,Literature; Art & Music,598,61,No,9.803279
19986,BAREC_TheFiveAdventurers_133 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 133,#,Arts & Humanities,Foundational Text,Literature; Art & Music,662,53,No,12.490566
19738,BAREC_Superman_010_011,Superman,Superman,Edition: 10,#,Arts & Humanities,Foundational Text,Literature; Art & Music,594,69,No,8.608696

In [23]:
sampled_LAM_foundational_sentences_indices = []
for i, row in sampled_LAM_foundational_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_LAM_foundational_sentences_indices.append(sampled_index)
print(sampled_LAM_foundational_sentences_indices)

[45, 10, 20, 49, 1, 10, 1, 16, 21, 27, 66, 28, 3, 4, 54, 33, 60]

In [24]:
sampled_LAM_foundational_df['sampled_sentence_index'] = sampled_LAM_foundational_sentences_indices

In [25]:
LAM_advanced_df = LAM_df[LAM_df['Readership Group']=='Advanced Text']
print("Literature; Art & Music - Advanced")
print("==========================")
print(f"Number of documents: {LAM_advanced_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {LAM_advanced_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {LAM_advanced_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {LAM_advanced_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{LAM_advanced_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{LAM_advanced_df['average sentence length'].describe().to_dict()}")
print("==========================")

Literature; Art & Music - Advanced
==========================
Number of documents: 407
--------------------------
Number of sentences: 13216
--------------------------
Number of unique books: 390
--------------------------
Number of unique authors: 107
--------------------------
Domain distribution:
{'Arts & Humanities': 407}
--------------------------
Average sentence length distribution:
{'count': 407.0, 'mean': 20.54016798418344, 'std': 11.93829403319979, 'min': 4.239316239316239, '25%': 13.561561561561561, '50%': 17.857142857142858, '75%': 24.11904761904762, 'max': 128.25}
==========================

In [26]:
sampled_LAM_advanced_df = LAM_advanced_df.sample(16, random_state=42)

In [27]:
sampled_LAM_advanced_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,average sentence length
13033,BAREC_Hindawi_28648582_001,Hindawi,Hindawi,Ragnarok,Antonia Susan Byatt,Arts & Humanities,Advanced Text,Literature; Art & Music,1366,82,Yes,16.658537
14107,BAREC_Hindawi_62505363_001,Hindawi,Hindawi,Steps in the Same River,Riyadh Hammadi,Arts & Humanities,Advanced Text,Literature; Art & Music,505,81,No,6.234568
14368,BAREC_Hindawi_71693707_001,Hindawi,Hindawi,Cases of John Thorndike,R. Austin Freeman,Arts & Humanities,Advanced Text,Literature; Art & Music,501,23,No,21.782609
12727,BAREC_Hindawi_18686373_001,Hindawi,Hindawi,The Gentle Strongman,Naguib Mahfouz,Arts & Humanities,Advanced Text,Literature; Art & Music,502,27,No,18.592593
12795,BAREC_Hindawi_20429368_001,Hindawi,Hindawi,The Younger Brother,Corey Ductoro,Arts & Humanities,Advanced Text,Literature; Art & Music,887,46,Yes,19.282609
13064,BAREC_Hindawi_29392697_001,Hindawi,Hindawi,The Virtuous Successor,Wadi’ Abu Fadil,Arts & Humanities,Advanced Text,Literature; Art & Music,544,18,No,30.222222
13515,BAREC_Hindawi_42475809_001,Hindawi,Hindawi,The Mystery of the Lost Necklace,Jack Footrell,Arts & Humanities,Advanced Text,Literature; Art & Music,516,23,No,22.434783
14867,BAREC_Hindawi_85802403_001,Hindawi,Hindawi,The Thief and the Dogs,Naguib Mahfouz,Arts & Humanities,Advanced Text,Literature; Art & Music,524,26,No,20.153846
14287,BAREC_Hindawi_69407460_001,Hindawi,Hindawi,The Heart of a Woman,Ponson du Terrail,Arts & Humanities,Advanced Text,Literature; Art & Music,544,26,No,20.923077
14412,BAREC_Hindawi_72735281_001,Hindawi,Hindawi,The Earth Gods,Gibran Khalil Gibran,Arts & Humanities,Advanced Text,Literature; Art & Music,503,61,No,8.245902
15102,BAREC_Hindawi_94264040_001,Hindawi,Hindawi,The Big Portrait Mystery and Other Stories,R. Austin Freeman,Arts & Humanities,Advanced Text,Literature; Art & Music,517,43,No,12.023256
13066,BAREC_Hindawi_29403629_001,Hindawi,Hindawi,I Am the Sultan of the Law of Existence,Yusuf Idris,Arts & Humanities,Advanced Text,Literature; Art & Music,740,46,Yes,16.086957
14492,BAREC_Hindawi_74859409_001,Hindawi,Hindawi,The Amazing Visit,Herbert George Wells,Arts & Humanities,Advanced Text,Literature; Art & Music,629,39,Yes,16.128205
19437,BAREC_Other_الكشكول_001,Other,Other Minor Sources,al-Kashkuul,Bayan Safadi,Arts & Humanities,Advanced Text,Literature; Art & Music,287,15,Yes,19.133333
13648,BAREC_Hindawi_48293606_001,Hindawi,Hindawi,The Specter of the Soul,Edward Page Mitchell,Arts & Humanities,Advanced Text,Literature; Art & Music,500,26,No,19.230769
13846,BAREC_Hindawi_52951836_001,Hindawi,Hindawi,The Adventure of Sherlo Combs,Robert Barr,Arts & Humanities,Advanced Text,Literature; Art & Music,504,48,No,10.500000

In [28]:
sampled_LAM_advanced_sentences_indices = []
for i, row in sampled_LAM_advanced_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_LAM_advanced_sentences_indices.append(sampled_index)
print(sampled_LAM_advanced_sentences_indices)

[5, 46, 1, 1, 39, 12, 1, 1, 9, 16, 15, 21, 18, 9, 2, 20]

In [29]:
sampled_LAM_advanced_df['sampled_sentence_index'] = sampled_LAM_advanced_sentences_indices

In [30]:
LAM_specialized_df = LAM_df[LAM_df['Readership Group']=='Specialized Text']
print("Literature; Art & Music - Specialized")
print("==========================")
print(f"Number of documents: {LAM_specialized_df.shape[0]}")
print("--------------------------")
print(f"Number of sentences: {LAM_specialized_df['Sentence Count'].sum()}")
print("--------------------------")
print(f"Number of unique books: {LAM_specialized_df['Book'].nunique()}")
print("--------------------------")
print(f"Number of unique authors: {LAM_specialized_df['Author'].nunique()}")
print("--------------------------")
print(f"Domain distribution:\n{LAM_specialized_df['Domain'].value_counts().to_dict()}")
print("--------------------------")
print(f"Average sentence length distribution:\n{LAM_specialized_df['average sentence length'].describe().to_dict()}")
print("==========================")

Literature; Art & Music - Specialized
==========================
Number of documents: 2286
--------------------------
Number of sentences: 76984
--------------------------
Number of unique books: 1464
--------------------------
Number of unique authors: 1568
--------------------------
Domain distribution:
{'Arts & Humanities': 2286}
--------------------------
Average sentence length distribution:
{'count': 2286.0, 'mean': 16.660290621118204, 'std': 13.36958423325814, 'min': 2.526315789473684, '25%': 9.314814814814815, '50%': 10.666666666666666, '75%': 20.962222222222223, 'max': 221.33333333333334}
==========================

In [31]:
sampled_LAM_specialized_df = LAM_specialized_df.sample(17, random_state=42)

In [32]:
sampled_LAM_specialized_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,average sentence length
13887,BAREC_Hindawi_53957515_001,Hindawi,Hindawi,Gardens and Satan,Nawal El-Saadawi,Arts & Humanities,Specialized Text,Literature; Art & Music,505,26,No,19.423077
12902,BAREC_Hindawi_25817168_001,Hindawi,Hindawi,Letters of Holy Ankara,Qudriya Hussein,Arts & Humanities,Specialized Text,Literature; Art & Music,523,20,No,26.150000
13898,BAREC_Hindawi_57097372_001,Hindawi,Hindawi,Breezes,Salma Saigh,Arts & Humanities,Specialized Text,Literature; Art & Music,506,32,No,15.812500
1077,BAREC_APCD_علي بن أبي طالب_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Ali ibn Abi Talib,Arts & Humanities,Specialized Text,Literature; Art & Music,501,52,No,9.634615
15676,BAREC_Kalima_عدو_001,Kalima,Kalima,Running,Jean Echenoz,Arts & Humanities,Specialized Text,Literature; Art & Music,687,47,Yes,14.617021
808,BAREC_APCD_جرجس عيسى السكاف_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Jurjis Isa al-Sakkaf,Arts & Humanities,Specialized Text,Literature; Art & Music,503,61,No,8.245902
975,BAREC_APCD_شيخ الدولة البركردزي_شيخ الدولة الب...,APCD,Arabic Poem Comprehensive Dataset (APCD),Shaykh Al-Dawla Al-Barkardzi,Shaykh Al-Dawla Al-Barkardzi,Arts & Humanities,Specialized Text,Literature; Art & Music,38,4,No,9.500000
15692,BAREC_Kalima_غوته_ونابليون_001,Kalima,Kalima,Goethe and Napoleon: A Historical Encounter,Gustave Seibt,Arts & Humanities,Specialized Text,Literature; Art & Music,729,35,No,20.828571
15280,BAREC_Kalima_الاسلام_الايطالي_001,Kalima,Kalima,Italian Islam: A Journey Through the Realities...,Stefano Alievi,Arts & Humanities,Specialized Text,Literature; Art & Music,748,31,No,24.129032
14933,BAREC_Hindawi_86952059_001,Hindawi,Hindawi,My Diaries in Women’s Prison,Nawal El-Saadawi,Arts & Humanities,Specialized Text,Literature; Art & Music,526,16,No,32.875000
643,BAREC_APCD_أبو جعفر الزوزني الزاهد_أبو جعفر ...,APCD,Arabic Poem Comprehensive Dataset (APCD),Abu Ja'far Al-Zuzani Al-Zahid,Abu Ja'far Al-Zuzani Al-Zahid,Arts & Humanities,Specialized Text,Literature; Art & Music,16,2,No,8.000000
14160,BAREC_Hindawi_63795362_001,Hindawi,Hindawi,Complete Works,Poet of the Nile Muhammad Hafiz Ibrahim,Arts & Humanities,Specialized Text,Literature; Art & Music,504,85,No,5.929412
13432,BAREC_Hindawi_40702826_001,Hindawi,Hindawi,Roland Barthes,Jonathan Koller,Arts & Humanities,Specialized Text,Literature; Art & Music,513,23,No,22.304348
448,BAREC_APCD_الحبسي_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Al-Habsi,Arts & Humanities,Specialized Text,Literature; Art & Music,507,62,No,8.177419
627,BAREC_APCD_أبو المواهب المعري_أبو المواهب ال...,APCD,Arabic Poem Comprehensive Dataset (APCD),Abu Al-Mawahib Al-Ma'arri,Abu Al-Mawahib Al-Ma'arri,Arts & Humanities,Specialized Text,Literature; Art & Music,52,5,No,10.400000
13756,BAREC_Hindawi_50926304_001,Hindawi,Hindawi,Letters of the Orators,Mohamed Kurd Ali,Arts & Humanities,Specialized Text,Literature; Art & Music,521,21,No,24.809524
15642,BAREC_Kalima_شعراء_القرن_16_بيير_دو_رونسار_001,Kalima,Kalima,Sixteenth Century Poets (3),Pierre de Ronsard,Arts & Humanities,Specialized Text,Literature; Art & Music,686,47,No,14.595745

In [33]:
sampled_LAM_specialized_sentences_indices = []
for i, row in sampled_LAM_specialized_df.iterrows():
    directory = row['Directory']
    document = row['Document']
    annotations_file_path = f"BAREC-10M/Data/Morphology_and_Readability/{directory}/{document}.json"

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
        annotations = pd.DataFrame(annotations)
    

    sampled_index = annotations[annotations['sents_word_count'] > 5].sample(1, random_state=42).index.item()
    sampled_LAM_specialized_sentences_indices.append(sampled_index)
print(sampled_LAM_specialized_sentences_indices)

[9, 1, 11, 19, 30, 0, 1, 15, 5, 11, 1, 22, 1, 0, 1, 2, 27]

In [34]:
sampled_LAM_specialized_df['sampled_sentence_index'] = sampled_LAM_specialized_sentences_indices

In [35]:
A_df = pd.concat([sampled_LAM_foundational_df, sampled_LAM_advanced_df, sampled_LAM_specialized_df], ignore_index=True)
A_df

,Document,Directory,Source,Book,Author,Domain,Readership Group,Text Category,Word Count,Sentence Count,In BAREC Corpus?,average sentence length,sampled_sentence_index
0,BAREC_TheFiveAdventurers_149 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 149,#,Arts & Humanities,Foundational Text,Literature; Art & Music,698,54,No,12.925926,45
1,BAREC_Hindawi_97962586_001,Hindawi,Hindawi,Baba Abdullah and the Dervish,Kamel Kilani,Arts & Humanities,Foundational Text,Literature; Art & Music,505,39,No,12.948718,10
2,BAREC_TheFiveAdventurers_128 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 128,#,Arts & Humanities,Foundational Text,Literature; Art & Music,691,44,No,15.704545,20
3,BAREC_Ladybird_القدر السحرية_001,Ladybird,Ladybird,The Magic Pot,#,Arts & Humanities,Foundational Text,Literature; Art & Music,630,56,No,11.250000,49
4,BAREC_Hindawi_83941583_001,Hindawi,Hindawi,The Poplar Forest,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,530,22,No,24.090909,1
5,BAREC_SpacetoonSong_أنا وأخي_001,SpacetoonSong,Spacetoon Songs,Me and My Brother,#,Arts & Humanities,Foundational Text,Literature; Art & Music,52,13,Yes,4.000000,10
6,BAREC_Hindawi_17290296_001,Hindawi,Hindawi,Information War,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,500,23,No,21.739130,1
7,BAREC_Superman_070_011,Superman,Superman,Edition: 70,#,Arts & Humanities,Foundational Text,Literature; Art & Music,349,43,No,8.116279,16
8,BAREC_Hindawi_24146069_001,Hindawi,Hindawi,The Adventure of the Missing Rugby Player,Arthur Conan Doyle,Arts & Humanities,Foundational Text,Literature; Art & Music,518,37,No,14.000000,21
9,BAREC_TheFiveAdventurers_077 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 077,#,Arts & Humanities,Foundational Text,Literature; Art & Music,731,68,No,10.750000,27
10,BAREC_Superman_100_010,Superman,Superman,Edition: 100,#,Arts & Humanities,Foundational Text,Literature; Art & Music,593,76,No,7.802632,66
11,BAREC_Hindawi_17271461_001,Hindawi,Hindawi,The Last of the Mohicans,James Fenimore Cooper,Arts & Humanities,Foundational Text,Literature; Art & Music,653,51,Yes,12.803922,28
12,BAREC_ArabYouthPublisher_مالك الحزين يشتري حذا...,ArabYouthPublisher,Arab Youth Publisher,The Heron Buys Shoes,#,Arts & Humanities,Foundational Text,Literature; Art & Music,280,22,No,12.727273,3
13,BAREC_ArabYouthPublisher_جزيرة الضياع_001,ArabYouthPublisher,Arab Youth Publisher,The Island of Loss,#,Arts & Humanities,Foundational Text,Literature; Art & Music,490,25,No,19.600000,4
14,BAREC_Superman_040_010,Superman,Superman,Edition: 40,#,Arts & Humanities,Foundational Text,Literature; Art & Music,598,61,No,9.803279,54
15,BAREC_TheFiveAdventurers_133 لغز_001,TheFiveAdventurers,The Five Adventurers,Riddle: 133,#,Arts & Humanities,Foundational Text,Literature; Art & Music,662,53,No,12.490566,33
16,BAREC_Superman_010_011,Superman,Superman,Edition: 10,#,Arts & Humanities,Foundational Text,Literature; Art & Music,594,69,No,8.608696,60
17,BAREC_Hindawi_28648582_001,Hindawi,Hindawi,Ragnarok,Antonia Susan Byatt,Arts & Humanities,Advanced Text,Literature; Art & Music,1366,82,Yes,16.658537,5
18,BAREC_Hindawi_62505363_001,Hindawi,Hindawi,Steps in the Same River,Riyadh Hammadi,Arts & Humanities,Advanced Text,Literature; Art & Music,505,81,No,6.234568,46
19,BAREC_Hindawi_71693707_001,Hindawi,Hindawi,Cases of John Thorndike,R. Austin Freeman,Arts & Humanities,Advanced Text,Literature; Art & Music,501,23,No,21.782609,1
20,BAREC_Hindawi_18686373_001,Hindawi,Hindawi,The Gentle Strongman,Naguib Mahfouz,Arts & Humanities,Advanced Text,Literature; Art & Music,502,27,No,18.592593,1
21,BAREC_Hindawi_20429368_001,Hindawi,Hindawi,The Younger Brother,Corey Ductoro,Arts & Humanities,Advanced Text,Literature; Art & Music,887,46,Yes,19.282609,39
22,BAREC_Hindawi_29392697_001,Hindawi,Hindawi,The Virtuous Successor,Wadi’ Abu Fadil,Arts & Humanities,Advanced Text,Literature; Art & Music,544,18,No,30.222222,12
23,BAREC_Hindawi_42475809_001,Hindawi,Hindawi,The Mystery of the Lost Necklace,Jack Footrell,Arts & Humanities,Advanced Text,Literature; Art & Music,516,23,No,22.434783,1
24,BAREC_Hindawi_85802403_001,Hindawi,Hindawi,The Thief and the Dogs,Naguib Mahfouz,Arts & Humanities,Advanced Text,Literature; Art & Music,524,26,No,20.153846,1
25,BAREC_Hindawi_69407460_001,Hindawi,Hindawi,The Heart of a Woman,Ponson du Terrail,Arts & Humanities,Advanced Text,Literature; Art & Music,544,26,No,20.923077,9
26,BAREC_Hindawi_72735281_001,Hindawi,Hindawi,The Earth Gods,Gibran Khalil Gibran,Arts & Humanities,Advanced Text,Literature; Art & Music,503,61,No,8.245902,16
27,BAREC_Hindawi_94264040_001,Hindawi,Hindawi,The Big Portrait Mystery and Other Stories,R. Austin Freeman,Arts & Humanities,Advanced Text,Literature; Art & Music,517,43,No,12.023256,15
28,BAREC_Hindawi_29403629_001,Hindawi,Hindawi,I Am the Sultan of the Law of Existence,Yusuf Idris,Arts & Humanities,Advanced Text,Literature; Art & Music,740,46,Yes,16.086957,21
29,BAREC_Hindawi_74859409_001,Hindawi,Hindawi,The Amazing Visit,Herbert George Wells,Arts & Humanities,Advanced Text,Literature; Art & Music,629,39,Yes,16.128205,18
30,BAREC_Other_الكشكول_001,Other,Other Minor Sources,al-Kashkuul,Bayan Safadi,Arts & Humanities,Advanced Text,Literature; Art & Music,287,15,Yes,19.133333,9
31,BAREC_Hindawi_48293606_001,Hindawi,Hindawi,The Specter of the Soul,Edward Page Mitchell,Arts & Humanities,Advanced Text,Literature; Art & Music,500,26,No,19.230769,2
32,BAREC_Hindawi_52951836_001,Hindawi,Hindawi,The Adventure of Sherlo Combs,Robert Barr,Arts & Humanities,Advanced Text,Literature; Art & Music,504,48,No,10.500000,20
33,BAREC_Hindawi_53957515_001,Hindawi,Hindawi,Gardens and Satan,Nawal El-Saadawi,Arts & Humanities,Specialized Text,Literature; Art & Music,505,26,No,19.423077,9
34,BAREC_Hindawi_25817168_001,Hindawi,Hindawi,Letters of Holy Ankara,Qudriya Hussein,Arts & Humanities,Specialized Text,Literature; Art & Music,523,20,No,26.150000,1
35,BAREC_Hindawi_57097372_001,Hindawi,Hindawi,Breezes,Salma Saigh,Arts & Humanities,Specialized Text,Literature; Art & Music,506,32,No,15.812500,11
36,BAREC_APCD_علي بن أبي طالب_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Ali ibn Abi Talib,Arts & Humanities,Specialized Text,Literature; Art & Music,501,52,No,9.634615,19
37,BAREC_Kalima_عدو_001,Kalima,Kalima,Running,Jean Echenoz,Arts & Humanities,Specialized Text,Literature; Art & Music,687,47,Yes,14.617021,30
38,BAREC_APCD_جرجس عيسى السكاف_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Jurjis Isa al-Sakkaf,Arts & Humanities,Specialized Text,Literature; Art & Music,503,61,No,8.245902,0
39,BAREC_APCD_شيخ الدولة البركردزي_شيخ الدولة الب...,APCD,Arabic Poem Comprehensive Dataset (APCD),Shaykh Al-Dawla Al-Barkardzi,Shaykh Al-Dawla Al-Barkardzi,Arts & Humanities,Specialized Text,Literature; Art & Music,38,4,No,9.500000,1
40,BAREC_Kalima_غوته_ونابليون_001,Kalima,Kalima,Goethe and Napoleon: A Historical Encounter,Gustave Seibt,Arts & Humanities,Specialized Text,Literature; Art & Music,729,35,No,20.828571,15
41,BAREC_Kalima_الاسلام_الايطالي_001,Kalima,Kalima,Italian Islam: A Journey Through the Realities...,Stefano Alievi,Arts & Humanities,Specialized Text,Literature; Art & Music,748,31,No,24.129032,5
42,BAREC_Hindawi_86952059_001,Hindawi,Hindawi,My Diaries in Women’s Prison,Nawal El-Saadawi,Arts & Humanities,Specialized Text,Literature; Art & Music,526,16,No,32.875000,11
43,BAREC_APCD_أبو جعفر الزوزني الزاهد_أبو جعفر ...,APCD,Arabic Poem Comprehensive Dataset (APCD),Abu Ja'far Al-Zuzani Al-Zahid,Abu Ja'far Al-Zuzani Al-Zahid,Arts & Humanities,Specialized Text,Literature; Art & Music,16,2,No,8.000000,1
44,BAREC_Hindawi_63795362_001,Hindawi,Hindawi,Complete Works,Poet of the Nile Muhammad Hafiz Ibrahim,Arts & Humanities,Specialized Text,Literature; Art & Music,504,85,No,5.929412,22
45,BAREC_Hindawi_40702826_001,Hindawi,Hindawi,Roland Barthes,Jonathan Koller,Arts & Humanities,Specialized Text,Literature; Art & Music,513,23,No,22.304348,1
46,BAREC_APCD_الحبسي_الديوان الرئيسي_001,APCD,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Al-Habsi,Arts & Humanities,Specialized Text,Literature; Art & Music,507,62,No,8.177419,0
47,BAREC_APCD_أبو المواهب المعري_أبو المواهب ال...,APCD,Arabic Poem Comprehensive Dataset (APCD),Abu Al-Mawahib Al-Ma'arri,Abu Al-Mawahib Al-Ma'arri,Arts & Humanities,Specialized Text,Literature; Art & Music,52,5,No,10.400000,1
48,BAREC_Hindawi_50926304_001,Hindawi,Hindawi,Letters of the Orators,Mohamed Kurd Ali,Arts & Humanities,Specialized Text,Literature; Art & Music,521,21,No,24.809524,2
49,BAREC_Kalima_شعراء_القرن_16_بيير_دو_رونسار_001,Kalima,Kalima,Sixteenth Century Poets (3),Pierre de Ronsard,Arts & Humanities,Specialized Text,Literature; Art & Music,686,47,No,14.595745,27

In [36]:
A_df['selected_sent_raw'] = None
A_df['selected_sent_word_count'] = None
A_df['selected_sent_words'] = None

for i, row in A_df.iterrows():
    directory = row['Directory']
    document = row['Document']

    annotations_file_path = (
        f"BAREC-10M/Data/Morphology_and_Readability/"
        f"{directory}/{document}.json"
    )

    with open(annotations_file_path, 'r', encoding='utf-8') as f:
        annotations = json.load(f)

    annotations = pd.DataFrame(annotations)

    selected_sentence_index = int(row['sampled_sentence_index'])

    selected_row = annotations.iloc[selected_sentence_index]

    raw_sentence = selected_row['raw_sents']
    word_count = selected_row['sents_word_count']
    words = selected_row['word']   # list of strings

    A_df.at[i, 'selected_sent_raw'] = raw_sentence
    A_df.at[i, 'selected_sent_word_count'] = word_count
    A_df.at[i, 'selected_sent_words'] = words

In [37]:
A_df = A_df[[
    'Directory',
    'Document',
    'sampled_sentence_index',
    'Source',
    'Book',
    'Author',
    'Domain',
    'Readership Group',
    'Text Category',
    'average sentence length',
    'selected_sent_raw',
    'selected_sent_word_count',
    'selected_sent_words'
]]

In [38]:
A_df.rename(columns={
    'average sentence length': 'average_sentence_length_per_doc',
}, inplace=True)

In [39]:
A_df

,Directory,Document,sampled_sentence_index,Source,Book,Author,Domain,Readership Group,Text Category,average_sentence_length_per_doc,selected_sent_raw,selected_sent_word_count,selected_sent_words
0,TheFiveAdventurers,BAREC_TheFiveAdventurers_149 لغز_001,45,The Five Adventurers,Riddle: 149,#,Arts & Humanities,Foundational Text,Literature; Art & Music,12.925926,"وسوف أبدؤها بزيارة أخي ""طلعت""..",9,"[وسوف, أبدؤها, بزيارة, أخي, "", طلعت, "", ., .]"
1,Hindawi,BAREC_Hindawi_97962586_001,10,Hindawi,Baba Abdullah and the Dervish,Kamel Kilani,Arts & Humanities,Foundational Text,Literature; Art & Music,12.948718,وَبَيْنا كانَ عَائِدًا وَجَدَ — فِي طَرِيقِهِ ...,11,"[وبينا, كان, عائدا, وجد, -, في, طريقه, -, مكان..."
2,TheFiveAdventurers,BAREC_TheFiveAdventurers_128 لغز_001,20,The Five Adventurers,Riddle: 128,#,Arts & Humanities,Foundational Text,Literature; Art & Music,15.704545,"أجاب ""ممدوح"" وهو يجري مبتعدًا: ليس عندي وقت لم...",20,"[أجاب, "", ممدوح, "", وهو, يجري, مبتعدا, :, ليس,..."
3,Ladybird,BAREC_Ladybird_القدر السحرية_001,49,Ladybird,The Magic Pot,#,Arts & Humanities,Foundational Text,Literature; Art & Music,11.250000,أما القدر الصغيرة فإنها واصلت طبخ المهلبية طبخ...,10,"[أما, القدر, الصغيرة, فإنها, واصلت, طبخ, المهل..."
4,Hindawi,BAREC_Hindawi_83941583_001,1,Hindawi,The Poplar Forest,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,24.090909,رقم «١»: «أحمد» من مصر.,11,"[رقم, "", ١, "", :, "", أحمد, "", من, مصر, .]"
5,SpacetoonSong,BAREC_SpacetoonSong_أنا وأخي_001,10,Spacetoon Songs,Me and My Brother,#,Arts & Humanities,Foundational Text,Literature; Art & Music,4.000000,لو سرقت منا الأيام قلبا معطاء بسّام لن نستسلم ...,10,"[لو, سرقت, منا, الأيام, قلبا, معطاء, بسام, لن,..."
6,Hindawi,BAREC_Hindawi_17290296_001,1,Hindawi,Information War,Mahmoud Salem,Arts & Humanities,Foundational Text,Literature; Art & Music,21.739130,رقم «١»: «أحمد» من مصر.,11,"[رقم, "", ١, "", :, "", أحمد, "", من, مصر, .]"
7,Superman,BAREC_Superman_070_011,16,Superman,Edition: 70,#,Arts & Humanities,Foundational Text,Literature; Art & Music,8.116279,ما أسهل سرقة المصرف الآن...,8,"[ما, أسهل, سرقة, المصرف, الآن, ., ., .]"
8,Hindawi,BAREC_Hindawi_24146069_001,21,Hindawi,The Adventure of the Missing Rugby Player,Arthur Conan Doyle,Arts & Humanities,Foundational Text,Literature; Art & Music,14.000000,وقد تَجاوَزَ المدخل بِمَنْكِبَيْهِ العَريضَين،...,18,"[وقد, تجاوز, المدخل, بمنكبيه, العريضين, ,, ورا..."
9,TheFiveAdventurers,BAREC_TheFiveAdventurers_077 لغز_001,27,The Five Adventurers,Riddle: 077,#,Arts & Humanities,Foundational Text,Literature; Art & Music,10.750000,وأخذت السيدة العجوز تشير بيدها..,7,"[وأخذت, السيدة, العجوز, تشير, بيدها, ., .]"
10,Superman,BAREC_Superman_100_010,66,Superman,Edition: 100,#,Arts & Humanities,Foundational Text,Literature; Art & Music,7.802632,"فتح ""سوبرمان"" خزانة خفية...",9,"[فتح, "", سوبرمان, "", خزانة, خفية, ., ., .]"
11,Hindawi,BAREC_Hindawi_17271461_001,28,Hindawi,The Last of the Mohicans,James Fenimore Cooper,Arts & Humanities,Foundational Text,Literature; Art & Music,12.803922,ثم استدار إلى كورا وساعدها على امتطاء حصانها.,9,"[ثم, استدار, إلى, كورا, وساعدها, على, امتطاء, ..."
12,ArabYouthPublisher,BAREC_ArabYouthPublisher_مالك الحزين يشتري حذا...,3,Arab Youth Publisher,The Heron Buys Shoes,#,Arts & Humanities,Foundational Text,Literature; Art & Music,12.727273,"ذهب ""مالك الحزين"" مع زوجته إلى سوق الأحذية ليش...",16,"[ذهب, "", مالك, الحزين, "", مع, زوجته, إلى, سوق,..."
13,ArabYouthPublisher,BAREC_ArabYouthPublisher_جزيرة الضياع_001,4,Arab Youth Publisher,The Island of Loss,#,Arts & Humanities,Foundational Text,Literature; Art & Music,19.600000,تحطمت سفينة السائحين وغرقت في بحر الظلمات، واس...,24,"[تحطمت, سفينة, السائحين, وغرقت, في, بحر, الظلم..."
14,Superman,BAREC_Superman_040_010,54,Superman,Edition: 40,#,Arts & Humanities,Foundational Text,Literature; Art & Music,9.803279,"نجحت خطة ""الفتى الجبار"" ولفت المعطف نظر كلبه...",13,"[نجحت, خطة, "", الفتى, الجبار, "", ولفت, المعطف,..."
15,TheFiveAdventurers,BAREC_TheFiveAdventurers_133 لغز_001,33,The Five Adventurers,Riddle: 133,#,Arts & Humanities,Foundational Text,Literature; Art & Music,12.490566,وقد تردد أن الثري المصري على علاقة بهذا المهرب...,18,"[وقد, تردد, أن, الثري, المصري, على, علاقة, بهذ..."
16,Superman,BAREC_Superman_010_011,60,Superman,Edition: 10,#,Arts & Humanities,Foundational Text,Literature; Art & Music,8.608696,يجب أن أبعد هذا الصاروخ!,6,"[يجب, أن, أبعد, هذا, الصاروخ, !]"
17,Hindawi,BAREC_Hindawi_28648582_001,5,Hindawi,Ragnarok,Antonia Susan Byatt,Arts & Humanities,Advanced Text,Literature; Art & Music,16.658537,كانت الحياةُ عبارة عن حالة تدور فيها رحى حرب م...,11,"[كانت, الحياة, عبارة, عن, حالة, تدور, فيها, رح..."
18,Hindawi,BAREC_Hindawi_62505363_001,46,Hindawi,Steps in the Same River,Riyadh Hammadi,Arts & Humanities,Advanced Text,Literature; Art & Music,6.234568,تنافَسَ تجار الفنون على لوحة بيضاء،,7,"[تنافس, تجار, الفنون, على, لوحة, بيضاء, ,]"
19,Hindawi,BAREC_Hindawi_71693707_001,1,Hindawi,Cases of John Thorndike,R. Austin Freeman,Arts & Humanities,Advanced Text,Literature; Art & Music,21.782609,في اعتقادي أنه ليس هناك الكثير من الأماكن حتى ...,28,"[في, اعتقادي, أنه, ليس, هناك, الكثير, من, الأم..."
20,Hindawi,BAREC_Hindawi_18686373_001,1,Hindawi,The Gentle Strongman,Naguib Mahfouz,Arts & Humanities,Advanced Text,Literature; Art & Music,18.592593,جلس ينظر إلى صورته في المرآة الكبيرة، ويتابع ب...,35,"[جلس, ينظر, إلى, صورته, في, المرآة, الكبيرة, ,..."
21,Hindawi,BAREC_Hindawi_20429368_001,39,Hindawi,The Younger Brother,Corey Ductoro,Arts & Humanities,Advanced Text,Literature; Art & Music,19.282609,كان فريدريك بينسان — رقم الضمان الاجتماعي ٥٤٥-...,34,"[كان, فريدريك, بينسان, -, رقم, الضمان, الاجتما..."
22,Hindawi,BAREC_Hindawi_29392697_001,12,Hindawi,The Virtuous Successor,Wadi’ Abu Fadil,Arts & Humanities,Advanced Text,Literature; Art & Music,30.222222,حاشا للدين أنْ يكون كما تفعلون وإلَّا كان الكف...,13,"[حاشا, للدين, أن, يكون, كما, تفعلون, وإلا, كان..."
23,Hindawi,BAREC_Hindawi_42475809_001,1,Hindawi,The Mystery of the Lost Necklace,Jack Footrell,Arts & Humanities,Advanced Text,Literature; Art & Music,22.434783,في صباح اليوم التالي تلقَّى «مُحب» رسالة من «ت...,29,"[في, صباح, اليوم, التالي, تلقى, "", محب, "", رسا..."
24,Hindawi,BAREC_Hindawi_85802403_001,1,Hindawi,The Thief and the Dogs,Naguib Mahfouz,Arts & Humanities,Advanced Text,Literature; Art & Music,20.153846,نظر إلى الباب المفتوح، المفتوح دائمًا كما عهِد...,32,"[نظر, إلى, الباب, المفتوح, ,, المفتوح, دائما, ..."
25,Hindawi,BAREC_Hindawi_69407460_001,9,Hindawi,The Heart of a Woman,Ponson du Terrail,Arts & Humanities,Advanced Text,Literature; Art & Music,20.923077,وأريد بذلك أن ابنك ليس لك الآن، بل هو للبوليس ...,18,"[وأريد, بذلك, أن, ابنك, ليس, لك, الآن, ,, بل, ..."
26,Hindawi,BAREC_Hindawi_72735281_001,16,Hindawi,The Earth Gods,Gibran Khalil Gibran,Arts & Humanities,Advanced Text,Literature; Art & Music,8.245902,وهي ما أودُّ أن أتنشقَّه الآن وفي كل أوان.,10,"[وهي, ما, أود, أن, أتنشقه, الآن, وفي, كل, أوان..."
27,Hindawi,BAREC_Hindawi_94264040_001,15,Hindawi,The Big Portrait Mystery and Other Stories,R. Austin Freeman,Arts & Humanities,Advanced Text,Literature; Art & Music,12.023256,وقد مثلت هذه المشكلةُ موضعَ اهتمام عميق للسيد ...,36,"[وقد, مثلت, هذه, المشكلة, موضع, اهتمام, عميق, ..."
28,Hindawi,BAREC_Hindawi_29403629_001,21,Hindawi,I Am the Sultan of the Law of Existence,Yusuf Idris,Arts & Humanities,Advanced Text,Literature; Art & Music,16.086957,في هالة من فرقعة الأسواط والجئير الذي تضخِّمه ...,22,"[في, هالة, من, فرقعة, الأسواط, والجئير, الذي, ..."
29,Hindawi,BAREC_Hindawi_74859409_001,18,Hindawi,The Amazing Visit,Herbert George Wells,Arts & Humanities,Advanced Text,Literature; Art & Music,16.128205,ولا أعرف إن كان لهذا الوهج أو تلك الموسيقى صلة...,18,"[ولا, أعرف, إن, كان, لهذا, الوهج, أو, تلك, الم..."
30,Other,BAREC_Other_الكشكول_001,9,Other Minor Sources,al-Kashkuul,Bayan Safadi,Arts & Humanities,Advanced Text,Literature; Art & Music,19.133333,إن اختيار النصوص لا يعني تفضيلاً فنياً لها على...,27,"[إن, اختيار, النصوص, لا, يعني, تفضيلا, فنيا, ل..."
31,Hindawi,BAREC_Hindawi_48293606_001,2,Hindawi,The Specter of the Soul,Edward Page Mitchell,Arts & Humanities,Advanced Text,Literature; Art & Music,19.230769,آراء البروفيسور تيندال التي أثبتَتها بما لا يد...,19,"[آراء, البروفيسور, تيندال, التي, أثبتتها, بما,..."
32,Hindawi,BAREC_Hindawi_52951836_001,20,Hindawi,The Adventure of Sherlo Combs,Robert Barr,Arts & Humanities,Advanced Text,Literature; Art & Music,10.500000,«حيَّر لغز بيجرام حتى المُحقق جريجوري من شرطة ...,12,"["", حير, لغز, بيجرام, حتى, المحقق, جريجوري, من..."
33,Hindawi,BAREC_Hindawi_53957515_001,9,Hindawi,Gardens and Satan,Nawal El-Saadawi,Arts & Humanities,Specialized Text,Literature; Art & Music,19.423077,وجوههم يغطيها شعرٌ ذابل يتدلَّى فوق صدورهم.,8,"[وجوههم, يغطيها, شعر, ذابل, يتدلى, فوق, صدورهم..."
34,Hindawi,BAREC_Hindawi_25817168_001,1,Hindawi,Letters of Holy Ankara,Qudriya Hussein,Arts & Humanities,Specialized Text,Literature; Art & Music,26.150000,رأيت أبناء وطني توَّاقين إلى الاستقلال متعطشين...,22,"[رأيت, أبناء, وطني, تواقين, إلى, الاستقلال, مت..."
35,Hindawi,BAREC_Hindawi_57097372_001,11,Hindawi,Breezes,Salma Saigh,Arts & Humanities,Specialized Text,Literature; Art & Music,15.812500,يا لجمالك في الماء تشابهين الدُّمى والتماثيل، ...,23,"[يا, لجمالك, في, الماء, تشابهين, الدمى, والتما..."
36,APCD,BAREC_APCD_علي بن أبي طالب_الديوان الرئيسي_001,19,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Ali ibn Abi Talib,Arts & Humanities,Specialized Text,Literature; Art & Music,9.634615,إِذا أَنكَرتُ عَهداً مِن حَميمٍ فَفي نَفسي ...,9,"[إذا, أنكرت, عهدا, من, حميم, ففي, نفسي, التكرم..."
37,Kalima,BAREC_Kalima_عدو_001,30,Kalima,Running,Jean Echenoz,Arts & Humanities,Specialized Text,Literature; Art & Music,14.617021,إميل في السابعة عشرة، وهو ولد فارع القامة أشقر...,26,"[إميل, في, السابعة, عشرة, ,, وهو, ولد, فارع, ا..."
38,APCD,BAREC_APCD_جرجس عيسى السكاف_الديوان الرئيسي_001,0,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Jurjis Isa al-Sakkaf,Arts & Humanities,Specialized Text,Literature; Art & Music,8.245902,لقد حزتم صفات الأكرمينا فعدتم في الورى غوثا...,9,"[لقد, حزتم, صفات, الأكرمينا, فعدتم, في, الورى,..."
39,APCD,BAREC_APCD_شيخ الدولة البركردزي_شيخ الدولة الب...,1,Arabic Poem Comprehensive Dataset (APCD),Shaykh Al-Dawla Al-Barkardzi,Shaykh Al-Dawla Al-Barkardzi,Arts & Humanities,Specialized Text,Literature; Art & Music,9.500000,من تراخي العظام عند قيام وفتور الكلام مع ما...,10,"[من, تراخي, العظام, عند, قيام, وفتور, الكلام, ..."
40,Kalima,BAREC_Kalima_غوته_ونابليون_001,15,Kalima,Goethe and Napoleon: A Historical Encounter,Gustave Seibt,Arts & Humanities,Specialized Text,Literature; Art & Music,20.828571,ثم بدأت عشرات القذائف تتساقط في معركة فالمي، ك...,46,"[ثم, بدأت, عشرات, القذائف, تتساقط, في, معركة, ..."
41,Kalima,BAREC_Kalima_الاسلام_الايطالي_001,5,Kalima,Italian Islam: A Journey Through the Realities...,Stefano Alievi,Arts & Humanities,Specialized Text,Literature; Art & Music,24.129032,عز الدين عناية - عدنان علي,6,"[عز, الدين, عناية, -, عدنان, علي]"
42,Hindawi,BAREC_Hindawi_86952059_001,11,Hindawi,My Diaries in Women’s Prison,Nawal El-Saadawi,Arts & Humanities,Specialized Text,Literature; Art & Music,32.875000,وإن كان عضوًا بحزب الجهاد أو داعش أو حزب الحكو...,26,"[وإن, كان, عضوا, بحزب, الجهاد, أو, داعش, أو, ح..."
43,APCD,BAREC_APCD_أبو جعفر الزوزني الزاهد_أبو جعفر ...,1,Arabic Poem Comprehensive Dataset (APCD),Abu Ja'far Al-Zuzani Al-Zahid,Abu Ja'far Al-Zuzani Al-Zahid,Arts & Humanities,Specialized Text,Literature; Art & Music,8.000000,بكيت عليه وقد فاتني بكاء الكظيم على يوسف,8,"[بكيت, عليه, وقد, فاتني, بكاء, الكظيم, على, يوسف]"
44,Hindawi,BAREC_Hindawi_63795362_001,22,Hindawi,Complete Works,Poet of the Nile Muhammad Hafiz Ibrahim,Arts & Humanities,Specialized Text,Literature; Art & Music,5.929412,(٤) تهنئة المؤيّد بداره وبمظهره الجديدين (نشرت...,17,"[(, ٤, ), تهنئة, المؤيد, بداره, وبمظهره, الجدي..."
45,Hindawi,BAREC_Hindawi_40702826_001,1,Hindawi,Roland Barthes,Jonathan Koller,Arts & Humanities,Specialized Text,Literature; Art & Music,22.304348,عندما رحل رولان بارت عن عالمنا عن عمر يناهز ال...,28,"[عندما, رحل, رولان, بارت, عن, عالمنا, عن, عمر,..."
46,APCD,BAREC_APCD_الحبسي_الديوان الرئيسي_001,0,Arabic Poem Comprehensive Dataset (APCD),The Main Diwan,Al-Habsi,Arts & Humanities,Specialized Text,Literature; Art & Music,8.177419,وقائلٍ مَن شفيعُ ال أنام يومَ اللقاءِ,7,"[وقائل, من, شفيع, ال, أنام, يوم, اللقاء]"
47,APCD,BAREC_APCD_أبو المواهب المعري_أبو المواهب ال...,1,Arabic Poem Comprehensive Dataset (APCD),Abu Al-Mawahib Al-Ma'arri,Abu Al-Mawahib Al-Ma'arri,Arts & Humanities,Specialized Text,Literature; Art & Music,10.400000,ليت شعري بأي جرمٍ تفرد ت عن الأصدقاء بأكل ا...,10,"[ليت, شعري, بأي, جرم, تفرد, ت, عن, الأصدقاء, ب..."
48,Hindawi,BAREC_Hindawi_50926304_001,2,Hindawi,Letters of the Orators,Mohamed Kurd Ali,Arts & Humanities,Specialized Text,Literature; Art & Music,24.809524,أمَّا بعد: فإنَّ لكل مخلوق حاجةً، ولكل حاجة غا...,37,"[أما, بعد, :, فإن, لكل, مخلوق, حاجة, ,, ولكل, ..."
49,Kalima,BAREC_Kalima_شعراء_القرن_16_بيير_دو_رونسار_001,27,Kalima,Sixteenth Century Poets (3),Pierre de Ronsard,Arts & Humanities,Specialized Text,Literature; Art & Music,14.595745,بالشمس التي أعشقها أوحد الشمس الأخرى.,7,"[بالشمس, التي, أعشقها, أوحد, الشمس, الأخرى, .]"

In [40]:
A_df.to_json('sampled_LAM_sentences.json', orient='records', force_ascii=False, indent=4)